var translator="Faber";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Hogar";		//Home
var Languageletter1="Usuario";		//User
var Languageletter2="Opciones";		//Settings
var Languageletter3="Tema";		//Theme
var Languageletter4="Teclas";		//Hotkeys
var Languageletter5="Youtube & sonidos";		//Youtube & Sounds
var Languageletter6="Herramientas";		//Tools
var Languageletter7="Dejarlo vacío para el público, o introduce una clave del clan, úsalo como tag";		//Password/Tag
var Languageletter7a="Clave/Tag";	//Password/Tag
var Languageletter8="Introduce tu nick de juego, 50 carácteres serán visibles en usuarios Mods y 15 para otros usuarios";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Nombre";		//Name
var Languageletter9="Introduce tu weblink manual";		//Insert your manual skin weblink
var Languageletter9a="Skin URL manual";		//Manual direct skin URL
var Languageletter10="La región para jugar";		//The region to play
var Languageletter11="El modo para jugar";		//The mode to play
var Languageletter12="Conectar al servidor o restablecer la comunicación";		//Connect to server, or restablish communication
var Languageletter12a="Conectar";		//Connect
var Languageletter13="Únete";		//Join
var Languageletter14="Jugar como huésped";		//Play as guest
var Languageletter15="Loguear y jugar";		//Login and Play
var Languageletter16="Espectar";		//Spectate
var Languageletter17="Registrarse con Facebook";		//Sign in with Facebook
var Languageletter18="Registrarse con Google";			//Sign in with Google
var Languageletter19="Jugar";		//Play
var Languageletter20="Tienda"	;		//Shop
var Languageletter21="Monedas gratis";		//Free Coins
var Languageletter22="Regalos";		//Gifts
var Languageletter23="Retos diarios";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Video promo de Legend";		//Legend Promo Video
var Languageletter26="Añadir skins";		//Add skins
var Languageletter27="Monedas gratis";		//Free Coins
var Languageletter31="Cerrar sesión";		//Logout
var Languageletter32="Veces usado";		//Times Used
var Languageletter33="Legend Mod por";		//Legend Mod by
var Languageletter34="Traducción por";		//Translation by
var Languageletter35="copiar nombres del leaderboard y de las células. (presiona x para mostrar/esconder)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animación";		//Animation
var Languageletter37="Demora de animación";		//Animation delay
var Languageletter37a="Auto zoom";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Velocidad zoom:";		//Zoom speed: 
var Languageletter39="Respawn";			//Respawn
var Languageletter40="Auto respawn";		//Auto respawn 
var Languageletter41="Respawn rápido (tecla)";			//Quick respawn (hotkey) 
var Languageletter42="Nicks";			//Names
var Languageletter43="No nicks";		//No names 
var Languageletter44="Nicks optimizados";		//Optimized names 
var Languageletter45="Auto esconder nicks";		//Auto hide names 
var Languageletter46="Esconder mi nick";		//Hide my name 
var Languageletter47="No nick de mi equipo";		//Hide teammates names 
var Languageletter48="Nicks trazados";		//Names stroke 
var Languageletter49="Masa";		//Mass
var Languageletter50="Mostrar masa";		//Show mass 
var Languageletter51="Masa optimizada (+/-2%)"	;	//Optimized mass (+/-2%) 
var Languageletter52="Auto esconder masa";			//Auto hide mass 
var Languageletter53="Esconder mi masa";		//Hide my mass                                  ff
var Languageletter54="Esconder masa de enemigos";		//Hide enemies mass 
var Languageletter55="Masa corta";		//Short mass
var Languageletter56="Disparos de virus";		//Virus shots 
var Languageletter57="Masa trazada";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="No skins ";		//No skins 
var Languageletter60="Skins customizadas";		//Custom skins 
var Languageletter61="Vanilla skins";		//Vanilla skins 
var Languageletter62="Comida optimizada";		//Optimized food 
var Languageletter6a2="Comida";		//Food 
var Languageletter63="Auto esconder comida (masa)";		//Auto hide food (mass) 
var Languageletter64="Auto esconder comida (zoom)";		//Auto hide food (zoom) 
var Languageletter65="Comida multicolor";		//Rainbow food 
var Languageletter66="Transparencia / colores";		//Transparency / colors
var Languageletter67="No colores";		//No colors 
var Languageletter68="Mi color customizado";		//My custom color 
var Languageletter69="Mi skin transparente";		//My transparent skin 
var Languageletter70="Skins transparentes";		//Transparent skins 
var Languageletter71="Virus transparentes";		//Transparent viruses 
var Languageletter70a="Células transparentes";		//Transparent cells
var Languageletter72="Cuadrícula / sectores";		//Grid / sectors
var Languageletter73="Mostrar cuadrícula";		//Show grid 
var Languageletter74="Mostrar sectores de fondo";		//Show background sectors 
var Languageletter75="Mostrar bordes de mapa";		//Show map borders 
var Languageletter76="Chat";		//Chat
var Languageletter77="Inhabilitar chat";		//Disable chat 
var Languageletter78="Notificaciones de sonido";		//Sound notifications 
var Languageletter79="Emoticonos";		//Emoticons 
var Languageletter80="Mostrar imágenes en chat";		//Show images on chat 
var Languageletter81="Mostrar vídeos en chat";		//Show videos on chat 
var Languageletter82="Caja de chat en vez de pop-ups";		//Chatbox instead of popups 
var Languageletter82a="Minimapa";		//Minimap
var Languageletter82b="Εμφάνιση μικρού χάρτη";		//Show minimap 
var Languageletter82c="Mostrar minimapa";		//Show minimap grid 
var Languageletter82d="Mostrar guías de minimapa";		//Show minimap guides 
var Languageletter82e="Compañeros de un color";		//One-colored teammates 
var Languageletter83="Ayudantes";		//Helpers
var Languageletter84="Colores de los oponentes";		//Opponents colors
var Languageletter85="Aros de los oponentes";		//Opponents rings 
var Languageletter86="Colores de los virus";		//Viruses colors 
var Languageletter87="Rango de división";		//Split range 
var Languageletter88="Rango de los virus";		//Viruses range 
var Languageletter89="Tracking del cursor";		//Cursor tracking 
var Languageletter90="Indicadores de compañeros";		//Teammates indicators 
var Languageletter91="Control por ratón";		//Mouse control
var Languageletter92="LMB - División por mouse";		//LMB - Mouse split 
var Languageletter93="RMB - Alimentar por mouse";		//RMB - Mouse feed 
var Languageletter94="Invertir botones del mouse";		//Invert mouse buttons                      ddd
var Languageletter94a="HUD";		// HUD
var Languageletter95="Mostrar top 5 del equipo";		//Show team top 5 
var Languageletter96="Mostrar rastreo";		//Show targeting 
var Languageletter97="Leaderboard centrada";		//Centered leaderboard 
var Languageletter98="Estadísticas de juego arriba";		//Game stats at the top 
var Languageletter99="Estadísticas";		//Stats
var Languageletter100="Mostrar estadísticas de juego";		//Show game stats 
var Languageletter101="Estadísticas: Masa";		//Game stats: Mass 
var Languageletter102="Estadísticas: STE";		//Game stats: STE 
var Languageletter103="Estadísticas: n/16";		//Game stats: n/16 
var Languageletter104="Estadísticas: FPS";		//Game stats: FPS 
var Languageletter105="Mostrar tiempo actual";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Saltar estadísticas después de morir";		//Skip stats after death 
var Languageletter108="Mostrar retos";		//Show quest 
var Languageletter109="Bloquear pop-ups (anuncios/tienda/retos)";		//Block popups (ads/shop/quest) 
var Languageletter110="-- Calidad de gráficos --";		//-- Graphics Quality --
var Languageletter111="Gráficos: Retina";		//Graphics: Retina
var Languageletter112="Gráficos: Altos";		//Graphics: High
var Languageletter113="Gráficos: Medios";		//Graphics: Medium"
var Languageletter114="Gráficos: Bajos";		//Graphics: Low
var Languageletter115="Gráficos: Muy bajos";		//Graphics: Very Low
var Languageletter116="Exportar / importar opciones";		//Export / import settings
var Languageletter117="Restaurar opciones por defecto";		//Restore default settings
var Languageletter118="Exportar opciones";		//Export settings
var Languageletter119="Importar opciones";		//Import settings
var Languageletter120="Para exportar las opciones seleccionadas, copia el código de abajo y guárdalo en un documento de texto en encriptación unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Para importar las opciones seleccionadas, pega un código exportado abajo y presiona el botón 'Importar opciones'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Comandos";		// Commands
var Languageletter123="Teclas";		// Hotkeys
var Languageletter124="Perfiles";		// Profiles
var Languageletter125="Opciones";		// Settings
var Languageletter126="Tema";		// Theme
var Languageletter127="Exportar opciones";		//Export settings
var Languageletter128="Importar opciones";		//Import settings
var Languageletter129="Temas básicos";		//Basic theming
var Languageletter130="Menú";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimapa";		//Minimap
var Languageletter134="Gráficos / cursores";		//Graphics / cursors
var Languageletter135="Tema predefinido";		//Theme preset
var Languageletter136="Legend Original";		//Legend Original
var Languageletter137="Estilo crazy";		//Crazy Style 1
var Languageletter139="Fondo";		//Background
var Languageletter140="Bordes de mapa";		//Map borders
var Languageletter141="Rejilla";		//Grid
var Languageletter142="Fuente de los sectores";		//Sectors font
var Languageletter143="Nicks";		//Names
var Languageletter144="Borde de nicks";		//Names stroke
var Languageletter145="Masa";		//Mass
var Languageletter146="Borde de masa";		//Mass stroke
var Languageletter147="Borde de virus";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter149="Comida";		//Food
var Languageletter150="Indicador de equipo";		//Teammate indicator
var Languageletter151="Tracking del cursor";		//Cursor tracking
var Languageletter152="Rango de división";		//Split range
var Languageletter153="Fuente de nicks";		//Names font
var Languageletter154="Fuente de masa";		//Mass font
var Languageletter155="Fuente de los sectores";		//Sectors font
var Languageletter157="Tamaño fuente de sectores";		//Sectors font size
var Languageletter158="Escala de nicks";		//Names scale
var Languageletter159="Escala de masa";		//Mass scale
var Languageletter160="Escala de masa de virus";		//Virus mass scale
var Languageletter161="Escala de borde de texto";		//Text stroke scale
var Languageletter162="Tamaño de comida";		//Food size: 
var Languageletter163="Tamaño borde del viurs";		//Virus stroke size
var Languageletter164="Amplitud bordes del mapa";		//Map borders width
var Languageletter165="Amplitud de los sectores";		//Sectors grid width
var Languageletter166="Transparencia de células";		//Cells transparency
var Languageletter167="Transparencia de skins";		//Skins transparency
var Languageletter168="Transparencia de virus";		//Virus transparency                            sfsfsfsfsfsf
var Languageletter169="Transparencia de nicks y masa";		//Names & mass transparency
var Languageletter170="Restablecer temas predeterminados";		//Restore theme default settings
var Languageletter171="Guardar opciones";		//Save settings
var Languageletter172="Tema del menú";		//Menu theme
var Languageletter173="Fondo";		//Background
var Languageletter174="Transparencia";		//Transparency
var Languageletter175="Color principal";		//Main color
var Languageletter176="Texto del botón";		//Button text
var Languageletter177="Panel";		//Panel
var Languageletter179="Texto del panel";		//Panel text
var Languageletter181="Botón";		//Button
var Languageletter189="Imágen fondo panel";		//Panel background image
var Languageletter190="URL Imágen";		//Image URL
var Languageletter191="Color principal";		//Main color
var Languageletter192="Fondo";		//Background
var Languageletter193="Texto";		//Text
var Languageletter194="Estadísticas";		//Stats
var Languageletter195="Tiempo";		//Time
var Languageletter196="Top 5 masa";		//Top 5 mass
var Languageletter197="Leaderboard - yo";		//Leaderboard - me
var Languageletter198="Leaderboard - compañero";		//Leaderboard - teammate
var Languageletter199="Fuente HUD";		//HUD font
var Languageletter200="Escala HUD";		//HUD scale: 
var Languageletter201="Fondo del mensaje";		//Message background
var Languageletter202="Texto del mensaje";		//Message text
var Languageletter203="Tiempo del mensaje";		//Message time
var Languageletter204="Nick del mensaje";		//Message nick
var Languageletter205="Comando del fondo";		//Command background
var Languageletter206="Comando del texto";		//Command text
var Languageletter207="Comando del tiempo";		//Command time
var Languageletter208="Comando del nick";		//Command nick
var Languageletter209="Color caja de chat";		//Chatbox color
var Languageletter210="Escala del chat";		//Chat scale
var Languageletter211="Sectores";		//Sectors
var Languageletter212="Sector Actual";		//Current sector
var Languageletter213="Nick";		//Nick
var Languageletter214="Borde del nick";		//Nick stroke
var Languageletter215="Mi célula";		//My cell
var Languageletter216="Borde de mi célula";		//My cell stroke
var Languageletter217="Compañeros";		//Teammates
var Languageletter218="Punto de muerte";		//Death location
var Languageletter219="Guías";		//Guides
var Languageletter220="Fuente del minimapa";		//Minimap font
var Languageletter221="Fuente del nick";		//Nick font
var Languageletter222="Amplitud del minimapa";		//Minimap width
var Languageletter223="Transparencia de sectores";		//Sectors transparency
var Languageletter224="Tamaño del nick";		//Nick size
var Languageletter225="Tamaño borde del nick";		//Nick stroke size
var Languageletter226="Tamaño de mi célula";		//My cell size
var Languageletter227="Tamaño borde de mi célula";		//My cell stroke size
var Languageletter228="Tamaño de compañeros";		//Teammates size
var Languageletter229="Imágen de fondo customizada";		//Custom background image
var Languageletter230="Cursor customizado";		//Custom cursor image
var Languageletter231="Imágen URL";		//Image URL
var Languageletter232="Imágen cursor URL";		//Cursor image URL
var Languageletter233="Alimentar";		//Feed
var Languageletter234="Macro alimentar";		//Macro feed
var Languageletter235="Dividir";		//Split
var Languageletter236="Double división";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="División x16";		//Split 16
var Languageletter239="Pausar célula";		//Cell pause
var Languageletter240="Mostrar/esconder Top 5 Equipo";		//Show/hide team top 5
var Languageletter241="Mostrar/esconder Tiempo actual";		//Show/hide current time
var Languageletter242="Mostrar/esconder Rango de división";		//Show/hide split range"
var Languageletter243="Mostrar/esconder Indicadores de compañeros";		//Show/hide teammates indicators
var Languageletter244="Mostrar/esconder Indicadores de división";		//Show/hide split indicators
var Languageletter245="Mostrar/esconder Colores de oponentes";		//Show/hide opponents colors
var Languageletter246="Activar skins (propia/predeterminada)";		//Toggle skins (custom/default)
var Languageletter247="Activar skins transparentes";		//Toggle transparent skins
var Languageletter248="Mostrar/esconder skins";		//Show/hide skins
var Languageletter249="Mostrar/esconder estadísticas de juego";		//Show/hide game stats
var Languageletter250="Activar propias células (las más pequeñas/grandes)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Mostrar/esconder comida";		//Show/hide food
var Languageletter252="Mostrar/esconder rejilla";		//Show/hide grid
var Languageletter253="Mostrar/esconder guías de minimapa";		//Show/hide minimap guides
var Languageletter254="Mostrar/esconder chat";		//Show/hide chat
var Languageletter255="Mostrar/esconder HUD";		//Show/hide HUD
var Languageletter256="Copiar leaderboard";		//Copy leaderboard
var Languageletter257="Mostrar/esconder leaderboard";		//Show/hide leaderboard
var Languageletter258="Activar auto zoom";		//Toggle auto zoom
var Languageletter259="Reiniciar zoom";		//Reset zoom
var Languageletter260="Activar posición de muerte";		//Toggle death location
var Languageletter261="Mostrar historial del chat / Clear chat";		//Show chat history / Clear chat
var Languageletter262="Mostrar/esconder sectores de fondo";		//Show/hide background sectors
var Languageletter263="Mostrar/esconder bots pequeños";		//Show/hide small bots
var Languageletter264="Mostrar/esconder nicks";		//Show/hide names
var Languageletter265="Mostrar/esconder nicks de equipo";		//Show/hide teammates names
var Languageletter266="Mostrar/esconder masa";		//Show/hide mass
var Languageletter267="Mostrar/esconder minimapa";		//Show/hide minimap
var Languageletter268="Enviar mensaje de chat";		//Enter chat message
var Languageletter269="Respawn rápido";		//Quick respawn
var Languageletter270="Activar auto respawn";		//Toggle auto respawn
var Languageletter271="Nivel zoom";		//Zoom level 
var Languageletter272="Mostrar/esconder panel de orientación";		//Show/hide targeting panel
var Languageletter273="Start/stop orientación (seguir)";		//Start/stop targeting (following)
var Languageletter274="Cancelar orientación";		//Cancel targeting
var Languageletter275="Cambiar orientación";		//Change target
var Languageletter276="Mostrar orientación en el minimapa";		//Show target on the minimap
var Languageletter277="Mostrar/esconder retos";		//Show/hide quest
var Languageletter278="Para asignar una tecla, haz click en el campo de texto y presiona la tecla deseada.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Para borrar una tecla, haz click en el campo de texto y presiona la tecla 'Retroceso'.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Posibles combinaciones de teclas con CTRL y ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Restablecer opciones predeterminadas";		//Restore default settings
var Languageletter282="Guardar opciones";		//Save settings
var Languageletter283="Cerrar";		//Close
var Languageletter284="Controlador Youtube";		//Youtube player
var Languageletter284a="URL Youtube";		// Youtube Url
var Languageletter285="Pon tu vídeo/playlist aquí";		//Paste your video/playlist here
var Languageletter286="Sonidos";		//Sounds
var Languageletter287="Sonido de notificación de mensaje";		//Message notification sound
var Languageletter288="Sonido de notificación de comandos";		//Command notification sound
var Languageletter289="Copiar Party/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Party";		//Token
var Languageletter290a="Tablero"; //Board
var Languageletter291="Copiar";		//Copy


var Languageletter291a="Copiar Leaderboard (L)";		//Copy Leaderboard (L)
var Languageletter292="Unirse a un servidor (Backspace)";		//Join server (Backspace)
var Languageletter293="Cambiar servidor (+)";		//Change server (+)
var Languageletter294="Historial del leaderboard";		//Leaderboard history
var Languageletter295="Poner el token/IP/leaderboard/name/tag de amigo...";		//Enter friend\'s token, IP, leaderboard, name or clan tag...
var Languageletter296="Jugadores activos";		// Active players
var Languageletter297="Masa total";		// Total mass
var Languageletter298="Top equipo ";		//Team top 
var Languageletter299="Leaderbodard";		//Leaderbodard
var Languageletter300="Comunicación";		//Communication
var Languageletter301="Mensaje de script de comandos";		//Message Script Commands
var Languageletter302="Mensaje de iconos Imgur";		//Message Imgur Icons
var Languageletter303="Mensaje de vídeos Youtube";		//Message Youtube Videos
var Languageletter304="Editar nicks";		//Edit names
var Languageletter305="[Solo modo espectador] Binoculares";		//[Spectate Mode Only] Binoculars
var Languageletter306="Jugar / Pausar";		//Play / Pause
var Languageletter307="Pantalla completa";		//Fullscreen
var Languageletter308="Rotar";		//Rotate
var Languageletter309="Por defecto";		//Default
var Languageletter310="Atrás";		//Back
var Languageletter311="Guardar para después";		//Save for later
var Languageletter312="Región";		//Region
var Languageletter313="Jugadores";		//Players
var Languageletter314="Servidores";		//Servers
var Languageletter315="[Orientación no establecida]";		//[Target not set]
var Languageletter316="Fondo manual";		//Manual background
var Languageletter317="Mensaje iconos & Youtube manual";		//Manual Message Icons&Youtube
var Languageletter318="Posición chat";		//Chat Position
var Languageletter319="Webhook URL de Discord (para mandar party)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Leaderboard";		//Leaderboard
var Languageletter321="Tablero de equipo";		//Teamboard
var Languageletter322="Mi canvas";		//Main Canvas
var Languageletter323="Mi banner";		//Main Banner
var Languageletter324="Hola equipo!";		//Hello Team!
var Languageletter325="Reír al equipo";		//Laugh to Team
var Languageletter326="Nombre del equipo";		//Team Change Name to yours
var Languageletter327="Troll al morir";		//Troll on Death
var Languageletter328="Abrir música de Youtube";		//Open Youtube Music
var Languageletter329="Modo insano (Esconder todo)";		//Insane mode (Hide Everything)
var Languageletter330="URL de la imágen, comenzando por http://... o https://...";		//Url of image starting with http://... or https://...
var Languageletter331="URL Imágen minimapa";		//Minimap Image URL
var Languageletter332="Texto minimapa";		//Minimap Text
var Languageletter333="Texto del leaderboard";		//Leaderboard Logo Text
var Languageletter333a="URL Imágen del leaderboard";		// Leaderboard Image URL
var Languageletter334="Texto logo tablero de equipo";		//Teamboard Logo Text
var Languageletter334a="URL Imágen tablero de equipo";		// Teamboard Image URL
var Languageletter335="URL Imágen canvas";		//Main Canvas Image URL
var Languageletter336="URL link de mi banner";		//Main Banner Icon URL
var Languageletter337="URL icono de mi banner";		//Main Banner Link URL
var Languageletter338="Icono";		//Icon
var Languageletter339="e.g";		//e.g
var Languageletter340="URL de Youtube para ser mostrada";		//Url of youtube to be shown
var Languageletter341="URL de link para redireccionar";		//Url of link to redirect
var Languageletter342="URL Webhook de Discord";		//Discord Webhook Url
var Languageletter342a="Texto icono imágen";		//Message Icon Text
var Languageletter342b="Texto mensaje Youtube";		//Youtube Message Text
var Languageletter342c="Mensaje URL icono Imgur";		//Message Icon Imgur Url
var Languageletter342d="Mensaje URL Youtube";		//Youtube Message Url
var Languageletter343="Debe ser rellenado para funcionar.";		//Must be filled for function to work.
var Languageletter344="Webhook secundario(opcional)";		//Secondary Webhook(optional)
var Languageletter345="Mostrar/esconder todo temporalmente. Función para Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Languageletter346="Escoger lenguages";		//Choose Language
var Languageletter347="¡ADVERTENCIA! Las ventanas emergentes se bloquean en la configuración.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Desbloqueo temporal";		//Temporary unblock

var Premadeletter0="Comunicación activada"; 		//Communication Activated
var Premadeletter1="Error al abrir link de Youtube";		 //Cannot open this youtube URL
var Premadeletter2="[SERVIDOR]: No puedes chatear si tu nick contiene más de 15 carácteres"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Activado"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Activado";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Activado";		//Easter Egg 3 Activated
var Premadeletter6="El vídeo funciona mejor en vanilla, visita:";		//Video works better on vanilla, visit:
var Premadeletter7="Notas: <b>Facebook</b> compatibilidad es mejor que <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notas: Agar.io solo puede conectar a Google Plus en eventos cargados. Si cierra sesión, recarga Agar.io o usa <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Si cierra sesión en eventos cargados, borra cookies de Chrome desde";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Desconectado del servidor :(";		//Disconnected from server :(
var Premadeletter11="Has sido baneado, reinicia tu router";		//You were banned, restart your rooter!
var Premadeletter12="Conectado!";		//Connected!
var Premadeletter13="JUGAR";		//PLAY
var Premadeletter14="ESPECTAR";		//SPECTATE
var Premadeletter15="Party inválida o el servidor ha sido cerrado :(";		//Invalid token or server has closed :(
var Premadeletter16="puede ser actualizado a";		//can be Updated to
var Premadeletter17="Bienvenido";			//Welcome back
var Premadeletter18="¡Tu área de atajo y otras áreas (de tu última tab) todavía están inhabilitadas! Te sugerimos que las habilites.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Habilítelas";		//Enable Them
var Premadeletter20="Mantenlas inhabilitadas";		//Keep Them Disabled
var Premadeletter21="Buscando IP";		//Searching IP
var Premadeletter22="Tu compañero";		//Your teammate
var Premadeletter23="quiere que escondas todo (leaderboard y minimapa)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Aceptar";		//Accept
var Premadeletter25="¡De ningún modo!";		//NO WAY!
var Premadeletter26="quiere que cambies tu nick a";		//wants you to change your name to
var Premadeletter27="quiere que habilites el modo troll al morir";		//wants you to hide Enable Troll on death
var Premadeletter28="quiere que abras el controlador de Youtube";			//wants you to open Youtube Player
var Premadeletter29="Leaderboard encontrado";		//Leaderboard found
var Premadeletter30="Buscar";		//Search
var Premadeletter31="El leaderboard no fue encontrado. Sigue buscando...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="La búsqueda fue cancelada";		//Search was canceled
var Premadeletter33="Eres invisible al Team/Clan";		//You are invisible to Team / Clan
var Premadeletter34="Eres visible al Team/Clan";		//You are visible to Team / Clan
var Premadeletter35="Mostrar/Apagar solo puede ser usado en juego";			//Hide/Show can be used only while playing
var Premadeletter36="¡Dirección Webhook de Discord inválida!";		//This is not valid Discord Webhook address
var Premadeletter37="El servidor está bloqueado";		//Server is locked
var Premadeletter38="Debes estar en modo espectador";		//You must be on spectate mode
var Premadeletter39="Debido a problemas de spam, debes estar en juego y usar una contraseña";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube Encendido";		//Auto Youtube On
var Premadeletter41="Auto Youtube Apagado";		//Auto Youtube Off
var Premadeletter42="Mostrar atajos";		//Show Shortcuts
var Premadeletter43="Esconder atajos";		//Hide Shortcuts
var Premadeletter44="Mostrar Barra XP";		//Show XP BAR
var Premadeletter45="Esconder Barra XP";		//Hide XP BAR
var Premadeletter46="Mostrar tiempo";		//Show TIME
var Premadeletter47="Esconder tiempo";		//Hide TIME
var Premadeletter48="Mostrar todo";		//Show Everything
var Premadeletter49="Esconder todo";		//Hide Everything
var Premadeletter50="Mostrar cálc. tiempo";		//Show Timer Calc.
var Premadeletter51="Esconder cálc. tiempo"		//Hide Timer Calc.
var Premadeletter52="Editar nicks";		//Edit Names
var Premadeletter52a="Cerrar nicks";		//Close Names
var Premadeletter53="Auto monedas gratis";		//Auto free coins
var Premadeletter54="Parar monedas gratis";		//Stop free coins
var Premadeletter55="Troll en morir";		//Troll on Death
var Premadeletter56="No troll en morir";		//No troll on Death

var Premadeletter57="Comunicación";		//Communication
var Premadeletter58="Escondido";		//Hidden
var Premadeletter59="Visible";		//Visible

