/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="Unknown";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Начало";		//Home
var Languageletter1="Потребител";		//User
var Languageletter2="Настройки";		//Settings
var Languageletter3="Теми";		//Theme
var Languageletter4="Бързи Клавиши";		//Hotkeys
var Languageletter5="Youtube & Звукове";		//Youtube & Sounds
var Languageletter6="Инструменти";		//Tools
var Languageletter7="Остави го празно за другите,или паролата на вашия клан, или използвай таг";		//Password/Tag
var Languageletter7a="Парола/Таг"	;	//Password/Tag
var Languageletter8="Постави си името, 50 букви са видими за потребителите на мода, 15 на други потребители";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Име";		//Name
var Languageletter9="Поставете своя Линк за вашия скин";		//Insert your manual skin weblink
var Languageletter9a="Директна връзка URL";		//Manual direct skin URL
var Languageletter10="Регион за игра";		//The region to play
var Languageletter11="Мод за игра";		//The mode to play
var Languageletter12="Свързане към сървъра, Или възстановяване на комуникацията";		//Connect to server, or restablish communication
var Languageletter12a="Връзка";		//Connect
var Languageletter13="Влез";		//Join
var Languageletter14="Играй като гост";		//Play as guest
var Languageletter15="Влезте и играйте";		//Login and Play
var Languageletter16="Наблюдавай";		//Spectate
var Languageletter17="Влезте със Facebook";		//Sign in with Facebook
var Languageletter18="Влезте със Google";			//Sign in with Google
var Languageletter19="Играй";		//Play
var Languageletter20="Магазин"	;		//Shop
var Languageletter21="Безплатни Пари";		//Free Coins
var Languageletter22="Подаръци";		//Gifts
var Languageletter23="Делнични Предизвикателства";			//Daily Quests
var Languageletter24="Скинове";		//Skins
var Languageletter25="Промо видеото на Legend";		//Legend Promo Video
var Languageletter25a="Нова форма на идеи и статистически данни";	//New Ideas & Statistics Form
var Languageletter25b="Модна информация и шаблони";		//Mod Info & Templates

var Languageletter26="Добави скинове";		//Add skins
var Languageletter26a="Сървър за копиране, парола, екип съвет и лидер съвет"; //Copy Server, Password, Teamboard & Leaderboard
var Languageletter31="Излез";		//Logout
var Languageletter32="Пъти използвано";		//Times Used
var Languageletter33="Legend Mod от";		//Legend Mod by
var Languageletter34="Преведено от ";		//Translation by
var Languageletter35="Kопирай Класацията, имената и имената на клетките. (натисни x да видиш/скриеш)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Анимаций";		//Animation
var Languageletter37="Анимационно Закъснение";		//Animation delay
var Languageletter37a="Aвтоматичен зуум";		// Auto zoom
var Languageletter37b="Зуум";		// Zoom
var Languageletter38="Скороста на зуума:";		//Zoom speed: 
var Languageletter39="Въстановяване";			//Respawn
var Languageletter40="Автоматично Въстановяване";		//Auto respawn 
var Languageletter41="Бързо Въстановяване (Бърз Клавиш)";			//Quick respawn (hotkey) 
var Languageletter41a="Започнете със специални ефекти";			//Spawn special effects 
var Languageletter41b="Сливане на часове ";			//Merge timer off
var Languageletter41c="Предложено да бъде активирано за намаляване на закъснението";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Звук от вирус";			//Virus shot sound

var Languageletter42="Имена";			//Names
var Languageletter43="Без имена";		//No names 
var Languageletter44="Оптимизирани имена";		//Optimized names 
var Languageletter45="Автоматично скриване на имената";		//Auto hide names 
var Languageletter46="Скрий името ми";		//Hide my name 
var Languageletter47="Скрий имената на Съотборниците ми";		//Hide teammates names 
var Languageletter48="Oчертание на имена";		//Names stroke 
var Languageletter49="Maса";		//Mass
var Languageletter50="Скрий масата";		//Show mass 
var Languageletter51="Оптимизирана масса (+/-2%)"	;	//Optimized mass (+/-2%) 
var Languageletter52="Автоматично скриване на массата";			//Auto hide mass 
var Languageletter53="Скрий масата ми";		//Hide my mass 
var Languageletter54="Скрийте масата на враговете";		//Hide enemies mass 
var Languageletter55="Малка Масса";		//Short mass
var Languageletter56="Изстрелване на вирус";		//Virus shots 
var Languageletter57="Учертание на масса";		//Mass stroke 
var Languageletter58="Скинове";		//Skins
var Languageletter59="Без скинове ";		//No skins 
var Languageletter60="Собствени скинове";		//Custom skins 
var Languageletter61="Vаnnila скинове";		//Vanilla skins 
var Languageletter61a="Физика от желе";		//Jelly physics 
var Languageletter61b="Видеоклипове";		//Video skins
var Languageletter61c="Звук от други видео кодове, когато и двете C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Оптимизирана храна";		//Optimized food 
var Languageletter6a2="Храна";		//Food 
var Languageletter63="Автоматично скриване на храната (масса)";		//Auto hide food (mass) 
var Languageletter64="Автоматично скриване на храна (зуум)";		//Auto hide food (zoom) 
var Languageletter65="Цвят на храна";		//Rainbow food 
var Languageletter66="Прозрачност / цветове";		//Transparency / colors
var Languageletter67="Без цветове";		//No colors 
var Languageletter68="Моя цвят";		//My custom color 
var Languageletter69="Mоя прозрачен скин";		//My transparent skin 
var Languageletter70="Прозрачни скинове";		//Transparent skins 
var Languageletter70a="Прозрачни клетки";		//Transparent skins 
var Languageletter71="Прозрачни вируси";		//Transparent viruses 
var Languageletter71a="Вирусът блести";		//Virus Glow
var Languageletter71b="Анимирани цветове на дъгата";		//Animated rainbow colors

var Languageletter72="решетка / сектори";		//Grid / sectors
var Languageletter73="Покажи решетка";		//Show grid 
var Languageletter74="Покажи фона на секторите";		//Show background sectors 
var Languageletter75="Покажи границите на мапа";		//Show map borders 
var Languageletter75a="Светлина на границите";		//Border Glow

var Languageletter76="Чат";		//Chat
var Languageletter77="Деактивиране на чата";		//Disable chat 
var Languageletter78="Звукови известия";		//Sound notifications 
var Languageletter79="Емотикони";		//Emoticons 
var Languageletter80="Покажи снимките на чата";		//Show images on chat 
var Languageletter81="Покажи видео на чата";		//Show videos on chat 
var Languageletter82="Chatbox вместо изскачащи прозорци";		//Chatbox instead of popups 
var Languageletter82a="Мини карта";
var Languageletter82b="Показване на мини карта";
var Languageletter82c="Показване на миниатюрната мрежа";
var Languageletter82d="Показване на миниатюрните ръководства";
var Languageletter82e="Едноцветни съотборници";		//One-colored teammates 
var Languageletter82f="Показване на допълнителни мини упътвания за карти";		//Show extra minimap guides
var Languageletter82g="Показване на клетки-призрак";		//Show ghost cells

var Languageletter83="Помощници";		//Helpers
var Languageletter84="Цветовете на опонента";		//Opponents colors
var Languageletter85="Пръстените на опонентите";		//Opponents rings 
var Languageletter86="Цветове на вирусите";		//Viruses colors 
var Languageletter87="Разделен диапазон";		//Split range 
var Languageletter87a="Бързо двойно разделен обхват";		//Quick double split range
var Languageletter87b="Бавно двойно разделяне";		//Slow double split range

var Languageletter88="Диапазон на вирусите";		//Viruses range 
var Languageletter89="Проследяване на курсора";		//Cursor tracking 
var Languageletter90="Индикатори на Съотборници";		//Teammates indicators 
var Languageletter90a="Духови клетки";		//Ghost cells

var Languageletter91="Контрол на мишка";		//Mouse control
var Languageletter92="LMB - Разделяне чрез мишка";		//LMB - Mouse split 
var Languageletter93="RMB - Хранене чрез мишка";		//RMB - Mouse feed 
var Languageletter94="Обърнете бутоните на мишката";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="екип";		//Team
var Languageletter96="Показване на насочването";		//Show targeting 
var Languageletter96a="Показване на маса за класиране";		//Show leaderboard mass

var Languageletter97="Централизирана класация";		//Centered leaderboard 
var Languageletter97a="Заглавна част на класацията";		//\"Leaderboard\" header 

var Languageletter98="Game stats at the top";		//Game stats at the top 
var Languageletter98a="Кожи върху екип";		//Skins on teamboard

var Languageletter99="Статистики";		//Stats
var Languageletter100="Покажи статистиките от играта";		//Show game stats 
var Languageletter101="Статистика на играта";		//Game stats
//the \' is needed
var Languageletter102="враг";		//Enemy\'s 		
var Languageletter103="наш";		//Our
var Languageletter104="Минималният мач на съотборника";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Максимална маса на врага за предварително разделяне";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Покажи конкретно време";		//Show current time 
var Languageletter106="Екстри";		//Extras
var Languageletter107="Пропусни статистиките след умиране";		//Skip stats after death 
var Languageletter108="Покажи предизвикателството";		//Show quest 
var Languageletter108a="Играта звучи";   //Game Sounds
var Languageletter108b="Менюто звучи"; //Menu Sounds
var Languageletter109="Блокиране на изскачащи прозорци (ads/shop/quest)";		//Block popups (ads/shop/quest) 
var Languageletter109a="ГЛАС"; //Voice
var Languageletter109b="Глас-Префикция"; //Voice-Prefix
var Languageletter109c="Глас-език"; //Voice-language
var Languageletter109d="Отмяна на паузата"; //UnPause

var Languageletter110="-- Качество на графиката --";		//-- Graphics Quality --
var Languageletter111="Графика: Ретина";		//Graphics: Retina
var Languageletter112="Графика: Високо";		//Graphics: High
var Languageletter113="Графика: Средно";		//Graphics: Medium"
var Languageletter114="Графика: Слабо";		//Graphics: Low
var Languageletter115="Графика: Много слабо";		//Graphics: Very Low
var Languageletter116="Износ / Настройките за импортиране";		//Export / import settings
var Languageletter117="Фабрични настройки";		//Restore default settings
var Languageletter118="Износ на данни";		//Export settings
var Languageletter119="Внос на данни";		//Import settings
var Languageletter120="За да експортирате избраните настройки, копирайте кода по-долу и го запазете в текстов файл, кодиран в Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="За да импортирате избраните настройки, поставете изнесения код по-долу и натиснете бутона 'Импортиране на настройките'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Команди";		// Commands
var Languageletter123="Бързи клавиши";		// Hotkeys
var Languageletter124="Профили";		// Profiles
var Languageletter125="Настройки";		// Settings
var Languageletter126="Тема";		// Theme
var Languageletter127="Износ на данни";		//Export settings
var Languageletter128="Внос на данни";		//Import settings
var Languageletter129="Основни теми";		//Basic theming
var Languageletter130="Меню";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Чат";		//Chat
var Languageletter133="Минимап";		//Minimap
var Languageletter134="Графика / Курсори";		//Graphics / cursors
var Languageletter135="Предварително зададена тема";		//Theme preset
var Languageletter136="Легенд Оригинал";		//Legend Original
var Languageletter137="Луд стил";		//Crazy Style 1
var Languageletter139="Фон";		//Background
var Languageletter140="Граници на мапа";		//Map borders
var Languageletter141="Решетка";		//Grid
var Languageletter142="Шрифт на секторите";		//Sectors font
var Languageletter143="Имена";		//Names
var Languageletter144="Учертание на имената";		//Names stroke
var Languageletter145="Масса";		//Mass
var Languageletter146="Учертание на массата";		//Mass stroke
var Languageletter147="Учертание на вирусите";		//Virus stroke
var Languageletter148="Вирус";		//Virus
var Languageletter148a="Mайка";		//Mothercell
var Languageletter148b="Инсулт на майката";		//Mothercell stroke
var Languageletter149="Храна";		//Food
var Languageletter150="Индикатор на Съотборници";		//Teammate indicator
var Languageletter151="Проследяване на курсора";		//Cursor tracking
var Languageletter152="Разделен диапазон";		//Split range
var Languageletter153="Шрифт на имената";		//Names font
var Languageletter154="Шрифт на массата";		//Mass font
var Languageletter154a="По-голям";		//Bigger
var Languageletter154b="По-малък";		//Smaller
var Languageletter155="Шрифта на секторите";		//Sectors font
var Languageletter157="Големина на шрифтна на секторите";		//Sectors font size
var Languageletter158="Мащаб на имената";		//Names scale
var Languageletter159="Мащаб на массата";		//Mass scale
var Languageletter160="Мащаб на вирус";		//Virus mass scale
var Languageletter161="Скала на текстовия ход";		//Text stroke scale
var Languageletter162="Размер на храната";		//Food size: 
var Languageletter163="Размер на вируса";		//Virus stroke size
var Languageletter164="Ширината на графите на картата";		//Map borders width
var Languageletter165="Ширина на сектора на мрежата";		//Sectors grid width
var Languageletter166="Прозрачност на клетките";		//Cells transparency
var Languageletter167="Прозрачност на скина";		//Skins transparency
var Languageletter168="Прозрачност на вируса";		//Virus transparency
var Languageletter169="Име и масова прозрачност";		//Names & mass transparency
var Languageletter170="Възстанови настройките по подразбиране за темата";		//Restore theme default settings
var Languageletter171="Запаси настройките";		//Save settings
var Languageletter172="Тема на менюто";		//Menu theme
var Languageletter173="Фон";		//Background
var Languageletter174="Прозрачност";		//Transparency
var Languageletter175="Основен цвят";		//Main color
var Languageletter176="Бутон текст";		//Button text
var Languageletter177="Панел";		//Panel
var Languageletter179="Текст на панела";		//Panel text
var Languageletter181="Бутон";		//Button
var Languageletter189="Панорамно изображение на панела";		//Panel background image
var Languageletter190="Снимка URL";		//Image URL
var Languageletter191="Основен Цвят";		//Main color
var Languageletter192="Фон";		//Background
var Languageletter193="Текст";		//Text
var Languageletter194="Статистики";		//Stats
var Languageletter195="Време";		//Time
var Languageletter196="Топ 5 маса";		//Top 5 mass
var Languageletter197="Класация - Аз";		//Leaderboard - me
var Languageletter198="Класация - Съотборник";		//Leaderboard - teammate
var Languageletter199="HUD Шрифт";		//HUD font
var Languageletter200="HUD Мащаб";		//HUD scale: 
var Languageletter201="Фонът на съобщенията";		//Message background
var Languageletter202="Текст на съобщението";		//Message text
var Languageletter203="Време за съобщения";		//Message time
var Languageletter204="Име на съобщения";		//Message nick
var Languageletter205="Команден фон";		//Command background
var Languageletter206="Команден текст";		//Command text
var Languageletter207="Време за командване";		//Command time
var Languageletter208="Име на команда";		//Command nick
var Languageletter209="Цвят на чата";		//Chatbox color
var Languageletter210="Мащаб на чата";		//Chat scale
var Languageletter211="Сектори";		//Sectors
var Languageletter212="Конкретен сектор";		//Current sector
var Languageletter213="Име";		//Nick
var Languageletter214="Учертание на името";		//Nick stroke
var Languageletter215="Моята клетка";		//My cell
var Languageletter216="Учертание на моята клетка";		//My cell stroke
var Languageletter217="Съотборници";		//Teammates
var Languageletter218="Местоположение на смъртта";		//Death location
var Languageletter219="Ръководство";		//Guides
var Languageletter220="Минимален шрифт";		//Minimap font
var Languageletter221="Шрифт на името";		//Nick font
var Languageletter222="Ширина на минимапа";		//Minimap width
var Languageletter223="Прозрачност на секторите";		//Sectors transparency
var Languageletter224="Размер на имена";		//Nick size
var Languageletter225="Размер на учертанията на имената";		//Nick stroke size
var Languageletter226="Размер на моята клетка";		//My cell size
var Languageletter227="Размерът на моите клетки";		//My cell stroke size
var Languageletter228="Размер на съотборници";		//Teammates size
var Languageletter229="Персонализирано фоново изображение";		//Custom background image
var Languageletter230="Персонализирано изображение на курсора";		//Custom cursor image
var Languageletter231="Изображение"	//Image URL
var Languageletter232="Изображение на курсора URL";		//Cursor image URL
var Languageletter233="Храна";		//Feed
var Languageletter234="Макро Хранене";		//Macro feed
var Languageletter235="Разделяне";		//Split
var Languageletter236="Двойно Разделяне";		//Double split
var Languageletter237="Поп Сплит";		//Popsplit
var Languageletter238="Разделяне на 16";		//Split 16
var Languageletter239="Паузиране на клетката";		//Cell pause
var Languageletter240="Покажи/скрий топ 5 отбора";		//Show/hide team top 5
var Languageletter241="Покажи/скрий конкретно време";		//Show/hide current time
var Languageletter242="Покажи/скрий разделен диапазон";		//Show/hide split range"
var Languageletter243="Покажи/скрий индикатор на съотборници";		//Show/hide teammates indicators
var Languageletter244="Покажи/скрий индикатори за разделяне";		//Show/hide split indicators
var Languageletter245="Покажи/скрий цветовете на опонента";		//Show/hide opponents colors
var Languageletter246="Щифт скинове (Персонализирано/обикновенно)";		//Toggle skins (custom/default)
var Languageletter247="Превключване на прозрачните скинове";		//Toggle transparent skins
var Languageletter248="Покажи/скрий скиновете";		//Show/hide skins
var Languageletter249="Покажи/скрий статистиките от играта";		//Show/hide game stats
var Languageletter250="Превключи на собствените си клетки (Малки/големи)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Покажи/скрий Храната";		//Show/hide food
var Languageletter252="Покажи/скрий Решетката";		//Show/hide grid
var Languageletter253="Покажи/скрий Минимап водачи";		//Show/hide minimap guides
var Languageletter254="Покажи/скрий чата";		//Show/hide chat
var Languageletter255="Покажи/скрий HUD";		//Show/hide HUD
var Languageletter256="Копирай класацията";		//Copy leaderboard
var Languageletter257="Покажи/скрий класацията";		//Show/hide leaderboard
var Languageletter258="Превключване на автомачен зуум";		//Toggle auto zoom
var Languageletter259="Въстановяване на зуум";		//Reset zoom
var Languageletter260="Превключване на мястото на смъртта";		//Toggle death location
var Languageletter261="Покажи историята на чата / Изчисти чата";		//Show chat history / Clear chat
var Languageletter262="Покажи/скрий фона на секторите";		//Show/hide background sectors
var Languageletter263="Покажи/скрий малките ботове";		//Show/hide small bots
var Languageletter264="Покажи/скрий имената";		//Show/hide names
var Languageletter265="Покажи/скрий имената на съотборниците";		//Show/hide teammates names
var Languageletter266="Покажи/скрий Масата";		//Show/hide mass
var Languageletter267="Покажи/скрий Минимапа";		//Show/hide minimap
var Languageletter268="Въведете съобщението за чат";		//Enter chat message
var Languageletter269="Бърз Respawn";		//Quick respawn
var Languageletter270="Превключване на автоматичen Respawn";		//Toggle auto respawn
var Languageletter271="Ниво на зуум";		//Zoom level 
var Languageletter271a="Глас към текст";		//Voice to text
var Languageletter271b="Показване на информация за духовните клетки";		//Show ghost cells information
var Languageletter271c="Automatisches Spiel";		//Auto Play
var Languageletter272="Покажи/скрий Панела за насочване";		//Show/hide targeting panel
var Languageletter273="Стартирай/спри Насочване  (Преследване)";		//Start/stop targeting (following)
var Languageletter274="Откажи Насочването";		//Cancel targeting
var Languageletter275="Change target";		//Change target
var Languageletter276="Показване на целта на минимап";		//Show target on the minimap
var Languageletter277="Покажи/скрий Предизвикателствата";		//Show/hide quest
var Languageletter278="За да зададете клавишна комбинация, кликнете върху полето за въвеждане и натиснете избрания от вас ключ.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="За да изтриете клавишна комбинация, кликнете върху полето за въвеждане и натиснете клавиша ИЗТРИЙ.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Възможни комбинации от клавиши с клавишите CTRL и ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Възстановете настройките по подразбиране";		//Restore default settings
var Languageletter282="Запази настройките";		//Save settings
var Languageletter283="Затвори";		//Close
var Languageletter284="Youtube играч";		//Youtube player
var Languageletter284a="Youtube Url";		// Youtube Url
var Languageletter285="Поставете вашето видео/плей листа тук";		//Paste your video/playlist here
var Languageletter286="Звукове";		//Sounds
var Languageletter287="Звуков сигнал за съобщения";		//Message notification sound
var Languageletter288="Звуков сигнал за управление";		//Command notification sound
var Languageletter289="Копирай Токен/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Токен";		//Token
var Languageletter290a="Табло"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Копирай";		//Copy


var Languageletter291a="Копирай класацията (L)";		//Copy Leaderboard (L)
var Languageletter291b="Копирайте Token / SIP и парола"; 	//Copy Token/SIP&Password
var Languageletter291c="Копирай всичко..."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="Влез в сървъра (Backspace)";		//Join server (Backspace)
var Languageletter293="Смени сървъра (+)";		//Change server (+)
var Languageletter294="История на класацията";		//Leaderboard history
var Languageletter295="Влез при приятел token, IP, Класация, име или клан таг...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Списък за изтриване"; //Clear list
var Languageletter295b="Въведете съобщението за чат..."; //Enter chat message...
var Languageletter298="Отбор на върха ";		//Team top 
var Languageletter299="Табло";		//Leaderbodard
var Languageletter300="Комуникация";		//Communication
var Languageletter301="Команди за скрипт на съобщения";		//Message Script Commands
var Languageletter302="Съобщение картини икони";		//Message Imgur Icons
var Languageletter303="Съобщение за видеоклипове в YouTube";		//Message Youtube Videos
var Languageletter304="Редактиране на имена";		//Edit names
var Languageletter305="[Само режим на спектър] Бинокъл";		//[Spectate Mode Only] Binoculars
var Languageletter306="Пусни / Пауза";		//Play / Pause
var Languageletter307="Цял екран";		//Fullscreen
var Languageletter308="Завъртане";		//Rotate
var Languageletter309="По подразбиране";		//Default
var Languageletter310="обратно";		//Back
var Languageletter311="Запази за по късно";		//Save for later
var Languageletter312="област";		//Region
var Languageletter313="Играчи";		//Players
var Languageletter314="Сървъри";		//Servers
var Languageletter315="[Целта не е зададена]";		//[Target not set]
var Languageletter316="Ръчен фон";		//Manual background
var Languageletter317="Икони за ръчно съобщение ";		//Manual Message Icons&Youtube
var Languageletter318="Чат позиция";		//Chat Position
var Languageletter319="URL адрес на Webhook (за изпращане на TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Табло";		//Leaderboard
var Languageletter321="Екипборд";		//Teamboard
var Languageletter322="Основно платно";		//Main Canvas
var Languageletter323="Основен банер";		//Main Banner
var Languageletter324="Здравей екип!";		//Hello Team!
var Languageletter325="Смейте се с екипа";		//Laugh to Team
var Languageletter326="Име на екипа за промяна на вашето";		//Team Change Name to yours
var Languageletter327="Трол на смъртта";		//Troll on Death
var Languageletter328="Отворете Музика в YouTube";		//Open Youtube Music
var Languageletter329="Безумен режим (Скрий всичко)";		//Insane mode (Hide Everything)
var Languageletter330="Url От изображението, започващо с http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="Минимап изображение URL";		//Minimap Image URL
var Languageletter332="Минимап текст";		//Minimap Text
var Languageletter333="Текст на лого на клавиатурата";		//Leaderboard Logo Text
var Languageletter333a="Изображение в класацията URL";		// Leaderboard Image URL
var Languageletter334="Отборбар лого текст";		//Teamboard Logo Text
var Languageletter334a="Отборбар изображение URL";		// Teamboard Image URL
var Languageletter335="Основно изображение на платноURL";		//Main Canvas Image URL
var Languageletter336="Икона на основния банер URL";		//Main Banner Icon URL
var Languageletter337="Основна връзка с банера URL";		//Main Banner Link URL
var Languageletter338="Икона";		//Icon
var Languageletter339="e.g";		//e.g
var Languageletter340="Url На YouTube, за да бъде показано";		//Url of youtube to be shown
var Languageletter341="Url На връзката за пренасочване";		//Url of link to redirect
var Languageletter342="Разхвърляй Webкука Url";		//Discord Webhook Url
var Languageletter342a="Икона на съобщението Текст";		//Message Icon Text
var Languageletter342b="Текст на съобщението в YouTube";		//Youtube Message Text
var Languageletter342c="Икона на съобщението снимка Url";		//Message Icon Imgur Url
var Languageletter342d="Съобщение в YouTube Url ";		//Youtube Message Url
var Languageletter343="Трябва да бъде изпълнено, за да функционира функцията";		//Must be filled for function to work.
var Languageletter344="Вторичен Webhook (по избор)";		//Secondary Webhook(optional)
var Languageletter345="Временно скриване / показване на всичко. Функция за Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Languageletter346="Изберете език";		//Choose Language
var Languageletter347="ВНИМАНИЕ! Изскачащите прозорци са блокирани в настройките.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Временно деблокиране";		//Temporary unblock

var Languageletter349="еликсири";	//Potions
var Languageletter350="Стари кожи";	//Old Skins
var Languageletter351="Специални оферти"; //Special Deals
var Languageletter352="Класирания"; //Leaderboards
var Languageletter353="Нова форма на идеи и статистически данни"; //New Ideas & Statistics Form
var Languageletter354="Видео кожи"; //Video Skins
var Languageletter355="Мини скриптове"; //Mini Scripts
var Languageletter356="Потребителски скриптове"; //User Scripts
var Languageletter357="Глас и камера Чат";	//Voice & Camera Chat
var Languageletter358="Моля, подкрепете разработването на Legend mod";	//Please support the development of Legend mod
var Languageletter359="Дизайн на псевдоним";	//Design Nickname Font
var Languageletter360="Сигнализирай за фалшивата кожа";	//Flag the Fake's Skin
var Languageletter361="Повече FPS";	//More FPS
var Languageletter362="име";	//Name
var Languageletter363="социален ID";	//Social ID
var Languageletter364="Разгъвания";	//Expansions
var Languageletter365="Yниверсаленl";	//Universal
var Languageletter366="Pезултат";	//Score
var Languageletter367="Pазстояние";	//Distance
var Languageletter368="Обща маса";	//Total Mass
var Languageletter369="мъртъв";	//Dead

var Premadeletter0="Активирана комуникация"; 		//Communication Activated
var Premadeletter1="Не може да се отвори тази UR на YouTubeL";		 //Cannot open this youtube URL
var Premadeletter2="Не можете да разговаряте, ако името на плейъра е> 15 символа"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Великденско яйце 1 активирано"; 		//Easter Egg 1 Activated
var Premadeletter4="Великденско яйце 2 е активирано";		//Easter Egg 2 Activated
var Premadeletter5="Великденско яйце 3 е активирано";		//Easter Egg 3 Activated
var Premadeletter6="Видеото работи по-добре на ванилия, посетете:";		//Video works better on vanilla, visit:
var Premadeletter7="Бележки: Съвместимостта <b> Facebook </ b> е по-добра от <b> Google Plus </ b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Забележки: Agar.io може да се свързва само с <b> Google Plus </ b> при събития със зареждане. Ако се появи изход, се присъединете отново към Agar.io или използвайте <b> Facebook </ b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Ако се случи излизане от събития при зареждане, изтрийте бисквитките на Chrome";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Прекъснато от сървъра :(";		//Disconnected from server :(
var Premadeletter11="Бяхте забранени, рестартирайте рутера си!";		//You were banned, restart your rooter!
var Premadeletter12="Свързана!";		//Connected!
var Premadeletter13="ИГРАЯ";		//PLAY
var Premadeletter14="НАБЛЮДАВАМ";		//SPECTATE
var Premadeletter15="Невалидно означение или сървър е затворено :(";		//Invalid token or server has closed :(
var Premadeletter16="Може да бъде актуализиран до";		//can be Updated to
var Premadeletter17="Добре дошъл обратно";			//Welcome back
var Premadeletter18="Вашата зона за бърз достъп и други области (от последния раздел) все още са забранени! Препоръчваме ви да ги активирате.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Активирайте ги";		//Enable Them
var Premadeletter20="Дръжте ги деактивирани";		//Keep Them Disabled
var Premadeletter21="Търсене на IP";		//Searching IP
var Premadeletter22="Вашият съотборник";		//Your teammate
var Premadeletter23="Иска да скриете всичко (класация и минимум)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Приемам";		//Accept
var Premadeletter25="НЯМА НАЧИН!";		//NO WAY!
var Premadeletter26="Иска да промените името си";		//wants you to change your name to
var Premadeletter27="Иска да активирате Troll при смърт";		//wants you to hide Enable Troll on death
var Premadeletter28="Иска да отворите плейъра на YouTube";			//wants you to open Youtube Player
var Premadeletter29="Намерена е класация";		//Leaderboard found
var Premadeletter30="Търсене";		//Search
var Premadeletter31="Класацията не бе намерена. Продължавай да опитваш...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Search was canceled";		//Search was canceled
var Premadeletter33="Вие сте невидими за отбор/клан";		//You are invisible to Team / Clan
var Premadeletter34="Вие сте видими за отбор/клан";		//You are visible to Team / Clan
var Premadeletter35="Скриване / Показване може да се използва само по време на възпроизвеждане";			//Hide/Show can be used only while playing
var Premadeletter36="Това не е валиден адрес на адрес Discord Webhook";		//This is not valid Discord Webhook address
var Premadeletter37="Сървърът е заключен";		//Server is locked
var Premadeletter38="Трябва да сте в режим на спектакъл";		//You must be on spectate mode
var Premadeletter39="Поради проблеми с спам, трябва да сте в игра и да използвате парола";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Авто вкл на YouTube";		//Auto Youtube On
var Premadeletter41="Авто изкл на YouTube";		//Auto Youtube Off
var Premadeletter42="Показ на преки път";		//Show Shortcuts
var Premadeletter43="Скри на преки път ";		//Hide Shortcuts
var Premadeletter44="Покажи XP бар";		//Show XP BAR
var Premadeletter45="Скрий  XP бар";		//Hide XP BAR
var Premadeletter45a = "объл Hud"; //Rounded Hud
var Premadeletter45b = "Квадрат Hud"; //Square Hud
var Premadeletter46 = "линейно оцветяване"; //Linear color Hud
var Premadeletter47 = "смел цвят на худ"; //Bold color Hud
var Premadeletter48="Покажи всичко";		//Show Everything
var Premadeletter49="Скрий всичко";		//Hide Everything
var Premadeletter50="Покажи таймер кал.";		//Show Timer Calc.
var Premadeletter51="Скрий таймер кал."		//Hide Timer Calc.
var Premadeletter52="Редак на имена";		//Edit Names
var Premadeletter52a="Затр имена";		//Close Names
var Premadeletter53="Авто безпл монети";		//Auto free coins
var Premadeletter54="Стоп безпл монети";		//Stop free coins
var Premadeletter55="Трол на смъртта";		//Troll on Death
var Premadeletter56="Няма трол на смъртта";		//No troll on Death

var Premadeletter57="Комуникация";		//Communication
var Premadeletter58="скрит";		//Hidden
var Premadeletter59="видим";		//Visible
var Premadeletter60="пауза";		//Pause

var Premadeletter61 = "Активирайте YT като фон";	//Enable YT as background
var Premadeletter62 = "Деактивирайте YT като фон;	//Disable YT as background";
var Premadeletter63 = "иска да отворите URL адреса";	//wants you to open the url
var Premadeletter64 = "иска да вградите и да пуснете този видеоклип на YouTube";	//wants you to embed and play this youtube video
var Premadeletter65 = "иска да се присъедините към следната Skype стая";	//wants you to join the following Skype room
var Premadeletter66 = "иска да се присъедините към следната зала Дискор";	//wants you to join the following Discord room
var Premadeletter67 = "иска да напуснете този сървър и да се присъедините към този нов";	//wants you to leave this server and join this new one
var Premadeletter68 = "Натиснахте"; //You pressed
var Premadeletter69 = "рестартирайте, ако"; //restart if
var Premadeletter70 = "капки"; //drops
var Premadeletter71 = "Анимирани кожи"; //Animated skins
var Premadeletter72 = "активиран"; //enabled
var Premadeletter73 = "изпускайте"; //drop
var Premadeletter74 = "кога"; //when
var Premadeletter75 = "Анимирани кожи ще бъдат"; //Animated skins will be
var Premadeletter76 = "хора с увреждания"; //disabled
var Premadeletter77 = "след като се върнете отново"; //after rejoin
var Premadeletter78 = "По-добро FPS"; //Better FPS
var Premadeletter79 = "когато 16"; //performance when 16
var Premadeletter80 = "Когато е активирано разширението Dying Light Expansion, Troll on death не може да се появи"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Частен сървър"; //Private Server
var Premadeletter82 = "Свържете се с някоя от тях"; //Connect to any
var Premadeletter83 = "сървър или направете своя собствена"; //server, or make your own
var Premadeletter84 = "Възпроизвеждане на игри, подобни на agario, ако знаете IP адреса на сървърите"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Изображението ви бе копирано в клипборда. Поставете го"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "към персонализираната област за URL адреси на кожата"; //to custom skin Url area
var Premadeletter87 = "Трябва да влезете, за да използвате снимката на потребителския си профил"; //You must Login to use picture of your profile
var Premadeletter88 = "Използвате грешна версия"; //You are using a wrong version
var Premadeletter89 = "Играта ще приключи сега"; //Game will terminate now
var Premadeletter90 = "Специални оферти"; //Special Deals
var Premadeletter91 = "Агарио може или не може да ви даде кожата, но само монетите"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Използвайте го на свой собствен риск"; //Use at your own risk
var Premadeletter92 = "Ако UID на приятеля ви не е наред, покупката ще се провали"; //If friend's UID is wrong, purchase will fail
var Premadeletter93 = "Фабричните настройки на UID"; //UID Factory Settings
var Premadeletter94 = "Трябва да влезете, за да заредите специални оферти"; //You must login to load Special Deals
var Premadeletter95 = "Фалшивото изображение е копирано в клипборда. Поставете го"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "за да персонализирате зоната на Url за да активирате функцията фалшив флаг"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Информирайте ме, когато приключите с Recaptcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "свърших"; //I have finished
var Premadeletter99 = "Няма значение"; //Never Mind
var Premadeletter100 = "Изчисляване на XP, моля изчакайте ..."; //Calculating your XP, please wait...
var Premadeletter101 = "правя"; //Do
var Premadeletter102 = "НЕ"; //NOT
var Premadeletter103 = "Натиснете"; //press
var Premadeletter104 = "Изтрийте URL адреса на персонализираната кожа"; //Erase custom skin URL
var Premadeletter105 = "изберете видео кожата";	//select video skin
var Premadeletter106 = "изчистване на видеоклипа"; //unselect video skin
var Premadeletter107 = "заглушаване на звука"; //mute audio
var Premadeletter108 = "Проектът LM"; //The LM Project
var Premadeletter109 = "Качи"; //Upload 
var Premadeletter109a = "Изтегли"; //Download
var Premadeletter109b = "Зареждане"; //Load

var Premadeletter110 = "не влизайте тук, освен ако не знаете какво е то";	//do not enter anything here unless you know what it is
var Premadeletter111 = "кликнете върху оранжевата икона, за да я купите"; //click on the orange icon to buy
var Premadeletter112 = "За някои начини на плащане"; //For some payment methods
var Premadeletter113 = "Близо";	//Close
var Premadeletter114 = "КОПИЕ"; //COPY	
var Premadeletter115 = "се използва за закупуване на оферти за вашите приятели"; //is used to buy offers for your friends
var Premadeletter116 = "За да правите покупки, трябва да сте влезли в профила си ..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Библиотека"; //Library
var Premadeletter118 = "посещение"; //visit
var Premadeletter119 = "Докладвайте като невярно (промяна на кожата)"; //Report as Fake (change Skin)
var Premadeletter120 = "Въведете вашето EXACT име на плейъра"; //Enter your EXACT name of the player
var Premadeletter121 = "Злоупотребата с играчи и неподходящата употреба ще доведат до UID на потребителите"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "за постоянна забрана от използването на това разширение"; //to permanent ban from usage of this extension
var Premadeletter128 = "Необходимо е потребителско влизане"; //User login needed
var Premadeletter129 = "Настройките са качени успешно"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "СЪРВЪРА"; //SERVER
var Premadeletter124 = "Избягвайте използването на видеоклипове по-големи от 6 минути"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Картата е фиксирана"; //Map fixed
var Premadeletter126 = "Влезли сте в"; //Logged in to
var Premadeletter127 = "Излезли"; //Logged out
var Premadeletter130 = "Oбщо"; //Total
var Premadeletter131 = "NEW"; //NEW
var Premadeletter132 = "Присъединете се обратно"; //Join Back
var Premadeletter133 = "Свържете се с последния изигран IP"; //Connect to last IP you played
var Premadeletter134 = "Северна Америка"; //North America
var Premadeletter135 = "Южна Америка"; //South America
var Premadeletter136 = "Европа"; //Europe
var Premadeletter137 = "Русия"; //Russia
var Premadeletter138 = "Турция"; //Turkey
var Premadeletter139 = "източна Азия"; //East Asia
var Premadeletter139a = "Китай"; //China
var Premadeletter140 = "Океания"; //Oceania
var Premadeletter140a = " -- Изберете регион -- "; // -- Select a Region -- 
var Premadeletter141 = "Безплатно"; //FFA
var Premadeletter142 = "Кралска битка"; //Battle Royale
var Premadeletter143 = "Отбори"; //Teams
var Premadeletter144 = "Eкспериментален"; //Experimental
var Premadeletter145 = "партия"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "ЕЗИЦИ"; //LANGUAGES
var Externalletter0b = "Изберете език"; //Choose a language
var Externalletter0c = "Промените ще се извършват напълно след рестартирането"; //Changes will take place completely after the restart
var Externalletter1 = "ИНФОРМАЦИЯ"; //INFORMATION
var Externalletter2 = "ШАБЛОНИ"; //TEMPLATES
var Externalletter3 = "РЪЧНИ ТАБЕЛИ"; //MANUAL TEMPLATES
var Externalletter4 = "Изберете шаблона си"; //Choose your template
var Externalletter5 = "Или изберете разширение"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "Изпратете кода на разработчиците"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Поставете скрипта си в тази Textarea, можете да заредите няколко скрипта"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Заредете скрипт от Textarea"; //Load Script from Textarea
var Externalletter8 = "Избирам"; //Choose
var Externalletter9 = "Изтриване на скрипта"; //Erase Script
var Externalletter10 = "име"; //Name
var Externalletter11 = "URL на суровия Github, или друг Raw Script, започвайки с"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Оставете този празен, ако скриптът не е импортиран от URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "ВАЖНО ЗАБЕЛЕЖКА: Не спазвайте URL адресите, които не работят, защото се използват като събития при зареждане. Ако сценарият поврежда събития при зареждане, ИЗТРИВАЙТЕ КООКИТЕ"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
