/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="Jimboy3100";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Αρχική";		//Home
var Languageletter1="Χρήστης";		//User
var Languageletter2="Ρυθμίσεις";		//Settings
var Languageletter3="Θέματα";		//Theme
var Languageletter4="Άμεσα Πλήκτρα";		//Hotkeys
var Languageletter5="Youtube & Ήχοι";		//Youtube & Sounds
var Languageletter6="Εργαλεια";		//Tools
var Languageletter7="Για δημόσιο αφησέ το κενό, ή βαλε κωδικό η το σύμβολο της ομάδας σου";		//Password/Tag
var Languageletter7a="Κωδικός / Σύμβολο"	;	//Password/Tag
var Languageletter8="Το όνομα σου, μέχρι 50 χαρακτήρες ωρατοί, μέχρι 15 για να ανοίξει η ενδοεπικοινωνία'";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Όνομα";		//Name
var Languageletter9="Βάλε τον υπερσύνδεσμο του δικού σου skin";		//Insert your manual skin weblink
var Languageletter9a="Ο υπερσύνδεσμος για το δικό σου skin";		//Manual direct skin URL
var Languageletter10="Βάλε περιοχή";		//The region to play
var Languageletter11="Έίδος παιχνιδιού";		//The mode to play
var Languageletter12="Συνδεθείτε στο διακομιστή ή επαναφέρετε την επικοινωνία";		//Connect to server, or restablish communication
var Languageletter12a="Συνδεση";		//Connect
var Languageletter13="Συμμετοχη";		//Join
var Languageletter14="Φιλοξενουμενος";		//Play as guest
var Languageletter15="Συνδεση Μεσω";		//Login and Play
var Languageletter16="Επιθεωρηση";		//Spectate
var Languageletter17="Συνδεση Μεσω Facebook";		//Sign in with Facebook
var Languageletter18="Συνδεση Μεσω Google";			//Sign in with Google
var Languageletter19="Παιξε";		//Play
var Languageletter20="Αγορα";		//Shop
var Languageletter21="Δωρεάν Νομίσματα";		//Free Coins
var Languageletter22="Δώρα";		//Gifts
var Languageletter23="Καθημερινες Αποστολες";			//Daily Quests
var Languageletter24="Εικόνες Skin";		//Skins
var Languageletter25="Προωθητικό Video Legend";		//Legend Promo Video
var Languageletter25a="Φόρμα ιδεών και στατιστικών";		//New Ideas & Statistics Form
var Languageletter25b="Πληροφορίες & Πρότυπα";		//Mod Info & Templates
var Languageletter26="Προσθηκη Εικονων";		//Add skins
var Languageletter26a="Διακομιστής αντιγραφής, κωδικός πρόσβασης, πίνακας ομάδας και ηγετών"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Αποσύνδεση";		//Logout
var Languageletter32="Χρησιμοποιήθηκε";		//Times Used
var Languageletter33="Legend επέκταση απο";		//Legend Mod by
var Languageletter34="Μετάφραση απο";		//Translation by
var Languageletter35="Αντιγράψτε τα ονόματα Ηγετών και ονόματα κελιών. (Πατήστε x για εμφάνιση / απόκρυψη)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Αναπαρασταση";		//Animation
var Languageletter37="Καθυστέρηση Αναπαραστασης";		//Animation delay: 
var Languageletter37a="Αυτόματο ζουμ";		// Auto zoom
var Languageletter37b="Ζουμ";		// Zoom
var Languageletter38="Ταχύτητα ζουμ";		//Zoom speed: 
var Languageletter39="Συνεχιση";			//Respawn
var Languageletter40="Αυτόματη συνέχιση";		//Auto respawn 
var Languageletter41="Γρήγορη συνέχιση ";			//Quick respawn 
var Languageletter41a="Ξεκινήστε με ειδικά εφέ";			//Spawn special effects 
var Languageletter41b="Συγχώνευση χρονοδιακόπτη ";			//Merge timer off
var Languageletter41c="Προτείνεται να είναι ενεργοποιημένη η μείωση Lag";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Ήχος πυροβολισμού ιών";			//Virus shot sound

var Languageletter42="Ονοματα";			//Names
var Languageletter43="Χωρίς ονόματα";		//No names 
var Languageletter44="Βέλτιστα ονόματα";		//Optimized names 
var Languageletter45="Αυτόματη απόκρυψη ονομάτων";		//Auto hide names 
var Languageletter46="Κρύψε το όνομα μου";		//Hide my name 
var Languageletter47="Απόκρυψη ονομάτων συμπαικτών";		//Hide teammates names 
var Languageletter48="Προσβολή ονόματος";		//Names stroke 
var Languageletter49="Μαζα";		//Mass
var Languageletter50="Εμφάνιση μάζας";		//Show mass 
var Languageletter51="Βελτιστοποιημένη μάζα ";	//Optimized mass
var Languageletter52="Αυτόματη απόκρυψη μάζας";			//Auto hide mass 
var Languageletter53="Κρύψτε τη μάζα μου";		//Hide my mass 
var Languageletter54="Απόκρυψη μάζας εχθρών";		//Hide enemies mass 
var Languageletter55="Συντόμευση μάζας";		//Short mass
var Languageletter56="Χτυπήματα ιών";		//Virus shots 
var Languageletter57="Προσβολή μάζας";		//Mass stroke 
var Languageletter58="Εικονες (skin)";		//Skins
var Languageletter59="Όχι skins ";		//No skins 
var Languageletter60="Προσαρμοσμένη εικόνα";		//Custom skins 
var Languageletter61="Εικόνες άνευ επέκτασης";		//Vanilla skins 
var Languageletter61a="Φυσική ζελέ";		//Jelly physics 
var Languageletter61b="Βίντεο δέρματα";		//Video skins
var Languageletter61c="Ήχος από άλλα βίντεο δέρματα όταν και οι δύο C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Βελτιστοποιημένο φαγητό";		//Optimized food 
var Languageletter6a2="Φαγητο";		//Food 
var Languageletter63="Αυτόματη απόκρυψη φαγητού (μάζα)";		//Auto hide food
var Languageletter64="Αυτόματη απόκρυψη φαγητού (ζούμ)";		//Auto hide food (zoom) 
var Languageletter65="Τροφή σαν ουράνιο τόξο";		//Rainbow food 
var Languageletter66="Διαφανεια / χρωματα";		//Transparency / colors
var Languageletter67="Χωρίς χρώματα";		//No colors 
var Languageletter68="Προσαρμοσμένο χρώμα μου";		//My custom color 
var Languageletter69="Διαφάνια εικόνας μου ";		//My transparent skin 
var Languageletter70="Διαφανείς εικόνες";		//Transparent skins 
var Languageletter70a="Διαφανείς κελιά";		//Transparent cells
var Languageletter71="Διαφανείς εικόνες ιοί ";		//Transparent viruses 
var Languageletter71a="Η λάμψη του ιού";		//Virus Glow
var Languageletter71b="Ζωγραφισμένα χρώματα ουράνιου τόξου";		//Animated rainbow colors

var Languageletter72="Πλεγμα / τομεις";		//Grid / sectors
var Languageletter73="Εμφάνιση πλέγματος";		//Show grid 
var Languageletter74="Εμφάνιση τομέων φόντου ";		//Show background sectors 
var Languageletter75="Εμφάνιση περιθωρίων χάρτη ";		//Show map borders 
var Languageletter75a="Λάμψη των συνόρων";		//Border Glow

var Languageletter76="Συζητηση";		//Chat
var Languageletter77="Απενεργοποιήση συζήτησης ";		//Disable chat 
var Languageletter78="Ήχοι ειδοποιήσεων ";		//Sound notifications 
var Languageletter79="Εικόνες Emoji";		//Emoticons 
var Languageletter80="Εμφάνιση εικόνων στη συνομιλία ";		//Show images on chat 
var Languageletter81="Εμφάνιση βίντεο στη συνομιλία ";		//Show videos on chat 
var Languageletter82="Κουτί συνομιλίας αντί για αναδυόμενα παράθυρα";		//Chatbox instead of popups 
var Languageletter82a="Μικρος χαρτης";		//Minimap
var Languageletter82b="Εμφάνιση μικρού χάρτη";		//Show minimap 
var Languageletter82c="Εμφάνιση πλέγματος μικρού χάρτη";		//Show minimap grid 
var Languageletter82d="Εμφάνιση οδηγιών μικρού χάρτη";		//Show minimap guides 
var Languageletter82e="Συμπαίκτες σε ένα χρώμα";		//One-colored teammates 
var Languageletter82f="Εμφάνιση επιπλέον οδηγοί μίνι χάρτη";		//Show extra minimap guides
var Languageletter82g="Εμφάνιση κελιών φάντασμα";		//Show ghost cells

var Languageletter83="Βοηθοι";		//Helpers
var Languageletter84="Χρώματα αντιπάλων";		//Opponents colors
var Languageletter85="Δαχτυλίδια αντιπάλων";		//Opponents rings 
var Languageletter86="Χρώματα ιών";		//Viruses colors 
var Languageletter87="Περιοχή διαχωρισμού";		//Split range 
var Languageletter87a="Γρήγορη περιοχή διπλού διαχωρισμού";		//Quick double split range
var Languageletter87b="Αργή περιοχή διπλού διαχωρισμού";		//Slow double split range

var Languageletter88="Περιοχή διαχωρισμού ιών";		//Viruses range 
var Languageletter89="Παρακολούθηση δρομέα ποντικιού ";		//Cursor tracking 
var Languageletter90="Δείκτες συμπαίκτών";		//Teammates indicators 
var Languageletter90a="Κύματα φάντασμα";		//Ghost cells 

var Languageletter91="Ελεγχος ποντικιου";		//Mouse control
var Languageletter92="Αριστερό κλίκ Ποντικιού - Διαχωρισμός";		//LMB - Mouse split 
var Languageletter93="Δεξί κλίκ Ποντικιού - Τροφοδοσία";		//RMB - Mouse feed 
var Languageletter94="Αντιστροφή κουμπιών ποντικιού";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="Εμφάνιση κορυφαίων 5 της ομάδας";		//Show team top 5 
var Languageletter96="Εμφάνιση στόχευσης";		//Show targeting 
var Languageletter96a="Εμφάνιση μάζας leaderboard";		//Show leaderboard mass

var Languageletter97="Κεντραρισμένος πίνακας ηγετών";		//Centered leaderboard 
var Languageletter97a="Επικεφαλίδα του leaderboard";		//\"Leaderboard\" header 

var Languageletter98="Στατιστικά παιχνιδιού στην κορυφή";		//Game stats at the top 
var Languageletter98a="Skins στην ομάδα εργασίας";		//Skins on teamboard

var Languageletter99="Στατιστικα";		//Stats
var Languageletter100="Εμφάνιση στατιστικών παιχνιδιού";		//Show game stats 
var Languageletter101="Στατιστικά παιχνιδιού";		//Game stats
//the \' is needed
var Languageletter102="Εχθρικό";		//Enemy\'s 		
var Languageletter103="Δικό μας";		//Our
var Languageletter104="Ελάχιστη μάζα του συμπαίκτη - tricksplit";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Μέγιστη μάζα του εχθρού για pre split";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Εμφάνιση τρέχουσας ώρας";		//Show current time 
var Languageletter106="Προσθετα";		//Extras
var Languageletter107="Παραλείψτε στατιστικών μετά το θάνατο";		//Skip stats after death 
var Languageletter108="Εμφάνιση αποστολής";		//Show quest 
var Languageletter108a="Ήχοι παιχνιδιου";  //Game Sounds
var Languageletter108b="Ήχοι Μενού"; //Menu Sounds
var Languageletter109="Αποκλεισμός αναδυόμενων παραθύρων";		//Block popups (ads/shop/quest) 
var Languageletter109a="ΦΩΝΗ"; //Voice
var Languageletter109b="Πρόθεμα-φωνής"; //Voice-Prefix
var Languageletter109c="Φωνητική-γλώσσα"; //Voice-language
var Languageletter109d="Απενεργοποίηση"; //UnPause

var Languageletter110="-- Ποιότητα γραφικών --";		//-- Graphics Quality --
var Languageletter111="Γραφικά: Ρετίνα";		//Graphics: Retina
var Languageletter112="Γραφικά: Καλά";		//Graphics: High
var Languageletter113="Γραφικά: Μεσαία";		//Graphics: Medium"
var Languageletter114="Γραφικά: Χαμηλά";		//Graphics: Low
var Languageletter115="Γραφικά: Πολύ χαμηλά";		//Graphics: Very Low
var Languageletter116="Εξαγωγη / εισαγωγη ρυθμισεων";		//Export / import settings
var Languageletter117="Επαναφορα αρχικών ρυθμίσεων";		//Restore default settings
var Languageletter118="Εξαγωγη Ρυθμισεων";		//Export settings
var Languageletter119="Εισαγωγη Ρυθμισεων";		//Import settings
var Languageletter120="Για να εξαγάγετε επιλεγμένες ρυθμίσεις, αντιγράψτε τον παρακάτω κώδικα και αποθηκεύστε τον σε ένα αρχείο κειμένου που κωδικοποιείται στο Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Για να εισαγάγετε επιλεγμένες ρυθμίσεις, επικολλήστε έναν εξαγόμενο κώδικα παρακάτω και πατήστε το κουμπί 'Εισαγωγή ρυθμίσεων'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Εντολές";		// Commands
var Languageletter123="Άμεσα Πλήκτρα'";		// Hotkeys
var Languageletter124="Προφίλ";		// Profiles
var Languageletter125="Ρυθμίσεις";		// Settings
var Languageletter126="Θέματα";		// Theme
var Languageletter127="Εξαγωγη Ρυθμισεων";		//Export settings
var Languageletter128="Εισαγωγη Ρυθμισεων";		//Import settings
var Languageletter129="Βασικά θέματα";		//Basic theming
var Languageletter130="Mενού";		//Menu
var Languageletter131="Περίγυρος παιχνιδιού - HUD'";		//HUD
var Languageletter132="Ομιλία";		//Chat
var Languageletter133="Μίνι χάρτης";		//Minimap
var Languageletter134="Γραφικά / δρομείς";		//Graphics / cursors
var Languageletter135="Προκαθορισμένα θέματα";		//Theme preset
var Languageletter136="Αυθεντικό Legend";		//Legend Original
var Languageletter137="Τρελό στυλ";		//Crazy Style 1
var Languageletter139="Φόντο";		//Background
var Languageletter140="Σύνορα χάρτη";		//Map borders
var Languageletter141="Πλέγμα";		//Grid
var Languageletter142="Γραμματοσειρές τομέων";		//Sectors font
var Languageletter143="Ονόματα";		//Names
var Languageletter144="Προσβολή ονόματος";		//Names stroke
var Languageletter145="Μάζα";		//Mass
var Languageletter146="Προσβολή μάζας";		//Mass stroke
var Languageletter147="Προσβολή Ιού";		//Virus stroke
var Languageletter148="Ιός";		//Virus
var Languageletter148a="Μητρικό κύτταρο";		//Mothercell
var Languageletter148b="Μητρική κυτταρική εγκεφαλίτιδα";		//Mothercell stroke
var Languageletter149="Φαγητό";		//Food
var Languageletter150="Δείκτης συμπαικτών";		//Teammate indicator
var Languageletter151="Παρακολούθηση δρομέα";		//Cursor tracking
var Languageletter152="Περιοχή διαχωρισμού";		//Split range
var Languageletter153="Γραμματοσειρά ονομάτων";		//Names font
var Languageletter154="Γραμματοσειρά μάζας";		//Mass font
var Languageletter154a="Μεγαλύτερος";		//Bigger
var Languageletter154b="Μικρότερος";		//Smaller
var Languageletter155="Γραμματοσειρές τομέων";		//Sectors font
var Languageletter157="Μέγεθος γραμματοσειράς τομέων";		//Sectors font size
var Languageletter158="Κλίμακα Ονόματος";		//Names scale
var Languageletter159="Κλίμακα μάζας";		//Mass scale
var Languageletter160="Κλίμακα μάζας ιού";		//Virus mass scale
var Languageletter161="Κλίμακα προσβολής ονόματος";		//Text stroke scale
var Languageletter162="Μέγεθος Φαγητού";		//Food size:
var Languageletter163="Μέγεθος προσβολής ιού";		//Virus stroke size
var Languageletter164="Πάχος συνόρων χάρτη";		//Map borders width
var Languageletter165="Πάχος Τομέων";		//Sectors grid width
var Languageletter166="Διαφανείς μπάλες (κελιά)";		//Cells transparency
var Languageletter167="Διάφανα skins";		//Skins transparency
var Languageletter168="Διαφανείς ιοί";		//Virus transparency
var Languageletter169="Διαφανα όνοματα και μάζα";		//Names & mass transparency
var Languageletter170="Επαναφορά ρυθμίσεων θεμάτων";		//Restore theme default settings
var Languageletter171="Αποθηκευση ρυθμισεων";		//Save settings
var Languageletter172="Θέμα μενού";		//Menu theme
var Languageletter173="Φόντο";		//Background
var Languageletter174="Διαφάνεια";		//Transparency
var Languageletter175="Κύριο χρώμα";		//Main color
var Languageletter176="Κείμενο κουμπιών";		//Button text
var Languageletter177="Πίνακας";		//Panel
var Languageletter179="Κείμενο πίνακα";		//Panel text
var Languageletter181="Κουμπί";		//Button
var Languageletter189="Εικόνα φόντου πίνακα";		//Panel background image
var Languageletter190="'URL της εικόνας'";		//Image URL
var Languageletter191="Κύριο χρώμα";		//Main color
var Languageletter192="Φόντο";		//Background
var Languageletter193="Κείμενο";		//Text
var Languageletter194="Στατιστικά";		//Stats
var Languageletter195="Χρόνος";		//Time
var Languageletter196="Μάζα των κορυφαίων 5";		//Top 5 mass
var Languageletter197="Πίνακας ηγετών - Εγώ";		//Leaderboard - me
var Languageletter198="Πίνακας ηγετών - Ομάδα";		//Leaderboard - teammate
var Languageletter199="Γραμματοσειρά περιγύρου παιχνιδιού";		//HUD font
var Languageletter200="Κλίμακα περίγυρου παιχνιδιού - HUD";		//HUD scale: 
var Languageletter201="Φόντο μηνυμάτων";		//Message background
var Languageletter202="Κείμενο μηνυμάτων";		//Message text
var Languageletter203="Ωρα κειμένου";		//Message time
var Languageletter204="Όνομα αποστολέα";		//Message nick
var Languageletter205="Φόντο εντολής";		//Command background
var Languageletter206="Κείμενο εντολής";		//Command text
var Languageletter207="Ώρα εντολής";		//Command time
var Languageletter208="Αποστολέας εντολής";		//Command nick
var Languageletter209="Χρώμα κουτιού συνομιλίας";		//Chatbox color
var Languageletter210="Κλίμακα συνομιλίας";		//Chat scale
var Languageletter211="Τομείς";		//Sectors
var Languageletter212="Τρέχων τομέας";		//Current sector
var Languageletter213="Όνομα";		//Nick
var Languageletter214="Προσβολή ονόματος";		//Nick stroke
var Languageletter215="Η μπάλα μου";		//My cell
var Languageletter216="Προσβολή μπάλας μου";		//My cell stroke
var Languageletter217="Συμπαίκτες";		//Teammates
var Languageletter218="Θέση θανάτου";		//Death location
var Languageletter219="Οδηγοί";		//Guides
var Languageletter220="Γραμματοσειρά μικρού χάρτη";		//Minimap font
var Languageletter221="Γραμματοσειρά ονόματος";		//Nick font
var Languageletter222="Μήκος μικρού χάρτη";		//Minimap width
var Languageletter223="Διαφάνεια των τομέων";		//Sectors transparency
var Languageletter224="Μέγεθος ονόματος";		//Nick size
var Languageletter225="Μέγεθος προσβολής ονόματος";		//Nick stroke size
var Languageletter226="Μέγεθος της μπάλας μου";		//My cell size
var Languageletter227="Μέγεθος προσβολής της μπάλας";		//My cell stroke size
var Languageletter228="Μέγεθος συμπαικτών";		//Teammates size
var Languageletter229="Προσαρμοσμένη εικόνα φόντου";		//Custom background image
var Languageletter230="Προσαρμοσμένη εικόνα δρομέα";		//Custom cursor image
var Languageletter231="URL της εικόνας";		//Image URL
var Languageletter232="URL εικόνας δρομέα";		//Cursor image URL
var Languageletter233="Τάισε";		//Feed
var Languageletter234="Γρήγορο ταίσμα (πατημένο πλήκτρο)";		//Macro feed
var Languageletter235="Χώρισμα";		//Split
var Languageletter236="Διπλό χώρισμα";		//Double split
var Languageletter237="Διπλό χώρισμα για Popsplit";		//Popsplit
var Languageletter238="Χώρισμα 16";		//Split 16
var Languageletter239="Ακινητοποίηση μπάλας";		//Cell pause
var Languageletter240="Εμφάνιση / απόκρυψη 5 κορυφαίων ομάδας";		//Show/hide team top 5
var Languageletter241="Εμφάνιση / απόκρυψη τρέχουσας ώρας";		//Show/hide current time
var Languageletter242="Εμφάνιση / απόκρυψη εύρους χωρίσματος";		//Show/hide split range"
var Languageletter243="Εμφάνιση / απόκρυψη δεικτών συμπαικτών";		//Show/hide teammates indicators
var Languageletter244="Εμφάνιση / απόκρυψη δεικτών χωρίσματος";		//Show/hide split indicators
var Languageletter245="Εμφάνιση / απόκρυψη χρωμάτων αντιπάλωνs";		//Show/hide opponents colors
var Languageletter246="προσαρμοσμένo / προεπιλεγμένη)";		//Toggle skins (custom/default)
var Languageletter247="Εναλλαγή διαφάνειας skins";		//Toggle transparent skins
var Languageletter248="Εμφάνιση / απόκρυψη skins";		//Show/hide skins
var Languageletter249="Εμφάνιση / απόκρυψη στατιστικών παιχνιδιών";		//Show/hide game stats
var Languageletter250="Εναλλαγή κελιών-μπάλες(μικρότερο / μεγαλύτερο)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Εμφάνιση / απόκρυψη φαγητού";		//Show/hide food
var Languageletter252="Εμφάνιση / απόκρυψη πλέγματος";		//Show/hide grid
var Languageletter253="Εμφάνιση / απόκρυψη οδηγών μικρού χάρτη";		//Show/hide minimap guides
var Languageletter254="Εμφάνιση / απόκρυψη ομιλίας";		//Show/hide chat
var Languageletter255="Εμφάνιση / απόκρυψη περίγυρου παιχνιδιού - HUD ";		//Show/hide HUD
var Languageletter256="Αντιγραφή πίνακα ηγετών";		//Copy leaderboard
var Languageletter257="Εμφάνιση / απόκρυψη πίνακα ηγετών";		//Show/hide leaderboard
var Languageletter258="Εναλλαγή αυτόματου ζουμ";		//Toggle auto zoom
var Languageletter259="Επαναφορά ζουμ";		//Reset zoom
var Languageletter260="Εναλλαγή θέσης θανάτου";		//Toggle death location
var Languageletter261="Εμφάνιση ιστορικού συνομιλίας / Εκκαθάριση συνομιλίας";		//Show chat history / Clear chat
var Languageletter262="Εμφάνιση / απόκρυψη τομέων φόντου";		//Show/hide background sectors
var Languageletter263="Εμφάνιση / απόκρυψη μικρών bots";		//Show/hide small bots
var Languageletter264="Εμφάνιση / απόκρυψη ονομάτων";		//Show/hide names
var Languageletter265="Εμφάνιση / απόκρυψη ονομάτων συμπαικτών";		//Show/hide teammates names
var Languageletter266="Εμφάνιση / απόκρυψη μάζας";		//Show/hide mass
var Languageletter267="Εμφάνιση / απόκρυψη μικρού χάρτη";		//Show/hide minimap
var Languageletter268="Εισαγωγή μηνύματος συνομιλίας";		//Enter chat message
var Languageletter269="Γρήγορη επανεκκίνηση";		//Quick respawn
var Languageletter270="Μεταβολή γρήγορης επανεκκίνησης";		//Toggle auto respawn
var Languageletter271="Επίπεδο ζουμ ";		//Zoom level 
var Languageletter271a="Φωνή στο κείμενο";		//Voice to text
var Languageletter271b="Εμφάνιση πληροφοριών κυψελών φάντασμα";		//Show ghost cells information
var Languageletter271c="Αυτόματο παιχνίδι";		//Auto Play
var Languageletter272="Εμφάνιση / απόκρυψη πλαισίου στόχευσης";		//Show/hide targeting panel
var Languageletter273="Εκκίνηση / διακοπή (επόμενου) εντοπισμού στόχευσης";		//Start/stop targeting (following)
var Languageletter274="Ακύρωση στόχευσης";		//Cancel targeting
var Languageletter275="Αλλαγή στόχου";		//Change target
var Languageletter276="Ένδειξη στόχου στον μικρό χάρτη";		//Show target on the minimap
var Languageletter277="Εμφάνιση / απόκρυψη αποστολής";		//Show/hide quest
var Languageletter278="Για να αντιστοιχίσετε ένα πλήκτρο πρόσβασης, κάντε κλικ στο πεδίο εισαγωγής και πατήστε το κλειδί που επιλέξατε.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Για να διαγράψετε ένα πλήκτρο πρόσβασης, κάντε κλικ στο πεδίο εισαγωγής και πατήστε το πλήκτρο DELETE.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Πιθανοί συνδυασμοί πλήκτρων με τα πλήκτρα CTRL και ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Επαναφορα αρχικων ρυθμισεων";		//Restore default settings
var Languageletter282="Αποθηκευση ρυθμισεων";		//Save settings
var Languageletter283="Εξοδος";		//Close
var Languageletter284="Αναπαραγωγη Youtube";		//Youtube player
var Languageletter284a="Youtube υπερσύνδεσης Url";		// Youtube Url
var Languageletter285="Επικολλήστε το βίντεο / λίστα αναπαραγωγής εδώ'=";		//Paste your video/playlist here
var Languageletter286="Ηχοι";		//Sounds
var Languageletter287="Ήχος ειδοποίησης μηνύματος";		//Message notification sound
var Languageletter288="Ήχος ειδοποίησης εντολής";		//Command notification sound
var Languageletter289="Αντιγραφή διεύθυνσης Πίστας";		//Copy Token/SIP

//keep this small
var Languageletter290="Πιστα";		//Token
var Languageletter290a="Ηγέτες"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Αντιγρ";		//Copy
var Languageletter291b="Αντιγραφή πίστας / IP & Κωδικού"; 	//Copy Token/SIP&Password
var Languageletter291c="Αντιγραφή όλων"; //Copy Token/SIP, Password, Leaderboard...
var Languageletter291a="Αντιγραφή Πίνακα ηγετών (L)";		//Copy Leaderboard (L)
var Languageletter292="Συνδεση σε Server (Backspace)";		//Join server (Backspace)
var Languageletter293="Αλλαγή Πίστας (+)";		//Change server (+)
var Languageletter294="Ιστορικό ηγετών";		//Leaderboard history
var Languageletter295="Εισάγετε διακριτικό φίλου, IP, τον πίνακα ηγετών, το όνομα ή ετικέτα ομάδας...";		//Enter friends token, IP, leaderboard, name or clan tag...
var Languageletter295a="Διαγραφή λίστας"; //Clear list
var Languageletter295b="Εισαγάγετε μήνυμα συνομιλίας ..."; //Enter chat message...
var Languageletter298="Ομάδα";		//Team
var Languageletter299="Ηγετες";		//Leaderbodard
var Languageletter300="Επικοινωνία";		//Communication
var Languageletter301="Μηνύματα Εντολών";		//Message Script Commands
var Languageletter302="Μηνύματα Εικόνων Imgur";		//Message Imgur Icons
var Languageletter303="Μηνύματα Βίντεο Youtube";		//Message Youtube Videos
var Languageletter304="Επεξεργασία ονομάτων";		//Edit names
var Languageletter305="[Μόνο με λειτουργία Επιθεώρησης] Διόπτρες";		//[Spectate Mode Only] Binoculars
var Languageletter306="Παίξε / Παύση";		//Play / Pause
var Languageletter307="Πλήρης Οθόνη";		//Fullscreen
var Languageletter308="Περιστροφή";		//Rotate
var Languageletter309="Επαναφορα";		//Default
var Languageletter310="Πισω";		//Back
var Languageletter311="Σώσε για μετά";		//Save for later
var Languageletter312="Περιοχή";		//Region
var Languageletter313="Παίκτες";		//Players
var Languageletter314="Πίστες";		//Servers
var Languageletter315="[Στόχος μη ορισμ.]";		//[Target not set]
var Languageletter316="Μη αυτόματο φόντο";		//Manual background
var Languageletter317="Επιλογή εικον. μηνυμ. & Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Θέση συνομιλίας";		//Chat Position
var Languageletter319="Discord Webhook Url (για αποστολή πίστας)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Ηγέτες";		//Leaderboard
var Languageletter321="Ηγέτες Ομάδας";		//Teamboard
var Languageletter322="Κύριος Καμβάς";		//Main Canvas
var Languageletter323="Κύριο banner";		//Main Banner
var Languageletter324="Γεια σας ομάδα!";		//Hello Team!
var Languageletter325="Κοροϊδευω την ομάδα";		//Laugh to Team
var Languageletter326="Η ομάδα να βάλει το δικό μου όνομα";		//Team Change Name to yours
var Languageletter327="Τρόλαρε στον θάνατο";		//Troll on Death
var Languageletter328="Άνηξε το Youtube";		//Open Youtube Music
var Languageletter329="Παράφρων λειτοθργία (Κρύψτα όλα)";		//Insane mode (Hide Everything)
var Languageletter330="Υπεσύνδεσμος εικόνας ο οποίος να αρχίζει με  http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="URL εικόνας μικρόυ χάρτη";		//Minimap Image URL
var Languageletter332="Κείμενο μικρού χάρτη";		//Minimap Text
var Languageletter333="Κείμενο κεφαλής ηγετών";		//Leaderboard Logo Text
var Languageletter333a="URL εικόνας ηγετών";		// Leaderboard Image URL
var Languageletter334="Teamboard Logo Text";		//Teamboard Logo Text
var Languageletter334a="Κείμενο κεφαλής ομάδας";		// Teamboard Image URL
var Languageletter335="URL εικόνας κεντρικού καμβά";		//Main Canvas Image URL
var Languageletter336="URL εικόνας κεντρικού banner";		//Main Banner Icon URL
var Languageletter337="URL υπερσυνδέσμου κεντρικού banner";		//Main Banner Link URL
var Languageletter338="Εικόνα";		//Icon
var Languageletter339="π.χ.";		//e.g
var Languageletter340="Url του youtube για αποστολή";		//Url of youtube to be shown
var Languageletter341="Url για υπερσύνδεση";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="Κείμενο στην εικόνα μηνήματος";		//Message Icon Text
var Languageletter342b="Κείμενο στο μηνήμα Youtube";		//Youtube Message Text
var Languageletter342c="Υπερσύνδ. Imgur εικόνας ";		//Message Icon Imgur Url
var Languageletter342d="Υπερσύνδ. Youtube ";		//Youtube Message Url
var Languageletter343="Πρέπει να υπάρχει για την ενεργοποίηση της λειτουργίας";		//Must be filled for function to work.
var Languageletter344="Δεύτερο Webhook(προαιρετικό)";		//Secondary Webhook(optional)
var Languageletter345="Προσωρινή Απόκρυψη / Εμφάνιση όλων. Λειτουργία για τους Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Languageletter346="Επέλεξε γλώσσα";		//Choose Language
var Languageletter347="ΠΡΟΕΙΔΟΠΟΙΗΣΗ! Τα αναδυόμενα παράθυρα αποκλείονται στις ρυθμίσεις.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Προσωρινή απεμπλοκή";		//Temporary unblock

var Languageletter349="Φίλτρα";	//Potions
var Languageletter350="Παλιά Skins";	//Old Skins
var Languageletter351="Ειδικές προσφορές"; //Special Deals
var Languageletter352="Ηγέτες"; //Leaderboards
var Languageletter353="Φόρμα νέων ιδεών και στατιστικών"; //New Ideas & Statistics Form
var Languageletter354="Βίντεο Skins"; //Video Skins
var Languageletter355="Μικροί κώδικες"; //Mini Scripts
var Languageletter356="Κώδικες χρηστών"; //User Scripts
var Languageletter357="Συνομιλία φωνής & κάμερας";	//Voice & Camera Chat
var Languageletter358="Υποστηρίξτε την ανάπτυξη του Mod Legend";	//Please support the development of Legend mod
var Languageletter359="Σχεδίαση γραμματοσειράς Ονόματος";	//Design Nickname Font
var Languageletter360="Σηματοδοτήστε το skin των Fake's";	//Flag the Fake's Skin
var Languageletter361="Περισσότερα FPS";	//More FPS
var Languageletter362="Όνομα";	//Name
var Languageletter363="Κοινονικό ID";	//Social ID
var Languageletter364="Επεκτάσεις";	//Expansions
var Languageletter365="Παγκόσμιος";	//Universal
var Languageletter366="Σκορ";	//Score
var Languageletter367="Απόσταση";	//Distance
var Languageletter368="Συνολική μάζα";	//Total Mass
var Languageletter369="Νεκρός";	//Dead

var Premadeletter0="Η επικοινωνία ενεργοποιήθηκε"; 		//Communication Activated
var Premadeletter1="Δεν είναι δυνατό να ανοίξει αυτή η διεύθυνση URL του YouTube";		 //Cannot open this youtube URL
var Premadeletter2="Δεν μπορείτε να συνομιλήσετε αν το όνομα παίκτη > 15 χαρακτήρες"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Ενεργοποιήθηκε το Πασχαλινό Αυγό 1"; 		//Easter Egg 1 Activated
var Premadeletter4="Ενεργοποιήθηκε το Πασχαλινό Αυγό 2";		//Easter Egg 2 Activated
var Premadeletter5="Ενεργοποιήθηκε το Πασχαλινό Αυγό 3";		//Easter Egg 3 Activated
var Premadeletter6="Το βίντεο λειτουργεί καλύτερα με βανίλια, επισκεφθείτε την:";		//Video works better on vanilla, visit:
var Premadeletter7="Σημειώσεις: Η συμβατότητα <b>Facebook</b> είναι καλύτερη από <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Σημειώσεις: Το Agar.io μπορεί να συνδεθεί στο <b>Google Plus</b> μόνο κατα την έναρξη. Εαν αποσυνδεθείτε, επαναφορτώστε η συνδεθείτε μέσω <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Αν εμφανιστεί αποσύνδεση στα συμβάντα onload, διαγράψτε τα cookies του Chrome";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Αποσύνδεση από το διακομιστή :(";		//Disconnected from server :(
var Premadeletter11="Έχετε αποκλειστεί, κάντε επανεκκίνηση του δρομολογητή (rooter) σας!";		//You were banned, restart your rooter!
var Premadeletter12="Συνδέθηκε!";		//Connected!
var Premadeletter13="Παίξε";		//PLAY
var Premadeletter14="Επιθεωρηση";		//SPECTATE
var Premadeletter15="Το μη έγκυρο διακριτικό ή ο διακομιστής έκλεισε :(";		//Invalid token or server has closed :(
var Premadeletter16="μπορεί να ενημερωθεί σε";		//can be Updated to
var Premadeletter17="Καλώς ήρθες";			//Welcome back
var Premadeletter18="Η περιοχή συντόμευσης και άλλες περιοχές (από την τελευταία καρτέλα) εξακολουθούν να είναι απενεργοποιημένες! Προτείνουμε να τους ενεργοποιήσετε.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Ενεργοποιήση";		//Enable Them
var Premadeletter20="Απενεργοποίηση";		//Keep Them Disabled
var Premadeletter21="Αναζήτηση IP";		//Searching IP
var Premadeletter22="Ο συμπαίκτης σου";		//Your teammate
var Premadeletter23="θέλει να τα κρύψετε όλα (μικρό και μεγάλο χάρτη)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Αποδοχη";		//Accept
var Premadeletter25="Με τιποτα!";		//NO WAY!
var Premadeletter26="θέλει να αλλάξετε το όνομά σας σε";		//wants you to change your name to
var Premadeletter27="θέλει να ενεργοποιήσετε τη λειτουργία Troll κατα τον θάνατο";		//wants you to hide Enable Troll on death
var Premadeletter28="θέλει να ανοίξετε το πρόγραμμα αναπαραγωγής του Youtube";			//wants you to open Youtube Player
var Premadeletter29="Ο πινάκας ηγετών βρέθηκε";		//Leaderboard found
var Premadeletter30="Αναζήτηση";		//Search
var Premadeletter31="Δεν βρέθηκε. Συνέχισε να προσπαθείς...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Η αναζήτηση ακυρώθηκε";		//Search was canceled
var Premadeletter33="Είστε αόρατοι στην Ομάδα / Clan";		//You are invisible to Team / Clan
var Premadeletter34="Είστε ορατοί στην Ομάδα / Clan";		//You are visible to Team / Clan
var Premadeletter35="Η απόκρυψη / Εμφάνιση μπορεί να χρησιμοποιηθεί μόνο κατά την διάρκεια παιχνιδιού";			//Hide/Show can be used only while playing
var Premadeletter36="Αυτό δεν είναι έγκυρη διεύθυνση για Webhook του Discord";		//This is not valid Discord Webhook address
var Premadeletter37="Η πίστα είναι κλειδωμένη";		//Server is locked
var Premadeletter38="Πρέπει να βρίσκεστε σε λειτουργία επιθεώρησης";		//You must be on spectate mode
var Premadeletter39="Για λόγους αποτροπής ανεπιθύμητης αλληλογραφίας, πρέπει να είστε στο παιχνίδι και να χρησιμοποιείτε κωδικό πρόσβασης";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Αυτόματο Ανηγ. Youtube";		//Auto Youtube On
var Premadeletter41="Αυτόματο Κλεισ. Youtube";		//Auto Youtube Off
var Premadeletter42="Ανηγ. συντομευσεων";		//Show Shortcuts
var Premadeletter43="Κλεισ. συντομευσ.";		//Hide Shortcuts
var Premadeletter44="Ανηγ. XP BAR";		//Show XP BAR
var Premadeletter45="Κλεισ. XP BAR";		//Hide XP BAR
var Premadeletter45a = "Στρογγυλ. Hud"; //Rounded Hud
var Premadeletter45b = "Τετράγωνο Hud"; //Square Hud

var Premadeletter46 = "Γραμμικό χρώμα"; //Linear color Hud
var Premadeletter47 = "Εντονο χρώμα"; //Bold color Hud
var Premadeletter48="Ανηγ. Ολων";		//Show Everything
var Premadeletter49="Κλεισ. Ολων";		//Hide Everything
var Premadeletter50="Ανηγ. Χρονομετρ.";		//Show Timer Calc.
var Premadeletter51="Κλεισ. Χρονομετρ.."		//Hide Timer Calc.
var Premadeletter52="Επεξεργ. Ονοματων";		//Edit Names
var Premadeletter52a="Κλεισ. Ονοματων";			//Close Names"
var Premadeletter53="Aυτομ. Νομισματα";		//Auto free coins
var Premadeletter54="Κλεισ. Νομισματα";		//Stop free coins
var Premadeletter55="Troll σε θανατο";		//Troll on Death
var Premadeletter56="Οχι troll σε θανατο";		//No troll on Death

var Premadeletter57="Επικοινωνία";		//Communication
var Premadeletter58="Κρυμμένος";		//Hidden
var Premadeletter59="Εμφανής";		//Visible
var Premadeletter60="Παύση";		//Pause

var Premadeletter61 = "Ενεργοπ. το YT ως φόντο";	//Enable YT as background
var Premadeletter62 = "Απεν. το YT ως φόντο";	//Disable YT as background";
var Premadeletter63 = "θέλει να ανοίξετε τη διεύθυνση URL";	//wants you to open the url
var Premadeletter64 = "θέλει να ενσωματώσετε και να παίξετε αυτό το βίντεο στο YouTube";	//wants you to embed and play this youtube video
var Premadeletter65 = "σας ζητά να συμμετάσχετε στο επόμενο δωμάτιο Skype";	//wants you to join the following Skype room
var Premadeletter66 = "θέλει να συμμετάσχετε στην ακόλουθη αίθουσα συζήτησης";	//wants you to join the following Discord room
var Premadeletter67 = "θέλει να εγκαταλείψετε αυτόν τον διακομιστή και να συμμετάσχετε σε αυτόν τον νέο";	//wants you to leave this server and join this new one

var Premadeletter68 = "Πατήσατε"; //You pressed
var Premadeletter69 = "επανεκκίνηση εάν τα"; //restart if
var Premadeletter70 = "πέσουν"; //drops
var Premadeletter71 = "Κινούμενα Skins"; //Animated skins
var Premadeletter72 = "ενεργοποιημένα"; //enabled
var Premadeletter73 = "θα πέσουν"; //drop
var Premadeletter74 = "όταν"; //when
var Premadeletter75 = "Κινούμενα Skins θα είναι"; //Animated skins will be
var Premadeletter76 = "απενεργοποιημένα"; //disabled
var Premadeletter77 = "μετά την επανεκκίνηση"; //after rejoin
var Premadeletter78 = "Καλύτερη FPS"; //Better FPS
var Premadeletter79 = "απόδοση όταν 16"; //performance when 16
var Premadeletter80 = "Όταν η λειτουργία Dying Light Expansion είναι ενεργοποιημένη, δεν μπορεί να συμβεί το Troll on death"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Ιδιωτικός διακομιστής"; //Private Server
var Premadeletter82 = "Συνδεθείτε σε οποιαδήποτε"; //Connect to any
var Premadeletter83 = "διακομιστή ή δημιουργήστε το δικό σας"; //server, or make your own
var Premadeletter84 = "Παίξτε παιχνίδια που μοιάζουν με agario αν γνωρίζετε την IP των διακομιστών"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Η εικόνα σας έχει αντιγραφεί στο πρόχειρο. Επικολλήστε τη"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "στην προσαρμοσμένη περιοχή Url Skin"; //to custom skin Url area
var Premadeletter87 = "Πρέπει να συνδεθείτε για να χρησιμοποιήσετε την εικόνα του προφίλ σας"; //You must Login to use picture of your profile
var Premadeletter88 = "Χρησιμοποιείτε μια λανθασμένη έκδοση"; //You are using a wrong version
var Premadeletter89 = "Το παιχνίδι θα τερματιστεί τώρα"; //Game will terminate now
var Premadeletter90 = "Ειδικές προσφορές"; //Special Deals
var Premadeletter91 = "Το Agario μπορεί ή δεν μπορεί να σας δώσει τα skins, αλλά μόνο τα νομίσματα"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Χρησιμοποιήστε το με δική σας ευθύνη"; //Use at your own risk
var Premadeletter92 = "Αν το UID του φίλου σας είναι λάθος, η αγορά θα αποτύχει"; //If friend's UID is wrong, purchase will fail
var Premadeletter93 = "Ρυθμίσεις εργοστασίου για UID"; //UID Factory Settings
var Premadeletter94 = "Πρέπει να συνδεθείτε για να φορτώσετε ειδικές προσφορές"; //You must login to load Special Deals
var Premadeletter95 = "Η ψεύτικη εικόνα έχει αντιγραφεί στο πρόχειρο. Επικολλήστε τη"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "στην προσαρμοσμένη περιοχή Url του Skin για να ενεργοποιήσετε τη λειτουργία ψεύτικης σημαίας"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Ενημερώστε με όταν τελειώσετε με την Recaptcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "Έχω τελειώσει"; //I have finished
var Premadeletter99 = "Δεν πειράζει"; //Never Mind
var Premadeletter100 = "Υπολογισμός του XP σας, παρακαλώ περιμένετε ..."; //Calculating your XP, please wait...
var Premadeletter101 = ""; //
var Premadeletter102 = "Μην"; //NOT
var Premadeletter103 = "πιέσετε"; //press
var Premadeletter104 = "Διαγράψτε τη διεύθυνση URL του προσαρμοσμένου Skin"; //Erase custom skin URL
var Premadeletter105 = "επιλέξτε το skin βίντεο";	//select video skin
var Premadeletter106 = "απενεργοποιήστε το βίντεο"; //unselect video skin
var Premadeletter107 = "σίγαση ήχου"; //mute audio
var Premadeletter108 = "Το έργο LM"; //The LM Project
var Premadeletter109 = "Ανεβάστε"; //Upload 
var Premadeletter109a = "Κατεβάστε"; //Download
var Premadeletter109b = "Φόρτωση"; //Load

var Premadeletter110 = "μην εισάγετε τίποτα εδώ αν δεν ξέρετε τι είναι";	//do not enter anything here unless you know what it is
var Premadeletter111 = "κάντε κλικ στο πορτοκαλί εικονίδιο για να το αγοράσετε"; //click on the orange icon to buy
var Premadeletter112 = "Για κάποιες μεθόδους πληρωμής"; //For some payment methods
var Premadeletter113 = "Κλείσε";	//Close
var Premadeletter114 = "Αντιγραφή"; //COPY	
var Premadeletter115 = "χρησιμοποιείται για να αγοράσει προσφορές για τους φίλους σας"; //is used to buy offers for your friends
var Premadeletter116 = "Για να κάνετε αγορές, πρέπει να είστε συνδεδεμένοι στο λογαριασμό σας ..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Βιβλιοθήκη"; //Library
var Premadeletter118 = "επίσκεψη"; //visit
var Premadeletter119 = "Αναφορά ως ψεύτικη (αλλαγή Skin)"; //Report as Fake (change Skin)
var Premadeletter120 = "Εισαγάγετε το ακριβές όνομα τoυ παίκτη"; //Enter your EXACT name of the player
var Premadeletter121 = "Η κατάχρηση παικτών και η ακατάλληλη χρήση θα οδηγήσει σε UID χρήστη"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "σε μόνιμη απαγόρευση της χρήσης αυτής της επέκτασης"; //to permanent ban from usage of this extension
var Premadeletter128 = "Απαιτείται σύνδεση χρήστη"; //User login needed
var Premadeletter129 = "Οι ρυθμίσεις έχουν μεταφορτωθεί με επιτυχία"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "ΥΠΗΡΕΤΗΣ"; //SERVER
var Premadeletter124 = "Αποφύγετε τη χρήση βίντεο skin μεγαλύτερο από 6 λεπτά"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Ο χάρτης έχει καθοριστεί"; //Map fixed
var Premadeletter126 = "Συνδεθήκατε στο"; //Logged in to
var Premadeletter127 = "Αποσυνδεθήκατε"; //Logged out
var Premadeletter130 = "Σύνολο"; //Total
var Premadeletter131 = "ΝΕΟ"; //NEW
var Premadeletter132 = "Εγγραφείτε πίσω"; //Join Back
var Premadeletter133 = "Συνδεθείτε στην τελευταία διεύθυνση IP που έχετε παίξει"; //Connect to last IP you played
var Premadeletter134 = "Βόρεια Αμερική"; //North America
var Premadeletter135 = "Νότια Αμερική"; //South America
var Premadeletter136 = "Ευρώπη"; //Europe
var Premadeletter137 = "Ρωσία"; //Russia
var Premadeletter138 = "Τουρκία"; //Turkey
var Premadeletter139 = "Ανατολική Ασία"; //East Asia
var Premadeletter139a = "Κίνα"; //China
var Premadeletter140 = "Ωκεανία"; //Oceania
var Premadeletter140a = " -- Επιλέξτε μια περιοχή -- "; // -- Select a Region -- 
var Premadeletter141 = "Ελεύθερο"; //FFA
var Premadeletter142 = "Μάχη Royale"; //Battle Royale
var Premadeletter143 = "Ομάδες"; //Teams
var Premadeletter144 = "Πειραματικό"; //Experimental
var Premadeletter145 = "Πάρτι"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "ΓΛΩΣΣΕΣ"; //LANGUAGES
var Externalletter0b = "Επιλέξτε μια γλώσσα"; //Choose a language
var Externalletter0c = "Οι αλλαγές θα πραγματοποιηθούν πλήρως μετά την επανεκκίνηση"; //Changes will take place completely after the restart
var Externalletter1 = "ΠΛΗΡΟΦΟΡΙΕΣ"; //INFORMATION
var Externalletter2 = "ΥΠΟΔΕΙΓΜΑΤΑ"; //TEMPLATES
var Externalletter3 = "ΧΕΙΡΟΚΙΝΗΤΑ ΥΠΟΔΕΙΓΜΑΤΑ"; //MANUAL TEMPLATES
var Externalletter4 = "Επιλέξτε το υπόδειγμα σας"; //Choose your template
var Externalletter5 = "Ή επιλέξτε επέκταση"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "ΑΠΟΣΤΟΛΤΕ ΚΩΔΙΚΑ ΣΤΟΥΣ ΠΡΟΓΡΑΜΜΑΤΙΣΤΕΣ"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Επικόλληση του σεναρίου σας σε αυτό το Textarea, μπορείτε να φορτώσετε πολλά Scripts"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Φορτώστε το σενάριο από το Textarea"; //Load Script from Textarea
var Externalletter8 = "Επιλέγω"; //Choose
var Externalletter9 = "Διαγρ. τον κώδικα"; //Erase Script
var Externalletter10 = "Όνομα"; //Name
var Externalletter11 = "Url απο Raw Github, ή άλλο Raw Script, που να ξεκινάει με"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Αφήστε αυτό το άδειο αν το σενάριο δεν εισαχθεί από τη διεύθυνση URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "ΣΗΜΑΝΤΙΚΗ ΕΙΔΟΠΟΙΗΣΗ: Μην κρατάτε τις διευθύνσεις URL που δεν λειτουργούν, επειδή χρησιμοποιούνται ως συμβάντα onload. Εάν το Scenario βλάψει τα γεγονότα φόρτωσης, στη συνέχεια ΣΒΉΣΤΕ ΤΑ COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
