
/* var Languageletter = "hello you" <--- You tranlate this, keep the " "; as they are. // <-Means notes, no need to change */
/* Example var Languageletter0="Home"; //Home -> var Languageletter0="Maison"; //Home */ /* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is */ 
/* Thank you for supporting Legend Agar.io mod */
var translator="Jimboy3100";		//Put your nickname, in order to be reffered to mod, or use name "Unknown" 
var Languageletter0="Главная";		//Home 
var Languageletter1="пользователь";		//User 
var Languageletter2="настройки";		//Settings 
var Languageletter3="тема";		//Theme 
var Languageletter4="Клавиатурный";		//Hotkeys 
var Languageletter5="Youtube & Звуки";		//Youtube & Sounds 
var Languageletter6="инструменты";		//Tools 
var Languageletter7="Оставьте его пустым для Public или вставьте пароль Clan или используйте его как Tag";		//Password/Tag 
var Languageletter7a="Пароль / Метки"	;	//Password/Tag 
var Languageletter8="Вставьте свое внутриигровое имя, 50 символов видны пользователям Mod, 15 - другим пользователям";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users 
var Languageletter8a="имя";		//Name
var Languageletter9="Вставьте свою ручную веб-ссылку для скинов";		//Insert your manual skin weblink
var Languageletter9a="URL прямой прямой ссылки";		//Manual direct skin URL 
var Languageletter10="Регион для игры";		//The region to play 
var Languageletter11="Режим воспроизведения";		//The mode to play 
var Languageletter12="Подключиться к серверу или установить связь";		//Connect to server, or restablish communication 
var Languageletter12a="соединять";		//Connect 
var Languageletter13="Присоединиться";		//Join 
var Languageletter14="Играть в качестве гостя";		//Play as guest
var Languageletter15="Вход и игра";		//Login and Play 
var Languageletter16="быть зрителем";		//Spectate 
var Languageletter17="Авторизоваться с помощью Фэйсбука";		//Sign in with Facebook 
var Languageletter18="Войти через Google";			//Sign in with Google
var Languageletter19="Играть";		//Play 
var Languageletter20="Магазин"	;		//Shop 
var Languageletter21="Бесплатные монеты";		//Free Coins 
var Languageletter22="Дары";		//Gifts 
var Languageletter23="Ежедневные квесты";			//Daily Quests 
var Languageletter24="Скины";		//Skins 
var Languageletter25="Легенда Промо-видео";		//Legend Promo Video
var Languageletter25a="Новые идеи и форма статистики";		//New Ideas & Statistics Form 
var Languageletter25b="Мода и шаблоны";		//Mod Info & Templates
var Languageletter26="Добавить скины";		//Add skins 
var Languageletter26a="Копировать сервер, пароль, тимбард и лидер"; //Copy Server, Password, Teamboard & Leaderboard 
var Languageletter31="Выйти";		//Logout 
var Languageletter32="Используемые времена";		//Times Used 
var Languageletter33="Legend Mod, автор:";		//Legend Mod by 
var Languageletter34="Перевод";		//Translation by 
var Languageletter35="копировать имена лидеров и имена ячеек. (нажмите x, чтобы показать / скрыть)";		//copy leaderboard names and cell names. (press x to show/hide) 
var Languageletter36="Анимация";		//Animation 
var Languageletter37="Задержка анимации";		//Animation delay 
var Languageletter37a="Автоматическое масштабирование";		// Auto zoom 
var Languageletter37b="Увеличить";		// Zoom 
var Languageletter38="Скорость масштабирования:";		//Zoom speed:
var Languageletter39="респаун";			//Respawn 
var Languageletter40="Автовоспроизведение";		//Auto respawn 
var Languageletter41="Быстрое респаун ";			//Quick respawn 
var Languageletter41a="Начните со спецэффектов";			//Spawn special effects 
var Languageletter41b="Таймер слияния выключен ";			//Merge timer off
var Languageletter41c="Предложено включить для уменьшения задержки";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Вирус выстрелил";			//Virus shot sound

var Languageletter42="имена";			//Names 
var Languageletter43="Нет имен";		//No names 
var Languageletter44="Оптимизированные имена";		//Optimized names 
var Languageletter45="Авто скрыть имена";		//Auto hide names 
var Languageletter46="Скрыть мое имя";		//Hide my name 
var Languageletter47="Скрыть имена товарищей по команде";		//Hide teammates names 
var Languageletter48="Имена имен";		//Names stroke 
var Languageletter49="масса";		//Mass 
var Languageletter50="Показать массу";		//Show mass 
var Languageletter51="Оптимизированная масса"	;	//Optimized mass 
var Languageletter52="Авто скрыть массу";			//Auto hide mass 
var Languageletter53="Скрыть мою массу";		//Hide my mass 
var Languageletter54="Скрыть массу врагов";		//Hide enemies mass 
var Languageletter55="Короткая масса";		//Short mass 
var Languageletter56="Вирусные снимки";		//Virus shots 
var Languageletter57="Массовый удар";		//Mass stroke 
var Languageletter58="Скины";		//Skins 
var Languageletter59="Нет скинов ";		//No skins 
var Languageletter60="Пользовательские скины";		//Custom skins 
var Languageletter61="Ванильные шкуры";		//Vanilla skins 
var Languageletter61a="Физика желе";		//Jelly physics 
var Languageletter61b="Видео скины";		//Video skins
var Languageletter61c="Звук из других видео скинов, когда оба C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Оптимизированная пища";		//Optimized food 
var Languageletter6a2="питание";		//Food 
var Languageletter63="Авто скрыть еду (Масса)";		//Auto hide food (mass) 
var Languageletter64="Авто скрыть еду (Увеличение)";		//Auto hide food (zoom) 
var Languageletter65="Радужная пища";		//Rainbow food 
var Languageletter66="Прозрачность / цвета";		//Transparency / colors
var Languageletter67="Нет цветов";		//No colors 
var Languageletter68="Мой пользовательский цвет";		//My custom color 
var Languageletter69="Моя прозрачная кожа";		//My transparent skin 
var Languageletter70="Прозрачные шкуры";		//Transparent skins 
var Languageletter70a="Прозрачные ячейки";		//Transparent cells 
var Languageletter71="Прозрачные вирусы";		//Transparent viruses 
var Languageletter71a="Вирусный блеск";		//Virus Glow
var Languageletter71b="Анимированные цвета радуги";		//Animated rainbow colors

var Languageletter72="Сетка / сектора";		//Grid / sectors 
var Languageletter73="Показать сетку";		//Show grid 
var Languageletter74="Показать фоновые сектора";		//Show background sectors 
var Languageletter75="Показать границы карты";		//Show map borders
var Languageletter75a="Свечение границ";		//Border Glow

var Languageletter76="чат";		//Chat
var Languageletter77="Отключить чат";		//Disable chat 
var Languageletter78="Звуковые уведомления";		//Sound notifications 
var Languageletter79="смайлов";		//Emoticons 
var Languageletter80="Показывать изображения в чате";		//Show images on chat 
var Languageletter81="Показать видео в чате";		//Show videos on chat 
var Languageletter82="Чатбокс вместо всплывающих окон";		//Chatbox instead of popups 
var Languageletter82a="Мини-карта";		//Minimap 
var Languageletter82b="Показать мини-карту";		//Show minimap 
var Languageletter82c="Показать мини-карту";		//Show minimap grid
var Languageletter82d="Показать мини-путеводы";		//Show minimap guides 
var Languageletter82e="Одноцветные товарищи по команде";		//One-colored teammates 
var Languageletter82f="Показать дополнительные мини-карты";		//Show extra minimap guides
var Languageletter82g="Показать призрачные клетки";		//Show ghost cells

var Languageletter83="Помощники";		//Helpers 
var Languageletter84="Цвет оппонентов";		//Opponents colors
var Languageletter85="Противники";		//Opponents rings 
var Languageletter86="Цвет вирусов";		//Viruses colors 
var Languageletter87="Сплит-диапазон";		//Split range 
var Languageletter87a="Быстрый двойной сплит диапазон";		//Quick double split range
var Languageletter87b="Медленный двойной сплит диапазон";		//Slow double split range

var Languageletter88="Диапазон вирусов";		//Viruses range 
var Languageletter89="Отслеживание курсора";		//Cursor tracking 
var Languageletter90="Показатели игроков";		//Teammates indicators
var Languageletter90a="Призрачные клетки";		//Ghost cells

var Languageletter91="Управление мышью";		//Mouse control 
var Languageletter92="LMB - разделение мыши";		//LMB - Mouse split 
var Languageletter93="RMB - Подача мыши";		//RMB - Mouse feed 
var Languageletter94="Инвертировать кнопки мыши";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD 
var Languageletter95="Показать 5 лучших команд";		//Show team top 5
var Languageletter96="Показать таргетинг";		//Show targeting 
var Languageletter96a="Показать список лидеров массы";		//Show leaderboard mass

var Languageletter97="Центрированная таблица лидеров";		//Centered leaderboard 
var Languageletter97a="Заголовок таблицы лидеров";		//\"Leaderboard\" header 

var Languageletter98="Статистика игры в верхней части";		//Game stats at the top 
var Languageletter98a="Скины на доске";		//Skins on teamboard

var Languageletter99="Статистика";		//Stats 
var Languageletter100="Показать статистику игры";		//Show game stats 
var Languageletter101="Статистика игры";		//Game stats
//the \' is needed
var Languageletter102="вражеский";		//Enemy\'s 		
var Languageletter103="наш";		//Our
var Languageletter104="Минимальный трюк разделить массу товарища по команде";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Максимальная масса врага для предварительного раскола";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Показать текущее время";		//Show current time 
var Languageletter106="Дополнительно";		//Extras 
var Languageletter107="Пропустить статистику после смерти";		//Skip stats after death 
var Languageletter108="Показать quesτ";		//Show quest 
var Languageletter108a="Игровые звуки"; //Game Sounds 
var Languageletter108b="Звуки меню"; //Menu Sounds 
var Languageletter109="Блокировать всплывающие окна (объявления / магазин / квест)";		//Block popups (ads/shop/quest) 
var Languageletter109a="глас"; //Voice 
var Languageletter109b="Голос Prefix"; //Voice-Prefix 
var Languageletter109c="Голос языка"; //Voice-language 
var Languageletter109d="Возобновить"; //UnPause

var Languageletter110="-- Качество графики --";		//-- Graphics Quality -- 
var Languageletter111="Графика: сетчатка";		//Graphics: Retina 
var Languageletter112="Графика: высокая";		//Graphics: High 
var Languageletter113="Графика: средний";		//Graphics: Medium" 
var Languageletter114="Графика: низкая";		//Graphics: Low 
var Languageletter115="Графика: очень низкая";		//Graphics: Very Low 
var Languageletter116="Настройки экспорта / импорта";		//Export / import settings 
var Languageletter117="Восстановить настройки по умолчанию";		//Restore default settings 
var Languageletter118="Настройки экспорта";		//Export settings 
var Languageletter119="Настройки импорта";		//Import settings 
var Languageletter120="Чтобы экспортировать выбранные настройки, скопируйте приведенный ниже код и сохраните его в текстовом файле, закодированном в Юникоде.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode. 
var Languageletter121="Чтобы импортировать выбранные параметры, вставьте экспортированный код ниже и нажмите кнопку «Импорт настроек».";		//To import selected settings paste an exported code below and press the 'Import settings' button. 
var Languageletter122="команды";		// Commands 
var Languageletter123="Клавиатурный";		// Hotkeys 
var Languageletter124="профили";		// Profiles 
var Languageletter125="настройки";		// Settings 
var Languageletter126="тема";		// Theme 
var Languageletter127="Настройки экспорта";		//Export settings 
var Languageletter128="Настройки импорта";		//Import settings 
var Languageletter129="Основные темы";		//Basic theming 
var Languageletter130="Меню";		//Menu 
var Languageletter131="HUD";		//HUD 
var Languageletter132="чат";		//Chat 
var Languageletter133="Мини-карта";		//Minimap 
var Languageletter134="Графика / курсоры";		//Graphics / cursors 
var Languageletter135="Предустановка темы";		//Theme preset 
var Languageletter136="Легенда Оригинал";		//Legend Original 
var Languageletter137="Сумасшедший стиль";		//Crazy Style 1 
var Languageletter139="Задний план";		//Background 
var Languageletter140="Границы карты";		//Map borders 
var Languageletter141="сетка";		//Grid 
var Languageletter142="Размер шрифта";		//Sectors font 
var Languageletter143="имена";		//Names 
var Languageletter144="Имена имен";		//Names stroke 
var Languageletter145="масса";		//Mass 
var Languageletter146="Массовый удар";		//Mass stroke 
var Languageletter147="Вирусный ход";		//Virus stroke 
var Languageletter148="Вирус";		//Virus 
var Languageletter148a="Mатеринская клетка";		//Mothercell
var Languageletter148b="Материнский инсульт";		//Mothercell stroke
var Languageletter149="питание";		//Food 
var Languageletter150="Индикатор для участников";		//Teammate indicator 
var Languageletter151="Отслеживание курсора";		//Cursor tracking 
var Languageletter152="Сплит-диапазон";		//Split range 
var Languageletter153="Шрифт имен";		//Names font 
var Languageletter154="Размер шрифта";		//Mass font 
var Languageletter154a="Больше";		//Bigger
var Languageletter154b="Меньшие";		//Smaller
var Languageletter155="Секторы шрифтов";		//Sectors font 
var Languageletter157="Размер шрифта для секторов";		//Sectors font size 
var Languageletter158="Масштаб имен";		//Names scale 
var Languageletter159="Масштаб";		//Mass scale 
var Languageletter160="Масштаб вируса";		//Virus mass scale 
var Languageletter161="Масштаб штриха текста";		//Text stroke scale 
var Languageletter162="Размер продукта";		//Food size: 
var Languageletter163="Размер инсульта";		//Virus stroke size 
var Languageletter164="Ширина границ карты";		//Map borders width 
var Languageletter165="Ширина сетки";		//Sectors grid width 
var Languageletter166="Прозрачность ячеек";		//Cells transparency 
var Languageletter167="Прозрачность скинов";		//Skins transparency 
var Languageletter168="Прозрачность вирусов";		//Virus transparency 
var Languageletter169="Имена и массовая прозрачность";		//Names & mass transparency 
var Languageletter170="Восстановить настройки по умолчанию темы";		//Restore theme default settings 
var Languageletter171="сохранить настройки";		//Save settings 
var Languageletter172="Тема меню";		//Menu theme 
var Languageletter173="Задний план";		//Background 
var Languageletter174="прозрачность";		//Transparency 
var Languageletter175="Основной цвет";		//Main color 
var Languageletter176="Текст кнопки";		//Button text 
var Languageletter177="панель";		//Panel 
var Languageletter179="Текст панели";		//Panel text 
var Languageletter181="кнопка";		//Button 
var Languageletter189="Изображение панели";		//Panel background image 
var Languageletter190="URL изображения";		//Image URL 
var Languageletter191="Основной цвет";		//Main color 
var Languageletter192="Задний план";		//Background 
var Languageletter193="Текст";		//Text 
var Languageletter194="Статистика";		//Stats 
var Languageletter195="Время";		//Time 
var Languageletter196="Top 5 масса";		//Top 5 mass 
var Languageletter197="Лидерская доска - меня";		//Leaderboard - me 
var Languageletter198="Лидерская доска - товарищ по команде";		//Leaderboard - teammate 
var Languageletter199="HUD шрифт";		//HUD font 
var Languageletter200="HUD масштаб";		//HUD scale: 
var Languageletter201="Фон сообщения";		//Message background 
var Languageletter202="Текст сообщения";		//Message text 
var Languageletter203="Время сообщения";		//Message time 
var Languageletter204="Ник сообщения";		//Message nick 
var Languageletter205="Командный фон";		//Command background 
var Languageletter206="Текст команды";		//Command text 
var Languageletter207="Время команды";		//Command time 
var Languageletter208="Ник команды";		//Command nick 
var Languageletter209="Цвет чата";		//Chatbox color 
var Languageletter210="Шкала чата";		//Chat scale 
var Languageletter211="секторов";		//Sectors 
var Languageletter212="Текущий сектор";		//Current sector 
var Languageletter213="Ник";		//Nick 
var Languageletter214="Ник удар";		//Nick stroke 
var Languageletter215="Моя ячейка";		//My cell 
var Languageletter216="Мой клеточный инсульт";		//My cell stroke 
var Languageletter217="Одноклубники";		//Teammates 
var Languageletter218="Место смерти";		//Death location 
var Languageletter219="руководства";		//Guides 
var Languageletter220="Мини-шрифт";		//Minimap font 
var Languageletter221="Ник шрифт";		//Nick font 
var Languageletter222="Минимальная ширина";		//Minimap width 
var Languageletter223="Прозрачность секторов";		//Sectors transparency 
var Languageletter224="Размер ник";		//Nick size 
var Languageletter225="Ник размерный ход";		//Nick stroke size 
var Languageletter226="Размер моей ячейки";		//My cell size 
var Languageletter227="Размер моего клеточного инсульта";		//My cell stroke size 
var Languageletter228="Размер товарищей по команде";		//Teammates size 
var Languageletter229="Пользовательское фоновое изображение";		//Custom background image 
var Languageletter230="Пользовательское изображение курсора";		//Custom cursor image 
var Languageletter231="URL изображения";		//Image URL 
var Languageletter232="URL-адрес курсора";		//Cursor image URL 
var Languageletter233="Корм";		//Feed 
var Languageletter234="Макросъемка";		//Macro feed 
var Languageletter235="Трещина";		//Split 
var Languageletter236="Двухместный сплит";		//Double split 
var Languageletter237="Расщепление";		//Popsplit 
var Languageletter238="Трещина 16";		//Split 16 
var Languageletter239="Пауза ячейки";		//Cell pause 
var Languageletter240="Показать / скрыть состав команды 5";		//Show/hide team top 5 
var Languageletter241="Показать / скрыть текущее время";		//Show/hide current time 
var Languageletter242="Показать / скрыть диапазон разделения";		//Show/hide split range" 
var Languageletter243="Показать / скрыть индикаторы команд";		//Show/hide teammates indicators 
var Languageletter244="Показать / скрыть сплит-индикаторы";		//Show/hide split indicators 
var Languageletter245="Показать / скрыть цвета противников";		//Show/hide opponents colors 
var Languageletter246="Переключить скины (пользовательские / по умолчанию)";		//Toggle skins (custom/default) 
var Languageletter247="Переключить прозрачные скины";		//Toggle transparent skins 
var Languageletter248="Показать / скрыть скины";		//Show/hide skins 
var Languageletter249="Показать / скрыть статистику игры";		//Show/hide game stats 
var Languageletter250="Переключить собственные ячейки (самые маленькие / самые большие)";		//Toggle own cells (smallest/biggest) 
var Languageletter251="Показать / скрыть продукты питания";		//Show/hide food 
var Languageletter252="Показать / скрыть сетку";		//Show/hide grid 
var Languageletter253="Показать / скрыть мини-путеводы";		//Show/hide minimap guides 
var Languageletter254="Показать / скрыть чат";		//Show/hide chat 
var Languageletter255="Показать спрятать HUD";		//Show/hide HUD 
var Languageletter256="Копировать таблицу лидеров";		//Copy leaderboard 
var Languageletter257="Показать / скрыть таблицу лидеров";		//Show/hide leaderboard 
var Languageletter258="Переключение автоматического масштабирования";		//Toggle auto zoom 
var Languageletter259="Reset zoom";		//Reset zoom 
var Languageletter260="Переключить местоположение смерти";		//Toggle death location 
var Languageletter261="Показать историю чата / Очистить чат";		//Show chat history / Clear chat 
var Languageletter262="Показать / скрыть фоновые сектора";		//Show/hide background sectors 
var Languageletter263="Показать / скрыть маленькие боты";		//Show/hide small bots 
var Languageletter264="Показать / скрыть имена";		//Show/hide names 
var Languageletter265="Показать / скрыть имена товарищей по команде";		//Show/hide teammates names 
var Languageletter266="Показать / скрыть массу";		//Show/hide mass 
var Languageletter267="Показать / скрыть майнап";		//Show/hide minimap 
var Languageletter268="Введите сообщение чата";		//Enter chat message 
var Languageletter269="Быстрое респаун";		//Quick respawn 
var Languageletter270="Переключить автоматический респаун";		//Toggle auto respawn 
var Languageletter271="Уровень масштабирования";		//Zoom level 
var Languageletter271a="Голос в текст";		//Voice to text
var Languageletter271b="Показать информацию о призрачных клетках";		//Show ghost cells information
var Languageletter271c="Автоматическая игра";		//Auto Play
var Languageletter272="Показать / скрыть панель таргетинга";		//Show/hide targeting panel 
var Languageletter273="Начать / остановить таргетинг (далее)";		//Start/stop targeting (following) 
var Languageletter274="Отменить таргетинг";		//Cancel targeting 
var Languageletter275="Изменить цель";		//Change target 
var Languageletter276="Показать цель на мини-карте";		//Show target on the minimap 
var Languageletter277="Показать / скрыть квест";		//Show/hide quest 
var Languageletter278="Чтобы назначить горячую клавишу, нажмите на поле ввода и нажмите выбранную вами клавишу.";		//To assign a hotkey click on the input field and press your chosen key. 
var Languageletter279="Чтобы удалить горячую клавишу, нажмите на поле ввода и нажмите клавишу DELETE.";		//To delete a hotkey click on the input field and press the DELETE key. 
var Languageletter280="Возможные комбинации клавиш с клавишами CTRL и ALT.";		//Possible key combinations with the CTRL and ALT keys. 
var Languageletter281="Восстановить настройки по умолчанию";		//Restore default settings 
var Languageletter282="Сохранить настройки";		//Save settings 
var Languageletter283="Закрыть";		//Close 
var Languageletter284="Youtube player";		//Youtube player 
var Languageletter284a="Youtube Url";		// Youtube Url 
var Languageletter285="Вставьте свой видео / плейлист здесь";		//Paste your video/playlist here 
var Languageletter286="Звуки";		//Sounds 
var Languageletter287="Звук уведомления о сообщении";		//Message notification sound 
var Languageletter288="Звук команды уведомления";		//Command notification sound 
var Languageletter289="Копировать токен / SIP";		//Copy Token/SIP //keep this small 
var Languageletter290="знак";		//Token 
var Languageletter290a="доска"; //Board 
var Languageletter290b="TK&PW";	//TK&PW (Token and Password) 
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All) 
var Languageletter291="копия";		//Copy 
var Languageletter291a="Копия лидера (L)";		//Copy Leaderboard (L) 
var Languageletter291b="Копировать токен / SIP и пароль"; 	//Copy Token/SIP&Password 
var Languageletter291c="Копировать токен / SIP, пароль, лидер ..."; //Copy Token/SIP, Password, Leaderboard... 
var Languageletter292="Присоединиться к серверу (Backspace)";		//Join server (Backspace) 
var Languageletter293="Изменить сервер (+)";		//Change server (+) 
var Languageletter294="История лидеров";		//Leaderboard history 
var Languageletter295="Введите токен друга, IP, таблицу лидеров, имя или клан ...";		//Enter friend token, IP, leaderboard, name or clan tag... 
var Languageletter295a="Очистить список"; //Clear list 
var Languageletter295b="Введите сообщение чата ..."; //Enter chat message... 
var Languageletter298="команда ";		//Team
var Languageletter299="Лидер бодар";		//Leaderbodard 
var Languageletter300="связь";		//Communication 
var Languageletter301="Команды сценария сообщения";		//Message Script Commands 
var Languageletter302="Значки сообщений Imgur";		//Message Imgur Icons 
var Languageletter303="Видео сообщений для Youtube";		//Message Youtube Videos 
var Languageletter304="Изменить имена";		//Edit names 
var Languageletter305="[Только для зрителей] Бинокль";		//[Spectate Mode Only] Binoculars 
var Languageletter306="Воспроизвести / Пауза";		//Play / Pause 
var Languageletter307="Полноэкранный";		//Fullscreen 
var Languageletter308="Поворот";		//Rotate 
var Languageletter309="По умолчанию";		//Default 
var Languageletter310="назад";		//Back 
var Languageletter311="Save for later";		//Save for later 
var Languageletter312="Область";		//Region 
var Languageletter313="игроки";		//Players 
var Languageletter314="Серверы";		//Servers 
var Languageletter315="[Цель не установлена]";		//[Target not set] 
var Languageletter316="Ручной фон";		//Manual background 
var Languageletter317="Иконки сообщений руководства и Youtube";		//Manual Message Icons&Youtube 
var Languageletter318="Позиция чата";		//Chat Position 
var Languageletter319="URL-адрес Discord Webhook (для отправки TOKEN)";		//Discord Webhook Url (for sending TOKEN) 
var Languageletter320="Доска лидеров";		//Leaderboard 
var Languageletter321="Командная доска";		//Teamboard 
var Languageletter322="Основной холст";		//Main Canvas 
var Languageletter323="Главный баннер";		//Main Banner 
var Languageletter324="Привет, команда!";		//Hello Team! 
var Languageletter325="Смех команды";		//Laugh to Team 
var Languageletter326="Изменить команду на свое имя";		//Team Change Name to yours 
var Languageletter327="Тролль по смерти";		//Troll on Death 
var Languageletter328="Открытая музыка Youtube";		//Open Youtube Music 
var Languageletter329="Безумный режим (Скрыть все)";		//Insane mode (Hide Everything) 
var Languageletter330="URL-адрес изображения, начинающегося с http: // ... или https: // ...";		//Url of image starting with http://... or https://... 
var Languageletter331="Минимальный URL-адрес изображения";		//Minimap Image URL 
var Languageletter332="Мини-карта Текст";		//Minimap Text 
var Languageletter333="Лидерская панель URL-адрес изображения";		//Leaderboard Logo Text 
var Languageletter333a="Leaderboard Image URL";		// Leaderboard Image URL 
var Languageletter334="Логотип команды";		//Teamboard Logo Text 
var Languageletter334a="URL-адрес изображения";		// Teamboard Image URL 
var Languageletter335="Основной URL изображения холста";		//Main Canvas Image URL 
var Languageletter336="Значок главной значки баннера";		//Main Banner Icon URL 
var Languageletter337="Основной URL-адрес баннерной ссылки";		//Main Banner Link URL 
var Languageletter338="Значок";		//Icon 
var Languageletter339="например";		//e.g 
var Languageletter340="Отобразится URL-адрес youtube";		//Url of youtube to be shown 
var Languageletter341="URL ссылки для перенаправления";		//Url of link to redirect 
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url 
var Languageletter342a="Текст сообщения сообщения";		//Message Icon Text 
var Languageletter342b="Текст сообщения Youtube";		//Youtube Message Text 
var Languageletter342c="Иконка сообщения Imgur Url";		//Message Icon Imgur Url 
var Languageletter342d="Адрес сообщения Youtube";		//Youtube Message Url 
var Languageletter343="Должен быть заполнен для работы";		//Must be filled for function to work. 
var Languageletter344="Вторичный Webhook (необязательно)";		//Secondary Webhook(optional) 
var Languageletter345="ПРЕДУПРЕЖДЕНИЕ! Всплывающие окна блокируются в настройках.";		//WARNING! Popups are blocked in the settings. 
var Languageletter346="Временный разблокировать";		//Temporary unblock 
var Languageletter347="ПРЕДУПРЕЖДЕНИЕ! Всплывающие окна блокируются в настройках.";		//WARNING! Popups are blocked in the settings. 
var Languageletter348="Временный разблокировать";		//Temporary unblock 
var Languageletter349="Зелья";	//Potions 
var Languageletter350="Старые скины";	//Old Skins 
var Languageletter351="Специ. предложения"; //Special Deals 
var Languageletter352="Доска лидеров"; //Leaderboards 
var Languageletter353="Новые идеи и форма статистики"; //New Ideas & Statistics Form 
var Languageletter354="Видео скины"; //Video Skins 
var Languageletter355="Мини-скрипты"; //Mini Scripts 
var Languageletter356="Пользовательские скрипты"; //User Scripts 
var Languageletter357="Голосовой чат и чат";	//Voice & Camera Chat 
var Languageletter358="Пожалуйста, поддержите разработку мода Legend";	//Please support the development of Legend mod 
var Languageletter359="Дизайн Псевдоним Шрифт";	//Design Nickname Font 
var Languageletter360="Флаг поддельной кожи";	//Flag the Fake Skin 
var Languageletter361="Больше FPS";	//More FPS 
var Languageletter362="имя";	//Name
var Languageletter363="ID Социальное";	//Social ID
var Languageletter364="расширения";	//Expansions

var Premadeletter0="Активация связи"; 		//Communication Activated 
var Premadeletter1="Не удается открыть этот URL-адрес YouTube.";		 //Cannot open this youtube URL 
var Premadeletter2="Вы не можете общаться, если имя игрока> 15 символов"; 		//[SERVER]: You cannot chat if player name > 15 chars 
var Premadeletter3="Пасхальное яйцо 1 активировано"; 		//Easter Egg 1 Activated 
var Premadeletter4="Пасхальное яйцо 2 активировано";		//Easter Egg 2 Activated 
var Premadeletter5="Пасхальное яйцо 3 активировано";		//Easter Egg 3 Activated 
var Premadeletter6="Видео работает лучше на ваниль, посетите:";		//Video works better on vanilla, visit: 
var Premadeletter7="Примечания: <b> Facebook </b> совместимость лучше, чем <b> Google Plus </b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>. 
var Premadeletter8="Примечания. Agar.io может подключаться только к <b> Google Plus </ b> при событиях onload. Если происходит выход из системы, присоединитесь к Agar.io или используйте <b> Facebook </b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>. 
var Premadeletter9="Если в событиях onload произошел выход из системы, удалите Chrome cookie из";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Отключен от сервера :(";		//Disconnected from server :( 
var Premadeletter11="Вы были заблокированы, перезапустите маршрутизатор!";		//You were banned, restart your rooter! 
var Premadeletter12="Связанный!";		//Connected! 
var Premadeletter13="ИГРАТЬ";		//PLAY 
var Premadeletter14="быть зрителем";		//SPECTATE 
var Premadeletter15="Недопустимый токен или сервер закрыт :(";		//Invalid token or server has closed :( 
var Premadeletter16="может быть обновлено до";		//can be Updated to 
var Premadeletter17="Добро пожаловать";			//Welcome back 
var Premadeletter18="Ваша область ярлыка и другие области (с последней вкладки) по-прежнему отключены! Мы предлагаем вам включить их.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them. 
var Premadeletter19="Включить их";		//Enable Them 
var Premadeletter20="Держите их отключенными";		//Keep Them Disabled 
var Premadeletter21="Поиск IP-адреса";		//Searching IP 
var Premadeletter22="Ваш товарищ по команде";		//Your teammate 
var Premadeletter23="хочет, чтобы вы спрятали все (таблица лидеров и мини-карта)";		//wants you to hide all (leaderboard and minimap) 
var Premadeletter24="принимать";		//Accept var Premadeletter25="НИ ЗА ЧТО!";		//NO WAY! 
var Premadeletter26="хочет, чтобы вы изменили свое имя на";		//wants you to change your name to 
var Premadeletter27="хочет, чтобы вы включили Тролля в смерть";		//wants you to hide Enable Troll on death 
var Premadeletter28="хочет, чтобы вы открыли Youtube Player";			//wants you to open Youtube Player 
var Premadeletter29="Найден лидер";		//Leaderboard found 
var Premadeletter30="Поиск";		//Search 
var Premadeletter31="Таблица лидеров не найдена. Продолжайте ...";		//The leaderboard was not found. Keep trying... 
var Premadeletter32="Поиск был отменен";		//Search was canceled 
var Premadeletter33="Вы невидимы для команды / клана";		//You are invisible to Team / Clan 
var Premadeletter34="Вы видите команду / клан";		//You are visible to Team / Clan 
var Premadeletter35="Скрыть / показать можно использовать только во время воспроизведения";			//Hide/Show can be used only while playing 
var Premadeletter36="Это недействительно";		//This is not valid Discord Webhook address 
var Premadeletter37="Сервер заблокирован";		//Server is locked 
var Premadeletter38="Вы должны быть в режиме просмотра";		//You must be on spectate mode 
var Premadeletter39="Из-за проблем со спамом вы должны быть в игре и использовать пароль";		//Due to spamming issues, you must be in game and use password //					These buttons must no be big in length 
var Premadeletter40="Авто Youtube On";		//Auto Youtube On 
var Premadeletter41="Авто Youtube Off";		//Auto Youtube Off 
var Premadeletter42="Показать ярлыки";		//Show Shortcuts 
var Premadeletter43="Скрыть ярлыки";		//Hide Shortcuts 
var Premadeletter44="Показать XP BAR";		//Show XP BAR 
var Premadeletter45="Скрыть XP BAR";		//Hide XP BAR 
var Premadeletter45a = "Округлый Хад"; //Rounded Hud 
var Premadeletter45b = "Площадь Хад"; //Square Hud 
var Premadeletter46 = "Линейный цвет худ"; //Linear color Hud
var Premadeletter47 = "Жирный цвет худ"; //Bold color Hud
var Premadeletter48="Показать все";		//Show Everything 
var Premadeletter49="Скрыть все";		//Hide Everything 
var Premadeletter50="Каль. тайм. обуви";		//Show Timer Calc. 
var Premadeletter51="Скры. кальк. тайм."		//Hide Timer Calc. 
var Premadeletter53="Автом. беспл. монеты";		//Auto free coins 
var Premadeletter54="Останов. беспл. монеты";		//Stop free coins 
var Premadeletter55="Тролль по смерти";		//Troll on Death 
var Premadeletter56="Нет тролля по Смерти";		//No troll on Death 
var Premadeletter57="связь";		//Communication 
var Premadeletter58="скрытый";		//Hidden 
var Premadeletter59="видимый";		//Visible 
var Premadeletter60="Пауза";		//Pause 
var Premadeletter61 = "Включить YT в качестве фона";	//Enable YT as background 
var Premadeletter62 = "Отключить YT в качестве фона";	//Disable YT as background"; 
var Premadeletter63 = "хочет, чтобы вы открыли URL-адрес";	//wants you to open the url 
var Premadeletter64 = "хочет, чтобы вы вставляли и воспроизводили это видео с YouTube";	//wants you to embed and play this youtube video 
var Premadeletter65 = "хочет, чтобы вы присоединились к следующей комнате Skype";	//wants you to join the following Skype room 
var Premadeletter66 = "хочет, чтобы вы присоединились к следующей комнате раздора";	//wants you to join the following Discord room 
var Premadeletter67 = "хочет, чтобы вы покинули этот сервер и присоединились к этому новому";	//wants you to leave this server and join this new one 
var Premadeletter68 = "Вы нажали"; //You pressed 
var Premadeletter69 = "перезапустить, если"; //restart if 
var Premadeletter70 = "капли"; //drops 
var Premadeletter71 = "Анимированные скины"; //Animated skins 
var Premadeletter72 = "включен"; //enabled 
var Premadeletter73 = "падение"; //drop 
var Premadeletter74 = "когда"; //when 
var Premadeletter75 = "Анимированные скины будут"; //Animated skins will be 
var Premadeletter76 = "отключен"; //disabled 
var Premadeletter77 = "после воссоединения"; //after rejoin 
var Premadeletter78 = "Лучше FPS"; //Better FPS 
var Premadeletter79 = "производительность, когда 16"; //performance when 16 
var Premadeletter80 = "Когда Dying Light Expansion включен, Тролль на смерть не может произойти"; //When Dying Light Expansion is enabled, Troll on death cannot occur 
var Premadeletter81 = "Частный сервер"; //Private Server 
var Premadeletter82 = "Подключиться к любому"; //Connect to any 
var Premadeletter83 = "сервера или создать собственный"; //server, or make your own 
var Premadeletter84 = "Играйте в игры, подобные азарио, если вы знаете IP-серверы"; //Play agario-like games if you know the IP of servers 
var Premadeletter85 = "Ваше изображение было скопировано в буфер обмена. Вставить его"; // Image of your has been copied to clipboard. Paste it 
var Premadeletter86 = "к пользовательской области URL-адреса"; //to custom skin Url area 
var Premadeletter87 = "Вы должны Войти, чтобы использовать фотографию своего профиля"; //You must Login to use picture of your profile 
var Premadeletter88 = "Вы используете неправильную версию"; //You are using a wrong version 
var Premadeletter89 = "Игра закончится сейчас"; //Game will terminate now 
var Premadeletter90 = "Специальные предложения"; //Special Deals 
var Premadeletter91 = "Агарио может или не может дать вам Кожа, но только монеты"; //Agario may or may not give you the Skin, but only the coins 
var Premadeletter91a = "Используйте на свой риск"; //Use at your own risk 
var Premadeletter92 = "Если UID вашего друга ошибочен, покупка не удастся"; //If friend UID is wrong, purchase will fail 
var Premadeletter93 = "Заводские настройки UID"; //UID Factory Settings 
var Premadeletter94 = "Вы должны войти, чтобы загрузить специальные предложения"; //You must login to load Special Deals 
var Premadeletter95 = "Поддельное изображение было скопировано в буфер обмена. Вставить его"; // Fake image has been copied to clipboard. Paste it 
var Premadeletter96 = "к пользовательской области URL-адреса скина, чтобы активировать функцию фальшивого флага"; // o custom skin Url area in order to activate the fake flag function 
var Premadeletter97 = "Сообщите мне, когда вы закончите с Recaptcha"; //Inform me when you finish with Recapatcha 
var Premadeletter98 = "Я закончил"; //I have finished 
var Premadeletter99 = "Неважно"; //Never Mind 
var Premadeletter100 = "Вычисляя ваш XP, подождите ..."; //Calculating your XP, please wait... 
var Premadeletter101 = "Делать"; //Do 
var Premadeletter102 = "НЕ"; //NOT 
var Premadeletter103 = "Нажмите"; //press 
var Premadeletter104 = "Стереть пользовательский URL-адрес скина"; //Erase custom skin URL 
var Premadeletter105 = "выбрать видео скин";	//select video skin 
var Premadeletter106 = "снять видео с экрана"; //unselect video skin 
var Premadeletter107 = "звук без звука"; //mute audio 
var Premadeletter108 = "Проект LM"; //The LM Project 
var Premadeletter109 = "Загрузить"; //Upload 
var Premadeletter109a = "Скачать"; //Download
var Premadeletter109b = "Load"; //Load
var Premadeletter109c = "SERVER"; //SERVER
var Premadeletter110 = "не вводите ничего здесь, если вы не знаете, что это такое";	//do not enter anything here unless you know what it is 
var Premadeletter111 = "нажмите на значок оранжевого цвета, чтобы купить"; //click on the orange icon to buy 
var Premadeletter112 = "Для некоторых способов оплаты"; //For some payment methods 
var Premadeletter113 = "Закрыть";	//Close 
var Premadeletter114 = "копия"; //COPY	 
var Premadeletter115 = "используется для покупки предложений для ваших друзей"; //is used to buy offers for your friends 
var Premadeletter116 = "Чтобы совершать покупки, вы должны войти в свою учетную запись ..."; //To make purchases, you must be logged in to your account… 
var Premadeletter117 = "Библиотека"; //Library 
var Premadeletter118 = "посещение"; //visit 
var Premadeletter119 = "Сообщить как фальшивый (изменить Кожа)"; //Report as Fake (change Skin) 
var Premadeletter120 = "Введите свое ТОЧНОЕ имя игрока"; //Enter your EXACT name of the player 
var Premadeletter121 = "Злоупотребление игроками и неправильное использование приведет к UID пользователя"; //Abusing players and inappropriate use will lead UID of user 
var Premadeletter122 = "к постоянному запрету использования этого расширения"; //to permanent ban from usage of this extension 
var Premadeletter128 = "Требуется логин"; //User login needed
var Premadeletter129 = "Настройки успешно загружены"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERVER"; //SERVER
var Premadeletter124 = "Избегайте использования видео-скинов больше 6 минут"; //Avoid using video skins bigger than 6 minutes
vvar Premadeletter125 = "Карта исправлена"; //Map fixed
var Premadeletter126 = "Войти в"; //Logged in to
var Premadeletter127 = "Вышли из"; //Logged out

var Externalletter0a = "ЯЗЫКИ"; //LANGUAGES 
var Externalletter0b = "Выберите язык"; //Choose a language 
var Externalletter0c = "Изменения будут выполнены полностью после перезапуска"; //Changes will take place completely after the restart 
var Externalletter1 = "ИНФОРМАЦИЯ"; //INFORMATION 
var Externalletter2 = "ШАБЛОНЫ"; //TEMPLATES 
var Externalletter3 = "РУЧНЫЕ ШАБЛОНЫ"; //MANUAL TEMPLATES 
var Externalletter4 = "Выберите шаблон"; //Choose your template 
var Externalletter5 = "Или выберите расширение"; //Or choose an expansion //These are for file: https://jimboy3100.github.io/legendformIframe.js 
var Externalletter5a = "ОТПРАВИТЬ КОДУ ДЛЯ РАЗРАБОТЧИКОВ"; //SEND CODE TO DEVELOPERS //These are for file: https://jimboy3100.github.io/legend.sniff3.js 
var Externalletter6 = "Вставьте свой скрипт в этот Textarea, вы можете загрузить несколько скриптов"; //Paste your Script in this Textarea, you can load multiple Scripts 
var Externalletter7 = "Загрузить скрипт из Textarea"; //Load Script from Textarea 
var Externalletter8 = "выберите"; //Choose 
var Externalletter9 = "Сценарий стирания"; //Erase Script 
var Externalletter10 = "имя"; //Name 
var Externalletter11 = "Url Github или другой Raw Script, начиная с"; //Url of Raw Github, or other Raw Script, starting with 
var Externalletter12 = "Оставьте это пустым, если скрипт не импортирован из URL"; //Leave this empty if script not imported from URL 
var Externalletter13 = "ВАЖНОЕ ЗАМЕЧАНИЕ. Не держите URL-адреса, которые не работают, потому что они используются как события onload. Если сценарий повреждает события onload, тогда DELETE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
