/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home (even if in french in this context home="accueil" :))                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="JdieR";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Accueil";		//Home
var Languageletter1="Joueur";		//User
var Languageletter2="Paramètres";		//Settings
var Languageletter3="Thème";		//Theme
var Languageletter4="Raccourcisn claver";		//Hotkeys
var Languageletter5="Sons & musiques Youtube";		//Youtube & Sounds
var Languageletter6="Outils";		//Tools
var Languageletter7="Laissez ce bloc vide pour être en public, sinon insérer un mot de passe de clan ou un tag";		//Password/Tag
var Languageletter7a="Mot de passe ou tag"	;	//Password/Tag
var Languageletter8="Insérez votre nom de joueur, 50 caractères sont visibles pour les utilisateurs du mode, 15 seulement pour les autres utilisateurs";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Nom";		//Name
var Languageletter9="Insérez le lien pour un skin manuel";		//Insert your manual skin weblink
var Languageletter9a="Lien URL direct pour un skin";		//Manual direct skin URL
var Languageletter10="Lieu du serveur";		//The region to play
var Languageletter11="Mode de jeu";		//The mode to play
var Languageletter12="Connectez-vous au serveur ou rétablissez la communication";		//Connect to server, or restablish communication
var Languageletter12a="Connex.";		//Connect
var Languageletter13="Joindre";		//Join
var Languageletter14="Jouer en tant qu'invité";		//Play as guest
var Languageletter15="S'dentifier et jouer";		//Login and Play
var Languageletter16="Regarder";		//Spectate
var Languageletter17="S'identifier avec Facebook";		//Sign in with Facebook
var Languageletter18="S'identifier avec Google";			//Sign in with Google
var Languageletter19="Jouer";		//Play
var Languageletter20="Boutique"	;		//Shop
var Languageletter21="Coins gratuits";		//Free Coins
var Languageletter22="Cadeaux";		//Gifts
var Languageletter23="Quêtes journalières";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Vidéo de promotion du Legend Mod";		//Legend Promo Video
var Languageletter25a="Nouveau formulaire d'idées et de statistiques";		//New Ideas & Statistics Form
var Languageletter25b="Mod Info et modèles";		//Mod Info & Templates
var Languageletter26="Ajouter des skins";		//Add skins
var Languageletter27="Coins gratuits";		//Free Coins
var Languageletter31="Se déconnecter";		//Logout
var Languageletter32="Nombre de fois utilisé";		//Times Used
var Languageletter33="Legend Mod fait par";		//Legend Mod by
var Languageletter34="Traduction faite par";		//Translation by
var Languageletter35="Copiez les noms du classement. (Pressez x pour montrer/cacher)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animation";		//Animation
var Languageletter37="Retard d'animation";		//Animation delay
var Languageletter37a="Zoom automatique";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Vitesse du zoom :";		//Zoom speed: 
var Languageletter39="Respawn";			//Respawn
var Languageletter40="Respawn automatique";		//Auto respawn 
var Languageletter41="Respawn rapide";			//Quick respawn 
var Languageletter42="Noms";			//Names
var Languageletter43="Pas de noms";		//No names 
var Languageletter44="Noms optimisés";		//Optimized names 
var Languageletter45="Masquage automatique des noms";		//Auto hide names 
var Languageletter46="Cacher mon nom";		//Hide my name 
var Languageletter47="Cacher le nom de mes coéquipiers";		//Hide teammates names 
var Languageletter48="Noms mis en avant";		//Names stroke 
var Languageletter49="Masse";		//Mass
var Languageletter50="Afficher la masse";		//Show mass 
var Languageletter51="Masse optimisée"	;	//Optimized mass 
var Languageletter52="Masquage automatique de la masse";			//Auto hide mass 
var Languageletter53="Cacher ma masse";		//Hide my mass 
var Languageletter54="Cacher la masse de mes ennemis";		//Hide enemies mass 
var Languageletter55="Mass courte";		//Short mass
var Languageletter56="Tirs de virus";		//Virus shots 
var Languageletter57="Masse mise en avant";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="Pas de skins ";		//No skins 
var Languageletter60="Skins personnalisés";		//Custom skins 
var Languageletter61="Vanilla skins";		//Vanilla skins 
var Languageletter62="Nourriture optimisée";		//Optimized food 
var Languageletter6a2="Nourriture";		//Food 
var Languageletter63="Masquage automatique de la nourriture";		//Auto hide food (mass) 
var Languageletter64="Masquage automatique de la nourriture";		//Auto hide food (zoom) 
var Languageletter65="Nourriture multicolores";		//Rainbow food 
var Languageletter66="Transparence / Couleurs";		//Transparency / colors
var Languageletter67="Pas de couleur";		//No colors 
var Languageletter68="Couleur personnalisée";		//My custom color 
var Languageletter69="Mon skin transparent";		//My transparent skin 
var Languageletter70="Skins transparents";		//Transparent skins 
var Languageletter70a="Cellules transparentes";		//Transparent cells
var Languageletter71="Virus transparents";		//Transparent viruses 
var Languageletter72="Grille et secteurs";		//Grid / sectors
var Languageletter73="Afficher la grille";		//Show grid 
var Languageletter74="Aficher les secteurs en fond";		//Show background sectors 
var Languageletter75="Afficher les bords de la map";		//Show map borders 
var Languageletter76="Chat";		//Chat
var Languageletter77="Désactiver le chat";		//Disable chat 
var Languageletter78="Notifications sonoress";		//Sound notifications 
var Languageletter79="Emoticônes";		//Emoticons 
var Languageletter80="Afficher les images dans le chat";		//Show images on chat 
var Languageletter81="Afficher les vidéos dans le chat";		//Show videos on chat 
var Languageletter82="Boîte de chat au lieu de fenêtres pop-up";		//Chatbox instead of popups 
var Languageletter82a="Minimap";		//Minimap
var Languageletter82b="Afficher la minimap";		//Show minimap 
var Languageletter82c="Afficher la grille sur la minimap";		//Show minimap grid 
var Languageletter82d="Afficher les guides sur la minimap";		//Show minimap guides 
var Languageletter82e="Les coéquipiers d'une seule couleur";		//One-colored teammates 
var Languageletter83="Aides";		//Helpers
var Languageletter84="Couleurs pour les adversaires";		//Opponents colors
var Languageletter85="Anneaux pour les adversaires";		//Opponents rings 
var Languageletter86="Couleur des virus";		//Viruses colors 
var Languageletter87="Portée de split";		//Split range 
var Languageletter88="Portée des virus";		//Viruses range 
var Languageletter89="Suivi du curseur";		//Cursor tracking 
var Languageletter90="Indicateurs des coéquipiers";		//Teammates indicators 
var Languageletter91="Contrôle de la souris";		//Mouse control
var Languageletter92="Clic gauche - Mouse split";		//LMB - Mouse split 
var Languageletter93="Clic droit - Mouse feed";		//RMB - Mouse feed 
var Languageletter94="Inverser les boutons de la souris";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="Afficher l'équipe top 5";		//Show team top 5 
var Languageletter96="Afficher le ciblage";		//Show targeting 
var Languageletter97="Centrer le classement";		//Centered leaderboard 
var Languageletter98="Statistiques du jeu en haut";		//Game stats at the top 
var Languageletter99="Statistiques";		//Stats
var Languageletter100="Afficher les statistiques de la partie";		//Show game stats 
var Languageletter101="Statistiques de jeu : Masse";		//Game stats: Mass 
var Languageletter102="Statistiques de jeu : STE";		//Game stats: STE 
var Languageletter103="Statistiques de jeu : n/16";		//Game stats: n/16 
var Languageletter104="Statistiques de jeu : FPS";		//Game stats: FPS 
var Languageletter105="Afficher l'heure actuelle";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Garder les statistiques après la mort";		//Skip stats after death 
var Languageletter108="Afficher la qûete";		//Show quest 
var Languageletter109="Bloquer les pop-ups (publicités/boutique/quête)";		//Block popups (ads/shop/quest) 
var Languageletter110="-- Qualité du graphisme --";		//-- Graphics Quality --
var Languageletter111="Graphisme : Retina";		//Graphics: Retina
var Languageletter112="Graphisme : Élevé";		//Graphics: High
var Languageletter113="Graphisme : Moyen";		//Graphics: Medium"
var Languageletter114="Graphisme : Faible";		//Graphics: Low
var Languageletter115="Graphisme : Très faible";		//Graphics: Very Low
var Languageletter116="Exporter/Importer les paramètres";		//Export / import settings
var Languageletter117="Restaurer les paramètres par défaut";		//Restore default settings
var Languageletter118="Exporter les paramètres";		//Export settings
var Languageletter119="Importer les paramètres";		//Import settings
var Languageletter120="Pour exporter les paramètres sélectionnés, copiez le code ci-dessous et enregistrez-le dans un fichier texte codé en Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Pour importer les paramètres sélectionnés, collez un code exporté ci-dessous et appuyez sur le bouton 'Importer les paramètres'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Commandes";		// Commands
var Languageletter123="Raccourcis";		// Hotkeys
var Languageletter124="Profil";		// Profiles
var Languageletter125="Paramètres";		// Settings
var Languageletter126="Thème";		// Theme
var Languageletter127="Paramètres exportés";		//Export settings
var Languageletter128="Paramètres importés";		//Import settings
var Languageletter129="Thème de base";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimap";		//Minimap
var Languageletter134="Graphique et curseur";		//Graphics / cursors
var Languageletter135="Préréglage du thème";		//Theme preset
var Languageletter136="Legend original";		//Legend Original
var Languageletter137="Crazy style";		//Crazy Style 1
var Languageletter139="Fond";		//Background
var Languageletter140="Bord de la map";		//Map borders
var Languageletter141="Grille";		//Grid
var Languageletter142="Police des secteurs";		//Sectors font
var Languageletter143="Noms";		//Names
var Languageletter144="Noms mis en avant";		//Names stroke
var Languageletter145="Masse";		//Mass
var Languageletter146="Masse mise en avant";		//Mass stroke
var Languageletter147="Virus mis en avant";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter149="Nourriture";		//Food
var Languageletter150="Indicateur de coéquipiers";		//Teammate indicator
var Languageletter151="Suivi du curseur";		//Cursor tracking
var Languageletter152="Portée de split";		//Split range
var Languageletter153="Police des noms";		//Names font
var Languageletter154="Police de la masse";		//Mass font
var Languageletter155="Police des secteurs";		//Sectors font
var Languageletter157="Taille de police des secteurs";		//Sectors font size
var Languageletter158="Echelle des noms";		//Names scale
var Languageletter159="Echelle de la masse";		//Mass scale
var Languageletter160="Echelle de la masse d'un virus";		//Virus mass scale
var Languageletter161="Echelle du texte mis en avant";		//Text stroke scale
var Languageletter162="Taille de la nourriture";		//Food size: 
var Languageletter163="Taille des virus mis en avant";		//Virus stroke size
var Languageletter164="Largeur des bords de la map";		//Map borders width
var Languageletter165="Largeur de la grille des secteurs";		//Sectors grid width
var Languageletter166="Cellules transparentes";		//Cells transparency
var Languageletter167="Skins transparents";		//Skins transparency
var Languageletter168="Virus transparents";		//Virus transparency
var Languageletter169="Noms et masse transparents";		//Names & mass transparency
var Languageletter170="Restaurer les paramètres par défaut du thème";		//Restore theme default settings
var Languageletter171="Sauvegarder les paramètres";		//Save settings
var Languageletter172="Thème du menu";		//Menu theme
var Languageletter173="Fond";		//Background
var Languageletter174="Transparence";		//Transparency
var Languageletter175="Couleur principale";		//Main color
var Languageletter176="Texte du bouton";		//Button text
var Languageletter177="Tableau de bord";		//Panel
var Languageletter179="Texte du tableau de bord";		//Panel text
var Languageletter181="Bouton";		//Button
var Languageletter189="Image d'arrière plan du tableau de bord";		//Panel background image
var Languageletter190="Image URL";		//Image URL
var Languageletter191="Couleur principale";		//Main color
var Languageletter192="Fond";		//Background
var Languageletter193="Texte";		//Text
var Languageletter194="Statistiques";		//Stats
var Languageletter195="Temps";		//Time
var Languageletter196="Top 5 de la masse";		//Top 5 mass
var Languageletter197="Classement - moi";		//Leaderboard - me
var Languageletter198="Classement - coéquipiers";		//Leaderboard - teammate
var Languageletter199="Police du HUD";		//HUD font
var Languageletter200="Echelle du HUD";		//HUD scale: 
var Languageletter201="Message du fond";		//Message background
var Languageletter202="Message du texte";		//Message text
var Languageletter203="Message du temps";		//Message time
var Languageletter204="Message du nom";		//Message nick
var Languageletter205="Commande du fond";		//Command background
var Languageletter206="Commande du texte";		//Command text
var Languageletter207="Commande du temps";		//Command time
var Languageletter208="Commande du nom";		//Command nick
var Languageletter209="Couleur du chat";		//Chatbox color
var Languageletter210="Echelle du chat";		//Chat scale
var Languageletter211="Secteurs";		//Sectors
var Languageletter212="Secteur actuel";		//Current sector
var Languageletter213="Nom";		//Nick
var Languageletter214="Nom mis en avant";		//Nick stroke
var Languageletter215="Ma cellule";		//My cell
var Languageletter216="Ma cellule mise en avant";		//My cell stroke
var Languageletter217="Coéquipiers";		//Teammates
var Languageletter218="Location de sa mort";		//Death location
var Languageletter219="Guides";		//Guides
var Languageletter220="Police de la minimap";		//Minimap font
var Languageletter221="Police du nom";		//Nick font
var Languageletter222="Largeur de la minimap";		//Minimap width
var Languageletter223="Secteurs transparents";		//Sectors transparency
var Languageletter224="Taille du nom";		//Nick size
var Languageletter225="Taille du nom en avant";		//Nick stroke size
var Languageletter226="Taille de ma cellule";		//My cell size
var Languageletter227="Taille de ma cellule mise en avant";		//My cell stroke size
var Languageletter228="Taille des coéquipiers";		//Teammates size
var Languageletter229="Image de fond personnalisé";		//Custom background image
var Languageletter230="Image de curseur personnalisée";		//Custom cursor image
var Languageletter231="Image URL";		//Image URL
var Languageletter232="Curseur de l'image URL";		//Cursor image URL
var Languageletter233="Feed";		//Feed
var Languageletter234="Macro feed";		//Macro feed
var Languageletter235="Split";		//Split
var Languageletter236="Double split";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="Split en 16";		//Split 16
var Languageletter239="Cellule en pause";		//Cell pause
var Languageletter240="Afficher/masquer le top 5 de l'équipe";		//Show/hide team top 5
var Languageletter241="Afficher/masquer le temps actuel";		//Show/hide current time
var Languageletter242="Afficher/masquer la portée de split";		//Show/hide split range"
var Languageletter243="Afficher/masquer les indicateurs de coéquipiers";		//Show/hide teammates indicators
var Languageletter244="Afficher/masquer les indicateurs de split";		//Show/hide split indicators
var Languageletter245="Afficher/masquer la couleur des adversaires";		//Show/hide opponents colors
var Languageletter246="Basculer les skins (customisé/par défaut)";		//Toggle skins (custom/default)
var Languageletter247="Basculer les skins transparents";		//Toggle transparent skins
var Languageletter248="Afficher/masquer les skins";		//Show/hide skins
var Languageletter249="Afficher/masquer les statistiques de jeu";		//Show/hide game stats
var Languageletter250="Basculer sur ses cellules (les plus petites/plus grandes)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Afficher/masquer la nourriture";		//Show/hide food
var Languageletter252="Afficher/masquer la grille";		//Show/hide grid
var Languageletter253="Afficher/masquer les guides sur la minimap";		//Show/hide minimap guides
var Languageletter254="Afficher/masquer le chat";		//Show/hide chat
var Languageletter255="Afficher/masquer le HUD";		//Show/hide HUD
var Languageletter256="Copier le classement";		//Copy leaderboard
var Languageletter257="Afficher/masquer le classement";		//Show/hide leaderboard
var Languageletter258="Lancer le zoom automatique";		//Toggle auto zoom
var Languageletter259="Réinitialiser le zoom";		//Reset zoom
var Languageletter260="Basculer la localisation de sa mort";		//Toggle death location
var Languageletter261="Show chat history / Clear chat";		//Show chat history / Clear chat
var Languageletter262="Afficher/masquer les secteurs de fond";		//Show/hide background sectors
var Languageletter263="Afficher/masquer les petits bots";		//Show/hide small bots
var Languageletter264="Afficher/masquer les noms";		//Show/hide names
var Languageletter265="Afficher/masquer le nom de ses coéquipiers";		//Show/hide teammates names
var Languageletter266="Afficher/masquer la masse";		//Show/hide mass
var Languageletter267="Afficher/masquer la minimap";		//Show/hide minimap
var Languageletter268="Entrer un message dans le chat";		//Enter chat message
var Languageletter269="Respawn rapide";		//Quick respawn
var Languageletter270="Basculer le respawn automatique";		//Toggle auto respawn
var Languageletter271="Niveau du zoom";		//Zoom level 
var Languageletter272="Afficher/masquer le panneau de ciblage";		//Show/hide targeting panel
var Languageletter273="Commencer/arrêter le ciblage (suivi)";		//Start/stop targeting (following)
var Languageletter274="Annuler le ciblage";		//Cancel targeting
var Languageletter275="Changer de cible";		//Change target
var Languageletter276="Montrer la cible sur la minimap";		//Show target on the minimap
var Languageletter277="Afficher/masquer la quête";		//Show/hide quest
var Languageletter278="Pour attribuer un raccourci, cliquez sur le champ de saisie et appuyez sur la touche choisie.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Pour supprimer un raccourci, cliquez sur le champ de saisie et appuyez sur la touche DELETE.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Possibilité de combinaisons de touches avec les touches CTRL et ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Restaurer les paramètres par défaut";		//Restore default settings
var Languageletter282="Sauvegarder les paramètres";		//Save settings
var Languageletter283="Fermer";		//Close
var Languageletter284="URL Youtube";		//Youtube player
var Languageletter284a="URL Youtube";		// Youtube Url
var Languageletter285="Collez votre vidéo/playlist ici";		//Paste your video/playlist here
var Languageletter286="Sons";		//Sounds
var Languageletter287="Message de notification sonore";		//Message notification sound
var Languageletter288="Commande de notification sonore";		//Command notification sound
var Languageletter289="Copier le lien/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Lien";		//Token
var Languageletter290a="Classement"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Copier";		//Copy


var Languageletter291a="Copier le classement (L)";		//Copy Leaderboard (L)
var Languageletter291b="Copier le jeton / SIP et mot de passe"; 	//Copy Token/SIP&Password
var Languageletter291c="Copier tout..."; //Copy Token/SIP, Password, Leaderboard
var Languageletter292="Joindre le serveur (Backspace)";		//Join server (Backspace)
var Languageletter293="Changer de serveur (+)";		//Change server (+)
var Languageletter294="Historique du classement";		//Leaderboard history
var Languageletter295="Entrer le lien d'un ami, adresse IP, classement, nom ou tag de clan...";		//Enter friend\'s token, IP, leaderboard, name or clan tag...


var Languageletter298="Top de l'équipe";		//Team top 
var Languageletter299="Classement";		//Leaderbodard
var Languageletter300="Communication";		//Communication
var Languageletter301="Message des scripts de commande";		//Message Script Commands
var Languageletter302="Message Imgur";		//Message Imgur Icons
var Languageletter303="Message des vidéos Youtube";		//Message Youtube Videos
var Languageletter304="Editer les noms";		//Edit names
var Languageletter305="[Mode spectateur uniquement] Jumelles";		//[Spectate Mode Only] Binoculars
var Languageletter306="Play / Pause";		//Play / Pause
var Languageletter307="Plein écran";		//Fullscreen
var Languageletter308="Tourner";		//Rotate
var Languageletter309="Défaut";		//Default
var Languageletter310="Retour";		//Back
var Languageletter311="Sauvegarder pour plus tard";		//Save for later
var Languageletter312="Région";		//Region
var Languageletter313="Joueurs";		//Players
var Languageletter314="Serveurs";		//Servers
var Languageletter315="[Cible non définie]";		//[Target not set]
var Languageletter316="Fond manuel";		//Manual background
var Languageletter317="Message manuel des îcones et de Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Position du chat";		//Chat Position
var Languageletter319="URL Discord Webhook (pour envoyer un lien)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Classement";		//Leaderboard
var Languageletter321="Tableau d'équipe";		//Teamboard
var Languageletter322="Bloc principal";		//Main Canvas
var Languageletter323="Bannière principale";		//Main Banner
var Languageletter324="Salut l'équipe !";		//Hello Team!
var Languageletter325="Rire";		//Laugh to Team
var Languageletter326="Changer le nom de l'équipe en";		//Team Change Name to yours
var Languageletter327="Troll";		//Troll on Death
var Languageletter328="Ouvrir la musique Youtube";		//Open Youtube Music
var Languageletter329="Mode insane (Cacher tout)";		//Insane mode (Hide Everything)
var Languageletter330="URL de l'image commençant par http://... ou https://...";		//Url of image starting with http://... or https://...
var Languageletter331="URL de l'image de la minimap";		//Minimap Image URL
var Languageletter332="Texte de la minimap";		//Minimap Text
var Languageletter333="Texte du logo du classement";		//Leaderboard Logo Text
var Languageletter333a="URL de l'image du classement";		// Leaderboard Image URL
var Languageletter334="Texte du logo du tableau de l'équipe";		//Teamboard Logo Text
var Languageletter334a="URL de l'image du tableau de l'équipe";		// Teamboard Image URL
var Languageletter335="URL de l'image principale";		//Main Canvas Image URL
var Languageletter336="URL principale de l'icône de la bannière";		//Main Banner Icon URL
var Languageletter337="URL principale du lien de bannière";		//Main Banner Link URL
var Languageletter338="Icône";		//Icon
var Languageletter339="par exemple";		//e.g
var Languageletter340="Url Youtube à afficher";		//Url of youtube to be shown
var Languageletter341="Url de redirection";		//Url of link to redirect
var Languageletter342="Url Discord Webhook";		//Discord Webhook Url
var Languageletter342a="Message du texte Imgur";		//Message Icon Text
var Languageletter342b="Message du texte Youtube";		//Youtube Message Text
var Languageletter342c="Message de l'URL Imgur";		//Message Icon Imgur Url
var Languageletter342d="Message de l'URL Youtube";		//Youtube Message Url
var Languageletter343="Doit être rempli pour fonctionner";		//Must be filled for function to work.
var Languageletter344="Webhook secondaire (optionnel)";		//Secondary Webhook(optional)
var Languageletter345="ATTENTION ! Les fenêtres popups sont bloquées dans les paramètres.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Débloquer temporairement";		//Temporary unblock
var Languageletter347="ATTENTION ! Les fenêtres popups sont bloquées dans les paramètres.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Débloquer temporairement";		//Temporary unblock

var Premadeletter0="Communication Activée"; 		//Communication Activated
var Premadeletter1="Impossible d'ouvrir cette URL Youtube";		 //Cannot open this youtube URL
var Premadeletter2="Vous ne pouvez pas discuter si le nom du joueur est supérieur à 15 caractères"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Activé"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Activé";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Activé";		//Easter Egg 3 Activated
var Premadeletter6="La vidéo fonctionne mieux sur vanilla, visitez :";		//Video works better on vanilla, visit:
var Premadeletter7="Notes : La compatibilité de <b>Facebook</b> est meilleure que celle de <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notes : Agar.io peut seulement se connecter à <b>Google Plus</b> sur les événements en charge. Si la déconnexion persiste, rejoignez Agar.io ou utiliser <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Si le déconnexion se produit sur les événements en charge, supprimez les cookies Chrome de";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Déconnecté du serveur :(";		//Disconnected from server :(
var Premadeletter11="Vous avez été banni, redémarrez votre routeur !";		//You were banned, restart your rooter!
var Premadeletter12="Connecté !";		//Connected!
var Premadeletter13="JOUER";		//PLAY
var Premadeletter14="REGARDER";		//SPECTATE
var Premadeletter15="Lien invalide ou le serveur a été fermé :(";		//Invalid token or server has closed :(
var Premadeletter16="Peut être mis à jour";		//can be Updated to
var Premadeletter17="Bon retour";			//Welcome back
var Premadeletter18="Votre zone de raccourci et d'autres zones (depuis le dernier onglet) sont encore désactivées ! Nous vous suggérons de les activer.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Activez-les";		//Enable Them
var Premadeletter20="Gardez-les désactivés";		//Keep Them Disabled
var Premadeletter21="Recherche de l'IP";		//Searching IP
var Premadeletter22="Votre coéquipier";		//Your teammate
var Premadeletter23="Voulez-vous tout cacher (le classement et la minimap) ?";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Acceptez";		//Accept
var Premadeletter25="PAS MOYEN !";		//NO WAY!
var Premadeletter26="Voulez-vous chnger votre nom en";		//wants you to change your name to
var Premadeletter27="Voulez-vous permettre un troll ?";		//wants you to hide Enable Troll on death
var Premadeletter28="Voulez-vous ouvrir Youtube ?";			//wants you to open Youtube Player
var Premadeletter29="Classement trouvé";		//Leaderboard found
var Premadeletter30="Recherche";		//Search
var Premadeletter31="Le classement n'a pas été trouvé. Continuez d'essayer...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="La recherche a été annulée";		//Search was canceled
var Premadeletter33="Vous êtes invisible pour vos coéquipiers";		//You are invisible to Team / Clan
var Premadeletter34="Vous êtes visible pour vos coéquipiers";		//You are visible to Team / Clan
var Premadeletter35="Afficher/masquer peut être utilisé uniquement pendant la lecture";			//Hide/Show can be used only while playing
var Premadeletter36="Ceci n'est pas une adresse Discord Webhook valide";		//This is not valid Discord Webhook address
var Premadeletter37="Le serveur est fermé";		//Server is locked
var Premadeletter38="Vous devez être en mode spectateur";		//You must be on spectate mode
var Premadeletter39="En raison de problèmes de spam, vous devez être dans le jeu et utiliser le mot de passe";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube on";		//Auto Youtube On
var Premadeletter41="Auto Youtube off";		//Auto Youtube Off
var Premadeletter42="Afficher raccour.";		//Show Shortcuts
var Premadeletter43="Masquer raccour.";		//Hide Shortcuts
var Premadeletter44="Afficher barre d'XP";		//Show XP BAR
var Premadeletter45="Masquer barre d'XP";		//Hide XP BAR
var Premadeletter45a = "Arrondie Hud"; //Rounded Hud
var Premadeletter45b = "Carré Hud"; //Square Hud

var Premadeletter46="Afficher Skin animé";		//Show TIME
var Premadeletter47="Masquer Skin animé";		//Hide TIME
var Premadeletter48="Tout afficher";		//Show Everything
var Premadeletter49="Tout masquer";		//Hide Everything
var Premadeletter50="Affich. chronom.";		//Show Timer Calc.
var Premadeletter51="Masquer chronom."		//Hide Timer Calc.
var Premadeletter52="Éditer les noms";		//Edit Names
var Premadeletter52a="Fermer les noms";		//Close Names
var Premadeletter53="automatiq. coins";		//Auto free coins
var Premadeletter54="Pas automatiques";		//Stop free coins
var Premadeletter55="Troll";		//Troll on Death
var Premadeletter56="Pas de troll";		//No troll on Death

var Premadeletter57="Communication";		//Communication
var Premadeletter58="Caché";		//Hidden
var Premadeletter59="Visible";		//Visible
var Premadeletter60="Pause";		//Pause
