                                                     
var translator="reinu";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Dom";		//Home
var Languageletter1="Użytkownik";		//User
var Languageletter2="Ustawienia";		//Settings
var Languageletter3="Motyw";		//Theme
var Languageletter4="Przyciski";		//Hotkeys
var Languageletter5="Youtube i Dźwięki";		//Youtube & Sounds
var Languageletter6="Przybory";		//Tools
var Languageletter7="Pozostaw to pole puste dla wszystkich, lub wpisz hasło klanowe, lub użyj go jako Tag";		//Password/Tag
var Languageletter7a="Hasło/Tag"	;	//Password/Tag
var Languageletter8="Wpisz swoją nazwę, 50 znaków jest widocznych dla użytkowników modyfikacji, 15 dla pozostałych";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Nazwa";		//Name
var Languageletter9="Wstaw swój link do strony ze skórką";		//Insert your manual skin weblink
var Languageletter9a="Bezpośredni adres URL skórki";		//Manual direct skin URL
var Languageletter10="Region do gry";		//The region to play
var Languageletter11="Tryb";		//The mode to play
var Languageletter12="Połącz się z serwerem lub przywróć komunikację";		//Connect to server, or restablish communication
var Languageletter12a="Połącz";		//Connect
var Languageletter13="Dołącz";		//Join
var Languageletter14="Graj jako Gość";		//Play as guest
var Languageletter15="Zaloguj i Graj";		//Login and Play
var Languageletter16="Oglądaj";		//Spectate
var Languageletter17="Zaloguj się przez Facebook";		//Sign in with Facebook
var Languageletter18="Zaloguj się przez Google";			//Sign in with Google
var Languageletter19="Graj";		//Play
var Languageletter20="Sklep"	;		//Shop
var Languageletter21="Darmowe Monety";		//Free Coins
var Languageletter22="Prezenty";		//Gifts
var Languageletter23="Codzienne Zadania";			//Daily Quests
var Languageletter24="Skórki";		//Skins
var Languageletter25="Legend Mod Promocyjne Wideo";		//Legend Promo Video
var Languageletter25a="Nowe Pomysły i Statystyki";		//New Ideas & Statistics Form
var Languageletter25b="Informacje i Szablony";		//Mod Info & Templates
var Languageletter26="Dodaj skórki";		//Add skins
var Languageletter26a="Kopiuj serwer, hasło, tablicę zespołową i tabelę rekordów"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Wyloguj";		//Logout
var Languageletter32="Czasy użyte";		//Times Used
var Languageletter33="Legend Mod stworzony przez";		//Legend Mod by
var Languageletter34="Translacja wykonana przez";		//Translation by
var Languageletter35="skopiuj tablicę wyników i nazwy komórek . (naciśnij x, żeby pokazać/schować)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animacja";		//Animation
var Languageletter37="Opóźnienie animacji";		//Animation delay
var Languageletter37a="Automatyczny zoom";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Szybkość zoom'a";		//Zoom speed:
var Languageletter39="Odrodzenie";			//Respawn
var Languageletter40="Automatyczne odrodzenie";		//Auto respawn
var Languageletter41="Szybkie odrodzenie ";			//Quick respawn
var Languageletter41a="Zacznij od efektów specjalnych";			//Spawn special effects 
var Languageletter41b="Wyłącz licznik czasu ";			//Merge timer off
var Languageletter41c="Sugerowane, aby włączyć dla opóźnienia zmniejszenia";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Dźwięk strzału wirusa";			//Virus shot sound

var Languageletter42="Nazwy";			//Names
var Languageletter43="Brak nazw";		//No names
var Languageletter44="Zoptymalizowane nazwy";		//Optimized names
var Languageletter45="Automatyczne ukrywanie masy";		//Auto hide names
var Languageletter46="Ukryj moją nazwę";		//Hide my name
var Languageletter47="Ukryj nazwy przyjaciół z drużyny";		//Hide teammates names
var Languageletter48="Obrys nazw";		//Names stroke
var Languageletter49="Masa";		//Mass
var Languageletter50="Pokaż masę";		//Show mass
var Languageletter51="Zoptymalizowana masa"	;	//Optimized mass
var Languageletter52="Automatyczne ukrywanie masy";			//Auto hide mass
var Languageletter53="Ukryj moją masę";		//Hide my mass
var Languageletter54="Ukryj masę wrogów";		//Hide enemies mass
var Languageletter55="Krótka masa";		//Short mass
var Languageletter56="Strzały wirusa";		//Virus shots
var Languageletter57="Obrys masy";		//Mass stroke
var Languageletter58="Skórki";		//Skins
var Languageletter59="Ukryj skórki";		//No skins
var Languageletter60="Niestandardowe skórki";		//Custom skins
var Languageletter61="Skórki z Vanilla'i";		//Vanilla skins
var Languageletter61a="Fizyka galaretki";		//Jelly physics 
var Languageletter61b="Skórki wideo";		//Video skins
var Languageletter61c="Dźwięk z innych skórek wideo, gdy oba C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Zoptymalizowane jedzenie";		//Optimized food
var Languageletter6a2="Jedzenie";		//Food
var Languageletter63="Automatyczne ukrywanie jedzenia (masa)";		//Auto hide food (mass)
var Languageletter64="Automatyczne ukrywanie jedzenia (Powiększenie)";		//Auto hide food (zoom)
var Languageletter65="Tęczowe jedzenie";		//Rainbow food
var Languageletter66="Przezroczystość / kolory";		//Transparency / colors
var Languageletter67="Ukryj kolory";		//No colors
var Languageletter68="Mój niestandardowy kolor";		//My custom color
var Languageletter69="Moja przezroczysta skórka";		//My transparent skin
var Languageletter70="Przezroczyste skórki";		//Transparent skins
var Languageletter70a="Przezroczyste komórki";		//Transparent cells
var Languageletter71="Przezroczyste wirusy";		//Transparent viruses
var Languageletter71a="Błyszczący wirus";		//Virus Glow
var Languageletter71b="Animowane kolory tęczy";		//Animated rainbow colors

var Languageletter72="Siatka / sektory";		//Grid / sectors
var Languageletter73="Pokaż siatkę";		//Show grid
var Languageletter74="Pokaż sektory w tle";		//Show background sectors
var Languageletter75="Pokaż granice mapy";		//Show map borders
var Languageletter75a="Blask granic";		//Border Glow

var Languageletter76="Czat";		//Chat
var Languageletter77="Wyłącz czat";		//Disable chat
var Languageletter78="Dźwięki powiadomień";		//Sound notifications
var Languageletter79="Emotikony";		//Emoticons
var Languageletter80="Pokaż obrazki na czacie";		//Show images on chat
var Languageletter81="Pokaż filmy na czacie";		//Show videos on chat
var Languageletter82="Okno czatu zamiast wyskakujących okien";		//Chatbox instead of popups
var Languageletter82a="Minimapa";		//Minimap
var Languageletter82b="Pokaż minimapę";		//Show minimap
var Languageletter82c="Pokaż obrys minimapy";		//Show minimap grid
var Languageletter82d="Pokaż wskazówki na minimapie";		//Show minimap guides
var Languageletter82e="Jednokolorowi przyjaciele z drużyny";		//One-colored teammates
var Languageletter82f="Pokaż dodatkowe mini przewodniki po mapach";		//Show extra minimap guides
var Languageletter82g="Pokaż komórki widmowe";		//Show ghost cells

var Languageletter83="Pomocnicy";		//Helpers
var Languageletter84="Kolory przeciwników";		//Opponents colors
var Languageletter85="Pierścienie przeciwników";		//Opponents rings
var Languageletter86="Kolory wirusów";		//Viruses colors
var Languageletter87="Zasięg rozdzielenia";		//Split range
var Languageletter87a="Szybki podwójny zakres podziału";		//Quick double split range
var Languageletter87b="Powolny podwójny zakres podziału";		//Slow double split range

var Languageletter88="Zasięg wirusów";		//Viruses range
var Languageletter89="Śledzenie kursora";		//Cursor tracking
var Languageletter90="Wskaźniki członków drużyny";		//Teammates indicators
var Languageletter90a="Komórki duchów";		//Ghost cells

var Languageletter91="Sterowanie myszką";		//Mouse control
var Languageletter92="LPM - Rozdzielanie myszką";		//LMB - Mouse split
var Languageletter93="PPM - Karmienie myszką";		//RMB - Mouse feed
var Languageletter94="Odwróć przyciski myszy";		//Invert mouse buttons
var Languageletter94a="HUD";		// HUD
var Languageletter95="Zespół";		//Team
var Languageletter96="Pokaż kierowanie";		//Show targeting
var Languageletter96a="Pokaż masę liderów";		//Show leaderboard mass

var Languageletter97="Wyśrodkowana tablica wyników";		//Centered leaderboard
var Languageletter97a="Nagłówek tablicy wyników";		//\"Leaderboard\" header 

var Languageletter98="Statystyki gry na górze";		//Game stats at the top
var Languageletter98a="Skórki na planszy zespołu";		//Skins on teamboard

var Languageletter99="Statystyki";		//Stats
var Languageletter100="Pokaż statystyki gry";		//Show game stats
var Languageletter101="Statystyki gry";		//Game stats
//the \' is needed
var Languageletter102="wroga";		//Enemy\'s 		
var Languageletter103="nasz";		//Our
var Languageletter104="Minimal trick podzielony na masę członka drużyny";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Maksymalna masa wroga do wstępnego podziału";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Pokaż aktualny czas";		//Show current time
var Languageletter106="Dodatki";		//Extras
var Languageletter107="Pomiń statystyki po śmierci";		//Skip stats after death
var Languageletter108="Pokaż zadania";		//Show quest
var Languageletter108a="Dźwięki Gry"; //Game Sounds
var Languageletter108b="Dźwięki Menu"; //Menu Sounds
var Languageletter109="Blokuj wyskakujące okienka (reklamy/sklep/zadanie)";		//Block popups (ads/shop/quest)
var Languageletter109a="GŁOS"; //Voice
var Languageletter109b="Prefiks Głosowy"; //Voice-Prefix
var Languageletter109c="Język Głosu"; //Voice-language
var Languageletter109d="UnPause"; //UnPause

var Languageletter110="-- Jakość graficzna --";		//-- Graphics Quality --
var Languageletter111="Grafika: Retina";		//Graphics: Retina
var Languageletter112="Grafika: Wysoka";		//Graphics: High
var Languageletter113="Grafika: Średnia";		//Graphics: Medium"
var Languageletter114="Grafika: Niska";		//Graphics: Low
var Languageletter115="Grafika: Bardzo niska";		//Graphics: Very Low
var Languageletter116="Eksportuj / Importuj ustawienia";		//Export / import settings
var Languageletter117="Przywróć ustawienia domyślne";		//Restore default settings
var Languageletter118="Eksportuj ustawienia";		//Export settings
var Languageletter119="Importuj ustawienia";		//Import settings
var Languageletter120="Aby wyeksportować wybrane ustawienia, skopiuj poniższy kod i zapisz go w pliku tekstowym zakodowanym w Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Aby zaimportować wybrane ustawienia, wklej wyeksportowany kod poniżej i naciśnij przycisk „Importuj ustawienia”.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Komendy";		// Commands
var Languageletter123="Przyciski";		// Hotkeys
var Languageletter124="Profile";		// Profiles
var Languageletter125="Ustawienia";		// Settings
var Languageletter126="Motyw";		// Theme
var Languageletter127="Eksportuj ustawienia";		//Export settings
var Languageletter128="Importuj ustawienia";		//Import settings
var Languageletter129="Podstawowe ustawienia tła";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Czat";		//Chat
var Languageletter133="Minimapa";		//Minimap
var Languageletter134="Grafika / Kursory";		//Graphics / cursors
var Languageletter135="Ustawienia motywu";		//Theme preset
var Languageletter136="Legend Original";		//Legend Original
var Languageletter137="Crazy Style";		//Crazy Style 1
var Languageletter139="Tło";		//Background
var Languageletter140="Granice mapy";		//Map borders
var Languageletter141="Siatka";		//Grid
var Languageletter142="Czcionka sektorów";		//Sectors font
var Languageletter143="Nazwy";		//Names
var Languageletter144="Obrysy nazw";		//Names stroke
var Languageletter145="Masa";		//Mass
var Languageletter146="Obrys masy";		//Mass stroke
var Languageletter147="Obrys wirusa";		//Virus stroke
var Languageletter148="Wirus";		//Virus
var Languageletter148a="komórka macierzysta";		//Mothercell
var Languageletter148b="Udar komórek macierzystych";		//Mothercell stroke
var Languageletter149="Jedzenie";		//Food
var Languageletter150="Wskaźnik drużynowy";		//Teammate indicator
var Languageletter151="Śledzenie kursora";		//Cursor tracking
var Languageletter152="Zasięg rozdzielenia";		//Split range
var Languageletter153="Czcionka nazw";		//Names font
var Languageletter154="Czcionka masy";		//Mass font
var Languageletter154a="Większy";		//Bigger
var Languageletter154b="Większy";		//Smaller
var Languageletter155="Czcionka sektorów";		//Sectors font
var Languageletter157="Rozmiar czcionki sektorów";		//Sectors font size
var Languageletter158="Skala nazw";		//Names scale
var Languageletter159="Skala masy";		//Mass scale
var Languageletter160="Skala masy wirusa";		//Virus mass scale
var Languageletter161="Skala tekstu";		//Text stroke scale
var Languageletter162="Rozmiar jedzenia";		//Food size:
var Languageletter163="Rozmiar obrysu wirusa";		//Virus stroke size
var Languageletter164="Szerokość granic mapy";		//Map borders width
var Languageletter165="Szerokość siatki sektorów";		//Sectors grid width
var Languageletter166="Przejrzystość komórek";		//Cells transparency
var Languageletter167="Przejrzystość skórek";		//Skins transparency
var Languageletter168="Przejrzystość wirusa";		//Virus transparency
var Languageletter169="Przejrzystość masy i nazw";		//Names & mass transparency
var Languageletter170="Przywróć domyślne ustawienia motywu";		//Restore theme default settings
var Languageletter171="Zapisz ustawienia";		//Save settings
var Languageletter172="Motyw Menu";		//Menu theme
var Languageletter173="Tło";		//Background
var Languageletter174="Przejrzystość";		//Transparency
var Languageletter175="Główny kolor";		//Main color
var Languageletter176="Przycisk tekstowy";		//Button text
var Languageletter177="Panel";		//Panel
var Languageletter179="Tekst panelu";		//Panel text
var Languageletter181="Przycisk";		//Button
var Languageletter189="Obraz tła panelu";		//Panel background image
var Languageletter190="Adres URL obrazu";		//Image URL
var Languageletter191="Główny kolor";		//Main color
var Languageletter192="Tło";		//Background
var Languageletter193="Tekst";		//Text
var Languageletter194="Statystyki";		//Stats
var Languageletter195="Czas";		//Time
var Languageletter196="Top 5 masa";		//Top 5 mass
var Languageletter197="Tablica wyników - ja";		//Leaderboard - me
var Languageletter198="Tablica wyników - członek drużyny";		//Leaderboard - teammate
var Languageletter199="HUD czcionka";		//HUD font
var Languageletter200="HUD skala";		//HUD scale:
var Languageletter201="Tło wiadomości";		//Message background
var Languageletter202="Tekst wiadomości";		//Message text
var Languageletter203="Czas wiadomości";		//Message time
var Languageletter204="Nazwa wiadomości";		//Message nick
var Languageletter205="Tło poleceń";		//Command background
var Languageletter206="Tekst poleceń";		//Command text
var Languageletter207="Czas poleceń";		//Command time
var Languageletter208="Nazwa poleceń";		//Command nick
var Languageletter209="Kolor okna czatu";		//Chatbox color
var Languageletter210="Skala czatu";		//Chat scale
var Languageletter211="Sektory";		//Sectors
var Languageletter212="Obecny sektor";		//Current sector
var Languageletter213="Nazwa";		//Nick
var Languageletter214="Obrys nazwy";		//Nick stroke
var Languageletter215="Moja komórka";		//My cell
var Languageletter216="Obrys mojej komórki";		//My cell stroke
var Languageletter217="Koledzy z drużyny";		//Teammates
var Languageletter218="Miejsce śmierci";		//Death location
var Languageletter219="Wskaźniki";		//Guides
var Languageletter220="Czcionka minimapy";		//Minimap font
var Languageletter221="Czcionka nazwy";		//Nick font
var Languageletter222="Szerokość minimapy";		//Minimap width
var Languageletter223="Przezroczystość sektorów";		//Sectors transparency
var Languageletter224="Rozmiar nazwy";		//Nick size
var Languageletter225="Rozmiar obrysu nazwy";		//Nick stroke size
var Languageletter226="Rozmiar mojej komórki";		//My cell size
var Languageletter227="Rozmiar obrysu mojej komórki";		//My cell stroke size
var Languageletter228="Rozmiar kolegów z drużyny";		//Teammates size
var Languageletter229="Niestandardowy obraz tła";		//Custom background image
var Languageletter230="Niestandardowy obraz kursora";		//Custom cursor image
var Languageletter231="Adres URL obrazu";		//Image URL
var Languageletter232="Adres URL obrazu kursora";		//Cursor image URL
var Languageletter233="Karmienie";		//Feed
var Languageletter234="Ciągłe karmienie";		//Macro feed
var Languageletter235="Rozdzielenie";		//Split
var Languageletter236="Podwójne rozdzielenie";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="Rozdzielenie na 16 komórek";		//Split 16
var Languageletter239="Pauza komórki";		//Cell pause
var Languageletter240="Pokaż/ukryj top 5 zespołu";		//Show/hide team top 5
var Languageletter241="Pokaż/ukryj obecny czas";		//Show/hide current time
var Languageletter242="Pokaż/ukryj zasięg rozdzielenia";		//Show/hide split range"
var Languageletter243="Pokaż/ukryj wskaźniki zespołu";		//Show/hide teammates indicators
var Languageletter244="Pokaż/ukryj wskaźniki rozdzielenia";		//Show/hide split indicators
var Languageletter245="Pokaż/ukryj kolory przeciwników";		//Show/hide opponents colors
var Languageletter246="Przełącz skórki (niestandardowe/domyślne)";		//Toggle skins (custom/default)
var Languageletter247="Przełącz przezroczyste skórki";		//Toggle transparent skins
var Languageletter248="Pokaż/ukryj skórki";		//Show/hide skins
var Languageletter249="Pokaż/ukryj statystyki gry";		//Show/hide game stats
var Languageletter250="Przełącz własne komórki (najmniejsze/największe)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Pokaż/ukryj jedzenie";		//Show/hide food
var Languageletter252="Pokaż/ukryj siatkę";		//Show/hide grid
var Languageletter253="Pokaż/ukryj przewodniki minimapy";		//Show/hide minimap guides
var Languageletter254="Pokaż/ukryj czat";		//Show/hide chat
var Languageletter255="Pokaż/ukryj HUD";		//Show/hide HUD
var Languageletter256="Kopiuj tablicę wyników";		//Copy leaderboard
var Languageletter257="Pokaż/ukryj tablicę wyników";		//Show/hide leaderboard
var Languageletter258="Przełącz automatyczny zoom";		//Toggle auto zoom
var Languageletter259="Resetuj zoom";		//Reset zoom
var Languageletter260="Przełącz miejsce śmierci";		//Toggle death location
var Languageletter261="Pokaż historię czatu / Wyczyść czat";		//Show chat history / Clear chat
var Languageletter262="Pokaż/ukryj sektory tła";		//Show/hide background sectors
var Languageletter263="Pokaż/ukryj małe boty";		//Show/hide small bots
var Languageletter264="Pokaż/ukryj nazwy";		//Show/hide names
var Languageletter265="Pokaż/ukryj nazwy kolegów z drużyny";		//Show/hide teammates names
var Languageletter266="Pokaż/ukryj masę";		//Show/hide mass
var Languageletter267="Pokaż/ukryj minimapę";		//Show/hide minimap
var Languageletter268="Wpisz wiadomość na czacie";		//Enter chat message
var Languageletter269="Szybkie odrodzenie";		//Quick respawn
var Languageletter270="Przełącz automatyczne odrodzenie";		//Toggle auto respawn
var Languageletter271="Poziom zoom'a";		//Zoom level
var Languageletter271a="Głos do tekstu";		//Voice to text
var Languageletter271b="Pokaż informacje o komórkach widm";		//Show ghost cells information
var Languageletter271c="Automatyczna gra";		//Auto Play
var Languageletter272="Pokaż/ukryj panel kierowania";		//Show/hide targeting panel
var Languageletter273="Rozpocznij/zatrzymaj kierowanie (podążające)";		//Start/stop targeting (following)
var Languageletter274="Anuluj kierowanie";		//Cancel targeting
var Languageletter275="Zmień cel";		//Change target
var Languageletter276="Pokaż cel na minimapie";		//Show target on the minimap
var Languageletter277="Pokaż/ukryj zadanie";		//Show/hide quest
var Languageletter278="Aby przypisać klawisz skrótu, kliknij pole wprowadzania i naciśnij wybrany klawisz.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Aby usunąć klawisz skrótu, kliknij pole wprowadzania i naciśnij klawisz DELETE.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Możliwe kombinacje klawiszy z klawiszami CTRL i ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Przywróć ustawienia domyślne";		//Restore default settings
var Languageletter282="Zapisz ustawienia";		//Save settings
var Languageletter283="Zamknij";		//Close
var Languageletter284="Odtwarzacz YouTube";		//Youtube player
var Languageletter284a="Youtube Url";		// Youtube Url
var Languageletter285="Wklej swój film/listę odtwarzania tutaj";		//Paste your video/playlist here
var Languageletter286="Dźwięki";		//Sounds
var Languageletter287="Dźwięk powiadomienia o wiadomości";		//Message notification sound
var Languageletter288="Dźwięk powiadomienia o poleceniu";		//Command notification sound
var Languageletter289="Kopiuj Token/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Token";		//Token
var Languageletter290a="Tablica"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&All"; //TK&ALL (Token and All)
var Languageletter291="Kopiuj";		//Copy

var Languageletter291a="Kopiuj Tabelę liderów (L)";		//Copy Leaderboard (L)
var Languageletter291b="Kopiuj Token/SIP i hasło"; 	//Copy Token/SIP&Password
var Languageletter291c="Kopiuj Token/SIP, Hasło, Tablicę wyników..."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="Dołącz do serwera (Backspace)";		//Join server (Backspace)
var Languageletter293="Zmień serwer (+)";		//Change server (+)
var Languageletter294="Historia Tablicy wyników";		//Leaderboard history
var Languageletter295="Wpisz token przyjaciela, adres IP, tablicę wyników, nazwę lub tag klanu ...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Czysta lista"; //Clear list
var Languageletter295b="Wpisz wiadomość czatu ..."; //Enter chat message...

var Languageletter298="Zespół";		//Team
var Languageletter299="Tabela liderów";		//Leaderbodard
var Languageletter300="Communication";		//Communication
var Languageletter301="Polecenia Skryptu Wiadomości";		//Message Script Commands
var Languageletter302="Ikony Wiadomości Imgur";		//Message Imgur Icons
var Languageletter303="Wiadomość Youtube Wideo";		//Message Youtube Videos
var Languageletter304="Edytuj nazwy";		//Edit names
var Languageletter305="[Tylko tryb oglądania] Lornetka";		//[Spectate Mode Only] Binoculars
var Languageletter306="Odtwórz / Pauza";		//Play / Pause
var Languageletter307="Pełny ekran";		//Fullscreen
var Languageletter308="Obróć";		//Rotate
var Languageletter309="Domyślna";		//Default
var Languageletter310="Z powrotem";		//Back
var Languageletter311="Zachowaj na później";		//Save for later
var Languageletter312="Region";		//Region
var Languageletter313="Gracze";		//Players
var Languageletter314="Serwery";		//Servers
var Languageletter315="[Cel nie został ustawiony]";		//[Target not set]
var Languageletter316="Ręczne tło";		//Manual background
var Languageletter317="Ręczne ikony wiadomości i YouTube";		//Manual Message Icons&Youtube
var Languageletter318="Pozycja czatu";		//Chat Position
var Languageletter319="Discord Webhook Url (do wysyłania TOKENu)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Tablica liderów";		//Leaderboard
var Languageletter321="Tablica liderów wśród przyjaciół";		//Teamboard
var Languageletter322="Główne płótno";		//Main Canvas
var Languageletter323="Główny baner";		//Main Banner
var Languageletter324="Hello Team!";		//Hello Team!
var Languageletter325="Śmiej się do zespołu";		//Laugh to Team
var Languageletter326="Zmień nazwę drużyny na twoją";		//Team Change Name to yours
var Languageletter327="Troll on Death";		//Troll on Death
var Languageletter328="Odtwórz muzykę Youtube";		//Open Youtube Music
var Languageletter329="Tryb szalony (Ukryj wszystko)";		//Insane mode (Hide Everything)
var Languageletter330="Adres URL obrazu rozpoczynający się od http:// ... lub https:// ...";		//Url of image starting with http://... or https://...
var Languageletter331="Adres URL obrazu minimapy";		//Minimap Image URL
var Languageletter332="Tekst minimapy";		//Minimap Text
var Languageletter333="Tekst logo liderów";		//Leaderboard Logo Text
var Languageletter333a="Adres URL obrazu tabeli liderów";		// Leaderboard Image URL
var Languageletter334="Tekst logo zespołu";		//Teamboard Logo Text
var Languageletter334a="Adres URL obrazu zespołu";		// Teamboard Image URL
var Languageletter335="Główny adres URL obrazu płótna";		//Main Canvas Image URL
var Languageletter336="Główny adres URL ikony banera";		//Main Banner Icon URL
var Languageletter337="Adres URL linku głównego banera";		//Main Banner Link URL
var Languageletter338="Ikona";		//Icon
var Languageletter339="e.g";		//e.g
var Languageletter340="Url youtube do wyświetlenia";		//Url of youtube to be shown
var Languageletter341="Adres URL linku do przekierowania";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="Tekst ikony wiadomości";		//Message Icon Text
var Languageletter342b="Youtube Message Text";		//Youtube Message Text
var Languageletter342c="Ikona wiadomości Imgur Url";		//Message Icon Imgur Url
var Languageletter342d="Youtube Message Url";		//Youtube Message Url
var Languageletter343="Należy wypełnić, aby funkcja działała";		//Must be filled for function to work.
var Languageletter344="Dodatkowy haczyk internetowy(opcjonalnie)";		//Secondary Webhook(optional)
var Languageletter345="OSTRZEŻENIE! Popupy są zablokowane w ustawieniach.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Tymczasowe odblokowanie";		//Temporary unblock
var Languageletter347="OSTRZEŻENIE! Popupy są zablokowane w ustawieniach.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Tymczasowe odblokowanie";		//Temporary unblock

var Languageletter349="Mikstury";	//Potions
var Languageletter350="Stare Skórki";	//Old Skins
var Languageletter351="Specjalne Oferty"; //Special Deals
var Languageletter352="Rankingi"; //Leaderboards
var Languageletter353="Nowe Pomysły i Statystyki"; //New Ideas & Statistics Form
var Languageletter354="Skórki Wideo"; //Video Skins
var Languageletter355="Mini Skrypty"; //Mini Scripts
var Languageletter356="Skrypty użytkownika"; //User Scripts
var Languageletter357="Czat Głosowy i Aparatowy";	//Voice & Camera Chat
var Languageletter358="Proszę wspierać rozwój Legendy";	//Please support the development of Legend mod
var Languageletter359="Stwórz Kreatywną Nazwę";	//Design Nickname Font
var Languageletter360="Oznacz Fałszywą Skórką";	//Flag the Fake Skin
var Languageletter361="Więcej fps'ów";	//More FPS
var Languageletter362="Imię";	//Name
var Languageletter363="ID społeczny";	//Social ID
var Languageletter364="Rozszerzenia";	//Expansions
var Languageletter365 = "Uniwersalny";	//Universal
var Languageletter366="Wynik";	//Score
var Languageletter367="Dystans";	//Distance
var Languageletter368="Masa całkowita";	//Total Mass
var Languageletter369="Nie żyje";	//Dead

var Premadeletter0="Komunikacja Aktywowana"; 		//Communication Activated
var Premadeletter1="Nie można otworzyć tego adresu URL YouTube";		 //Cannot open this youtube URL
var Premadeletter2="Nie możesz rozmawiać, jeśli nazwa gracza > 15 znaków"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Aktywowany"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Aktywowany";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Aktywowany";		//Easter Egg 3 Activated
var Premadeletter6="Wideo działa lepiej na wanilii, odwiedź:";		//Video works better on vanilla, visit:
var Premadeletter7="Uwagi:<b>Facebook'owa</b> kompatybilność jest lepsza niż <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Uwagi:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="If logout occurs on onload events, delete Chrome cookies from";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Rozłączony z serwerem :(";		//Disconnected from server :(
var Premadeletter11="Zostałeś zbanowany, uruchom ponownie rooter!";		//You were banned, restart your rooter!
var Premadeletter12="Połączono!";		//Connected!
var Premadeletter13="GRAJ";		//PLAY
var Premadeletter14="OGLĄDAJ";		//SPECTATE
var Premadeletter15="Nieprawidłowy token lub serwer został zamknięty :(";		//Invalid token or server has closed :(
var Premadeletter16="można Zaktualizować do";		//can be Updated to
var Premadeletter17="Witaj spowrotem";			//Welcome back
var Premadeletter18="Twój obszar skrótu i inne obszary (z ostatniej karty) są nadal wyłączone! Sugerujemy ich włączenie.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Włącz Je";		//Enable Them
var Premadeletter20="Zachowaj Je Wyłączone";		//Keep Them Disabled
var Premadeletter21="Szukanie IP";		//Searching IP
var Premadeletter22="Twój kolega z drużyny";		//Your teammate
var Premadeletter23="chce, abyś ukrył wszystko (tablica liderów i minimapa)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Akceptuj";		//Accept
var Premadeletter25="NIE MA MOWY!";		//NO WAY!
var Premadeletter26="chce, żebyś zmienił swoje imię na";		//wants you to change your name to
var Premadeletter27="chce, żebyś ukrył Troll on death";		//wants you to hide Enable Troll on death
var Premadeletter28="chce, abyś otworzył odtwarzacz Youtube";			//wants you to open Youtube Player
var Premadeletter29="Znaleziono tabelę liderów";		//Leaderboard found
var Premadeletter30="Szukaj";		//Search
var Premadeletter31="Tabela wyników nie została znaleziona. Próbuj dalej...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Wyszukiwanie zostało anulowane";		//Search was canceled
var Premadeletter33="Jesteś niewidoczny dla zespołu / klanu";		//You are invisible to Team / Clan
var Premadeletter34="Jesteś widoczny dla zespoły / klanu";		//You are visible to Team / Clan
var Premadeletter35="Ukryj/Pokaż może być używany tylko podczas gry";			//Hide/Show can be used only while playing
var Premadeletter36="To nie jest prawidłowy adres Discord Webhook";		//This is not valid Discord Webhook address
var Premadeletter37="Serwer jest zablokowany";		//Server is locked
var Premadeletter38="Musisz być w trybie oglądania";		//You must be on spectate mode
var Premadeletter39="Ze względu na problemy ze spamem musisz być w grze i używać hasła";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube On";		//Auto Youtube On
var Premadeletter41="Auto Youtube Off";		//Auto Youtube Off
var Premadeletter42="Pokaż skróty";		//Show Shortcuts
var Premadeletter43="Ukryj skróty";		//Hide Shortcuts
var Premadeletter44="Pokaż PASEK XP";		//Show XP BAR
var Premadeletter45="Ukryj PASEK XP";		//Hide XP BAR
var Premadeletter45a = "Zaokrąglony Hud"; //Rounded Hud
var Premadeletter45b = "Kwadratowy Hud"; //Square Hud
var Premadeletter46 = "Pokaż Anim. Skórki"; //Show Anim. Skins
var Premadeletter47 = "Ukryj Anim. Skórki"; //Hide Anim. Skins

var Premadeletter48="Pokaż Wszystko";		//Show Everything
var Premadeletter49="Ukryj Wszystko";		//Hide Everything
var Premadeletter50="Pokaż Timer Calc.";		//Show Timer Calc.
var Premadeletter51="Ukryj Timer Calc."		//Hide Timer Calc.

var Premadeletter53="Automatyczne darmowe monety";		//Auto free coins
var Premadeletter54="Zatrzymaj darmowe monety";		//Stop free coins
var Premadeletter55="Troll on Death";		//Troll on Death
var Premadeletter56="No troll on Death";		//No troll on Death

var Premadeletter57="Komunikacja";		//Communication
var Premadeletter58="Ukryta";		//Hidden
var Premadeletter59="Widzialna";		//Visible
var Premadeletter60="Pauza";		//Pause

var Premadeletter61 = "Włącz YT jako tło";	//Enable YT as background
var Premadeletter62 = "Wyłącz YT jako tło";	//Disable YT as background";
var Premadeletter63 = "chce, abyś otworzył adres URL";	//wants you to open the url
var Premadeletter64 = "chce, abyś umieścił i odtworzył to wideo z YouTube";	//wants you to embed and play this youtube video
var Premadeletter65 = "chce, abyś dołączył do następującego pokoju Skype";	//wants you to join the following Skype room
var Premadeletter66 = "chce, abyś dołączył do następującego pokoju Discord";	//wants you to join the following Discord room
var Premadeletter67 = "chce, abyś opuścił ten serwer i przyłączył się do nowego";	//wants you to leave this server and join this new one

var Premadeletter68 = "Nacisnąłeś"; //You pressed
var Premadeletter69 = "uruchom ponownie, jeśli"; //restart if
var Premadeletter70 = "Spadki"; //drops
var Premadeletter71 = "Animowane skórki"; //Animated skins
var Premadeletter72 = "włączone"; //enabled
var Premadeletter73 = "Spadek"; //drop
var Premadeletter74 = "gdy"; //when
var Premadeletter75 = "Będą animowane skórki"; //Animated skins will be
var Premadeletter76 = "wyłączone"; //disabled
var Premadeletter77 = "po ponownym dołączeniu"; //after rejoin
var Premadeletter78 = "Więcej fps'ów"; //Better FPS
var Premadeletter79 = "wydajność, gdy 16"; //performance when 16
var Premadeletter80 = "Po włączeniu rozszerzenia Dying Light Troll on death nie może wystąpić"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Prywatny Serwer"; //Private Server
var Premadeletter82 = "Połącz się z dowolnym"; //Connect to any
var Premadeletter83 = "serwer lub stwórz własny"; //server, or make your own
var Premadeletter84 = "Graj w gry podobne do agario, jeśli znasz IP serwerów"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Twój obraz został skopiowany do schowka. Wklej to"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "do niestandardowego obszaru adresu URL skórki"; //to custom skin Url area
var Premadeletter87 = "Musisz się zalogować, aby użyć zdjęcia swojego profilu"; //You must Login to use picture of your profile
var Premadeletter88 = "Używasz niewłaściwej wersji"; //You are using a wrong version
var Premadeletter89 = "Gra zakończy się teraz"; //Game will terminate now
var Premadeletter90 = "Specjalne Oferty"; //Special Deals
var Premadeletter91 = "Agario może nie dać Ci skórki, lecz tylko monety"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Używaj na własne ryzyko"; //Use at your own risk
var Premadeletter92 = "Jeśli identyfikator UID Twojego przyjaciela jest zły, zakup nie powiedzie się"; //If friend UID is wrong, purchase will fail
var Premadeletter93 = "Ustawienia fabryczne UID"; //UID Factory Settings
var Premadeletter94 = "Musisz się zalogować, aby załadować Oferty Specjalne"; //You must login to load Special Deals
var Premadeletter95 = "Fałszywy obraz został skopiowany do schowka. Wklej to"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "do niestandardowego obszaru Url skórki, aby aktywować funkcję fałszywej flagi"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Poinformuj mnie, gdy skończysz z Recapatcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "Skończyłem"; //I have finished
var Premadeletter99 = "Nieważne"; //Never Mind
var Premadeletter100 = "Obliczanie Twojego XP, proszę czekać ..."; //Calculating your XP, please wait...
var Premadeletter101 = ""; //Do
var Premadeletter102 = "Nie"; //NOT
var Premadeletter103 = "Naciskać"; //press
var Premadeletter104 = "Wymaż niestandardowy adres URL skórki"; //Erase custom skin URL
var Premadeletter105 = "wybierz skórkę wideo";	//select video skin
var Premadeletter106 = "odznacz skórę wideo”; //unselect video skin";
var Premadeletter107 = "wycisz dźwięk"; //mute audio
var Premadeletter108 = "Projekt LM"; //The LM Project
var Premadeletter109 = "Przekazać plik"; //Upload 
var Premadeletter109a = "Ściągnij"; //Download
var Premadeletter109b = "Ładuję"; //Load

var Premadeletter110 = "nie wpisuj niczego tutaj, chyba że wiesz, co to jest";	//do not enter anything here unless you know what it is
var Premadeletter111 = "kliknij pomarańczową ikonę, aby kupić"; //click on the orange icon to buy
var Premadeletter112 = "Dla niektórych metod płatności"; //For some payment methods
var Premadeletter113 = "Wyjdź";	//Close
var Premadeletter114 = "KOPIUJ"; //COPY
var Premadeletter115 = "służy do kupowania ofert dla znajomych"; //is used to buy offers for your friends
var Premadeletter116 = "Aby dokonywać zakupów, musisz być zalogowany na swoje konto…"; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Biblioteka"; //Library
var Premadeletter118 = "odwiedź"; //visit
var Premadeletter119 = "Zgłoś jako Fałszywy (zmień skórę)"; //Report as Fake (change Skin)
var Premadeletter120 = "Wprowadź swoją DOKŁADNĄ nazwę gracza"; //Enter your EXACT name of the player
var Premadeletter121 = "Nadużywanie graczy i niewłaściwe użycie doprowadzi do UID użytkownika"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "do stałego zakazu używania tego rozszerzenia"; //to permanent ban from usage of this extension
var Premadeletter128 = "Wymagany login użytkownika"; //User login needed
var Premadeletter129 = "Ustawienia zostały pomyślnie przesłane"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERWER"; //SERVER
var Premadeletter124 = "Unikaj używania skórek wideo dłuższych niż 6 minut"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Mapa naprawiona"; //Map fixed
var Premadeletter126 = "Zalogowano do"; //Logged in to
var Premadeletter127 = "Wylogowano"; //Logged out
var Premadeletter130 = "Całkowity"; //Total
var Premadeletter131 = "NOWY"; //NEW
var Premadeletter132 = "Dołącz z powrotem"; //Join Back
var Premadeletter133 = "Połącz z ostatnio odtwarzanym adresem IP"; //Connect to last IP you played
var Premadeletter134 = "Ameryka północna"; //North America
var Premadeletter135 = "Ameryka Południowa"; //South America
var Premadeletter136 = "Europa"; //Europe
var Premadeletter137 = "Rosja"; //Russia
var Premadeletter138 = "Turcja"; //Turkey
var Premadeletter139 = "Wschodnia Azja"; //East Asia
var Premadeletter139a = "Chiny"; //China
var Premadeletter140 = "Oceania"; //Oceania
var Premadeletter140a = " -- Wybierz region -- "; // -- Select a Region -- 
var Premadeletter141 = "Darmowy"; //FFA
var Premadeletter142 = "Bitwa Royale"; //Battle Royale
var Premadeletter143 = "Zespoły"; //Teams
var Premadeletter144 = "Eksperymentalny"; //Experimental
var Premadeletter145 = "Partia"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "JĘZYKI"; //LANGUAGES
var Externalletter0b = "Wybierz język"; //Choose a language
var Externalletter0c = "Zmiany zostaną wprowadzone całkowicie po ponownym uruchomieniu"; //Changes will take place completely after the restart
var Externalletter1 = "INFORMACJA"; //INFORMATION
var Externalletter2 = "SZABLONY"; //TEMPLATES
var Externalletter3 = "RĘCZNE SZABLONY"; //MANUAL TEMPLATES
var Externalletter4 = "Wybierz swój szablon"; //Choose your template
var Externalletter5 = "Lub wybierz rozszerzenie"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "WYŚLIJ KOD DO DEWELOPERÓW"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Wklej swój skrypt w tym polu tekstowym, możesz załadować wiele skryptów"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Załaduj skrypt z Textarea"; //Load Script from Textarea
var Externalletter8 = "Wybierz"; //Choose
var Externalletter9 = "Wymaż skrypt"; //Erase Script
var Externalletter10 = "Nazwa"; //Name
var Externalletter11 = "Url of Raw Github lub inny Raw Script, zaczynając od"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Pozostaw to puste, jeśli skrypt nie został zaimportowany z adresu URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "WAŻNA UWAGA: Nie przechowuj adresów URL, które nie działają, ponieważ są używane jako zdarzenia typu onload. Jeśli scenariusz szkodzi zdarzeniom onload, usuń pliki cookie"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
