var translator="Samantha NL (discord:samanthamelissa)";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Hoofdpagina";		//Home
var Languageletter1="Gebruiker";		//User
var Languageletter2="Instellingen";		//Settings
var Languageletter3="Thema";		//Theme
var Languageletter4="Sneltoetsen";		//Hotkeys
var Languageletter5="Youtube & Geluiden";		//Youtube & Sounds
var Languageletter6="Hulpmiddelen";		//Tools
var Languageletter7="Laat leeg voor Open, of vul een wachtwoord in van uw Clan of gebruik het ls een Tag";		//Password/Tag
var Languageletter7a="Wachtwoord/Tag"	;	//Password/Tag
var Languageletter8="Vul een nicknaam in. 50 characters zijn zichtbaar oor Mod gebruikers, 15 voor standaard gebruikers";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Naam";		//Name
var Languageletter9="Vul uw skin weblink in";		//Insert your manual skin weblink
var Languageletter9a="Vul uw directe skin URL in";		//Manual direct skin URL
var Languageletter10="Spelregio";		//The region to play
var Languageletter11="Spelmodus";		//The mode to play
var Languageletter12="Verbinden met een server, of verbinding opnieuw opbouwen";		//Connect to server, or restablish communication
var Languageletter12a="Verbinden";		//Connect
var Languageletter13="Deelnemen";		//Join
var Languageletter14="Speel als gast";		//Play as guest
var Languageletter15="Inloggen en spelen";		//Login and Play
var Languageletter16="Kijken";		//Spectate
var Languageletter17="Inloggen met Facebook";		//Sign in with Facebook
var Languageletter18="Inloggen met Google";			//Sign in with Google
var Languageletter19="Spelen";		//Play
var Languageletter20="Winkel"	;		//Shop
var Languageletter21="Gratis munten";		//Free Coins
var Languageletter22="Cadeaus";		//Gifts
var Languageletter23="Missies";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Legend Promo Video";		//Legend Promo Video
var Languageletter25a="Nieuwe IdeeÃ«n & Statistieken Formulier";		//New Ideas & Statistics Form
var Languageletter25b="Mod Info & Templates";		//Mod Info & Templates
var Languageletter26="Skins toevoegen";		//Add skins
var Languageletter26a="Kopieer Server, Wachtwoord, Teamlijst & Ranglijst"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Uitloggen";		//Logout
var Languageletter32="Keren gebruikt";		//Times Used
var Languageletter33="Legend Mod door";		//Legend Mod by
var Languageletter34="Vertaling door";		//Translation by
var Languageletter35="Kopieer nicknamen en celnamen van de ranglijst. (druk x om te tonen of verbergen)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animatie";		//Animation
var Languageletter37="Animatievertraging";		//Animation delay
var Languageletter37a="Automatische zoom";		// Auto zoom
var Languageletter37b="Zoomen";		// Zoom
var Languageletter38="Zoom snelheid:";		//Zoom speed:

var Languageletter39="Opnieuw spelen";			//Respawn
var Languageletter40="Automatisch opnieuw spelen";		//Auto respawn
var Languageletter41="Snel opnieuw spelen";			//Quick respawn
var Languageletter41a="Speciale effecten bij opnieuw spelen";			//Spawn special effects
var Languageletter41b="Samenvoeg timer uit";			//Merge timer BETA off
var Languageletter41c="Laat AAN om vertraging tijdens het spelen te verminderen";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Geluid bij op virus schieten";			//Virus shot sound

var Languageletter42="Namen";			//Names
var Languageletter43="Geen namen";		//No names
var Languageletter44="Geoptimaliseerde namen";		//Optimized names
var Languageletter45="Automatisch verbergen van namen";		//Auto hide names
var Languageletter46="Verberg mijn naam";		//Hide my name
var Languageletter47="Verberg namen van teamleden";		//Hide teammates names
var Languageletter48="Naamomlijning";		//Names stroke
var Languageletter49="Massa";		//Mass
var Languageletter50="Toon massa";		//Show mass
var Languageletter51="Geoptimaliseerde massa"	;	//Optimized mass
var Languageletter52="Automatisch verbergen massa";			//Auto hide mass
var Languageletter53="Verberg mijn massa";		//Hide my mass
var Languageletter54="Verberg massa vijanden";		//Hide enemies mass
var Languageletter55="Massa (verkort)";		//Short mass
var Languageletter56="Virus schoten";		//Virus shots
var Languageletter57="Massa omlijning";		//Mass stroke
var Languageletter58="Skins";		//Skins
var Languageletter59="Geen skins ";		//No skins
var Languageletter60="Aangepaste skins";		//Custom skins
var Languageletter61="Vanilla skins";		//Vanilla skins
var Languageletter61a="Jelly fysica";		//Jelly physics
var Languageletter61b="Video skins";		//Video skins
var Languageletter61c="Geluid van andere videoskins wanneer beiden n C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Geoptimaliseerd voedsel";		//Optimized food
var Languageletter6a2="Voedsel";		//Food
var Languageletter63="Automatisch verbergen voedsel (mass)";		//Auto hide food (mass)
var Languageletter64="Automatisch verbergen voedsel (zoom)";		//Auto hide food (zoom)
var Languageletter65="Regenboogvoedsel";		//Rainbow food
var Languageletter66="Transparantie / kleuren";		//Transparency / colors
var Languageletter67="Geen kleuren";		//No colors
var Languageletter68="Mijn aangepaste kleur";		//My custom color
var Languageletter69="Mijn transparante skin";		//My transparent skin
var Languageletter70="Transparante skins";		//Transparent skins
var Languageletter70a="Transparante cellen";		//Transparent cells
var Languageletter71="Transparante virussen";		//Transparent viruses
var Languageletter71a="Virus Gloeien";		//Virus Glow
var Languageletter71b="Geanimeerde regenboogkleuren";		//Animated rainbow colors

var Languageletter72="Raster / sectoren";		//Grid / sectors
var Languageletter73="Toon raster";		//Show grid
var Languageletter74="Toon achtergrondsectoren";		//Show background sectors
var Languageletter75="Toon kaartbegrenzingen";		//Show map borders
var Languageletter75a="Kaartbegrenzing gloeien";		//Border Glow

var Languageletter76="Chat";		//Chat
var Languageletter77="Chat uitschakelen";		//Disable chat
var Languageletter78="Geluidsnotificaties";		//Sound notifications
var Languageletter79="Emoticons";		//Emoticons
var Languageletter80="Toon afbeeldingen in chat";		//Show images on chat
var Languageletter81="Toon videos in chat";		//Show videos on chat
var Languageletter82="Chatbox in plaats van pop-ups";		//Chatbox instead of popups
var Languageletter82a="Minikaart";		//Minimap
var Languageletter82b="Toon minikaart";		//Show minimap
var Languageletter82c="Toon minikaart raster";		//Show minimap grid
var Languageletter82d="Toon minikaart hulpmiddelen";		//Show minimap guides
var Languageletter82e="Teamleden in dezelfde kleur";		//One-colored teammates
var Languageletter82f="Toon extra minikaart hulpmiddelen";		//Show extra minimap guides
var Languageletter82g="Toon dode cellen";		//Show ghost cells

var Languageletter83="Hulpmiddelen";		//Helpers
var Languageletter84="Kleuren tegenstanders";		//Opponents colors
var Languageletter85="Ringen tegenstanders";		//Opponents rings
var Languageletter86="Kleuren virussen";		//Viruses colors
var Languageletter87="Splitbereik";		//Split range
var Languageletter87a="Snelle dubbelsplit bereik";		//Quick double split range
var Languageletter87b="Langzame dubbelsplit bereik";		//Slow double split range

var Languageletter88="Virusbereik";		//Viruses range
var Languageletter89="Cursor volgen";		//Cursor tracking
var Languageletter90="Teamleden indicatoren";		//Teammates indicators
var Languageletter90a="Dode cellen";		//Ghost cells

var Languageletter91="Muisacties";		//Mouse control
var Languageletter92="LMB - Muis split";		//LMB - Mouse split
var Languageletter93="RMB - Muis voeren";		//RMB - Mouse feed
var Languageletter94="Keer muisknoppen om";		//Invert mouse buttons
var Languageletter94a="HUD";		// HUD
var Languageletter95="Team";		//Team
var Languageletter96="Toon doelen";		//Show targeting
var Languageletter96a="Toon massa in ranglijst";		//Show leaderboard mass

var Languageletter97="Gecentreerde ranglijst";		//Centered leaderboard
var Languageletter97a="\"Ranglijst\" koptekst ";		//\"Leaderboard\" header

var Languageletter98="Spelstatistieken bovenaan";		//Game stats at the top
var Languageletter98a="Skins op teamlijst";		//Skins on teamboard

var Languageletter99="Statistieken";		//Stats
var Languageletter100="Toon spelstatistieken";		//Show game stats
var Languageletter101="Spelstatistieken";		//Game stats
//the \' is needed
var Languageletter102="Vijanden";		//Enemy\'s
var Languageletter103="Onze";		//Our
var Languageletter104="Minimale tricksplit massa teamlid";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Maximale massa vijand voor pre-split";		//Maximal enemy\'s mass for presplit
var Languageletter105="Toon huidige tijd";		//Show current time
var Languageletter106="Extras";		//Extras
var Languageletter107="Sla statistieken na dood over";		//Skip stats after death
var Languageletter108="Toon missie";		//Show quest
var Languageletter108a="Spelgeluiden"; //Game Sounds
var Languageletter108b="Menugeluiden"; //Menu Sounds
var Languageletter109="Blokkeer pop-ups (advertenties/winkel/missie)";		//Block popups (ads/shop/quest)
var Languageletter109a="SPRAAK"; //Voice
var Languageletter109b="Spraak Prefix"; //Voice-Prefix
var Languageletter109c="Spraak taal"; //Voice-language
var Languageletter109d="Pauze opheffen"; //UnPause

var Languageletter110="-- Beeldkwaliteit --";		//-- Graphics Quality --
var Languageletter111="Beeld: Retina";		//Graphics: Retina
var Languageletter112="Beeld: Hoog";		//Graphics: High
var Languageletter113="Beeld: Gemiddeld";		//Graphics: Medium"
var Languageletter114="Beeld: Laag";		//Graphics: Low
var Languageletter115="Beeld: Zeer laag";		//Graphics: Very Low
var Languageletter116="Exporteer / Importeer instellingen";		//Export / import settings
var Languageletter117="Herstel standaard instellingen";		//Restore default settings
var Languageletter118="Exporteer instellingen";		//Export settings
var Languageletter119="Importeer instellingen";		//Import settings
var Languageletter120="Om geselecteerde instellingen te EXPORTEREN kopieert u de onderstaande code en slaat u dit op in een tekstbestand in Unicode formaat.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Om geselecteerde instellingen te IMPORTEREN plakt u onderstaand de inhoud van een geexporteerd tekstbestand en drukt u op 'Importeer instellingen'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Commandos";		// Commands
var Languageletter123="Sneltoetsen";		// Hotkeys
var Languageletter124="Profielen";		// Profiles
var Languageletter125="Instellingen";		// Settings
var Languageletter126="Thema";		// Theme
var Languageletter127="Exporteer instellingen";		//Export settings
var Languageletter128="Importeer instellingen";		//Import settings
var Languageletter129="Basis themas";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minikaart";		//Minimap
var Languageletter134="Beeld / cursors";		//Graphics / cursors
var Languageletter135="Voorgeprogrammeerd thema";		//Theme preset
var Languageletter136="Legend Origineel";		//Legend Original
var Languageletter137="Crazy Stijl";		//Crazy Style 1
var Languageletter139="Achtergrond";		//Background
var Languageletter140="Kaartbegrenzingen";		//Map borders
var Languageletter141="Raster";		//Grid
var Languageletter142="Lettertype Sectoren";		//Sectors font
var Languageletter143="Namen";		//Names
var Languageletter144="Omlijning Naam";		//Names stroke
var Languageletter145="Massa";		//Mass
var Languageletter146="Omlijning Massa";		//Mass stroke
var Languageletter147="Omlijning Virus";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter148a="Moedercel";		//Mothercell
var Languageletter148b="Omlijning Moedercel";		//Mothercell stroke
var Languageletter149="Voedsel";		//Food
var Languageletter150="Teamlid indicator";		//Teammate indicator
var Languageletter151="Cursor volgen";		//Cursor tracking
var Languageletter152="Splitbereik";		//Split range
var Languageletter153="Lettertype Namen";		//Names font
var Languageletter154="Lettertype Massa";		//Mass font
var Languageletter154a="Groter";		//Bigger
var Languageletter154b="Kleiner";		//Smaller
var Languageletter155="Lettertype Sectoren";		//Sectors font
var Languageletter157="Grootte letters Sectoren";		//Sectors font size
var Languageletter158="Schaal Namen";		//Names scale
var Languageletter159="Schaal Massa";		//Mass scale
var Languageletter160="Schaal Virus Massa";		//Virus mass scale
var Languageletter161="Schaal Omlijning Tekst";		//Text stroke scale
var Languageletter162="Grootte Voedsel";		//Food size:
var Languageletter163="Breedte Omlijning Virus";		//Virus stroke size
var Languageletter164="Breedte Kaartbegrenzingen";		//Map borders width
var Languageletter165="Breedte Sectorraster";		//Sectors grid width
var Languageletter166="Transparantie Cellen";		//Cells transparency
var Languageletter167="Transparantie Skins";		//Skins transparency
var Languageletter168="Transparantie Virussen";		//Virus transparency
var Languageletter169="Transparantie Namen & Massa";		//Names & mass transparency
var Languageletter170="Herstel standaard thema instellingen";		//Restore theme default settings
var Languageletter171="Instellingen opslaan";		//Save settings
var Languageletter172="Menu thema";		//Menu theme
var Languageletter173="Achtergrond";		//Background
var Languageletter174="Transparantie";		//Transparency
var Languageletter175="Hoofdkleur";		//Main color
var Languageletter176="Knoptekst";		//Button text
var Languageletter177="Paneel";		//Panel
var Languageletter179="Paneel tekst";		//Panel text
var Languageletter181="Knop";		//Button
var Languageletter189="Paneel achtergrondafbeelding";		//Panel background image
var Languageletter190="Afbeelding URL";		//Image URL
//var Languageletter191="Hoofdkleur";		//Main color
var Languageletter192="Achtergrond";		//Background
var Languageletter193="Tekst";		//Text
var Languageletter194="Statistieken";		//Stats
var Languageletter195="Tijd";		//Time
var Languageletter196="Top 5 massa";		//Top 5 mass
var Languageletter197="Ranglijst - ik";		//Leaderboard - me
var Languageletter198="Ranglijst - teamlid";		//Leaderboard - teammate
var Languageletter199="Lettertype HUD";		//HUD font
var Languageletter200="Schaal HUD";		//HUD scale:
var Languageletter201="Bericht achtergrond";		//Message background
var Languageletter202="Bericht tekst";		//Message text
var Languageletter203="Bericht tijd";		//Message time
var Languageletter204="Bericht nick";		//Message nick
var Languageletter205="Commando achtergrond";		//Command background
var Languageletter206="Commando tekst";		//Command text
var Languageletter207="Commando tijd";		//Command time
var Languageletter208="Commando nick";		//Command nick
var Languageletter209="Chatbox kleur";		//Chatbox color
var Languageletter210="Schaal Chat";		//Chat scale
var Languageletter211="Sectoren";		//Sectors
var Languageletter212="Huidige sector";		//Current sector
var Languageletter213="Nick";		//Nick
var Languageletter214="Omlijning Nick";		//Nick stroke
var Languageletter215="Mijn cell";		//My cell
var Languageletter216="Omlijning van mijn cel";		//My cell stroke
var Languageletter217="Teamleden";		//Teammates
var Languageletter218="Sterflocatie";		//Death location
var Languageletter219="Hulpmiddelen";		//Guides
var Languageletter220="Lettertype Minikaart";		//Minimap font
var Languageletter221="Lettertype Nick";		//Nick font
var Languageletter222="Breedte Minimap";		//Minimap width
var Languageletter223="Transparantie Sectoren";		//Sectors transparency
var Languageletter224="Grootte Nick";		//Nick size
var Languageletter225="Breedte Nick omlijning";		//Nick stroke size
var Languageletter226="Grootte eigen cel";		//My cell size
var Languageletter227="Breedte eigen cel omlijning";		//My cell stroke size
var Languageletter228="Grootte Teamleden";		//Teammates size
var Languageletter229="Aangepaste achtergrondafbeelding";		//Custom background image
var Languageletter230="Aangepaste cursorafbeelding";		//Custom cursor image
var Languageletter231="Achtergrondafbeelding URL";		//Image URL
var Languageletter232="Cursorafbeelding URL";		//Cursor image URL
var Languageletter233="Voeren";		//Feed
var Languageletter234="Macro voeren";		//Macro feed
var Languageletter235="Split";		//Split
var Languageletter236="Dubbele split";		//Double split
var Languageletter237="Pop-split";		//Popsplit
var Languageletter238="Split 16";		//Split 16
var Languageletter239="Cell pauze";		//Cell pause
var Languageletter240="Toon/Verberg team top 5";		//Show/hide team top 5
var Languageletter241="Toon/Verberg huidige tijd";		//Show/hide current time
var Languageletter242="Toon/Verberg split bereik";		//Show/hide split range"
var Languageletter243="Toon/Verberg indicatoren teamleden";		//Show/hide teammates indicators
var Languageletter244="Toon/Verberg split indicatoren";		//Show/hide split indicators
var Languageletter245="Toon/Verberg kleuren vijanden";		//Show/hide opponents colors
var Languageletter246="Activeer skins (aangepast/standaard)";		//Toggle skins (custom/default)
var Languageletter247="Activeer transparante skins";		//Toggle transparent skins
var Languageletter248="Toon/Verberg skins";		//Show/hide skins
var Languageletter249="Toon/Verberg spelstatistieken";		//Show/hide game stats
var Languageletter250="Activeer eigen cellen (kleinste/grootste)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Toon/Verberg voedsel";		//Show/hide food
var Languageletter252="Toon/Verberg raster";		//Show/hide grid
var Languageletter253="Toon/Verberg minikaart hulpmiddelen";		//Show/hide minimap guides
var Languageletter254="Toon/Verberg chat";		//Show/hide chat
var Languageletter255="Toon/Verberg HUD";		//Show/hide HUD
var Languageletter256="Kopieer ranglijst";		//Copy leaderboard
var Languageletter257="Toon/Verberg ranglijst";		//Show/hide leaderboard
var Languageletter258="Activeer auto zoom";		//Toggle auto zoom
var Languageletter259="Herstel zoom";		//Reset zoom
var Languageletter260="Activeer sterflocatie";		//Toggle death location
var Languageletter261="Toon chat historie / Wis chat";		//Show chat history / Clear chat
var Languageletter262="Toon/Verberg achtergrondsectoren";		//Show/hide background sectors
var Languageletter263="Toon/Verberg kleine bots";		//Show/hide small bots
var Languageletter264="Toon/Verberg namen";		//Show/hide names
var Languageletter265="Toon/Verberg namen teamleden";		//Show/hide teammates names
var Languageletter266="Toon/Verberg massa";		//Show/hide mass
var Languageletter267="Toon/Verberg minikaart";		//Show/hide minimap
var Languageletter268="Chatbericht";		//Enter chat message
var Languageletter269="Snel opnieuw spelen";		//Quick respawn
var Languageletter270="Activeer automatisch opnieuw spelen";		//Toggle auto respawn
var Languageletter271="Zoom niveau";		//Zoom level
var Languageletter271a="Spraak naar tekst";		//Voice to text
var Languageletter271b="Laat informatie over dode cellen zien";		//Show ghost cells information
var Languageletter271c="Automatisch spelen";		//Auto Play
var Languageletter272="Toon/Verberg doelen paneel";		//Show/hide targeting panel
var Languageletter273="Start/stop doelen volgen";		//Start/stop targeting (following)
var Languageletter274="Onderbreek doelen volgen";		//Cancel targeting
var Languageletter275="Wijzig doel";		//Change target
var Languageletter276="Toon doel op de minikaart";		//Show target on the minimap
var Languageletter277="Toon/Verberg missie";		//Show/hide quest
var Languageletter278="Om een sneltoets toe te wijzen, klik op het inputveld en voer de toets van uw keuze in.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Om een sneltoets te verwijderen, klik op het inputveld en druk op DELETE.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Toetscombinaties met CTRL en ALT zijn mogelijk.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Herstel standaard instellingen";		//Restore default settings
var Languageletter282="Instellingen opslaan";		//Save settings
var Languageletter283="Sluiten";		//Close
var Languageletter284="Youtube speler";		//Youtube player
var Languageletter284a="Youtube URL";		// Youtube Url
var Languageletter285="Plak uw video/afspeellijst hier";		//Paste your video/playlist here
var Languageletter286="Geluiden";		//Sounds
var Languageletter287="Bericht notificatie geluid";		//Message notification sound
var Languageletter288="Commando notificatie geluid";		//Command notification sound
var Languageletter289="Kopieer Token/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Token";		//Token
var Languageletter290a="Board"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Kopieer";		//Copy

var Languageletter291a="Kopieer Ranglijst (L)";		//Copy Leaderboard (L)
var Languageletter291b="Kopieer Token/SIP&Password"; 	//Copy Token/SIP&Password
var Languageletter291c="Kopieer Token/SIP, Password, Leaderboard..."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="Serverdeelname (Backspace)";		//Join server (Backspace)
var Languageletter293="Wijzig server (+)";		//Change server (+)
var Languageletter294="Ranglijst historie";		//Leaderboard history
var Languageletter295="Voer een gemeenschappelijk (discord)token in, IP, ranglijst, naam of clan tag...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Wis lijst"; //Clear list
var Languageletter295b="Chatbericht..."; //Enter chat message...
var Languageletter298="Team top ";		//Team top
var Languageletter299="Ranglijst";		//Leaderbodard
var Languageletter300="Communicatie";		//Communication
var Languageletter301="Bericht Script Commandos";		//Message Script Commands
var Languageletter302="Bericht Imgur Iconen";		//Message Imgur Icons
var Languageletter303="Bericht Youtube Videos";		//Message Youtube Videos
var Languageletter304="Wijzig namen";		//Edit names
var Languageletter305="[Alleen in toeschouwermodus] Verrekijker";		//[Spectate Mode Only] Binoculars
var Languageletter306="Speel / Pauze";		//Play / Pause
var Languageletter307="Volledig scherm";		//Fullscreen
var Languageletter308="Roteren";		//Rotate
var Languageletter309="Standaard";		//Default
var Languageletter310="Terug";		//Back
var Languageletter311="Bewaar voor later";		//Save for later
var Languageletter312="Regio";		//Region
var Languageletter313="Spelers";		//Players
var Languageletter314="Servers";		//Servers
var Languageletter315="[Doel niet ingesteld]";		//[Target not set]
var Languageletter316="Handmatige achtergrond";		//Manual background
var Languageletter317="Handmatig bericht Iconen & Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Chat Positie";		//Chat Position
var Languageletter319="Discord Webhook URL (for sending TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Ranglijst";		//Leaderboard
var Languageletter321="Teamlijst";		//Teamboard
var Languageletter322="Hoofdscherm";		//Main Canvas
var Languageletter323="Hoofdbanner";		//Main Banner
var Languageletter324="Hella Team!";		//Hello Team!
var Languageletter325="Lach naar Team";		//Laugh to Team
var Languageletter326="Wijzig Team Naam naar die van u";		//Team Change Name to yours
var Languageletter327="Troll on Death";		//Troll on Death
var Languageletter328="Open Youtube Music";		//Open Youtube Music
var Languageletter329="Gestoorde modus (Verberg alles)";		//Insane mode (Hide Everything)
var Languageletter330="URL van afbeelding beginnend met http://... of https://...";		//Url of image starting with http://... or https://...
var Languageletter331="URL Minikaart afbeelding";		//Minimap Image URL
var Languageletter332="Minikaart Tekst";		//Minimap Text
var Languageletter333="Ranglijst Logo Tekst";		//Leaderboard Logo Text
var Languageletter333a="URL van afbeelding ranglijst";		// Leaderboard Image URL
var Languageletter334="Teamlijst Logo Tekst";		//Teamboard Logo Text
var Languageletter334a="URL van afbeelding Teamlijst";		// Teamboard Image URL
var Languageletter335="URL van afbeelding hoofdscherm";		//Main Canvas Image URL
var Languageletter336="URL van hoofdbanner icoon";		//Main Banner Icon URL
var Languageletter337="URL van afbeelding hoofdbanner";		//Main Banner Link URL
var Languageletter338="Icoon";		//Icon
var Languageletter339="d.w.z.";		//e.g
var Languageletter340="URL van YT video";		//Url of youtube to be shown
var Languageletter341="URL van redirectlink";		//Url of link to redirect
var Languageletter342="URL Primaire Discord Webhook";		//Discord Webhook Url
var Languageletter342a="Bericht icoon tekst";		//Message Icon Text
var Languageletter342b="YT berichttekst";		//Youtube Message Text
var Languageletter342c="URL van bericht icoon Imgur";		//Message Icon Imgur Url
var Languageletter342d="URL van Youtube bericht";		//Youtube Message Url
var Languageletter343="Moet worden gevuld om de functie te laten werken";		//Must be filled for function to work.
var Languageletter344="URL Secundaire Discord Webhook (optioneel)";		//Secondary Webhook(optional)
var Languageletter345="WAARSCHUWING! Pop-ups worden geblokkeerd in de instellingen.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Tijdelijk deblokkeren";		//Temporary unblock
var Languageletter347="WAARSCHUWING! Pop-ups worden geblokkeerd in de instellingen.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Tijdelijk deblokkeren";		//Temporary unblock

var Languageletter349="Drankjes";	//Potions
var Languageletter350="Oude Skins";	//Old Skins
var Languageletter351="Speciale Aanbiedingen"; //Special Deals
var Languageletter352="Ranglijsten"; //Leaderboards
var Languageletter353="Nieuwe ideeÃ«n & Statistieken Formulier"; //New Ideas & Statistics Form
var Languageletter354="Video Skins"; //Video Skins
var Languageletter355="Mini Scripts"; //Mini Scripts
var Languageletter356="Gebruiker Scripts"; //User Scripts
var Languageletter357="Spraak & Video Chat";	//Voice & Camera Chat
var Languageletter358="Steun de ontwikkeling van de Legend Mod";	//Please support the development of Legend mod
var Languageletter359="Lettertype ontwerp nicknaam";	//Design Nickname Font
var Languageletter360="Wijs de Fake Skin aan";	//Flag the Fake Skin
var Languageletter361="Meer FPS";	//More FPS
var Languageletter362="Naam";	//Name
var Languageletter363="Social ID";	//Social ID
var Languageletter364="Expansies";	//Expansions
var Languageletter365="Universeel";	//Universal
var Languageletter366="Score";	//Score
var Languageletter367="Afstand";	//Distance
var Languageletter368="Totale Massa";	//Total Mass
var Languageletter369="Dood";	//Dead

var Premadeletter0="Communicatie geactiveerd"; 		//Communication Activated
var Premadeletter1="Kan deze Youtube URL niet openen";		 //Cannot open this youtube URL
var Premadeletter2="U kunt niet chatten met een speler met > 15 characters in de nick"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 geactiveerd"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 geactiveerd";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 geactiveerd";		//Easter Egg 3 Activated
var Premadeletter6="Video werkt beter met Vanilla. Ga naar:";		//Video works better on vanilla, visit:
var Premadeletter7="Noot:<b>Facebook</b> compatibileit is beter dan met <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Noot:Agar.io kan alleen verbinden met <b>Google Plus</b> gedurende onload events. Indien u uitlogt, logt u weer in op Agar.io of gebruikt u <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Indien u verbinding verliest en uitlogt gedurende onload events, verwijder dan Chrome cookies van";		//If logout occurs on onload events, delete Chrome cookies from
var Premadeletter10="Verbinding verloren met server :(";		//Disconnected from server :(
var Premadeletter11="U bent verbannen. Herstart uw router!";		//You were banned, restart your rooter!
var Premadeletter12="Verbonden!";		//Connected!
var Premadeletter13="SPELEN";		//PLAY
var Premadeletter14="KIJKEN";		//SPECTATE
var Premadeletter15="Ongeldig token of de server is gesloten :(";		//Invalid token or server has closed :(
var Premadeletter16="kan worden geupdate naar";		//can be Updated to
var Premadeletter17="Welkom terug";			//Welcome back
var Premadeletter18="Uw shortcut veld en andere velden (van het laatste tabblad) staan nog uit! We bevelen aan dat u ze aan zet.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Zet ze aan";		//Enable Them
var Premadeletter20="Laat ze uit staan";		//Keep Them Disabled
var Premadeletter21="Zoekt IP";		//Searching IP
var Premadeletter22="Uw teamlid";		//Your teammate
var Premadeletter23="wil dat u alles verbergt (ranglijst en minikaart)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Accepteer";		//Accept
var Premadeletter25="Nee, ECHT?!";		//NO WAY!
var Premadeletter26="wil dat u uw nicknaam wijzigt naar";		//wants you to change your name to
var Premadeletter27="wil dat u Troll on death activeert";		//wants you to hide Enable Troll on death
var Premadeletter28="wil dat u de Youtube Player opent";			//wants you to open Youtube Player
var Premadeletter29="Ranglijst gevonden";		//Leaderboard found
var Premadeletter30="Zoeken";		//Search
var Premadeletter31="De ranglijst werd niet gevonden. Probeer het opnieuw...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="De zoekactie was stopgezet";		//Search was canceled
var Premadeletter33="U bent onzichtbaar voor Team / Clan";		//You are invisible to Team / Clan
var Premadeletter34="U bent zichtbaar voor Team / Clan";		//You are visible to Team / Clan
var Premadeletter35="Toon/Verberg kan alleen tijdens het spelen worden gebruikt";			//Hide/Show can be used only while playing
var Premadeletter36="Dit is geen geldige Discord Webhook URL";		//This is not valid Discord Webhook address
var Premadeletter37="Server is gesloten";		//Server is locked
var Premadeletter38="U bent vast aan het kijken";		//You must be on spectate mode
var Premadeletter39="Vanwege spamgedrag dient u gedurende het spel uw password opnieuw in te voeren";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube Aan";		//Auto Youtube On
var Premadeletter41="Auto Youtube Uit";		//Auto Youtube Off
var Premadeletter42="Toon Shortcuts";		//Show Shortcuts
var Premadeletter43="Verberg Shortcuts";		//Hide Shortcuts
var Premadeletter44="Toon XP BALK";		//Show XP BAR
var Premadeletter45="Verberg XP BALK";		//Hide XP BAR
var Premadeletter45a = "Ronde HUD"; //Rounded Hud
var Premadeletter45b = "Vierkante HUD"; //Square Hud
var Premadeletter46 = "Lin. kleuren HUD"; //Linear color Hud
var Premadeletter47 = "Verberg Geanim. Skins"; //Bold color Hud

var Premadeletter48="Toon Alles";		//Show Everything
var Premadeletter49="Verberg Alles";		//Hide Everything
var Premadeletter50="Toon Timer Calc.";		//Show Timer Calc.
var Premadeletter51="Verberg Timer Calc."		//Hide Timer Calc.

var Premadeletter53="Automatisch gratis munten";		//Auto free coins
var Premadeletter54="Stop gratis munten";		//Stop free coins
var Premadeletter55="Troll on Death";		//Troll on Death
var Premadeletter56="Geen Troll on Death";		//No troll on Death

var Premadeletter57="Communicatie";		//Communication
var Premadeletter58="Verborgen";		//Hidden
var Premadeletter59="Zichtbaar";		//Visible
var Premadeletter60="Pauze";		//Pause

var Premadeletter61 = "Schakel YT als achtergrond in";	//Enable YT as background
var Premadeletter62 = "Schakel YT als achtergrond uit";	//Disable YT as background";
var Premadeletter63 = "wil dat u deze URL opent";	//wants you to open the url
var Premadeletter64 = "wil dat u deze youtube video embed en afspreelt";	//wants you to embed and play this youtube video
var Premadeletter65 = "wil dat u naar deze Skype server komt";	//wants you to join the following Skype room
var Premadeletter66 = "wil dat u naar deze Discord server komt";	//wants you to join the following Discord room
var Premadeletter67 = "wil dat u de server verlaat en naar deze nieuwe komt";	//wants you to leave this server and join this new one

var Premadeletter68 = "U heeft gedrukt"; //You pressed
var Premadeletter69 = "Herstart indien"; //restart if
var Premadeletter70 = "druppels"; //drops
var Premadeletter71 = "Geanimeerde skins"; //Animated skins
var Premadeletter72 = "Ingeschakeld"; //enabled
var Premadeletter73 = "druppel"; //drop
var Premadeletter74 = "indien"; //when
var Premadeletter75 = "Geanimeerde skins zullen"; //Animated skins will be
var Premadeletter76 = "Uitgeschakeld"; //disabled
var Premadeletter77 = "na opnieuw meedoen"; //after rejoin
var Premadeletter78 = "Betere FPS"; //Better FPS
var Premadeletter79 = "prestaties wanneer 16"; //performance when 16
var Premadeletter80 = "Wanneer Dying Light Expansie is ingeschakeld zal Troll on Death niet plaastvinden"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "PrivÃ© Server"; //Private Server
var Premadeletter82 = "Verbind met willekeurige"; //Connect to any
var Premadeletter83 = "server, of maak er zelf Ã©Ã©n aan."; //server, or make your own
var Premadeletter84 = "Speel agario-achtige spellen als u het IP of de servernaam kent"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Uw afbeelding is gekopieerd naar het klembord. Plak het nu."; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "naar aangepaste skin URL veld"; //to custom skin Url area
var Premadeletter87 = "U moet ingelogd zijn om de profielafbeelding te gebruiken"; //You must Login to use picture of your profile
var Premadeletter88 = "U heeft een verkeerde versie"; //You are using a wrong version
var Premadeletter89 = "Het spel wordt nu beÃ«indigd"; //Game will terminate now
var Premadeletter90 = "Speciale Aanbiedingen"; //Special Deals
var Premadeletter91 = "Agario kan u de skin niet geven, maar wel de munten"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Gebruik voor eigen risico"; //Use at your own risk
var Premadeletter92 = "Indien het gebruikers-ID van uw vriend onjuist is zal de aanschaf mislukken"; //If friend UID is wrong, purchase will fail
var Premadeletter93 = "Gebruikers-ID Fabrieksinstellingen"; //UID Factory Settings
var Premadeletter94 = "U dient ingelogd te zijn om van de Speciale Aanbiedingen gebruik te kunnen maken"; //You must login to load Special Deals
var Premadeletter95 = "Fake afbeelding is gekopieerd naar het klembord. Plak het nu."; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "naar aangepast skin URL veld om de Fake Flag functie te activeren"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Geef me een seintje wanneer Recapatcha klaar is"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "Ik ben klaar"; //I have finished
var Premadeletter99 = "Laat Maar!"; //Never Mind
var Premadeletter100 = "Bezig uw XP te berekenen, even wachten..."; //Calculating your XP, please wait...
var Premadeletter101 = "NIET"; //Do
var Premadeletter102 = "op"; //NOT
var Premadeletter103 = "drukken"; //press
var Premadeletter104 = "Wis aangepaste skin URL"; //Erase custom skin URL
var Premadeletter105 = "Selecteer videoskin";	//select video skin
var Premadeletter106 = "De-selecteer videoskin"; //unselect video skin
var Premadeletter107 = "Onderdruk audio"; //mute audio
var Premadeletter108 = "Het LM Project"; //The LM Project
var Premadeletter109 = "Uploaden"; //Upload
var Premadeletter109a = "Downloaden"; //Download
var Premadeletter109b = "Laden"; //Load
var Premadeletter110 = "schrijf hier niets tenzij je weet wat dit inhoudt";	//do not enter anything here unless you know what it is
var Premadeletter111 = "klik op het oranje icoon om te kopen"; //click on the orange icon to buy
var Premadeletter112 = "Voor bepaalde betalingsmogelijkheden"; //For some payment methods
var Premadeletter113 = "Sluiten";	//Close
var Premadeletter114 = "KOPIEER"; //COPY
var Premadeletter115 = "wordt gebruikt om cadeaus voor uw vrienden te kopen"; //is used to buy offers for your friends
var Premadeletter116 = "Om iets af te rekenen moet u zijn ingelogdâ€¦"; //To make purchases, you must be logged in to your accountâ€¦
var Premadeletter117 = "Bibliotheek"; //Library
var Premadeletter118 = "Bezoek"; //visit
var Premadeletter119 = "Rapporteer als Fake (wijzig Skin)"; //Report as Fake (change Skin)
var Premadeletter120 = "Voer de EXACTE spelernaam in"; //Enter your EXACT name of the player
var Premadeletter121 = "Spelers die misbruik maken en ongepast gedrag vertonen zullen worden"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "verbannen om nog verder gebruik te kunnen maken van deze extensie"; //to permanent ban from usage of this extension
var Premadeletter128 = "Gebruiker login vereist"; //User login needed
var Premadeletter129 = "Instellingen succesvol geupload"; //Settings successfully uploaded

//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERVER"; //SERVER
var Premadeletter124 = "Vermijd het gebruik van videoskins die langer duren dan 6 minuten"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Kaart hersteld"; //Map fixed
var Premadeletter126 = "Ingelogd bij"; //Logged in to
var Premadeletter127 = "Uitgelogd"; //Logged out
var Premadeletter130 = "Totaal"; //Total
var Premadeletter131 = "NIEUW"; //NEW
var Premadeletter132 = "Opnieuw verbinden"; //Join Back
var Premadeletter133 = "Verbind met laatste server IP waar u heeft gespeeld"; //Connect to last IP you played
var Premadeletter134 = "Noord-Amerika"; //North America
var Premadeletter135 = "Zuid-Amerika"; //South America
var Premadeletter136 = "Europa"; //Europe
var Premadeletter137 = "Oekraine"; //Russia
var Premadeletter138 = "Turkije"; //Turkey
var Premadeletter139 = "Oost AziÃ«"; //East Asia
var Premadeletter139a = "China"; //China
var Premadeletter140 = "OceaniÃ«"; //Oceania
var Premadeletter140a = " -- Select a Region -- "; // -- Select a Region --
var Premadeletter141 = "FFA"; //FFA
var Premadeletter142 = "Battle Royale"; //Battle Royale
var Premadeletter143 = "Teams"; //Teams
var Premadeletter144 = "Experimenteel"; //Experimental
var Premadeletter145 = "Party Modus"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "TALEN"; //LANGUAGES
var Externalletter0b = "Kies een taal"; //Choose a language
var Externalletter0c = "Wijzigingen worden doorgevoerd na een herstart"; //Changes will take place completely after the restart
var Externalletter1 = "INFORMATIE"; //INFORMATION
var Externalletter2 = "TEMPLATES"; //TEMPLATES
var Externalletter3 = "HANDMATIGE TEMPLATES"; //MANUAL TEMPLATES
var Externalletter4 = "Kies uw template"; //Choose your template
var Externalletter5 = "Of kies een expansie"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "VERSTUUR CODE NAAR ONTWIKKELAARS"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Plak uw Script in dit tekstgebied. U kunt meerdere Scripts laden"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Laad Script vanuit het tekstgebied"; //Load Script from Textarea
var Externalletter8 = "Kiezen"; //Choose
var Externalletter9 = "Script wissen"; //Erase Script
var Externalletter10 = "Naam"; //Name
var Externalletter11 = "URL van Raw Github, of ander Raw Script, beginnend met"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Laat dit leeg als het script niet is geimporteerd vanuit een URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "BELANGRIJKE MEDEDELING: Bewaar geen URL's die niet werken, omdat deze worden gebruikt als onload-events. Als Scenario de onload-events beschadigt, VERWIJDER DAN DE COOKIES."; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
