/*         var Languageletter =         "مرحبا بك" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="صفحة البداية";  //Home      ->    var Languageletter0="المُهِمة";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                             شُكراَ لِدعَمَك لِمُوُد ليجاند للَعِبة أجَاريُو
Thank you for supporting Legend Agar.io mod                                                             */



var translator="غير محُدَد";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="صفحة البداية";		//Home
var Languageletter1="المُستَخِدم";		//User
var Languageletter2="الاعِدَادَات";		//Settings
var Languageletter3="الثيم";		//Theme
var Languageletter4="أزرار الاِختصَارَات";		//Hotkeys
var Languageletter5="اليُوتُيوب & الصُوت";		//Youtube & Sounds
var Languageletter6="الادوَات";		//Tools
var Languageletter7="اتركها فارغه لتري العامه, او ضع الباسوورد الخاصة بالكلان, او استخدمها كتاج";		//Password/Tag
var Languageletter7a="الباسُوورد/التَاج"	;	//Password/Tag
var Languageletter8="ادخل اسمك باللعبة, يُمكنك استخدام 50 رمز سيراها فقط مستخدمي المود, باستخدامك 15 حرف باسمك يري اسمك الجميع"		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="الاسم";		//Name
var Languageletter9="أدخل عنوان الاسِكن الذي ترغب باستخدامه";		//Insert your manual skin weblink
var Languageletter9a="عنوان مُباشر للاسِكن";		//Manual direct skin URL
var Languageletter10="مَنطقة اللعِب ";		//The region to play
var Languageletter11="وَضع اللعب";		//The mode to play
var Languageletter12="اتصِل بالسِيرفَر, أو قُم بإعادة الإتصال";		//Connect to server, or restablish communication
var Languageletter12a="إتصل";		//Connect
var Languageletter13="شارك";		//Join
var Languageletter14="الِعَب كَضَيف";		//Play as guest
var Languageletter15="سجل الدخول وألعَب";		//Login and Play
var Languageletter16="مُشَاهَدة بَث حَي للسِيرفَر";		//Spectate
var Languageletter17="سجل دخولك باسِتخَدام الفيِسبُوك";		//Sign in with Facebook
var Languageletter18="سَجل دخُول باسِتخَدام جَوجَل";			//Sign in with Google
var Languageletter19="إِلعَب";		//Play
var Languageletter20="التسوق"	;		//Shop
var Languageletter21="كوين مجانية";		//Free Coins
var Languageletter22="هَدايَا";		//Gifts
var Languageletter23=" المهَام اليَومِيَة ";			//Daily Quests
var Languageletter24="سكينَاَت";		//Skins
var Languageletter25="الفيِديُو التَرويِجِي لليجَاند";		//Legend Promo Video
var Languageletter25a="نموذج الأفكار والإحصاءات الجديدة";		//Legend Promo Video
var Languageletter25b=" معلومات المود والقوالب الجاهزة";		//Mod Info & Templates
var Languageletter26="اضَافِة سكينَات";		//Add skins
var Languageletter26a="نسخ الخادم ، كلمة المرور ، لوحة الفريق و لوح المتصدرين"; //Copy Server, Password, Teamboard & Leaderboard

var Premadeletter27="يريد منك تمكين ترول عند الموت";		//wants you to hide Enable Troll on death
var Premadeletter28="يريد منك فتح مشغل Youtube";			//wants you to open Youtube Player
var Premadeletter29="وجدت قائمة الأوائل";		//Leaderboard found
var Premadeletter30="بحث";		//Search
var Languageletter31="تَسجِيِل الخُرُوُج";		//Logout
var Languageletter32="الوقت المُستَخدم";		//Times Used
var Languageletter33="ليِجَانَد مُوُد بِوَاسِطَة";		//Legend Mod by
var Languageletter34="تَرجَمِه";		//Translation by
var Languageletter35=" نَسَخ أَسمَاء المُتصَدِرِيِن وأَسمَاء الخَلايَا. (اضغَط xللإلغاء أو الظهور)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="الأنيِميِشَن";		//Animation
var Languageletter37="تأخير الرسوم المتحركة";		//Animation delay
var Languageletter37a="زُوُوُم تِلقَائِي";		// Auto zoom
var Languageletter37b="الزُوُوُم";		// Zoom
var Languageletter38="سُرعِة الزُوُوُم:";		//Zoom speed: 
var Languageletter39="إعَادة البَدء";			//Respawn
var Languageletter40="بَدء تِلقَائِي";		//Auto respawn 
var Languageletter41="زِر البَدء التِلقَائِي";			//Quick respawn (hotkey) 
var Languageletter42="الأسَمَاء";			//Names
var Languageletter43="بِدُوُن أَسمَاء";		//No names 
var Languageletter44="تَحسِيِن الأسمَاء";		//Optimized names 
var Languageletter45="الإخفَاء التِلقَائِي لِلَأسمَاء";		//Auto hide names 
var Languageletter46="إِخفَاء إِسمِي";		//Hide my name 
var Languageletter47="إِخفَاء أسمَاء  الفَريِق";		//Hide teammates names 
var Languageletter48="تَغلِيِظ الأسمَاء";		//Names stroke 
var Languageletter49="المَاس";		//Mass
var Languageletter50="أَظهِر المَاس";		//Show mass 
var Languageletter51="تَحسِيِن المَاس (+/-2%)"	;	//Optimized mass (+/-2%) 
var Languageletter52="إِخفَاء تِلقَائي للِمَاس";			//Auto hide mass 
var Languageletter53="إخفَاء المَاس الخَاص بِي";		//Hide my mass 
var Languageletter54="إخفاء المَاس الخَاص بالأعداء";		//Hide enemies mass 
var Languageletter55="اختصَار الماس";		//Short mass
var Languageletter56="تَسدِيدات الفيرس";		//Virus shots 
var Languageletter57="تغليظ الماس";		//Mass stroke 
var Languageletter58="الاسكِنَات";		//Skins
var Languageletter59="إخفاء الإسكِنات ";		//No skins 
var Languageletter60="سكينات مُخصَصَة";		//Custom skins 
var Languageletter61="سِكنِات الفانيليا ";		//Vanilla skins 
var Languageletter62="تَحسِين نِقاط المَاس";		//Optimized food 
var Languageletter6a2="نِقَاط المَاس ";		//Food 
var Languageletter63="إخفَاء تِلقَائي لنِقَاط المَاس";		//Auto hide food (mass) 
var Languageletter64="إخفاء تلقائي لِنقَاط المَاس (الزوم)";		//Auto hide food (zoom) 
var Languageletter65="نِقَاط المَاس بألوَان قُوس قَزح";		//Rainbow food 
var Languageletter66="الشَفَافيَه / الألوان";		//Transparency / colors
var Languageletter67="بِدوُن ألوَان";		//No colors 
var Languageletter68="الألوَان المُحَدَدة الخَاصة بِي";		//My custom color 
var Languageletter69="الإسكنات الشَفَافَه الخَاصة بِي";		//My transparent skin 
var Languageletter70="شَفافِية الإسكنَات";		//Transparent skins 
var Languageletter70a="خلايا شفافة"; //Transparent cells 
var Languageletter71="شَفَافية الفَيرُسَات";		//Transparent viruses 
var Languageletter72="الشَبَكة / القِطَاعَات";		//Grid / sectors
var Languageletter73="أظهِر الخُطُوط الشَبَكيِة";		//Show grid 
var Languageletter74="أظهِر ";		//Show background sectors 
var Languageletter75="أظهِر حُدوُد الخَريطة";		//Show map borders 
var Languageletter76="المُحَادثة";		//Chat
var Languageletter77="عَدم تَفعِيل المُحَادثة";		//Disable chat 
var Languageletter78="أصَواَت الِإخطَارات";		//Sound notifications 
var Languageletter79=" الرُمُوُز الاِنفِعَالِيِة ";		//Emoticons 
var Languageletter80="إظهَار الصِوِر بالمُحَادثة";		//Show images on chat 
var Languageletter81="إظهار فِيديُوهات بالمُحَادثة";		//Show videos on chat 
var Languageletter82="إظهر صَندُوق المُحَادثة";		//Chatbox instead of popups 
var Languageletter82a="الخريطة المصغرة"; //minimap
var Languageletter82b="عرض الخريطة المصغرة"; //show minimap
var Languageletter82c="عرض شبكة الخريطة المصغرة"; //show minimap grid
var Languageletter82d="إظهار أدلة الخريطة المصغرة";		//Show minimap guides 
var Languageletter82e="لو واحد للفريق";		//One-colored teammates 
var Languageletter83="أدَوَات مُسَاعدة";		//Helpers
var Languageletter84="تغيِر دَرجِة لوُن سِكن الخِصم";		//Opponents colors
var Languageletter85="دَوائِر حَولَ الخِصم";		//Opponents rings 
var Languageletter86="ألوَان الفيرُسات";		//Viruses colors 
var Languageletter87="نطاق الانِقسَام";		//Split range 
var Languageletter88="نِطَاق الفيرُوسَاَت";		//Viruses range 
var Languageletter89="تَتَبُع مُؤشِر بالمَاوس";		//Cursor tracking 
var Languageletter90="إِشَاَرَات لَأعَضَاء الفَريِق";		//Teammates indicators 
var Languageletter91="التحكُم بالمَاوِس";		//Mouse control
var Languageletter92=" الإنِقسَام بالمَاوس";		//LMB - Mouse split 
var Languageletter93="إِعطَاء المَاس بالمَاوس";		//RMB - Mouse feed 
var Languageletter94="تبديل أزرَار المَاوِس";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="إِظهَار أعَلَي 5 بِالفَريِق";		//Show team top 5 
var Languageletter96="إظهار المُستهدف";		//Show targeting 
var Languageletter97="قَائِمَة الأوَائِل بالمُنتَصَف";		//Centered leaderboard 
var Languageletter98="إِحصَائيَات اللَعِبة بِالأَعلَي";		//Game stats at the top 
var Languageletter99="الإحِصَائِيَات";		//Stats
var Languageletter100="أظهِر إحِصَائيَات اللعِبة";		//Show game stats 
var Languageletter101=" الماس- إحِصَائيَات اللعِبة ";		//Game stats: Mass 
var Languageletter102=" إحِصَائيَات اللعِبة: STE";		//Game stats: STE 
var Languageletter103=" إحِصَائيَات اللعِبة-عدد القطع: n/16";		//Game stats: n/16 
var Languageletter104=" إحِصَائيَات اللعِبة: FPS";		//Game stats: FPS 
var Languageletter105="أظهِر الوَقت الحَالي";		//Show current time 
var Languageletter106=" إضَافَات ";		//Extras
var Languageletter107="تجَاهَل الإحِصَائِيات بَعد المَوت";		//Skip stats after death 
var Languageletter108="أَظهِر المَهَام";		//Show quest
var Languageletter108a="لعبة الأصوات"; //Game Sounds
var Languageletter108b="أصوات القائمة"; //Menu Sounds
var Languageletter109="حَظر النَوَافِذ المُزعِجَة";		//Block popups (ads/shop/quest) 
var Languageletter109a="صوت"; //Voice
var Languageletter109b="صوت البادئة"; //Voice-Prefix
var Languageletter109c="صوت اللغة"; //Voice-language
var Languageletter110="—جَودِة الجِرافِيِك--";		//-- Graphics Quality --
var Languageletter111="جِرافِيك: Retina";		//Graphics: Retina
var Languageletter112="جِرافِيك: عالي";		//Graphics: High
var Languageletter113="جِرافِيك: متوسط";		//Graphics: Medium"
var Languageletter114="جِرافِيك: مُنخَفِض";		//Graphics: Low
var Languageletter115="جِرافِيك: جِدَاً مُنخَفِض ";		//Graphics: Very Low
var Languageletter116="تَصِديِر / إسِتيراد للإعدِادِات";		//Export / import settings
var Languageletter117="إستِعَادة الإعدَات الإفتِرَاضِية ";		//Restore default settings
var Languageletter118="تَصديِر الإعِدَادَات";		//Export settings
var Languageletter119="إِستِيرَاد الإِعدَادَات";		//Import settings
var Languageletter120="لتَصدِير الإِعدَادات المُختَارة إنِسَخ الكُود فِي الأَسفَل لملف نَصِي.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="لإِستِيرَاد الإعِدَادات المَطلُوبة قُم بلَصق الكُود المَطلُوب وقُم بالضَغط عَلي زِر إِستِيرَاد.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="الأواَمِر";		// Commands
var Languageletter123="الإِختصَارَات";		// Hotkeys
var Languageletter124="البُرُوفَايل";		// Profiles
var Languageletter125="الإِعدَادات";		// Settings
var Languageletter126="الثِيم";		// Theme
var Languageletter127="تَصديِر الإعِدادَات";		//Export settings
var Languageletter128=" إستِيرَاد الإعِدادات ";		//Import settings
var Languageletter129="الثِيمَات الأسَاسِية";		//Basic theming
var Languageletter130="القَائمة";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="المُحادَثَة";		//Chat
var Languageletter133="الخَريطَة المُصَغَرة";		//Minimap
var Languageletter134="الجِرافِيك / المؤِشِرات";		//Graphics / cursors
var Languageletter135="الثِيم الإِفتِرَاضِية";		//Theme preset
var Languageletter136="إعداد ليجاند الإفتراضية";		//Legend Original
var Languageletter137="الإسِتايل المَجنُون";		//Crazy Style 1
var Languageletter139="الخَلفيِة";		//Background
var Languageletter140="حِدُود الخَريِطَة";		//Map borders
var Languageletter141="الخُطوط الشَبَكيِة";		//Grid
var Languageletter142="خَط القِطَاعَات";		//Sectors font
var Languageletter143="الأسمَاء";		//Names
var Languageletter144="تَغلِيظ الأسمَاء";		//Names stroke
var Languageletter145="المَاَس";		//Mass
var Languageletter146="تَغلِيظ المَاس";		//Mass stroke
var Languageletter147="تَغلِيظ المَاس";		//Virus stroke
var Languageletter148="الفَيرُوسَات";		//Virus
var Languageletter149="المَاس";		//Food
var Languageletter150="مؤشر لأعضاء الفريق";		//Teammate indicator
var Languageletter151="تَتَبُع المُؤشِر";		//Cursor tracking
var Languageletter152="نطاق الإنِقسَام";		//Split range
var Languageletter153="خَط الأسماء";		//Names font
var Languageletter154="خَط المَاس";		//Mass font
var Languageletter155="خَط القِطَاعات";		//Sectors font
var Languageletter157="حَجم خَط القِطاعات";		//Sectors font size
var Languageletter158="نِطاق الأسمَاء";		//Names scale
var Languageletter159="نِطاق المِاس";		//Mass scale
var Languageletter160="مقياس كتلة الفيروسات";		//Virus mass scale
var Languageletter161="تغليظ مدي الخط";		//Text stroke scale
var Languageletter162="حجم النِقَاط";		//Food size: 
var Languageletter163="تَغليظ حَجم خَط الفَيرس";		//Virus stroke size
var Languageletter164="عَرض حُدُد الخَريطة";		//Map borders width
var Languageletter165="عرَض شَبَكِة القِطاعَات";		//Sectors grid width
var Languageletter166="شَفَافية الخَلايا";		//Cells transparency
var Languageletter167="شَفافِية الإِسكِنات";		//Skins transparency
var Languageletter168="شَفافِية الفَيرَس";		//Virus transparency
var Languageletter169="شَفَافِية الأسماء والمَاس";		//Names & mass transparency
var Languageletter170="إستعادة الإعدادات المَبدئية للثِيِم";		//Restore theme default settings
var Languageletter171="حِفظ الإعِدَادات";		//Save settings
var Languageletter172="قَائمة للثِيِم ";		//Menu theme
var Languageletter173="الخَلفِية";		//Background
var Languageletter174="الشَفَافِية";		//Transparency
var Languageletter175="اللَون الرَئِيسِي";		//Main color
var Languageletter176="زِر الكـِتَابة";		//Button text
var Languageletter177="التحَكُم";		//Panel
var Languageletter179="خَط التَحكُم";		//Panel text
var Languageletter181="الزِر";		//Button
var Languageletter189="صُورة خَلفِية التَحكُم";		//Panel background image
var Languageletter190="عِنوَان الصُورَة";		//Image URL
var Languageletter191="اللَوُن الأسَاسِي";		//Main color
var Languageletter192="الخَلفِية";		//Background
var Languageletter193="النَص";		//Text
var Languageletter194=" اِحصَائِيَات ";		//Stats
var Languageletter195="الوَقت";		//Time
var Languageletter196="أعلي 5 في المَاس";		//Top 5 mass
var Languageletter197="قَائِمَة الأَوَائِل";		//Leaderboard - me
var Languageletter198="قَائمة الأوائل - الفريق";		//Leaderboard - teammate
var Languageletter199="HUD خَط";		//HUD font
var Languageletter200="HUD نِطَاق";		//HUD scale: 
var Languageletter201="خَلفِية الرِسَالة";		//Message background
var Languageletter202="نَص الرِسَالة";		//Message text
var Languageletter203="وَقت الرِسَالة";		//Message time
var Languageletter204="حالة الرسالة";		//Message nick
var Languageletter205="أَوَامِر الخَلفِية";		//Command background
var Languageletter206="نَص الأَوَامِر";		//Command text
var Languageletter207="وَقت الأَمر";		//Command time
var Languageletter208="حالة الأمر";		//Command nick
var Languageletter209="لَوَن صَندُوق المُحَادَثة";		//Chatbox color
var Languageletter210="نِطَاق المُحَادَثَة";		//Chat scale
var Languageletter211="القِطَاعَات";		//Sectors
var Languageletter212="القِطَاع الحَالِي";		//Current sector
var Languageletter213="الأسم";		//Nick
var Languageletter214="تَوضِيِح الإِسِم";		//Nick stroke
var Languageletter215="خَلِيَتى";		//My cell
var Languageletter216="تغلِيِظ خَلِيَتِى";		//My cell stroke
var Languageletter217="الفَريِق";		//Teammates
var Languageletter218="مَكَان المَوَت";		//Death location
var Languageletter219="دَليِل الإِرشَاَد";		//Guides
var Languageletter220="خَط الخَرِيِطَة المُصَغَرة";		//Minimap font
var Languageletter221="خَط الإِسِم";		//Nick font
var Languageletter222="عَرَض الخَريِطَة المُصَغَرة";		//Minimap width
var Languageletter223="شَفَافِيِة القِطَاعَاَت";		//Sectors transparency
var Languageletter224="حَجَم الإِسم";		//Nick size
var Languageletter225="تَوضِيِح خَط الإِسم";		//Nick stroke size
var Languageletter226="حَجَم خَليَتى";		//My cell size
var Languageletter227="تَوضِيِح حَجَم الخَلِيَة";		//My cell stroke size
var Languageletter228="حجم الفَريق";		//Teammates size
var Languageletter229="اِختيَار صُوَرة الخَلفِيِة";		//Custom background image
var Languageletter230="إِختِيَار مُؤَشِر الصُورَة";		//Custom cursor image
var Languageletter231="عِنوَان الصُوَرة";		//Image URL
var Languageletter232="مُؤَشِر عِنواَن الصُوَرة";		//Cursor image URL
var Languageletter233="تَغذِيَة";		//Feed
var Languageletter234=" تَغذِيَة سَريِعَة";		//Macro feed
var Languageletter235="إنِقسِم";		//Split
var Languageletter236="إِنقِسَام مُزدَوَج";		//Double split
var Languageletter237="بوُب سِبِلِيِت";		//Popsplit
var Languageletter238="إنِقِسام 16 قِطعَة";		//Split 16
var Languageletter239="تَوقُف الخَليِة";		//Cell pause
var Languageletter240="إِظهَار أو إِخِفَاء أعلي خَمسَة ";		//Show/hide team top 5
var Languageletter241="إِظهَار أو إِخِفَاء الوَقَت";		//Show/hide current time
var Languageletter242=" إِظهَار أو إِخِفَاء نِطَاق الإنقِسَام ";		//Show/hide split range"
var Languageletter243=" إظهَار أو أخفَاء مُؤشِرات الفريق";		//Show/hide teammates indicators
var Languageletter244="إِظهَار أو إِخِفَاء مُؤِشِرَات الإِنقِسَام";		//Show/hide split indicators
var Languageletter245="إِظهَار أو إِخِفَاء لَون الخِصِم";		//Show/hide opponents colors
var Languageletter246=" تَبدِيل الإِسِكِنَات (مُخصَصة/إِعتيَادية)";		//Toggle skins (custom/default)
var Languageletter247="التَبدِيل بالإِسِكِنَات الشَفَافَه";		//Toggle transparent skins
var Languageletter248="إظِهَارأو إِخفَاء الإسِكِنَات";		//Show/hide skins
var Languageletter249=" إظِهَارأو إِخفَاء إِحصَائِيَات اللِعِبة ";		//Show/hide game stats
var Languageletter250="تَبدِيل الخلايا الَتي تملُكها-الصغيرة أو الكبيرة";		//Toggle own cells (smallest/biggest)
var Languageletter251="إخِفَاء أو إظهار النِقاط";		//Show/hide food
var Languageletter252=" إِخفَاء أو إِظهَار الخُطُوط الشَبَكيِة ";		//Show/hide grid
var Languageletter253=" عَرَض الخُطوط الشَبَكيِة الخَريِطَة المُصَغَرة ";		//Show/hide minimap guides
var Languageletter254="إظهَار أو إخفَاء المُحَادثَة";		//Show/hide chat
var Languageletter255=" إظهَار أو إخفَاء HUD  ";		//Show/hide HUD
var Languageletter256="نَسخ قَائِمَة الأَوَائِل ";		//Copy leaderboard
var Languageletter257="إِظهَار أو إِخفَاء قَائِمَة الأَوَائِل ";		//Show/hide leaderboard
var Languageletter258="تَبديل الزُوُم التِلقَائِي";		//Toggle auto zoom
var Languageletter259="إعَادة ضَبط الزُوُم ";		//Reset zoom
var Languageletter260="تبديل موقع الموت";		//Toggle death location
var Languageletter261=" إِظهَار أو إِخفَاء سِجِل المُحَادَثة";		//Show chat history / Clear chat
var Languageletter262=" إِظهَار أو إِخفَاء خَلفِيِة القِطَاَعَاَت";		//Show/hide background sectors
var Languageletter263="إظهار / إخفاء برامج التتبع الصغيرة";		//Show/hide small bots
var Languageletter264=" إِظهَار أو إِخفَاء الأسَمَاء";		//Show/hide names
var Languageletter265=" إِظهَار أو إِخفَاء أسمَاء الفَريِق ";		//Show/hide teammates names
var Languageletter266=" إِظهَار أو إِخفَاء المَاس";		//Show/hide mass
var Languageletter267=" إِظهَار أو إِخفَاء الخَريِطة المُصَغرة";		//Show/hide minimap
var Languageletter268="أدخِل رِسَاَلة المُحَادَثَة";		//Enter chat message
var Languageletter269="بيضة سريعة";		//Quick respawn
var Languageletter270="تبديل اعادة البدء تلقائيا";		//Toggle auto respawn
var Languageletter271="مُستَوي الزُوُم";		//Zoom level 
var Languageletter272="إِظهَار أو إِخفَاء المستهدَف";		//Show/hide targeting panel
var Languageletter273="بداية / إيقاف الاستهداف (متابعة)";		//Start/stop targeting (following)
var Languageletter274="إلغاء الاستهداف";		//Cancel targeting
var Languageletter275="تغيير الهدف";		//Change target
var Languageletter276="عرض الهدف على الخريطة الصغيرة";		//Show target on the minimap
var Languageletter277=" أَظهِار أو إِخفَاء المَهَام ";		//Show/hide quest
var Languageletter278=" لتعيين مفتاح التشغيل السريع انقر على حقل الإدخال واضغط على المفتاح الذي اخترته.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279=" لحذف مفتاح التشغيل السريع انقر على حقل الإدخال واضغط على المفتاح ديليت.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="مجموعات المفاتيح الممكنة مع مفاتيح CTRL و ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281=" إستِعَادة الإعدَادَات الإفتِرَاضِية ";		//Restore default settings
var Languageletter282="حِفظ الإِعدَادات";		//Save settings
var Languageletter283="إغِلَاق";		//Close
var Languageletter284="مُشغل اليوتيوب";		//Youtube player
var Languageletter284a="عنوان اليوتيوب";		// Youtube Url
var Languageletter285="انسَخ الفيديُو الخَاص بِك /قائمة الفيديوهات هنا";		//Paste your video/playlist here
var Languageletter286="الأصوَاَت";		//Sounds
var Languageletter287="صَوَت إِخطَارَات الرسَائِل";		//Message notification sound
var Languageletter288="صَوَت إِخطَارَات الأَوامِر ";		//Command notification sound
var Languageletter289="نَسخ عِنوان السِيرفَر SIP ";		//Copy Token/SIP
//keep this small
var Languageletter290="عِنوَان السِيرفَر";		//Token
var Languageletter290a="قَاَئِمَة الأوَائِل"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="نسخ الكل"; //TK&ALL (Token and All)
var Languageletter291="نَسخ";		//Copy
var Languageletter291a="نَسخ قَاَئِمَة الأوَائِل (L)";		//Copy Leaderboard (L)
var Languageletter291b="نسخ رمز / سيب وكلمة المرور"; 	//Copy Token/SIP&Password
var Languageletter291c="نسخ كل شيء"; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="إنِضَم للِسِيرفَر (Backspace)";		//Join server (Backspace)
var Languageletter293="تَغِيِير السِيرفَر (+)";		//Change server (+)
var Languageletter294="سِجِل قَائِمَة الأَوَائِل";		//Leaderboard history
var Languageletter295="أَدخِل اسم صَدِيق أو الأي بي أو قَائِمَة الأوئل أو رَمز كِلان..";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter296=" الأعَبُون النَشِطُون ";		// Active players
var Languageletter297="مَجمُوع المَاس";		// Total mass
var Languageletter298="أوَائِل الفَريِق ";		//Team top 
var Languageletter299="قَائِمَة الأوَائِل";		//Leaderbodard
var Languageletter300=" الإتِصَالاَت ";		//Communication
var Languageletter301="أوَامِر نَص الرِسَالة";		//Message Script Commands
var Languageletter302="أيقُونَات رَسَائِل الصُوُر";		//Message Imgur Icons
var Languageletter303="رَسَائِل فِيدُيوهَات اليُوتيُوُب";		//Message Youtube Videos
var Languageletter304="تَعدِيِل الأَسمَاء";		//Edit names
var Languageletter305="[وَضَع التَصَفُح فَقَط] Binoculars";		//[Spectate Mode Only] Binoculars
var Languageletter306="إِلعَب / تَوقَف";		//Play / Pause
var Languageletter307="مَلء الشَاشَة";		//Fullscreen
var Languageletter308="إِستِدَارة";		//Rotate
var Languageletter309="إِعتِيَادي";		//Default
var Languageletter310=" الخَلف";		//Back
var Languageletter311="حِفظ لِوَقت لَاحِق ";		//Save for later
var Languageletter312="المَنطِقَة";		//Region
var Languageletter313="اللاعبين";		//Players
var Languageletter314="السِيرفَرَات";		//Servers
var Languageletter315="[ لَم يَتم تَعيِيِن الهَدَف]";		//[Target not set]
var Languageletter316="خلفية يدوية";		//Manual background
var Languageletter317="أيقونات رسالة يدوية & يوتيوب";		//Manual Message Icons&Youtube
var Languageletter318="مَكَان المُحَادَثة ";		//Chat Position
var Languageletter319="Discord Webhook Url (لإرسال رمز TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="قَائِمَة الأَوَائِل";		//Leaderboard
var Languageletter321=" قَائِمَة الفَرِيِق ";		//Teamboard
var Languageletter322="قماش الرئيسي";		//Main Canvas
var Languageletter323="بانر الرئيسي";		//Main Banner
var Languageletter324="مَرحَباً بالفَريِق!";		//Hello Team!
var Languageletter325="اضحك على الفريق";		//Laugh to Team
var Languageletter326="الفَريق يُغَير اسمَه مِثلَ إسمَك";		//Team Change Name to yours
var Languageletter327=" العَزاء عِند المَوت";		//Troll on Death
var Languageletter328="فَتح مُوسِيقي يُوتيُوب";		//Open Youtube Music
var Languageletter329="Insane mode (إِخفَاء كُل شَىء)";		//Insane mode (Hide Everything)
var Languageletter330="عِنوَان الصُورَة يَبدأ بـ http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="عِنوان صُورة الخَرِيطَة المُصَغَرة";		//Minimap Image URL
var Languageletter332="خَط الخَرِيطَة المُصَغَرة";		//Minimap Text
var Languageletter333="نَص قَائِمة الأَوائِل";		//Leaderboard Logo Text
var Languageletter333a="عِنوَان صُورة قَائِمَة الأوَائِل";		// Leaderboard Image URL
var Languageletter334="نَص قَائِمَة الفَريِق";		//Teamboard Logo Text
var Languageletter334a=" عِنوَان صُورة قَائِمَة الفَرِيق ";		// Teamboard Image URL
var Languageletter335="العنوان الرئيسي لصورة Canvas";		//Main Canvas Image URL
var Languageletter336="عنوان أيقونة بانر الرئيسي";		//Main Banner Icon URL
var Languageletter337="رابط رابط العنوان الرئيسي";		//Main Banner Link URL
var Languageletter338="أَيقونة";		//Icon
var Languageletter339="عَلَي سَبِيِل المِثَال";		//e.g
var Languageletter340="عِنوَان فِيديِو اليُتيُوب المَطلوُب عَرضَه";		//Url of youtube to be shown
var Languageletter341="عِنوان الوَصلَة المَطلُوب إِعَادة التَوجيه لَها";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="رسالة نص النص";		//Message Icon Text
var Languageletter342b="نَص رِسَالة اليُوتيُوب";		//Youtube Message Text
var Languageletter342c="Message Icon Imgur Url";		//Message Icon Imgur Url
var Languageletter342d="عِنوان رِسالة اليوُتيُوب";		//Youtube Message Url
var Languageletter343="يَجِب أَن تَفشَل لِتعمَل هَذه الوَظِيفَة";		//Must be filled for function to work.
var Languageletter344="Secondary Webhook(اختياري)";		//Secondary Webhook(optional)
var Languageletter345="مُؤقَتا إِخفَاء كُل شَىء. Function for Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Languageletter346="إِختَار اللُغة";		//Choose Language
var Languageletter347="تحذير! يتم حظر النوافذ المنبثقة في الإعدادات.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="إلغاء المنع المؤقت";		//Temporary unblock

var Languageletter349="الجُرع";	//Potions
var Languageletter350="سكينات قديمة";	//Old Skins
var Languageletter351="صفقة خاصة"; //Special Deals
var Languageletter352="المُتَصَدِرِين"; //Leaderboards
var Languageletter353="نموذج جديد وإحصائيات"; //New Ideas & Statistics Form
var Languageletter354="سكنات فيديو"; //Video Skins
var Languageletter355="سكريبتات مُصغرة"; //Mini Scripts
var Languageletter356="سكريبتات المُستخدم"; //User Scripts
var Languageletter357="دردشة صوت والكاميرا";	//Voice & Camera Chat
var Languageletter358="يرجى دعم تطوير مطوري ليجاند مُود";	//Please support the development of Legend mod
var Languageletter359="تصميم اسم الخط";	//Design Nickname Font
var Languageletter360="التنويه بوضع اسكن شخص مزور";	//Flag the Fake Skin
var Languageletter361="المزيد من FPS";	//More FPS

var Premadeletter0="تَم تَفعِيِل الإتِصَالات"; 		//Communication Activated
var Premadeletter1="لَا يُمكِن فَتح عِنوان اليُوتيُوب";		 //Cannot open this youtube URL
var Premadeletter2="لا يُمكنك الدَردَشة لَو اسمك تَعدي 15 رَمز"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="بيضة عيد1الفصح 1 تفعيلها"; 		//Easter Egg 1 Activated
var Premadeletter4="بيضة عيد الفصح 2 تفعيلها";		//Easter Egg 2 Activated
var Premadeletter5="بيضة عيد الفصح 3 تفعيلها";		//Easter Egg 3 Activated
var Premadeletter6=" vanillaالفيديو تعمل أفضل عند استخدام إعدادات    ";		//Video works better on vanilla, visit:
var Premadeletter7=" ملاحظات : فيسبوك متوافق افضل من جوجل بلاس."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter="8ملاحظات: اجاريو يمكنها فقط الاتصال من حساب جوجل .. اذا حصل عدم تسجيل قم بإعادة محاولة الدخول أو استخدم حساب فيسبوك.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter="لو حدث عدم تسجيل قم بحذف الكوكيز من متصفح الكروم";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10=" غير مُتصل بالسيرفر :(";		//Disconnected from server :(
var Premadeletter11="تم حظرك ، قم بعمل إعادة تشغيل للراوتر!";		//You were banned, restart your rooter!
var Premadeletter12="مُتصل!";		//Connected!
var Premadeletter13="إِلعَب";		//PLAY
var Premadeletter14="وضع التصفح";		//SPECTATE
var Premadeletter15="عنوان سيرفر خاطئ أو تم إغلاقه :(";		//Invalid token or server has closed :(
var Premadeletter16="يمكن تحديثها إلي";		//can be Updated to
var Premadeletter17="مرحبا بعودتك";			//Welcome back
var Premadeletter18="أختصاراتك مازالت غير مفعلة  . نقترح تفعيلها.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="قُم بتَفعِيلَهُم";		//Enable Them
var Premadeletter20="دَعَهُم غير مُفَعَلِين";		//Keep Them Disabled
var Premadeletter21="بَحَث الأي بي ";		//Searching IP
var Premadeletter22="صديقك";		//Your teammate
var Premadeletter23="يَرغَب فِي إخِفاء قَائمَة الأوائل (leaderboard and minimap)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="موافق";		//Accept
var Premadeletter25="أرفُض!";		//NO WAY!
var Premadeletter26="يَرغَب فِي تَغيِر إسمَك إلي";		//wants you to change your name to
var Premadeletter27="يَرَغب فِي إخِفاء تَفعِيل العَزاء بَعد المَوت";		//wants you to hide Enable Troll on death
var Premadeletter28="يَرغَب فِي قِيَامَك بِفَتح مُشَغِل اليُوتيُوب";			//wants you to open Youtube Player
var Premadeletter29="تَم إِيجَاد قَائمة الأوائل";		//Leaderboard found
var Premadeletter30="بَحَث";		//Search
var Premadeletter31="قَائمة الأوائل لَم تُوُجَد .إِستَمِر بالِمُحَاولَه...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="تَم إلغَاء البَحَث";		//Search was canceled
var Premadeletter33="أنتَ الأَن مَرئِي لأعضَاء الفَريِق/الكِلان";		//You are invisible to Team / Clan
var Premadeletter34="أنتَ الأَن غَير مَرئِي لأعضَاء الفَريِق/الكِلان ";		//You are visible to Team / Clan
var Premadeletter35="إخفَاء/إظهَار يُمكِن استخدامُه فَقَط أثنَاء اللِعب";			//Hide/Show can be used only while playing
var Premadeletter36="عِنوَان دِيسكورد غَير صَحِيح";		//This is not valid Discord Webhook address
var Premadeletter37="السِيرفر مُغلق ";		//Server is locked
var Premadeletter38="يَجب أن تَكُون فِي وَضع تَصفُح اللِعِبة";		//You must be on spectate mode
var Premadeletter39="نظرا للإعلانات المُزعجة ، يجب أن تكون في وضع اللعب مُستخدما الباسوورد";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="تَفعِيل اليُوتيُوب";		//Auto Youtube On
var Premadeletter41="غَلق تِلقائي لليوتيُوب";		//Auto Youtube Off
var Premadeletter42="إظهَار الإِختِصَارات";		//Show Shortcuts
var Premadeletter43="إخِفاء الإخِتصَارات";		//Hide Shortcuts
var Premadeletter44="إظهَار شَريِط المُستَوي";		//Show XP BAR
var Premadeletter45="إخِفاء شِريط المُستَوي";		//Hide XP BAR
var Premadeletter45a = "دور Hud"; //Rounded Hud
var Premadeletter45b = "مربع Hud"; //Square Hud

var Premadeletter46="إظهَار الوَقت";		//Show TIME
var Premadeletter47="إخفَاء الوَقت";		//Hide TIME
var Premadeletter48="إظهـار الكُل";		//Show Everything
var Premadeletter49="إخفَاء الكُل";		//Hide Everything
var Premadeletter50=" إظهار الموقت";		//Show Timer Calc.
var Premadeletter51=" إخفاء المؤقت"		//Hide Timer Calc.
var Premadeletter52="تَعديِل الأسمَاء";		//Edit Names
var Premadeletter52a="إغلاق الأسماء";		//Close Names
var Premadeletter53="تَفعيِل تِلقائي للِكُوينِز";		//Auto free coins
var Premadeletter54="أَوقِف الكُوِيِنز المَجـانِية";		//Stop free coins
var Premadeletter55="العَزاء بَعَد المَوَت";		//Troll on Death
var Premadeletter56="لا عَزاء بَعَد المَوَت";		//No troll on Death

var Premadeletter57="الإتِصَالاَت";		//Communication
var Premadeletter58="إِخفَاء";		//Hidden
var Premadeletter59="مَرئِي";		//Visible
var Premadeletter60="توقف";		//Pause

var Premadeletter61 = "تمكين اليوتيوب كخلفية";	//Enable YT as background
var Premadeletter62 = "تعطيل يوتيوب كخلفية";	//Disable YT as background";
var Premadeletter63 = "يريد منك فتح صفحة الويب";	//wants you to open the url
var Premadeletter64 = "يريد منك تشغيل هذا الفيديو ";	//wants you to embed and play this youtube video
var Premadeletter65 = "يريد منك الانضمام إلى غرفة سكايب التالية";	//wants you to join the following Skype room
var Premadeletter66 = "يريد منك الانضمام إلى غرفة ديسكورد التالية";	//wants you to join the following Discord room
var Premadeletter67 = "يريد منك ترك هذا السيرفر والانضمام إلى هذا الجديد";	//wants you to leave this server and join this new one

//I did it like this because Arabic language is using the opposite side of writing
var Premadeletter68 = "";
var Premadeletter69 = ". أعد تشغيل agario في حالة انخفاض FPS ، لأنك قمت بالضغط على:"; //. Restart agario if FPS drops, because you pressed:
var Premadeletter70 = "";

var Premadeletter71 = ""; 
var Premadeletter72 = ""; 
var Premadeletter73 = "عندما تكون على مثل هذه القطع ، سينخفض ذلك (يتم تمكين جلود الرسوم المتحركة)"; //When you will be on such pieces, this will drop (Animates skins are enabled)
var Premadeletter74 = ""; 
var Premadeletter75 = ""; 
var Premadeletter76 = ""; //
var Premadeletter77 = ""; 
var Premadeletter78 = "سيتم تعطيل الرسوم المتحركة بعد إعادة الانضمام. أداء أفضل FPS عندما 16"; //Animated skins will be disabled after rejoin. Better FPS performance when 16
var Premadeletter79 = ""; //
var Premadeletter80 = "عند تمكين تعديل Dying Light ، لا يمكن وضع Troll عند الموت"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "خادم خاص"; //Private Server
var Premadeletter82 = "";
var Premadeletter83 = "اتصل بأي خادم أو أنشئ بنفسك"; //server, or make your own
var Premadeletter84 = "العب ألعاب مشابهة للأجوار إذا كنت تعرف عنوان IP للخوادم"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "";
var Premadeletter86 = "تم نسخ صورتك إلى الحافظة. لصقه إلى منطقة مخصصة للعناية بالبشرة:"; //Your image has been copied to clipboard. Paste it to custom skin Url area:
var Premadeletter87 = "يجب عليك تسجيل الدخول لاستخدام صورة ملفك الشخصي"; //You must Login to use picture of your profile
var Premadeletter88 = "أنت تستخدم إصدارًا خاطئًا"; //You are using a wrong version
var Premadeletter89 = "اللعبة ستنتهي الآن"; //Game will terminate now
var Premadeletter90 = "صفقة خاصة"; //Special Deals
var Premadeletter91 = "قد أو لا تعطيك Agario الجلد ، ولكن فقط العملات"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "استخدام على مسؤوليتك الخاصة"; //Use at your own risk
var Premadeletter92 = "إذا كان UID الخاص بصديقك غير صحيح ، فستفشل عملية الشراء"; //If friend UID is wrong, purchase will fail
var Premadeletter93 = "إعدادات المصنع UID"; //UID Factory Settings
var Premadeletter94 = "يجب عليك تسجيل الدخول لتحميل العروض الخاصة"; //You must login to load Special Deals
var Premadeletter95 = "";
var Premadeletter96 = "تم نسخ الصورة المزيفة إلى الحافظة. قم بلصقها لمنطقة Url المخصصة للجلد لتنشيط وظيفة العلم المزيف:"; // Fake image has been copied to clipboard. Paste it to custom skin Url area in order to activate the fake flag function:
var Premadeletter97 = "أبلغني عند الانتهاء من Recaptcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "لقد انتهيت"; //I have finished
var Premadeletter99 = "لا يهم"; //Never Mind
var Premadeletter100 = "حساب XP الخاص بك ، يرجى الانتظار ..."; //Calculating your XP, please wait...
var Premadeletter101 = ""; //
var Premadeletter102 = "لا تضغط"; //Do NOT press
var Premadeletter103 = ""; //
var Premadeletter104 = "محو عنوان URL مخصص للجلد"; //Erase custom skin URL
var Premadeletter105 = "حدد جلد الفيديو";	//select video skin
var Premadeletter106 = "إلغاء تحديد الجلد الفيديو"; //unselect video skin
var Premadeletter107 = "كتم الصوت"; //mute audio
var Premadeletter108 = "مشروع LM"; //The LM Project
var Premadeletter109 = "تحميل تنزيل"; //Upload / Download
var Premadeletter110 = "لا تدخل أي شيء هنا إلا إذا كنت تعرف ما هو";	//do not enter anything here unless you know what it is
var Premadeletter111 = "انقر على أيقونة اللون البرتقالي للشراء"; //click on the orange icon to buy
var Premadeletter112 = "لبعض طرق الدفع"; //For some payment methods
var Premadeletter113 = "قريب";	//Close
var Premadeletter114 = "نسخ"; //COPY	
var Premadeletter115 = "يستخدم لشراء العروض لأصدقائك"; //is used to buy offers for your friends
var Premadeletter116 = "لإجراء عمليات شراء ، يجب تسجيل الدخول إلى حسابك ..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "مكتبة"; //Library
var Premadeletter118 = "يزور"; //visit
var Premadeletter119 = "الإبلاغ عن خطأ (تغيير الجلد)"; //Report as Fake (change Skin)
var Premadeletter120 = "أدخل اسمك الخاص بالمشغل"; //Enter your EXACT name of the player
var Premadeletter121 = "سيؤدي استغلال اللاعبين والاستخدام غير المناسب إلى UID للمستخدم"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "لحظر دائم من استخدام هذا التمديد"; //to permanent ban from usage of this extension

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "اللغات"; //LANGUAGES
var Externalletter0b = "اختر لغة"; //Choose a language
var Externalletter0c = "ستحدث التغييرات تمامًا بعد إعادة التشغيل"; //Changes will take place completely after the restart
var Externalletter1 = "معلومات"; //INFORMATION
var Externalletter2 = "قالب"; //TEMPLATES
var Externalletter3 = "الدليل اليدوي"; //MANUAL TEMPLATES
var Externalletter4 = "اختر القالب الخاص بك"; //Choose your template
var Externalletter5 = "أو اختيار التوسع"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "إرسال الكود إلى المطورين"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "الصق Script الخاص بك في هذا Textarea ، يمكنك تحميل برامج نصية متعددة"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "تحميل البرنامج النصي من Textarea"; //Load Script from Textarea
var Externalletter8 = "أختر"; //Choose
var Externalletter9 = "مسح السيناريو"; //Erase Script
var Externalletter10 = "اسم"; //Name
var Externalletter11 = "Url (raw) Github أو أي سيناريو خام آخر يبدأ بـ"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "اترك هذا فارغًا إذا لم يتم استيراد البرنامج النصي من عنوان URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "إشعار هام: لا تحتفظ بعناوين URL التي لا تعمل ، لأنها تستخدم في أحداث التحميل. إذا كان الأضرار السيناريوهات على أحداث التحميل ، ثم DELETE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
