

/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */

var translator="【你媽】AENQ.com【你媽】";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="首頁";		//Home
var Languageletter1="使用者";		//User
var Languageletter2="設定";		//Settings
var Languageletter3="主題";		//Theme
var Languageletter4="熱鍵";		//Hotkeys
var Languageletter5="Youtube 與 音效";		//Youtube & Sounds
var Languageletter6="工具";		//Tools
var Languageletter7="將其留空為公開，或插入氏族的密碼，或使用它作為標籤";		//Password/Tag
var Languageletter7a="密碼 或 Tag"	;	//Password/Tag
var Languageletter8="填入遊戲暱稱。 插件使用者可用50個字，沒插件的可見到前15字。";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="暱稱";		//Name
var Languageletter9="填入自訂皮網址";		//Insert your manual skin weblink
var Languageletter9a="手動啥的網址";		//Manual direct skin URL
var Languageletter10="選擇地區";		//The region to play
var Languageletter11="選擇模式";		//The mode to play
var Languageletter12="連接伺服器中 或 重新恢復連線中";		//Connect to server, or restablish communication
var Languageletter12a="連線";		//Connect
var Languageletter13="加入";		//Join
var Languageletter14="直接玩不登入";		//Play as guest
var Languageletter15="登入";		//Login and Play
var Languageletter16="觀戰";		//Spectate
var Languageletter17="用 FaceBook 帳號登入";		//Sign in with Facebook
var Languageletter18="用 Google 帳號登入";			//Sign in with Google
var Languageletter19="開始玩";		//Play
var Languageletter20="商店"	;		//Shop
var Languageletter21="免費金幣";		//Free Coins
var Languageletter22="送禮";		//Gifts
var Languageletter23="每日任務";			//Daily Quests
var Languageletter24="皮";		//Skins
var Languageletter25="Legend 的影片";		//Legend Promo Video
var Languageletter25a="新思路與統計表";		//New Ideas & Statistics Form
var Languageletter25b="Mod 信息和模板";		//Mod Info & Templates
var Languageletter26="增加皮";		//Add skins
var Languageletter26a="複製服務器，密碼，團隊板和排行榜"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="登出";		//Logout
var Languageletter32="使用時間";		//Times Used
var Languageletter33="Legend Mod 作者: ";		//Legend Mod by
var Languageletter34="翻譯者: ";		//Translation by
var Languageletter35="複製排行榜及玩家名 (按x鍵可切換 顯示/隱藏)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="動畫";		//Animation
var Languageletter37="動畫延遲";		//Animation delay
var Languageletter37a="自動縮放";		// Auto zoom
var Languageletter37b="縮放";		// Zoom
var Languageletter38="縮放速度:";		//Zoom speed: 
var Languageletter39="重生";			//Respawn
var Languageletter40="自動重生";		//Auto respawn 
var Languageletter41="快速重生 ";			//Quick respawn 
var Languageletter41a="從特效開始";			//Spawn special effects 
var Languageletter41b="合併時間";			//Merge timer off
var Languageletter41c="建議啟用沒有滯後";			//Suggested to be enabled for Lag reduce
var Languageletter41d="病毒拍攝聲音";			//Virus shot sound

var Languageletter42="名稱";			//Names
var Languageletter43="沒有名字";		//No names 
var Languageletter44="最佳化名字";		//Optimized names 
var Languageletter45="自動隱藏名字";		//Auto hide names 
var Languageletter46="隱藏我的名字";		//Hide my name 
var Languageletter47="隱藏隊友名字";		//Hide teammates names 
var Languageletter48="名字外框";		//Names stroke 
var Languageletter49="質量";		//Mass
var Languageletter50="顯示質量";		//Show mass 
var Languageletter51="最佳化質量"	;	//Optimized mass 
var Languageletter52="自動隱藏質量";			//Auto hide mass 
var Languageletter53="隱藏我的質量";		//Hide my mass 
var Languageletter54="隱藏敵人質量";		//Hide enemies mass 
var Languageletter55="縮短質量";		//Short mass
var Languageletter56="病毒鏡頭";		//Virus shots 
var Languageletter57="質量字型外框";		//Mass stroke 
var Languageletter58="皮膚";		//Skins
var Languageletter59="沒皮膚";		//No skins 
var Languageletter60="自訂皮膚";		//Custom skins 
var Languageletter61="官方皮膚";		//Vanilla skins 
var Languageletter61a="果凍物理學";		//Jelly physics 
var Languageletter61b="視頻皮膚";		//Video skins
var Languageletter61c="C3時，來自其他視頻皮膚的聲音";		//Sound from other\'s Video skins when both C3

var Languageletter62="最佳化點點";		//Optimized food 
var Languageletter6a2="點點";		//Food 
var Languageletter63="自動隱藏點點(質量)";		//Auto hide food (mass) 
var Languageletter64="自動隱藏點點(縮放)";		//Auto hide food (zoom) 
var Languageletter65="彩虹點點";		//Rainbow food 
var Languageletter66="透明 / 顏色";		//Transparency / colors
var Languageletter67="沒顏色";		//No colors 
var Languageletter68="我的自訂顏色";		//My custom color 
var Languageletter69="我的透明皮膚";		//My transparent skin 
var Languageletter70="透明皮膚";		//Transparent skins 
var Languageletter70a="透明細胞";		//Transparent cells
var Languageletter71="透明刺";		//Transparent viruses 
var Languageletter71a="病毒大放異彩";		//Virus Glow
var Languageletter71b="動畫的彩虹色";		//Animated rainbow colors

var Languageletter72="格子 / 座標";		//Grid / sectors
var Languageletter73="顯示格子";		//Show grid 
var Languageletter74="顯示背景座標";		//Show background sectors 
var Languageletter75="顯示地圖外框";		//Show map borders 
var Languageletter75a="邊界的光輝";		//Border Glow

var Languageletter76="聊天";		//Chat
var Languageletter77="關閉聊天";		//Disable chat 
var Languageletter78="聊天音效";		//Sound notifications 
var Languageletter79="表情圖示";		//Emoticons 
var Languageletter80="在聊天中顯示圖片";		//Show images on chat 
var Languageletter81="在聊天中顯示影片";		//Show videos on chat 
var Languageletter82="以對話框取代跳出訊息";		//Chatbox instead of popups 
var Languageletter82a="小地圖";		//Minimap
var Languageletter82b="顯示小地圖";		//Show minimap 
var Languageletter82c="顯示小地圖格線";		//Show minimap grid 
var Languageletter82d="顯示小地圖指引線";		//Show minimap guides 
var Languageletter82e="以單色顯示隊友";		//One-colored teammates 
var Languageletter82f="顯示額外的迷你地圖指南";		//Show extra minimap guides
var Languageletter82g="顯示幽靈細胞";		//Show ghost cells

var Languageletter83="幫助";		//Helpers
var Languageletter84="對手顏色";		//Opponents colors
var Languageletter85="敵人狀態指示框";		//Opponents rings 
var Languageletter86="刺球顏色";		//Viruses colors 
var Languageletter87="分裂距離";		//Split range 
var Languageletter87a="快速雙分割範圍";		//Quick double split range
var Languageletter87b="慢速雙分割範圍";		//Slow double split range

var Languageletter88="刺球距離";		//Viruses range 
var Languageletter89="游標追蹤";		//Cursor tracking 
var Languageletter90="隊友顯示";		//Teammates indicators 
var Languageletter90a="鬼細胞";		//Ghost cells

var Languageletter91="滑鼠控制";		//Mouse control
var Languageletter92="滑鼠左鍵 - 分裂";		//LMB - Mouse split 
var Languageletter93="滑鼠右鍵 - 同W ";		//RMB - Mouse feed 
var Languageletter94="滑鼠按鍵左右互換";		//Invert mouse buttons 
var Languageletter94a="螢幕資訊";		// HUD
var Languageletter95="顯示隊友前五名";		//Show team top 5 
var Languageletter96="顯示目標";		//Show targeting 
var Languageletter96a="顯示排行榜質量";		//Show leaderboard mass

var Languageletter97="排行榜置中";		//Centered leaderboard 
var Languageletter97a="排行榜標題";		//\"Leaderboard\" header 

var Languageletter98="於最上方顯示遊戲狀態";		//Game stats at the top 
var Languageletter98a="在茶棚上的皮膚";		//Skins on teamboard

var Languageletter99="統計";		//Stats
var Languageletter100="顯示遊戲資訊";		//Show game stats 
var Languageletter101="遊戲統計數據";		//Game stats
//the \' is needed
var Languageletter102="敵人的";		//Enemy\'s 		
var Languageletter103="我們的";		//Our
var Languageletter104="最小的技巧分裂隊友的質量";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="預分裂的最大敵人質量";		//Maximal enemy\'s mass for presplit 
var Languageletter105="顯示目前時間";		//Show current time 
var Languageletter106="額外";		//Extras
var Languageletter107="死後跳過遊戲統計";		//Skip stats after death 
var Languageletter108="顯示任務";		//Show quest 
var Languageletter108a="遊戲的聲音"; //Game Sounds
var Languageletter108b="菜單聽起來"; //Menu Sounds
var Languageletter109="屏蔽跳出視窗 (廣告/商店/任務)";		//Block popups (ads/shop/quest) 
var Languageletter109a="語音"; //Voice
var Languageletter109b="語音前綴"; //Voice-Prefix
var Languageletter109c="語音語言"; //Voice-language
var Languageletter109d="取消暫停"; //UnPause

var Languageletter110="-- 繪圖品質 --";		//-- Graphics Quality --
var Languageletter111="繪圖品質: 最高";		//Graphics: Retina
var Languageletter112="繪圖品質: 高";		//Graphics: High
var Languageletter113="繪圖品質: 中";		//Graphics: Medium"
var Languageletter114="繪圖品質: 低";		//Graphics: Low
var Languageletter115="繪圖品質: 最低";		//Graphics: Very Low
var Languageletter116="存檔 /  設定";		//Export / import settings
var Languageletter117="恢復原始設定";		//Restore default settings
var Languageletter118="設定存檔";		//Export settings
var Languageletter119="讀取設定檔";		//Import settings
var Languageletter120="如要將設定存檔，可複製下面文字，將它用Unicode格式，儲存成文字檔。";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="如要匯入設定，可在下方貼上設定文字，之後按下 匯入設定 按鈕。";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="指令";		// Commands
var Languageletter123="熱鍵";		// Hotkeys
var Languageletter124="設定檔";		// Profiles
var Languageletter125="設定";		// Settings
var Languageletter126="主題";		// Theme
var Languageletter127="設定存檔";		//Export settings
var Languageletter128="讀入設定檔";		//Import settings
var Languageletter129="基本主題";		//Basic theming
var Languageletter130="菜單";		//Menu
var Languageletter131="螢幕資訊";		//HUD
var Languageletter132="對話";		//Chat
var Languageletter133="小地圖";		//Minimap
var Languageletter134="繪圖 / 游標";		//Graphics / cursors
var Languageletter135="預設主題";		//Theme preset
var Languageletter136="原創主題";		//Legend Original
var Languageletter137="瘋狂風格";		//Crazy Style 1
var Languageletter139="背景";		//Background
var Languageletter140="地圖外框";		//Map borders
var Languageletter141="格線";		//Grid
var Languageletter142="格自型";		//Sectors font
var Languageletter143="名字";		//Names
var Languageletter144="名字外框";		//Names stroke
var Languageletter145="質量";		//Mass
var Languageletter146="質量外框";		//Mass stroke
var Languageletter147="刺球外框";		//Virus stroke
var Languageletter148="刺球";		//Virus
var Languageletter148a="母細胞";		//Mothercell
var Languageletter148b="母親細胞中風";		//Mothercell stroke
var Languageletter149="點點";		//Food
var Languageletter150="隊友指示";		//Teammate indicator
var Languageletter151="游標追蹤";		//Cursor tracking
var Languageletter152="分裂距離";		//Split range
var Languageletter153="名字自型";		//Names font
var Languageletter154="質量字型";		//Mass font
var Languageletter154a="大";		//Bigger
var Languageletter154b="小";		//Smaller
var Languageletter155="格子自行";		//Sectors font
var Languageletter157="格子字型大小";		//Sectors font size
var Languageletter158="名字縮放";		//Names scale
var Languageletter159="質量縮放";		//Mass scale
var Languageletter160="刺球質量縮放";		//Virus mass scale
var Languageletter161="字的外框縮放";		//Text stroke scale
var Languageletter162="點點大小";		//Food size: 
var Languageletter163="刺球外框大小";		//Virus stroke size
var Languageletter164="地圖外框寬度";		//Map borders width
var Languageletter165="格子寬度";		//Sectors grid width
var Languageletter166="細胞透明度";		//Cells transparency
var Languageletter167="皮膚透明度";		//Skins transparency
var Languageletter168="刺球透明度";		//Virus transparency
var Languageletter169="名字 & 質量 透明度";		//Names & mass transparency
var Languageletter170="回復預設主題";		//Restore theme default settings
var Languageletter171="設定存檔";		//Save settings
var Languageletter172="菜單主題";		//Menu theme
var Languageletter173="背景";		//Background
var Languageletter174="透明度";		//Transparency
var Languageletter175="主要顏色";		//Main color
var Languageletter176="底部文字";		//Button text
var Languageletter177="面板";		//Panel
var Languageletter179="面板文字";		//Panel text
var Languageletter181="底部";		//Button
var Languageletter189="面板背景圖";		//Panel background image
var Languageletter190="圖片網址";		//Image URL
var Languageletter191="主要顏色";		//Main color
var Languageletter192="背脊";		//Background
var Languageletter193="文字";		//Text
var Languageletter194="統計";		//Stats
var Languageletter195="職間";		//Time
var Languageletter196="前五名質量";		//Top 5 mass
var Languageletter197="排行榜 - 我";		//Leaderboard - me
var Languageletter198="旁行榜 - 隊友";		//Leaderboard - teammate
var Languageletter199="螢幕資訊的自型";		//HUD font
var Languageletter200="螢幕資訊的縮放";		//HUD scale: 
var Languageletter201="對話背景";		//Message background
var Languageletter202="對話自型t";		//Message text
var Languageletter203="對話時間e";		//Message time
var Languageletter204="對話名字";		//Message nick
var Languageletter205="指令背景";		//Command background
var Languageletter206="指令文字";		//Command text
var Languageletter207="指令時間";		//Command time
var Languageletter208="指令名字";		//Command nick
var Languageletter209="對話框顏色";		//Chatbox color
var Languageletter210="對話縮放";		//Chat scale
var Languageletter211="座標";		//Sectors
var Languageletter212="目前座標";		//Current sector
var Languageletter213="名字";		//Nick
var Languageletter214="名字外框";		//Nick stroke
var Languageletter215="我的球";		//My cell
var Languageletter216="我的球外框";		//My cell stroke
var Languageletter217="隊友";		//Teammates
var Languageletter218="死的地點";		//Death location
var Languageletter219="指南";		//Guides
var Languageletter220="小地圖自型";		//Minimap font
var Languageletter221="名字自型";		//Nick font
var Languageletter222="小地圖寬度";		//Minimap width
var Languageletter223="座標透明度";		//Sectors transparency
var Languageletter224="名字大小";		//Nick size
var Languageletter225="名字外框大小";		//Nick stroke size
var Languageletter226="我的球大小";		//My cell size
var Languageletter227="我的球外框大小";		//My cell stroke size
var Languageletter228="隊友大小";		//Teammates size
var Languageletter229="自訂背景圖";		//Custom background image
var Languageletter230="自訂游標圖";		//Custom cursor image
var Languageletter231="圖片網址";		//Image URL
var Languageletter232="游標圖片網址";		//Cursor image URL
var Languageletter233="餵W";		//Feed
var Languageletter234="連續餵W";		//Macro feed
var Languageletter235="分裂";		//Split
var Languageletter236="雙空";		//Double split
var Languageletter237="POP分裂";		//Popsplit
var Languageletter238="16分";		//Split 16
var Languageletter239="球停止";		//Cell pause
var Languageletter240="顯示/隱藏 前五名隊友";		//Show/hide team top 5
var Languageletter241="顯示/隱藏 目前時間";		//Show/hide current time
var Languageletter242="顯示/隱藏 分裂距離";		//Show/hide split range"
var Languageletter243="顯示/隱藏 隊友指示";		//Show/hide teammates indicators
var Languageletter244="顯示/隱藏 分裂指示";		//Show/hide split indicators
var Languageletter245="顯示/隱藏 對手顏色";		//Show/hide opponents colors
var Languageletter246="皮切換 (自訂/預設)";		//Toggle skins (custom/default)
var Languageletter247="皮透明度切換";		//Toggle transparent skins
var Languageletter248="顯示/隱藏 皮";		//Show/hide skins
var Languageletter249="顯示/隱藏 遊戲統計資料";		//Show/hide game stats
var Languageletter250="切換球的 (最小/最大)";		//Toggle own cells (smallest/biggest)
var Languageletter251="顯示/隱藏 點點";		//Show/hide food
var Languageletter252="顯示/隱藏 格線";		//Show/hide grid
var Languageletter253="顯示/隱藏 小地圖指示線";		//Show/hide minimap guides
var Languageletter254="顯示/隱藏 對話";		//Show/hide chat
var Languageletter255="顯示/隱藏 螢幕資訊";		//Show/hide HUD
var Languageletter256="複製排行榜";		//Copy leaderboard
var Languageletter257="顯示/隱藏 排行榜";		//Show/hide leaderboard
var Languageletter258="自動縮放切換";		//Toggle auto zoom
var Languageletter259="重設縮放";		//Reset zoom
var Languageletter260="死亡地點切換";		//Toggle death location
var Languageletter261="顯示歷史對話 / 清除對話";		//Show chat history / Clear chat
var Languageletter262="顯示/隱藏 背景座標";		//Show/hide background sectors
var Languageletter263="顯示/隱藏 小機器人";		//Show/hide small bots
var Languageletter264="顯示/隱藏 名字";		//Show/hide names
var Languageletter265="顯示/隱藏 隊友名字";		//Show/hide teammates names
var Languageletter266="顯示/隱藏 質量";		//Show/hide mass
var Languageletter267="顯示/隱藏 小地圖";		//Show/hide minimap
var Languageletter268="輸入對話訊息";		//Enter chat message
var Languageletter269="快速重生";		//Quick respawn
var Languageletter270="自動重生切換";		//Toggle auto respawn
var Languageletter271="縮放程度";		//Zoom level 
var Languageletter271a="語音到文字";		//Voice to text
var Languageletter271b="顯示鬼細胞信息";		//Show ghost cells information
var Languageletter271c="自動玩遊戲";		//Auto Play
var Languageletter272="顯示/隱藏 追蹤目標面板";		//Show/hide targeting panel
var Languageletter273="開始/停止 追蹤目標";		//Start/stop targeting (following)
var Languageletter274="停止追蹤目標";		//Cancel targeting
var Languageletter275="改變追蹤目標";		//Change target
var Languageletter276="在小地圖顯示目標";		//Show target on the minimap
var Languageletter277="顯示/隱藏 任務";		//Show/hide quest
var Languageletter278="在框內按下你要的自訂快速鍵";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="框內按下DELETE鍵可刪除自訂快速鍵";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="可加上CTRL或ALT於快速鍵";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="恢復預設設定";		//Restore default settings
var Languageletter282="儲存設定";		//Save settings
var Languageletter283="關閉";		//Close
var Languageletter284="Youtube 播放";		//Youtube player
var Languageletter284a="Youtube 網址";		// Youtube Url
var Languageletter285="在這裡貼上你的影片/歌單";		//Paste your video/playlist here
var Languageletter286="聲音";		//Sounds
var Languageletter287="訊息提示音";		//Message notification sound
var Languageletter288="指令提示音";		//Command notification sound
var Languageletter289="複製Token/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="服務器";		//Token
var Languageletter290a="排行榜"; //Board
var Languageletter290b="TK&密碼";	//TK&PW (Token and Password)
var Languageletter290c="TK&所有"; //TK&ALL (Token and All)
var Languageletter291="複製";		//Copy


var Languageletter291a="複製榜單(L)";		//Copy Leaderboard (L)
var Languageletter291b="複製令牌/ SIP和密碼"; 	//Copy Token/SIP&Password
var Languageletter291c="複製令牌/ SIP，密碼，排行榜..."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="加入伺服器 (Backspace)";		//Join server (Backspace)
var Languageletter293="切換伺服器 (+)";		//Change server (+)
var Languageletter294="歷史榜單";		//Leaderboard history
var Languageletter295="輸入朋友的 token / IP / leaderboard / name / tag...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="清除列表"; //Clear list
var Languageletter295b="輸入聊天消息..."; //Enter chat message...
var Languageletter298="球隊";		//Team
var Languageletter299="排行榜";		//Leaderbodard
var Languageletter300="通訊";		//Communication
var Languageletter301="消息腳本命令";		//Message Script Commands
var Languageletter302="消息圖標 Imgur";		//Message Imgur Icons
var Languageletter303="留言視頻 Youtube";		//Message Youtube Videos
var Languageletter304="編輯名字";		//Edit names
var Languageletter305="[只限觀戰模式] Binoculars";		//[Spectate Mode Only] Binoculars
var Languageletter306="開始 / 暫停";		//Play / Pause
var Languageletter307="全螢幕";		//Fullscreen
var Languageletter308="旋轉";		//Rotate
var Languageletter309="預設";		//Default
var Languageletter310="倒退";		//Back
var Languageletter311="存起來";		//Save for later
var Languageletter312="地區";		//Region
var Languageletter313="玩家";		//Players
var Languageletter314="伺服器";		//Servers
var Languageletter315="[目標未設定]";		//[Target not set]
var Languageletter316="手動背景";		//Manual background
var Languageletter317="手動訊息圖示及Youtube";		//Manual Message Icons&Youtube
var Languageletter318="對話位置";		//Chat Position
var Languageletter319="Discord Webhook 網址 (for sending TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="排行榜";		//Leaderboard
var Languageletter321="隊友榜";		//Teamboard
var Languageletter322="主畫布";		//Main Canvas
var Languageletter323="主橫幅";		//Main Banner
var Languageletter324="你好團隊！";		//Hello Team!
var Languageletter325="笑到團隊";		//Laugh to Team
var Languageletter326="團隊改名為你的";		//Team Change Name to yours
var Languageletter327="死時自嘲";		//Troll on Death
var Languageletter328="打開 Youtube 音樂";		//Open Youtube Music
var Languageletter329="瘋狂模式 (所有東西都隱藏)";		//Insane mode (Hide Everything)
var Languageletter330="圖片網址以 http:// 或 https:// 開頭";		//Url of image starting with http://... or https://...
var Languageletter331="小地圖圖片網址";		//Minimap Image URL
var Languageletter332="小地圖文字";		//Minimap Text
var Languageletter333="排行榜標題文字";		//Leaderboard Logo Text
var Languageletter333a="排行榜圖片網址";		// Leaderboard Image URL
var Languageletter334="Teamboard 標題文字";		//Teamboard Logo Text
var Languageletter334a="Teamboard 圖片網址";		// Teamboard Image URL
var Languageletter335="Main Canvas 圖片網址";		//Main Canvas Image URL
var Languageletter336="Main Banner Icon 網址";		//Main Banner Icon URL
var Languageletter337="Main Banner Link 網址";		//Main Banner Link URL
var Languageletter338="圖標";		//Icon
var Languageletter339="例";		//e.g
var Languageletter340="要顯示的網址或youtube";		//Url of youtube to be shown
var Languageletter341="重新轉向的網址或連結";		//Url of link to redirect
var Languageletter342="Discord Webhook 網址";		//Discord Webhook Url
var Languageletter342a="對話圖形文字";		//Message Icon Text
var Languageletter342b="Youtube 訊息文字";		//Youtube Message Text
var Languageletter342c="訊息圖片 Imgur 網址";		//Message Icon Imgur Url
var Languageletter342d="Youtube 訊息網址";		//Youtube Message Url
var Languageletter343="必須填寫功能才能工作";		//Must be filled for function to work.
var Languageletter344="第二 Webhook(選用)";		//Secondary Webhook(optional)
var Languageletter345="警告! 設定裡已禁用跳出視窗";		//WARNING! Popups are blocked in the settings.
var Languageletter346="暫時解禁";		//Temporary unblock
var Languageletter347="警告! 設定裡已禁用跳出視窗";		//WARNING! Popups are blocked in the settings.
var Languageletter348="暫時解禁";		//Temporary unblock

var Languageletter349="藥水";	//Potions
var Languageletter350="老皮膚";	//Old Skins
var Languageletter351="特惠"; //Special Deals
var Languageletter352="排行榜"; //Leaderboards
var Languageletter353="新的想法和統計表格"; //New Ideas & Statistics Form
var Languageletter354="視頻皮膚"; //Video Skins
var Languageletter355="迷你腳本"; //Mini Scripts
var Languageletter356="用戶腳本"; //User Scripts
var Languageletter357="語音和相機聊天";	//Voice & Camera Chat
var Languageletter358="請支持Legend mod的開發";	//Please support the development of Legend mod
var Languageletter359="設計暱稱字體";	//Design Nickname Font
var Languageletter360="標記假皮膚";	//Flag the Fake's Skin
var Languageletter361="更多FPS";	//More FPS
var Languageletter362="名稱";	//Name
var Languageletter363="社交ID";	//Social ID
var Languageletter364="展開";	//Expansions
var Languageletter365 = "普遍";	//Universal
var Languageletter366="得分了";	//Score
var Languageletter367="距離";	//Distance
var Languageletter368="總質量";	//Total Mass
var Languageletter369="死";	//Dead

var Premadeletter0="通訊激活"; 		//Communication Activated
var Premadeletter1="無法打開這個youtube網址";		 //Cannot open this youtube URL
var Premadeletter2="名字大於15字無法對話"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="復活節彩蛋 1 啟用"; 		//Easter Egg 1 Activated
var Premadeletter4="復活節彩蛋 2 啟用";		//Easter Egg 2 Activated
var Premadeletter5="復活節彩蛋 3 啟用";		//Easter Egg 3 Activated
var Premadeletter6="視頻在香草上效果更好，參觀：";		//Video works better on vanilla, visit:
var Premadeletter7="筆記:<b>Facebook</b> 兼容性比 <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="筆記:Agar.io 只能連接到 <b>Google Plus</b> 負載事件。 如果發生註銷，請重新加入 Agar.io 或使用 <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="如果卸載事件發生註銷，請從中刪除Chrome Cookies";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="已從伺服器斷線 :(";		//Disconnected from server :(
var Premadeletter11="你IP被鎖了，重開小烏龜換IP吧!";		//You were banned, restart your rooter!
var Premadeletter12="已連線!";		//Connected!
var Premadeletter13="玩";		//PLAY
var Premadeletter14="觀戰";		//SPECTATE
var Premadeletter15="無效的token 或已關服 :(";		//Invalid token or server has closed :(
var Premadeletter16="可以更新到";		//can be Updated to
var Premadeletter17="歡迎回來";			//Welcome back
var Premadeletter18="您的快捷方式區域和其他區域（從上一個選項卡）仍然禁用！ 我們建議您啟用它們。";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="讓他們打開";		//Enable Them
var Premadeletter20="讓他們關閉";		//Keep Them Disabled
var Premadeletter21="搜尋 IP";		//Searching IP
var Premadeletter22="你的隊友";		//Your teammate
var Premadeletter23="要你隱藏全部 (排行榜及小地圖)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="接受";		//Accept
var Premadeletter25="別想!";		//NO WAY!
var Premadeletter26="要你將名字變更成";		//wants you to change your name to
var Premadeletter27="要你開啟死時自嘲";		//wants you to hide Enable Troll on death
var Premadeletter28="要你開啟 Youtube 撥放器";			//wants you to open Youtube Player
var Premadeletter29="已找到排行榜";		//Leaderboard found
var Premadeletter30="搜尋";		//Search
var Premadeletter31="排行榜找不到，繼續嘗試...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="搜尋已取消";		//Search was canceled
var Premadeletter33="隊友不可看到你";		//You are invisible to Team / Clan
var Premadeletter34="隊友已可看到你";		//You are visible to Team / Clan
var Premadeletter35="隱藏/顯示 的功能只能於正在遊戲時使用";			//Hide/Show can be used only while playing
var Premadeletter36="這是不對的 Discord Webhook 網址";		//This is not valid Discord Webhook address
var Premadeletter37="伺服器已鎖定";		//Server is locked
var Premadeletter38="你必須用觀戰模式";		//You must be on spectate mode
var Premadeletter39="為避免濫用，你必須在遊戲中且使用密碼";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="自動打開 Youtube";		//Auto Youtube On
var Premadeletter41="自動關閉 Youtube";		//Auto Youtube Off
var Premadeletter42="顯示快捷鍵";		//Show Shortcuts
var Premadeletter43="隱藏快捷鍵";		//Hide Shortcuts
var Premadeletter44="顯示 XP BAR";		//Show XP BAR
var Premadeletter45="隱藏 XP BAR";		//Hide XP BAR
var Premadeletter45a = "圓角 Hud"; //Rounded Hud
var Premadeletter45b = "廣場 Hud"; //Square Hud
var Premadeletter46 = "大膽的顏色"; //Linear color Hud
var Premadeletter47 = "線性色調"; //Bold color Hud

var Premadeletter48="顯示全部";		//Show Everything
var Premadeletter49="隱藏全部g";		//Hide Everything
var Premadeletter50="顯示時間統計";		//Show Timer Calc.
var Premadeletter51="隱藏時間統計"		//Hide Timer Calc.

var Premadeletter53="自動免費金幣";		//Auto free coins
var Premadeletter54="停止免費金幣s";		//Stop free coins
var Premadeletter55="巨魔死亡";		//Troll on Death
var Premadeletter56="沒有巨魔死亡";		//No troll on Death

var Premadeletter57="通訊";		//Communication
var Premadeletter58="隱藏";		//Hidden
var Premadeletter59="可見";		//Visible
var Premadeletter60="暫停";		//Pause

var Premadeletter61 = "啟用YouTube作為背景";	//Enable YT as background
var Premadeletter62 = "禁用YouTube作為背景";	//Disable YT as background";
var Premadeletter63 = "希望你打開網址";	//wants you to open the url
var Premadeletter64 = "希望您嵌入並播放此YouTube視頻";	//wants you to embed and play this youtube video
var Premadeletter65 = "希望您加入以下Skype客房";	//wants you to join the following Skype room
var Premadeletter66 = "希望你加入以下Discord會議室";	//wants you to join the following Discord room
var Premadeletter67 = "希望你離開這台服務器並加入這個新服務器";	//wants you to leave this server and join this new one

var Premadeletter68 = "你按下了"; //You pressed
var Premadeletter69 = "如果重啟"; //restart if
var Premadeletter70 = "滴劑"; //drops
var Premadeletter71 = "動畫皮膚"; //Animated skins
var Premadeletter72 = "啟用"; //enabled
var Premadeletter73 = "下降"; //drop
var Premadeletter74 = "什麼時候"; //when
var Premadeletter75 = "動畫皮膚將會"; //Animated skins will be
var Premadeletter76 = "殘"; //disabled
var Premadeletter77 = "重新加入後"; //after rejoin
var Premadeletter78 = "更好的FPS"; //Better FPS
var Premadeletter79 = "表演時16"; //performance when 16
var Premadeletter80 = "當死光擴張啟用時，死亡巨魔不會發生"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "私人服務器"; //Private Server
var Premadeletter82 = "連接到任何"; //Connect to any
var Premadeletter83 = "服務器，或製作你自己的"; //server, or make your own
var Premadeletter84 = "如果你知道服務器的IP，那麼玩類似agario的遊戲"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "您的圖片已被複製到剪貼板。 粘貼它"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "自定義皮膚網址區域"; //to custom skin Url area
var Premadeletter87 = "您必須登錄才能使用您的個人資料圖片"; //You must Login to use picture of your profile
var Premadeletter88 = "您正在使用錯誤的版本"; //You are using a wrong version
var Premadeletter89 = "遊戲現在將終止"; //Game will terminate now
var Premadeletter90 = "特惠"; //Special Deals
var Premadeletter91 = "Agario可能會也可能不會給你皮膚，但只有硬幣"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "使用風險自負"; //Use at your own risk
var Premadeletter92 = "如果你的朋友的UID錯誤，購買將失敗"; //If friend's UID is wrong, purchase will fail
var Premadeletter93 = "UID出廠設置"; //UID Factory Settings
var Premadeletter94 = "您必須登錄才能加載特惠"; //You must login to load Special Deals
var Premadeletter95 = "假圖像已被複製到剪貼板。 粘貼它"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "自定義皮膚網址區域以激活假標誌功能"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "當您完成Recaptcha時通知我"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "我完成了"; //I have finished
var Premadeletter99 = "沒關係"; //Never Mind
var Premadeletter100 = "計算您的XP，請稍候..."; //Calculating your XP, please wait...
var Premadeletter101 = "做"; //Do
var Premadeletter102 = "不"; //NOT
var Premadeletter103 = "按"; //press
var Premadeletter104 = "清除自定義皮膚網址"; //Erase custom skin URL
var Premadeletter105 = "選擇視頻皮膚";	//select video skin
var Premadeletter106 = "取消選擇視頻皮膚"; //unselect video skin
var Premadeletter107 = "靜音"; //mute audio
var Premadeletter108 = "LM項目"; //The LM Project
var Premadeletter109 = "上傳"; //Upload 
var Premadeletter109a = "下載"; //Download
var Premadeletter109b = "載入中"; //Load

var Premadeletter110 = "除非你知道它是什麼，否則不要在這裡輸入任何內容";	//do not enter anything here unless you know what it is
var Premadeletter111 = "點擊橙色圖標購買"; //click on the orange icon to buy
var Premadeletter112 = "對於某些付款方式"; //For some payment methods
var Premadeletter113 = "關";	//Close
var Premadeletter114 = "複製"; //COPY	
var Premadeletter115 = "用於為您的朋友購買優惠"; //is used to buy offers for your friends
var Premadeletter116 = "要進行購買，您必須登錄到您的帳戶..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "圖書館"; //Library
var Premadeletter118 = "訪問"; //visit
var Premadeletter119 = "報告為假（更換皮膚）"; //Report as Fake (change Skin)
var Premadeletter120 = "輸入您的玩家的真實姓名"; //Enter your EXACT name of the player
var Premadeletter121 = "濫用玩家和不恰當的使用會導致用戶的UID"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "永久禁止使用此擴展程序"; //to permanent ban from usage of this extension
var Premadeletter128 = "需要用戶登錄"; //User login needed
var Premadeletter129 = "設置已成功上傳"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "服務器"; //SERVER
var Premadeletter124 = "避免使用超過6分鐘的視頻皮膚"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "地圖已修復"; //Map fixed
var Premadeletter126 = "登錄到"; //Logged in to
var Premadeletter127 = "登出"; //Logged out
var Premadeletter130 = "總"; //Total
var Premadeletter131 = "新"; //NEW
var Premadeletter132 = "加入吧"; //Join Back
var Premadeletter133 = "連接到您播放的最後一個IP"; //Connect to last IP you played
var Premadeletter134 = "北美"; //North America
var Premadeletter135 = "南美洲"; //South America
var Premadeletter136 = "歐洲"; //Europe
var Premadeletter137 = "俄國"; //Russia
var Premadeletter138 = "土耳其"; //Turkey
var Premadeletter139 = "東亞"; //East Asia
var Premadeletter139a = "中國"; //China
var Premadeletter140 = "大洋洲"; //Oceania
var Premadeletter140a = " -- 選擇一個地區 -- "; // -- Select a Region -- 
var Premadeletter141 = "自由"; //FFA
var Premadeletter142 = "戰斗羅伊爾"; //Battle Royale
var Premadeletter143 = "小組"; //Teams
var Premadeletter144 = "試驗"; //Experimental
var Premadeletter145 = "黨"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "語言"; //LANGUAGES
var Externalletter0b = "選擇一種語言"; //Choose a language
var Externalletter0c = "重新啟動後，更改將完全發生"; //Changes will take place completely after the restart
var Externalletter1 = "信息"; //INFORMATION
var Externalletter2 = "模板"; //TEMPLATES
var Externalletter3 = "手冊模板"; //MANUAL TEMPLATES
var Externalletter4 = "選擇你的模板"; //Choose your template
var Externalletter5 = "或者選擇一個擴展"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "向開發者發送代碼"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "將你的腳本粘貼到這個Textarea中，你可以加載多個腳本"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "從Textarea加載腳本"; //Load Script from Textarea
var Externalletter8 = "選擇"; //Choose
var Externalletter9 = "擦除腳本"; //Erase Script
var Externalletter10 = "名稱"; //Name
var Externalletter11 = "Raw Github的Url或其他原始腳本"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "如果腳本未從URL導入，請將其保留為空"; //Leave this empty if script not imported from URL
var Externalletter13 = "重要提示：不要使URL不起作用，因為它們被用作加載事件。 如果Scenario損壞了加載事件，則刪除COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
