/*         var Languageletter =         "مرحبا بك" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="صفحة البداية";  //Home      ->    var Languageletter0="المُهِمة";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                             شُكراَ لِدعَمَك لِمُوُد ليجاند للَعِبة أجَاريُو
Thank you for supporting Legend Agar.io mod                                                             */



var translator="غير معروف";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="صفحة البداية";		//Home
var Languageletter1="المستخدم";		//User
var Languageletter2="الاعدادات";		//Settings
var Languageletter3="الثيم";		//Theme
var Languageletter4="أزرار الاختصار";		//Hotkeys
var Languageletter5="الصوت واليوتيوب";		//Youtube & Sounds
var Languageletter6="الادوَات";		//Tools
var Languageletter7="اتركها فارغه لتري العامه, او ضع الباسوورد الخاصة بالكلان, او استخدمها كتاج";		//Password/Tag
var Languageletter7a="التاج/الباسوورد"	;	//Password/Tag
var Languageletter8="ادخل اسمك باللعبة, يُمكنك استخدام 50 رمز سيراها فقط مستخدمي المود, باستخدامك 15 حرف باسمك يري اسمك الجميع"		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="الاسم";		//Name
var Languageletter9="أدخل عنوان الاسِكن الذي ترغب باستخدامه";		//Insert your manual skin weblink
var Languageletter9a="عنوان مُباشر للاسِكن";		//Manual direct skin URL
var Languageletter10="منطقةاللعب ";		//The region to play
var Languageletter11="وضع اللعب";		//The mode to play
var Languageletter12="اتصل بالسيرفر ، أو قم بإعادة الاتصال";		//Connect to server, or restablish communication
var Languageletter12a="إتصل";		//Connect
var Languageletter13="شارك";		//Join
var Languageletter14="العب كضيف";		//Play as guest
var Languageletter15="سجل الدخول والعب";		//Login and Play
var Languageletter16="بث حي للاول";		//Spectate
var Languageletter17="سجل دخول بالفيسبوك";		//Sign in with Facebook
var Languageletter18="سجل بحساب جوجل";			//Sign in with Google
var Languageletter19="بدء اللعب";		//Play
var Languageletter20="التسوق"	;		//Shop
var Languageletter21="كوين مجانية";		//Free Coins
var Languageletter22="هدايا";		//Gifts
var Languageletter23=" المهام اليومية ";			//Daily Quests
var Languageletter24="الاسكنات";		//Skins
var Languageletter25="االفيديو الترويجي لليجاند مود";		//Legend Promo Video
var Languageletter25a="نموذج الأفكار والإحصاءات الجديدة";		//Legend Promo Video
var Languageletter25b=" معلومات المود والقوالب الجاهزة";		//Mod Info & Templates
var Languageletter26="اضف سكنات";		//Add skins
var Languageletter26a="نسخ الخادم ، كلمة المرور ، لوحة الفريق و لوح المتصدرين"; //Copy Server, Password, Teamboard & Leaderboard
var Premadeletter27="يريد منك تمكين ترول عند الموت";		//wants you to hide Enable Troll on death
var Premadeletter28="يريد منك فتح مشغل Youtube";			//wants you to open Youtube Player
var Premadeletter29="وجدت قائمة الأوائل";		//Leaderboard found
var Premadeletter30="بحث";		//Search
var Languageletter31="تسجيل الخروج";		//Logout
var Languageletter32="الوقت المستخدم";		//Times Used
var Languageletter33="ليجاند مود بواسطة :";		//Legend Mod by
var Languageletter34="ترجمه لكم أخوكم: هاني الجو هري  من مصر";		//Translation by
var Languageletter35=" نسخ اسماء المتصدرين. (اضغَط xللإلغاء أو الظهور)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="الانيمشن";		//Animation
var Languageletter37="تأخير الرسوم المتحركة";		//Animation delay
var Languageletter37a="زووم تلقائى";		// Auto zoom
var Languageletter37b="الزووم";		// Zoom
var Languageletter38="سرعة الزووم:";		//Zoom speed: 
var Languageletter39="إعادة البدء";			//Respawn
var Languageletter40="بدء اللعب بمجرد الموت";		//Auto respawn 
var Languageletter41="زر اختصار بالبدء التلقائي";			//Quick respawn (hotkey) 
var Languageletter41a="بدء تأثير خاص عند بدء اللعب";			//Spawn special effects 
var Languageletter41b="مؤقت لدمج الخلايا";			//Merge timer off
var Languageletter41c="يقترح أن يكون مفعلا لتقليل اللاج";			//Suggested to be enabled for Lag reduce
var Languageletter41d="صوت عند تعبئة الفيرس";			//Virus shot sound

var Languageletter42="الأسماء";			//Names
var Languageletter43="بدون أسماء";		//No names 
var Languageletter44="تحسين الأسماء";		//Optimized names 
var Languageletter45="اخفاء تلقائي للاسماء";		//Auto hide names 
var Languageletter46="اخفاء إسمي";		//Hide my name 
var Languageletter47="إخفاء اسماء الفريق";		//Hide teammates names 
var Languageletter48="تغليظ الأسماء";		//Names stroke 
var Languageletter49="الماس";		//Mass
var Languageletter50="إظهار الماس";		//Show mass 
var Languageletter51="تحسين الماس (+/-2%)"	;	//Optimized mass (+/-2%) 
var Languageletter52="اخفاء تلقائي للماس";			//Auto hide mass 
var Languageletter53="أخفاء الماس الخاص  بي";		//Hide my mass 
var Languageletter54="إخفاء الماس الخاص بالاعداء";		//Hide enemies mass 
var Languageletter55="اختصار الماس";		//Short mass
var Languageletter56="تسديدات الفيرس";		//Virus shots 
var Languageletter57="تغليظ الماس";		//Mass stroke 
var Languageletter58="الاسكنات";		//Skins
var Languageletter59="إخفاء الاسكنات ";		//No skins 
var Languageletter60="سكنات مخصصة";		//Custom skins 
var Languageletter61="سكنات اجاريو الاصلية ";		//Vanilla skins 
var Languageletter61a="فيزياء جيلي";		//Jelly physics 
var Languageletter61b="سكنات الفيديو";		//Video skins
var Languageletter61c="تفعيل صوت فيديو  الاخرين عند تواجد كلاكما بسى3";		//Sound from other\'s Video skins when both C3

var Languageletter62="تحسين نقاط الماس";		//Optimized food 
var Languageletter6a2="نقاط الماس ";		//Food 
var Languageletter63="اخفاء تلقائي لنقاط الماس";		//Auto hide food (mass) 
var Languageletter64="اخفاء تلقائي لنقاط الماس(الزووم)";		//Auto hide food (zoom) 
var Languageletter65="نقاط الماس بلون قوس قزح";		//Rainbow food 
var Languageletter66="الشفافية/الالوان";		//Transparency / colors
var Languageletter67="بدون لون";		//No colors 
var Languageletter68="الواني المخصصة";		//My custom color 
var Languageletter69="سكناتى الشفافة";		//My transparent skin 
var Languageletter70="شفافية الاسكنات";		//Transparent skins 
var Languageletter70a="شفافية الخلايا"; //Transparent cells 
var Languageletter71="شفافية الفيروسات";		//Transparent viruses 
var Languageletter71a="توهج الفيروس";		//Virus Glow
var Languageletter71b="ألوان قوس قزح متحركة";		//Animated rainbow colors

var Languageletter72="الشبكة/القطاعات";		//Grid / sectors
var Languageletter73="اظهر الخطوط الشبكية";		//Show grid 
var Languageletter74="أظهر اسماءالقطاعات ";		//Show background sectors 
var Languageletter75="اظهر حدود الخريطة";		//Show map borders 
var Languageletter75a="توهج الحدود";		//Border Glow

var Languageletter76="المحادثة";		//Chat
var Languageletter77="أيقاف المحادثة";		//Disable chat 
var Languageletter78="أصوات الاخطارات";		//Sound notifications 
var Languageletter79=" التعبيرات الانفعالية ";		//Emoticons 
var Languageletter80="اظهار الصور بالمحادثة";		//Show images on chat 
var Languageletter81="إاظهار الفيديو بالمحادثة";		//Show videos on chat 
var Languageletter82="اظهار صندوق المحادثة";		//Chatbox instead of popups 
var Languageletter82a="الخريطة المصغرة"; //minimap
var Languageletter82b="عرض الخريطة المصغرة"; //show minimap
var Languageletter82c="عرض شبكة الخريطة المصغرة"; //show minimap grid
var Languageletter82d="إظهار أدلة الخريطة المصغرة";		//Show minimap guides 
var Languageletter82e="لون واحد للفريق";		//One-colored teammates 
var Languageletter82f="عرض أدلة خرائط مصغرة إضافية";		//Show extra minimap guides
var Languageletter82g="إظهار الخلايا الشبح";		//Show ghost cells

var Languageletter83="أدوات مساعدة";		//Helpers
var Languageletter84="تغير لون سكن العدو ";		//Opponents colors
var Languageletter85="دوائر حول الخصم";		//Opponents rings 
var Languageletter86="الوان الفيروس";		//Viruses colors 
var Languageletter87="نطاق الانقسام";		//Split range 
var Languageletter87a="نطاق الدابل سبليت";		//Quick double split range
var Languageletter87b="نطاق الدابل سبليت  البطىء";		//Slow double split range

var Languageletter88="نطاق الفيروس";		//Viruses range 
var Languageletter89="تتتبع مؤشر الفارة";		//Cursor tracking 
var Languageletter90="اشارات لأعضاء الفريق";		//Teammates indicators 
var Languageletter90a="خلايا الأشباح";		//Ghost cells

var Languageletter91="التحكم بالماوس";		//Mouse control
var Languageletter92="الانقسام بالماوس";		//LMB - Mouse split 
var Languageletter93="أخراج الماس بالماوس";		//RMB - Mouse feed 
var Languageletter94="تبديل ازرارالماوس";		//Invert mouse buttons 
var Languageletter94a="Hud";		// HUD
var Languageletter95="الفريق";		//Team
var Languageletter96="إظهار المُستهدف";		//Show targeting 
var Languageletter96a="أظهار ماس الأوائل";		//Show leaderboard mass

var Languageletter97="قائمةالاوائل بالمنتصف";		//Centered leaderboard 
var Languageletter97a="جعل قائمة الأوائل بالأعلي";		//\"Leaderboard\" header 

var Languageletter98="احصائيات اللعبة بالاعلي";		//Game stats at the top 
var Languageletter98a="سكنات بقائمة الفريق";		//Skins on teamboard


var Languageletter99="الاحصائيات";		//Stats
var Languageletter100="اظهار احصائيات اللعبة";		//Show game stats 
var Languageletter101="احصائيات اللعبة";		//Game stats
//the \' is needed
var Languageletter102="العدو/الاعداء";		//Enemy\'s 		
var Languageletter103="لنا";		//Our
var Languageletter104="الحد الأدني لماس الشريك لخدعة التريك سبليت";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="الحد الأقصي لماس العدو لخدعة البريسبليت";		//Maximal enemy\'s mass for presplit 
var Languageletter105="اظهار الوقت الحالي";		//Show current time 
var Languageletter106=" اضافات ";		//Extras
var Languageletter107="تجاهل الاحصائيات بعد الموت";		//Skip stats after death 
var Languageletter108="اظهار المهام";		//Show quest
var Languageletter108a="الاصوات باللعبة"; //Game Sounds
var Languageletter108b="أصوات القائمة"; //Menu Sounds
var Languageletter109="حظر النوافذالمزعجة والاعلانات";		//Block popups (ads/shop/quest) 
var Languageletter109a="صوت"; //Voice
var Languageletter109b="صوت البادئة"; //Voice-Prefix
var Languageletter109c="صوت اللغة"; //Voice-language
var Languageletter109d="إلغاء الإيقاف المؤقت"; //UnPause

var Languageletter110="—جودة الجرافيك--";		//-- Graphics Quality --
var Languageletter111="جرافيك: Retina";		//Graphics: Retina
var Languageletter112="جرافيك:عالي";		//Graphics: High
var Languageletter113="جرافيك :متوسط";		//Graphics: Medium"
var Languageletter114="جرافيك :منخفض";		//Graphics: Low
var Languageletter115="جرافيك منخفض جدا ";		//Graphics: Very Low
var Languageletter116="تصدير/استيرادالاعدادات";		//Export / import settings
var Languageletter117="إعداد ضبط المصنع :) ";		//Restore default settings
var Languageletter118="تصدير الاعدادات";		//Export settings
var Languageletter119="استيراد الاعدادات";		//Import settings
var Languageletter120="لتصدير الاعدادات المختارة انسخ الكود بالاسفل واحفظه في ملف نصي.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="لاستيراد الاعدادات المختارة قم بلصق  الكود الذي تم تصديره مسبقا بالاسفل";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="الاوامر";		// Commands
var Languageletter123="الاختصارات";		// Hotkeys
var Languageletter124="البروفايل";		// Profiles
var Languageletter125="الاعدادات";		// Settings
var Languageletter126="الثيم";		// Theme
var Languageletter127="تصدير الاعدادات";		//Export settings
var Languageletter128="استيراد الاعدادات";		//Import settings
var Languageletter129="الثيمات الأساسية";		//Basic theming
var Languageletter130="القائمة";		//Menu
var Languageletter131="Hud";		//HUD
var Languageletter132="المحادثة";		//Chat
var Languageletter133="الخريطة المصغرة";		//Minimap
var Languageletter134="الجرافيك /المؤشرات";		//Graphics / cursors
var Languageletter135="الثيم الافتراضية";		//Theme preset
var Languageletter136="إعداد ليجاند الإفتراضية";		//Legend Original
var Languageletter137="الاستايل المجنون";		//Crazy Style 1
var Languageletter139="الخلفية";		//Background
var Languageletter140="حدود الخريطة";		//Map borders
var Languageletter141="الخطوط الشبكية";		//Grid
var Languageletter142="خط أسماء القطاعات";		//Sectors font
var Languageletter143="الأسماء";		//Names
var Languageletter144="تغليظ الأسماء";		//Names stroke
var Languageletter145="الماس";		//Mass
var Languageletter146="تغليظ الماس";		//Mass stroke
var Languageletter147="تغليظ الفيروس";		//Virus stroke
var Languageletter148="الفيروسات";		//Virus
var Languageletter148a="الخلية الأم";		//Mothercell
var Languageletter148b="السكتة الدماغية الخلية الأم";		//Mothercell stroke
var Languageletter149="الماس";		//Food
var Languageletter150="مؤشر لأعضاء الفريق";		//Teammate indicator
var Languageletter151="تتبع مؤشر الماوس";		//Cursor tracking
var Languageletter152="نطاق الانقسام";		//Split range
var Languageletter153="خط الاسماء";		//Names font
var Languageletter154="خط كمية الماس";		//Mass font
var Languageletter154a="أكبر";		//Bigger
var Languageletter154b="الأصغر";		//Smaller
var Languageletter155="خط أسماء القطاعات";		//Sectors font
var Languageletter157="حجم خط أسماء القطاعات";		//Sectors font size
var Languageletter158="مقياس الاسماء";		//Names scale
var Languageletter159="مقياس الماس";		//Mass scale
var Languageletter160="مقياس ماس الفيروسات";		//Virus mass scale
var Languageletter161="مقياس تغليظ الخط";		//Text stroke scale
var Languageletter162="حجم نقاط الماس";		//Food size: 
var Languageletter163="تغليظ حجم الفيروسات";		//Virus stroke size
var Languageletter164="عرض حدودالخريطة";		//Map borders width
var Languageletter165="عرض خطوط القطاعات";		//Sectors grid width
var Languageletter166="شفافية الخلايا";		//Cells transparency
var Languageletter167="شفافية الأسكنات";		//Skins transparency
var Languageletter168="شفافية الاسكنات";		//Virus transparency
var Languageletter169="شفافية الماس والاسماء";		//Names & mass transparency
var Languageletter170="استعادة ضبط المصنع للثيم";		//Restore theme default settings
var Languageletter171="حفظ الاعدادات";		//Save settings
var Languageletter172="قائمة الثيم ";		//Menu theme
var Languageletter173="الخلفية";		//Background
var Languageletter174="الشفافية";		//Transparency
var Languageletter175="اللون الأساسي";		//Main color
var Languageletter176="زر الكتابة";		//Button text
var Languageletter177="التحكم";		//Panel
var Languageletter179="خط التحكم";		//Panel text
var Languageletter181="الزِر";		//Button
var Languageletter189="صورة لوحة التحكم";		//Panel background image
var Languageletter190="عنوان الصورة	";		//Image URL
var Languageletter191="اللون الأساسي";		//Main color
var Languageletter192="الخلفية";		//Background
var Languageletter193="النص";		//Text
var Languageletter194="احصائيات";		//Stats
var Languageletter195="الوقت";		//Time
var Languageletter196="أعلي 5 بالماس";		//Top 5 mass
var Languageletter197="قائمة الأوائل";		//Leaderboard - me
var Languageletter198="قائمة الاوائل للفريق";		//Leaderboard - teammate
var Languageletter199="خط الـ Hud";		//HUD font
var Languageletter200="مقياس الـ Hud";		//HUD scale: 
var Languageletter201="خلفية الرسالة";		//Message background
var Languageletter202="نص الرسالة";		//Message text
var Languageletter203="وقت الرسالة";		//Message time
var Languageletter204="حالة الرسالة";		//Message nick
var Languageletter205="أوامر الخلفية";		//Command background
var Languageletter206="نص الأوامر	";		//Command text
var Languageletter207="وقت الأمر";		//Command time
var Languageletter208="حالة الأمر";		//Command nick
var Languageletter209="لون صندوق المحادثة";		//Chatbox color
var Languageletter210="مقياس المحادثة";		//Chat scale
var Languageletter211="القطاعات";		//Sectors
var Languageletter212="القطاع الحالي";		//Current sector
var Languageletter213="الأسم";		//Nick
var Languageletter214="Nick stroke";		//Nick stroke
var Languageletter215="خليتى";		//My cell
var Languageletter216="My cell Storke ";		//My cell stroke
var Languageletter217="الفريق";		//Teammates
var Languageletter218="مكان الموت الأخير";		//Death location
var Languageletter219="دليل الارشاد";		//Guides
var Languageletter220="خط الخريطة المصغرة";		//Minimap font
var Languageletter221="خط الاسم";		//Nick font
var Languageletter222="عرض الخريطة المصغرة";		//Minimap width
var Languageletter223="شفافية القطاعات	";		//Sectors transparency
var Languageletter224="ححم الاسم";		//Nick size
var Languageletter225="//Nick stroke size";		//Nick stroke size
var Languageletter226="حجم خليتى";		//My cell size
var Languageletter227="My cell stroke size";		//My cell stroke size
var Languageletter228="حجم الفريق";		//Teammates size
var Languageletter229="اختيار صورة الخلفية";		//Custom background image
var Languageletter230="اختيار صورة المؤشرات";		//Custom cursor image
var Languageletter231="ععنوان الصورة";		//Image URL
var Languageletter232="عنوان صورة المؤشرات";		//Cursor image URL
var Languageletter233="اخراج الماس";		//Feed
var Languageletter234=" اخراج سريع للماس";		//Macro feed
var Languageletter235="انقسم";		//Split
var Languageletter236="دبل سبليت";		//Double split
var Languageletter237="بوب سبليت";		//Popsplit
var Languageletter238="انقسم 16";		//Split 16
var Languageletter239="ايقاف حركة الخلية";		//Cell pause
var Languageletter240="اظهار/اخفاء أعلي خمسة بالفريق	 ";		//Show/hide team top 5
var Languageletter241="اظهار/اخفاء الوقت";		//Show/hide current time
var Languageletter242="اظهار/اخفاء نطاق الانقسام";		//Show/hide split range"
var Languageletter243="اظهار/اخفاءمؤشرات الفريق";		//Show/hide teammates indicators
var Languageletter244="اظهار/اخفاءمؤشرات الانقسام";		//Show/hide split indicators
var Languageletter245="اظهار/اخفاء الوان الخصم";		//Show/hide opponents colors
var Languageletter246="تبديل الاسكنات (اجاريو الاصلية/مخصصة)";		//Toggle skins (custom/default)
var Languageletter247="التبديل بالاسكنات الشفافة";		//Toggle transparent skins
var Languageletter248="اظهار/اخفاءالاسكنات";		//Show/hide skins
var Languageletter249=" اظهار/اخفاء احصائيات اللعبة ";		//Show/hide game stats
var Languageletter250="تبديل خلاياك (الصغيرة/الكبيرة)";		//Toggle own cells (smallest/biggest)
var Languageletter251="اظهار/اخفاء نقاط الماس";		//Show/hide food
var Languageletter252="اظهار/اخفاء الخطوط الشبكية ";		//Show/hide grid
var Languageletter253="اظهار/اخفاء الخريطة المصغرة";		//Show/hide minimap guides
var Languageletter254="اظهار/اخفاء المحادثة";		//Show/hide chat
var Languageletter255="اظهار/اخفاء(Hud)";		//Show/hide HUD
var Languageletter256="نسخ اسماء اوائل السيرفر ";		//Copy leaderboard
var Languageletter257="اظهار/اخفاء قائمة الاوائل";		//Show/hide leaderboard
var Languageletter258="تبديل الزووم التلقائي";		//Toggle auto zoom
var Languageletter259="استعادة الضبط الافتراضي للزووم";		//Reset zoom
var Languageletter260="تبديل موقع الموت";		//Toggle death location
var Languageletter261=" اظهار أو مسح المحادثات";		//Show chat history / Clear chat
var Languageletter262="اظهار/اخفاء خلفيات القطاعات	";		//Show/hide background sectors
var Languageletter263="اظهار/اخفاء البووت الصغيرة";		//Show/hide small bots
var Languageletter264="اظهار/اخفاء الاسماء";		//Show/hide names
var Languageletter265=" اظهار/اخفاء اسماء الفريق ";		//Show/hide teammates names
var Languageletter266="اظهار/اخفاء الماس";		//Show/hide mass
var Languageletter267="اظهار/اخفاء الخريطة المصغرة";		//Show/hide minimap
var Languageletter268="اكتب رسالة المحادثة";		//Enter chat message
var Languageletter269="بدء سريع للعب";		//Quick respawn
var Languageletter270="تبديل اعادة البدء تلقائيا";		//Toggle auto respawn
var Languageletter271="مستوي الزووم";		//Zoom level 
var Languageletter271a="صوت إلى نص";		//Voice to text
var Languageletter271b="إظهار معلومات خلايا الأشباح";		//Show ghost cells information
var Languageletter271c="تحكم تلقائي بالخليةبدون";		//Auto Play
var Languageletter272="اظهار/اخفاء تحكم المستهدف";		//Show/hide targeting panel
var Languageletter273="بداية / إيقاف الاستهداف (متابعة)";		//Start/stop targeting (following)
var Languageletter274="إلغاء الاستهداف";		//Cancel targeting
var Languageletter275="تغيير الهدف";		//Change target
var Languageletter276="عرض الهدف على الخريطة الصغيرة";		//Show target on the minimap
var Languageletter277="اظهار/اخفاءالمهمة اليومية";		//Show/hide quest
var Languageletter278=" لتعيين مفتاح التشغيل السريع انقر على حقل الإدخال واضغط على المفتاح الذي اخترته.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279=" لحذف مفتاح التشغيل السريع انقر على حقل الإدخال واضغط على المفتاح ديليت.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="مجموعات المفاتيح الممكنة مع مفاتيح CTRL و ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="ضبط المصنع :)";		//Restore default settings
var Languageletter282="حفظ الإعدادات";		//Save settings
var Languageletter283="إغلاق";		//Close
var Languageletter284="مشغل اليوتيوب";		//Youtube player
var Languageletter284a="عنوان اليوتيوب";		// Youtube Url
var Languageletter285="انسخ عنوان الفيديو هنا";		//Paste your video/playlist here
var Languageletter286="الأصوات";		//Sounds
var Languageletter287="صوت اخطارات الرسالة";		//Message notification sound
var Languageletter288="صوت اخطارات  الامر";		//Command notification sound
var Languageletter289="نسخ السيرفر ";		//Copy Token/SIP
//keep this small
var Languageletter290="السيرفر";		//Token
var Languageletter290a="قائمة "; //Board
var Languageletter290b="سيرفر&PW";	//TK&PW (Token and Password)
var Languageletter290c="نسخ الكل"; //TK&ALL (Token and All)
var Languageletter291="نسخ";		//Copy
var Languageletter291a="نسخ الأوائل";		//Copy Leaderboard (L)
var Languageletter291b="نسخ رمز / سيب وكلمة المرور"; 	//Copy Token/SIP&Password
var Languageletter291c="نسخ الجميع"; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="انضم للسيرفر(Backspace)";		//Join server (Backspace)
var Languageletter293="تغير السيرفر (+)";		//Change server (+)
var Languageletter294="سجل قائمة الاوائل";		//Leaderboard history
var Languageletter295="أبحث باسم صديق او ايبي أو شعار كلان...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="محو القائمة"; //Clear list
var Languageletter295b="أدخل رسالة الدردشة..."; //Enter chat message...
var Languageletter298="أوائل الفريق";		//Team top 
var Languageletter299="قائمة الأوائل";		//Leaderbodard
var Languageletter300=" الاتصالات ";		//Communication
var Languageletter301="اوامر نص الرسالة";		//Message Script Commands
var Languageletter302="أيقونات صور الرسالة";		//Message Imgur Icons
var Languageletter303="فيديو يوتيوب الرسالة";		//Message Youtube Videos
var Languageletter304="تعديل الأسماء";		//Edit names
var Languageletter305="[وضع التصفح فقط]";		//[Spectate Mode Only] Binoculars
var Languageletter306="العب/توقف";		//Play / Pause
var Languageletter307="ملء الشاشة";		//Fullscreen
var Languageletter308="استدارة";		//Rotate
var Languageletter309="اعتيادي";		//Default
var Languageletter310="الخلف";		//Back
var Languageletter311="حفظ لوقت لاحق ";		//Save for later
var Languageletter312="منطقة اللعب";		//Region
var Languageletter313="اللاعبين";		//Players
var Languageletter314="السيرفرات";		//Servers
var Languageletter315="[لم يتم تعيين الهدف]";		//[Target not set]
var Languageletter316="دليل صورة الخلفية";		//Manual background
var Languageletter317="دليل رسالة الايقونات واليوتيوب";		//Manual Message Icons&Youtube
var Languageletter318="مكان صندوق المحادثة";		//Chat Position
var Languageletter319="Discord Webhook Url (لإرسال رمز TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="الأوائل ";		//Leaderboard
var Languageletter321="الفريق";		//Teamboard
var Languageletter322="قماش الرئيسي";		//Main Canvas
var Languageletter323="بانر الرئيسي";		//Main Banner
var Languageletter324="مرحبا بالفرييق!";		//Hello Team!
var Languageletter325="اضحك على الفريق";		//Laugh to Team
var Languageletter326="ارسال دعوة للفريق لتغير اسمهم كأسمي";		//Team Change Name to yours
var Languageletter327=" العزاء عند الموت";		//Troll on Death
var Languageletter328="تشغيل موسيقي يوتيوب";		//Open Youtube Music
var Languageletter329="Insane mode (إخفاء كل شىء)";		//Insane mode (Hide Everything)
var Languageletter330="عنوان الصورة يبدأ بـ http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="عِنوان صُورة الخَرِيطَة المُصَغَرة";		//Minimap Image URL
var Languageletter332="خَط الخَرِيطَة المُصَغَرة";		//Minimap Text
var Languageletter333="نص لوجو قائمةالأوائل";		//Leaderboard Logo Text
var Languageletter333a="عنوان صورة قائمةالاوائل";		// Leaderboard Image URL
var Languageletter334="نص قائمة الأوائل";		//Teamboard Logo Text
var Languageletter334a="عنوان صورة قائمة الفريق";		// Teamboard Image URL
var Languageletter335="العنوان الرئيسي لصورة (Canvas)";		//Main Canvas Image URL
var Languageletter336="عنوان أيقونة بانر الرئيسي";		//Main Banner Icon URL
var Languageletter337="رابط رابط العنوان الرئيسي";		//Main Banner Link URL
var Languageletter338="أَيقونة";		//Icon
var Languageletter339="علي سبيل المثال";		//e.g
var Languageletter340="عنوان الفيديو المطلوب عرضه";		//Url of youtube to be shown
var Languageletter341="عنوان اللينك المطلوب التحويل اليه";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="رسالة نص النص";		//Message Icon Text
var Languageletter342b="نص رسالة اليوتيوب";		//Youtube Message Text
var Languageletter342c="عنون  صورة رسالة ايمجور";		//Message Icon Imgur Url
var Languageletter342d="عنوان رسالة اليوتيوب";		//Youtube Message Url
var Languageletter343="يجب ملء هذه الوظيفة لكي تعمل";		//Must be filled for function to work.
var Languageletter344="Secondary Webhook(اختياري)";		//Secondary Webhook(optional)
var Languageletter345="مؤقتا اظهار/اخفاء كل شىء. Function for Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Languageletter346="اختار اللغة";		//Choose Language
var Languageletter347="تحذير! يتم حظر النوافذ المنبثقة في الإعدادات.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="إلغاء المنع المؤقت";		//Temporary unblock

var Languageletter349="الجرعات";	//Potions
var Languageletter350="سكينات قديمة";	//Old Skins
var Languageletter351="صفقة خاصة"; //Special Deals
var Languageletter352="الاوائل"; //Leaderboards
var Languageletter353="نموذج جديد وإحصائيات"; //New Ideas & Statistics Form
var Languageletter354="سكنات فيديو"; //Video Skins
var Languageletter355="سكريبتات مصغرة"; //Mini Scripts
var Languageletter356="سكريبتات المستخدم"; //User Scripts
var Languageletter357="دردشة صوت والكاميرا";	//Voice & Camera Chat
var Languageletter358="يرجي دعم تطوير ليجاند مود";	//Please support the development of Legend mod
var Languageletter359="تصميم اسم الخط";	//Design Nickname Font
var Languageletter360="التنويه بوضع اسكن شخص مزور";	//Flag the Fake Skin
var Languageletter361="المزيد من FPS";	//More FPS
var Languageletter362="الاسم";	//Name
var Languageletter363="الهوية الاجتماعية";	//Social ID
var Languageletter364="التوسعات";	//Expansions
var Languageletter365="اجارتولز";	//Universal
var Languageletter366="اعلي ماس";	//Score
var Languageletter367="مسافه: بعد";	//Distance
var Languageletter368="الحجم الكلي";	//Total Mass
var Languageletter369="ميت";	//Dead

var Premadeletter0="تم تفعيل الاتصالات"; 		//Communication Activated
var Premadeletter1="لا يمكن فتح عنوان هذا اليوتيوب";		 //Cannot open this youtube URL
var Premadeletter2="[SERVER]:لا يمكنك الدردشة اذا تجاوز اسمك 15 حرف/رمز"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="بيضة عيد1الفصح 1 تفعيلها"; 		//Easter Egg 1 Activated
var Premadeletter4="بيضة عيد الفصح 2 تفعيلها";		//Easter Egg 2 Activated
var Premadeletter5="بيضة عيد الفصح 3 تفعيلها";		//Easter Egg 3 Activated
var Premadeletter6=" vanillaالفيديو تعمل أفضل عند استخدام إعدادات    ";		//Video works better on vanilla, visit:
var Premadeletter7=" ملاحظات : فيسبوك متوافق افضل من جوجل بلاس."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter="8ملاحظات: اجاريو يمكنها فقط الاتصال من حساب جوجل .. اذا حصل عدم تسجيل قم بإعادة محاولة الدخول أو استخدم حساب فيسبوك.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter="لو حدث عدم تسجيل قم بحذف الكوكيز من متصفح الكروم";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="غير متصل بالسيرفر :(";		//Disconnected from server :(
var Premadeletter11="تم حظرك ، قم بعمل إعادة تشغيل للراوتر!";		//You were banned, restart your rooter!
var Premadeletter12="متصل!";		//Connected!
var Premadeletter13="بدء اللعب";		//PLAY
var Premadeletter14="وضع التصفح";		//SPECTATE
var Premadeletter15="عنوان سيرفر خاطئ أو تم إغلاقه :(";		//Invalid token or server has closed :(
var Premadeletter16="يمكن تحديثها إلي";		//can be Updated to
var Premadeletter17="مرحبا بعودتك";			//Welcome back
var Premadeletter18="أختصاراتك مازالت غير مفعلة  . نقترح تفعيلها.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="قم بتفعيلهم";		//Enable Them
var Premadeletter20="اتركهم غير مفعلين";		//Keep Them Disabled
var Premadeletter21="بحث بالايبي ";		//Searching IP
var Premadeletter22="صديقك";		//Your teammate
var Premadeletter23="يرغب أن تقوم باخفاء الجميع (الاوائل/الخريطة المصغرة)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="موافق";		//Accept
var Premadeletter25="أرفض!";		//NO WAY!
var Premadeletter26="يرغب في تغير اسمك إلي:";		//wants you to change your name to
var Premadeletter27="يرغب في اخفاء العزاء بعد الموت";		//wants you to hide Enable Troll on death
var Premadeletter28="يرغب في فتح مشغل اليوتيوب";			//wants you to open Youtube Player
var Premadeletter29="تم ايجاد قائمةالاوائل المطلوبة :)";		//Leaderboard found
var Premadeletter30="بـحث";		//Search
var Premadeletter31="قائمة الأوائل لم يتم إيجادها .. استمر بالمحاولة	";		//The leaderboard was not found. Keep trying...
var Premadeletter32="تم الغاء البحث";		//Search was canceled
var Premadeletter33="أنت الأن غير مرئى لأعضاء الفريق/الكلان";		//You are invisible to Team / Clan
var Premadeletter34="أنت الأن مرئى لأعضاء الفريق ";		//You are visible to Team / Clan
var Premadeletter35="اظهار/اخفاء يمكن فقط استخدامه في وضعية اللعب ";			//Hide/Show can be used only while playing
var Premadeletter36="عنوان ديسكورت غير صحيح";		//This is not valid Discord Webhook address
var Premadeletter37="السيرفر مغلق :( ";		//Server is locked
var Premadeletter38="يجب أن تكون في وضع التصفح ";		//You must be on spectate mode
var Premadeletter39="لمنع الازعاج ، فقط اثناء اللعب مستخدما التاج/كلمة السر";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="تفعيل اليوتيوب";		//Auto Youtube On
var Premadeletter41="غلق تلقائي لليوتيوب";		//Auto Youtube Off
var Premadeletter42="اظهار الاختصارات";		//Show Shortcuts
var Premadeletter43="اخفاء الاختصارات";		//Hide Shortcuts
var Premadeletter44="اظهار شريط المستوي";		//Show XP BAR
var Premadeletter45="اخفاء شريط المستوي";		//Hide XP BAR
var Premadeletter45a = "حواف دائرية"; //Rounded Hud
var Premadeletter45b = "حواف مربعة"; //Square Hud

var Premadeletter46 = "هود اللون الخطي"; //Linear color Hud
var Premadeletter47 = "هود اللون الغامق"; //Bold color Hud
var Premadeletter48="اظهار الكل";		//Show Everything
var Premadeletter49="اخفاء الكل";		//Hide Everything
var Premadeletter50=" إظهار الموقت";		//Show Timer Calc.
var Premadeletter51=" إخفاء المؤقت"		//Hide Timer Calc.
var Premadeletter52="تعديل الأسماء";		//Edit Names
var Premadeletter52a="إغلاق الأسماء";		//Close Names
var Premadeletter53="تفعيل تلقائى للكوين المجانية";		//Auto free coins
var Premadeletter54="أيقاف الكوين المجانية";		//Stop free coins
var Premadeletter55="العزاء بعد الموت";		//Troll on Death
var Premadeletter56="ايقاف العزاء بعد الموت";		//No troll on Death

var Premadeletter57="الاتصالات";		//Communication
var Premadeletter58="اخفاء";		//Hidden
var Premadeletter59="مرئي";		//Visible
var Premadeletter60="إيقاف";		//Pause

var Premadeletter61 = "تمكين اليوتيوب كخلفية";	//Enable YT as background
var Premadeletter62 = "تعطيل يوتيوب كخلفية";	//Disable YT as background";
var Premadeletter63 = "يريد منك فتح صفحة الويب";	//wants you to open the url
var Premadeletter64 = "يريد منك تشغيل هذا الفيديو ";	//wants you to embed and play this youtube video
var Premadeletter65 = "يريد منك الانضمام إلى غرفة سكايب التالية";	//wants you to join the following Skype room
var Premadeletter66 = "يريد منك الانضمام إلى غرفة ديسكورد التالية";	//wants you to join the following Discord room
var Premadeletter67 = "يريد منك ترك هذا السيرفر والانضمام إلى هذا الجديد";	//wants you to leave this server and join this new one

//I did it like this because Arabic language is using the opposite side of writing
var Premadeletter68 = "";
var Premadeletter69 = ". أعد تشغيل agario في حالة انخفاض FPS ، لأنك قمت بالضغط على:"; //. Restart agario if FPS drops, because you pressed:
var Premadeletter70 = "";

var Premadeletter71 = ""; 
var Premadeletter72 = ""; 
var Premadeletter73 = " عندما تكون هناك قطع كثيرة ،سيتم ايقاف (تمكين الاسكنات المتحركة)"; //When you will be on such pieces, this will drop (Animates skins are enabled)
var Premadeletter74 = ""; 
var Premadeletter75 = ""; 
var Premadeletter76 = ""; //
var Premadeletter77 = ""; 
var Premadeletter78 = "سيتم تعطيل الرسوم المتحركة بعد إعادة الانضمام. أداء أفضل FPS عندما 16"; //Animated skins will be disabled after rejoin. Better FPS performance when 16
var Premadeletter79 = ""; //
var Premadeletter80 = "عند تمكين تعديل Dying Light ، لا يمكن وضع Troll عند الموت"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "خادم خاص"; //Private Server
var Premadeletter82 = "";
var Premadeletter83 = "اتصل بأي خادم أو أنشئ بنفسك"; //server, or make your own
var Premadeletter84 = "العب اجاريو مثل الالعاب اذا كنت تعرف ايبي السيرفرات"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "";
var Premadeletter86 = "صورتك تم نسخة لحافظة الشاشة  قم بلصقها في عنوان الاسكن المخصصة:"; //Your image has been copied to clipboard. Paste it to custom skin Url area:
var Premadeletter87 = "يجب عليك تسجيل الدخول لاستخدام صورة ملفك الشخصي"; //You must Login to use picture of your profile
var Premadeletter88 = "أنت تستخدم إصدارًا خاطئًا"; //You are using a wrong version
var Premadeletter89 = "اللعبة ستنتهي الآن"; //Game will terminate now
var Premadeletter90 = "صفقة خاصة"; //Special Deals
var Premadeletter91 = "قد أو لا تعطيك Agario الجلد ، ولكن فقط العملات"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "استخدام على مسؤوليتك الخاصة"; //Use at your own risk
var Premadeletter92 = "إذا كان UID الخاص بصديقك غير صحيح ، فستفشل عملية الشراء"; //If friend UID is wrong, purchase will fail
var Premadeletter93 = "إعدادات المصنع UID"; //UID Factory Settings
var Premadeletter94 = "يجب عليك تسجيل الدخول لتحميل العروض الخاصة"; //You must login to load Special Deals
var Premadeletter95 = "";
var Premadeletter96 = "تم نسخ الصورة المزيفة إلى الحافظة. قم بلصقها لمنطقة Url المخصصة للجلد لتنشيط وظيفة العلم المزيف:"; // Fake image has been copied to clipboard. Paste it to custom skin Url area in order to activate the fake flag function:
var Premadeletter97 = "أبلغني عند الانتهاء من Recaptcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "لقد انتهيت"; //I have finished
var Premadeletter99 = "لا تهتم"; //Never Mind
var Premadeletter100 = "حساب XP الخاص بك ، يرجى الانتظار ..."; //Calculating your XP, please wait...
var Premadeletter101 = ""; //
var Premadeletter102 = "لا تضغط"; //Do NOT press
var Premadeletter103 = ""; //
var Premadeletter104 = "محو عنوان مخصص للاسكن"; //Erase custom skin URL
var Premadeletter105 = "اختيار فيديو للاسكن";	//select video skin
var Premadeletter106 = "إلغاء تحديد الجلد الفيديو"; //unselect video skin
var Premadeletter107 = "كتم الصوت"; //mute audio
var Premadeletter108 = "مشروع ليجاند مود"; //The LM Project
var Premadeletter109 = "رفع"; //Upload 
var Premadeletter109a = "تحميل"; //Download
var Premadeletter109b = "جار التحميل"; //Load

var Premadeletter110 = "لا تدخل أي شيء هنا إلا إذا كنت تعرف ما هو";	//do not enter anything here unless you know what it is
var Premadeletter111 = "انقر على أيقونة اللون البرتقالي للشراء"; //click on the orange icon to buy
var Premadeletter112 = "لبعض طرق الدفع"; //For some payment methods
var Premadeletter113 = "قريب";	//Close
var Premadeletter114 = "نسخ"; //COPY	
var Premadeletter115 = "يستخدم لشراء العروض لأصدقائك"; //is used to buy offers for your friends
var Premadeletter116 = "لإجراء عمليات شراء ، يجب تسجيل الدخول إلى حسابك ..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "مكتبة"; //Library
var Premadeletter118 = "يزور"; //visit
var Premadeletter119 = "الإبلاغ عن خطأ (تغيير الجلد)"; //Report as Fake (change Skin)
var Premadeletter120 = "أدخل اسمك الخاص بالمشغل"; //Enter your EXACT name of the player
var Premadeletter121 = "سيؤدي استغلال اللاعبين والاستخدام غير المناسب إلى UID للمستخدم"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "لحظر دائم من استخدام هذا التمديد"; //to permanent ban from usage of this extension
var Premadeletter128 = "تسجيل دخول المستخدم اللازمة"; //User login needed
var Premadeletter129 = "تم تحميل الإعدادات بنجاح"; //Settings successfully uploaded

//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "الخادم"; //SERVER
var Premadeletter124 = "تجنب استخدام مقاطع فيديو أكبر من 6 دقائق"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "خريطة ثابتة"; //Map fixed
var Premadeletter126 = "الدخول الى"; //Logged in to
var Premadeletter127 = "تسجيل الخروج"; //Logged out
var Premadeletter130 = "مجموع"; //Total
var Premadeletter131 = "الجديد"; //NEW
var Premadeletter132 = "الانضمام مرة أخرى"; //Join Back
var Premadeletter133 = "الاتصال بآخر عنوان IP لعبته"; //Connect to last IP you played
var Premadeletter134 = "شمال امريكا"; //North America
var Premadeletter135 = "جنوب امريكا"; //South America
var Premadeletter136 = "أوروبا"; //Europe
var Premadeletter137 = "روسيا"; //Russia
var Premadeletter138 = "ديك رومي"; //Turkey
var Premadeletter139 = "شرق اسيا"; //East Asia
var Premadeletter139a = "الصين"; //China
var Premadeletter140 = "أوقيانوسيا"; //Oceania
var Premadeletter140a = " -- اختر المنطقة -- "; // -- Select a Region -- 
var Premadeletter141 = "حر"; //FFA
var Premadeletter142 = "معركة رويال"; //Battle Royale
var Premadeletter143 = "فرق"; //Teams
var Premadeletter144 = "تجريبي"; //Experimental
var Premadeletter145 = "حفلة"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "اللغات"; //LANGUAGES
var Externalletter0b = "اختر لغة"; //Choose a language
var Externalletter0c = "ستحدث التغييرات تمامًا بعد إعادة التشغيل"; //Changes will take place completely after the restart
var Externalletter1 = "معلومات"; //INFORMATION
var Externalletter2 = "قالب"; //TEMPLATES
var Externalletter3 = "الدليل اليدوي"; //MANUAL TEMPLATES
var Externalletter4 = "اختر القالب الخاص بك"; //Choose your template
var Externalletter5 = "أو اختيار التوسع"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "إرسال الكود إلى المطورين"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "الصق Script الخاص بك في هذا Textarea ، يمكنك تحميل برامج نصية متعددة"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "تحميل البرنامج النصي من Textarea"; //Load Script from Textarea
var Externalletter8 = "أختر"; //Choose
var Externalletter9 = "مسح السيناريو"; //Erase Script
var Externalletter10 = "اسم"; //Name
var Externalletter11 = "Url (raw) Github أو أي سيناريو خام آخر يبدأ بـ"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "اترك هذا فارغًا إذا لم يتم استيراد البرنامج النصي من عنوان URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "إشعار هام: لا تحتفظ بعناوين URL التي لا تعمل ، لأنها تستخدم في أحداث التحميل. إذا كان الأضرار السيناريوهات على أحداث التحميل ، ثم DELETE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
