/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home (even if in french in this context home="accueil" :))                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="JdieR";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Accueil";		//Home
var Languageletter1="Joueur";		//User
var Languageletter2="Paramètres";		//Settings
var Languageletter3="Thème";		//Theme
var Languageletter4="Raccourcisn claver";		//Hotkeys
var Languageletter5="Sons & musiques Youtube";		//Youtube & Sounds
var Languageletter6="Outils";		//Tools
var Languageletter7="Laissez ce bloc vide pour être en public, sinon insérer un mot de passe de clan ou un tag";		//Password/Tag
var Languageletter7a="Mot de passe ou tag"	;	//Password/Tag
var Languageletter8="Insérez votre nom de joueur, 50 caractères sont visibles pour les utilisateurs du mode, 15 seulement pour les autres utilisateurs";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Nom";		//Name
var Languageletter9="Insérez le lien pour un skin manuel";		//Insert your manual skin weblink
var Languageletter9a="Lien URL direct pour un skin";		//Manual direct skin URL
var Languageletter10="Lieu du serveur";		//The region to play
var Languageletter11="Mode de jeu";		//The mode to play
var Languageletter12="Connectez-vous au serveur ou rétablissez la communication";		//Connect to server, or restablish communication
var Languageletter12a="Connex.";		//Connect
var Languageletter13="Joindre";		//Join
var Languageletter14="Jouer en tant qu'invité";		//Play as guest
var Languageletter15="S'dentifier et jouer";		//Login and Play
var Languageletter16="Regarder";		//Spectate
var Languageletter17="S'identifier avec Facebook";		//Sign in with Facebook
var Languageletter18="S'identifier avec Google";			//Sign in with Google
var Languageletter19="Jouer";		//Play
var Languageletter20="Boutique"	;		//Shop
var Languageletter21="Coins gratuits";		//Free Coins
var Languageletter22="Cadeaux";		//Gifts
var Languageletter23="Quêtes journalières";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Vidéo de promotion du Legend Mod";		//Legend Promo Video
var Languageletter25a="Nouveau formulaire d'idées et de statistiques";		//New Ideas & Statistics Form
var Languageletter25b="Mod Info et modèles";		//Mod Info & Templates
var Languageletter26="Ajouter des skins";		//Add skins
var Languageletter26a="Copier le serveur, le mot de passe, le tableau d'équipe et le tableau des leaders"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Se déconnecter";		//Logout
var Languageletter32="Nombre de fois utilisé";		//Times Used
var Languageletter33="Legend Mod fait par";		//Legend Mod by
var Languageletter34="Traduction faite par";		//Translation by
var Languageletter35="Copiez les noms du classement. (Pressez x pour montrer/cacher)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animation";		//Animation
var Languageletter37="Retard d'animation";		//Animation delay
var Languageletter37a="Zoom automatique";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Vitesse du zoom :";		//Zoom speed: 
var Languageletter39="Respawn";			//Respawn
var Languageletter40="Respawn automatique";		//Auto respawn 
var Languageletter41="Respawn rapide";			//Quick respawn 
var Languageletter41a="Commencez avec des effets spéciaux";			//Spawn special effects 
var Languageletter41b="Fusionner le minuteur ";			//Merge timer off
var Languageletter41c="Il est suggéré d’activer le lag reduction";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Son virus tiré";			//Virus shot sound

var Languageletter42="Noms";			//Names
var Languageletter43="Pas de noms";		//No names 
var Languageletter44="Noms optimisés";		//Optimized names 
var Languageletter45="Masquage automatique des noms";		//Auto hide names 
var Languageletter46="Cacher mon nom";		//Hide my name 
var Languageletter47="Cacher le nom de mes coéquipiers";		//Hide teammates names 
var Languageletter48="Noms mis en avant";		//Names stroke 
var Languageletter49="Masse";		//Mass
var Languageletter50="Afficher la masse";		//Show mass 
var Languageletter51="Masse optimisée"	;	//Optimized mass 
var Languageletter52="Masquage automatique de la masse";			//Auto hide mass 
var Languageletter53="Cacher ma masse";		//Hide my mass 
var Languageletter54="Cacher la masse de mes ennemis";		//Hide enemies mass 
var Languageletter55="Mass courte";		//Short mass
var Languageletter56="Tirs de virus";		//Virus shots 
var Languageletter57="Masse mise en avant";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="Pas de skins ";		//No skins 
var Languageletter60="Skins personnalisés";		//Custom skins 
var Languageletter61="Vanilla skins";		//Vanilla skins 
var Languageletter61a="Gelée physique";		//Jelly physics 
var Languageletter61b="Skins vidéo";		//Video skins
var Languageletter61c="Le son des skins des autres vidéos lorsque les deux C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Nourriture optimisée";		//Optimized food 
var Languageletter6a2="Nourriture";		//Food 
var Languageletter63="Masquage automatique de la nourriture (masse)";		//Auto hide food (mass) 
var Languageletter64="Masquage automatique de la nourriture (zoom) ";		//Auto hide food (zoom) 
var Languageletter65="Nourriture multicolores";		//Rainbow food 
var Languageletter66="Transparence / Couleurs";		//Transparency / colors
var Languageletter67="Pas de couleur";		//No colors 
var Languageletter68="Couleur personnalisée";		//My custom color 
var Languageletter69="Mon skin transparent";		//My transparent skin 
var Languageletter70="Skins transparents";		//Transparent skins 
var Languageletter70a="Cellules transparentes";		//Transparent cells
var Languageletter71="Virus transparents";		//Transparent viruses 
var Languageletter71a="Brillance du virus";		//Virus Glow
var Languageletter71b="Couleurs animées arc-en-ciel";		//Animated rainbow colors

var Languageletter72="Grille et secteurs";		//Grid / sectors
var Languageletter73="Afficher la grille";		//Show grid 
var Languageletter74="Aficher les secteurs en fond";		//Show background sectors 
var Languageletter75="Afficher les bords de la map";		//Show map borders 
var Languageletter75a="Lueur des frontières";		//Border Glow

var Languageletter76="Chat";		//Chat
var Languageletter77="Désactiver le chat";		//Disable chat 
var Languageletter78="Notifications sonoress";		//Sound notifications 
var Languageletter79="Emoticônes";		//Emoticons 
var Languageletter80="Afficher les images dans le chat";		//Show images on chat 
var Languageletter81="Afficher les vidéos dans le chat";		//Show videos on chat 
var Languageletter82="Boîte de chat au lieu de fenêtres pop-up";		//Chatbox instead of popups 
var Languageletter82a="Minimap";		//Minimap
var Languageletter82b="Afficher la minimap";		//Show minimap 
var Languageletter82c="Afficher la grille sur la minimap";		//Show minimap grid 
var Languageletter82d="Afficher les guides sur la minimap";		//Show minimap guides 
var Languageletter82e="Les coéquipiers d'une seule couleur";		//One-colored teammates 
var Languageletter82f="Afficher des mini guides de carte supplémentaires";		//Show extra minimap guides
var Languageletter82g="Afficher les cellules fantômes";		//Show ghost cells


var Languageletter83="Aides";		//Helpers
var Languageletter84="Couleurs pour les adversaires";		//Opponents colors
var Languageletter85="Anneaux pour les adversaires";		//Opponents rings 
var Languageletter86="Couleur des virus";		//Viruses colors 
var Languageletter87="Portée de split";		//Split range 
var Languageletter87a="Gamme double split rapide";		//Quick double split range
var Languageletter87b="Lente double split gamme";		//Slow double split range

var Languageletter88="Portée des virus";		//Viruses range 
var Languageletter89="Suivi du curseur";		//Cursor tracking 
var Languageletter90="Indicateurs des coéquipiers";		//Teammates indicators 
var Languageletter90a="Cellules fantômes";		//Ghost cells

var Languageletter91="Contrôle de la souris";		//Mouse control
var Languageletter92="Clic gauche - Mouse split";		//LMB - Mouse split 
var Languageletter93="Clic droit - Mouse feed";		//RMB - Mouse feed 
var Languageletter94="Inverser les boutons de la souris";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="Équipe";		//Team
var Languageletter96="Afficher le ciblage";		//Show targeting 
var Languageletter96a="Montrer la masse du classement";		//Show leaderboard mass

var Languageletter97="Centrer le classement";		//Centered leaderboard 
var Languageletter97a="En-tête du classement";		//\"Leaderboard\" header 

var Languageletter98="Statistiques du jeu en haut";		//Game stats at the top 
var Languageletter98a="Skins sur le teamboard";		//Skins on teamboard

var Languageletter99="Statistiques";		//Stats
var Languageletter100="Afficher les statistiques de la partie";		//Show game stats 
var Languageletter101="Statistiques du jeu";		//Game stats
//the \' is needed
var Languageletter102="de l\'ennemi";		//Enemy\'s 		
var Languageletter103="les notres";		//Our
var Languageletter104="Un truc minimal divise la masse de son coéquipier";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Masse maximale de l'ennemi pour la division préalable";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Afficher l'heure actuelle";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Garder les statistiques après la mort";		//Skip stats after death 
var Languageletter108="Afficher la qûete";		//Show quest 
var Languageletter108a="Les sons du jeu"; //Game Sounds
var Languageletter108b="Les sons du menu"; //Menu Sounds
var Languageletter109="Bloquer les pop-ups (publicités/boutique/quête)";		//Block popups (ads/shop/quest) 
var Languageletter109a="VOIX"; //Voice
var Languageletter109b="Voix-Préfixe"; //Voice-Prefix
var Languageletter109c="Voix-langue"; //Voice-language
var Languageletter109d="UnPause"; //UnPause

var Languageletter110="-- Qualité du graphisme --";		//-- Graphics Quality --
var Languageletter111="Graphisme : Retina";		//Graphics: Retina
var Languageletter112="Graphisme : Élevé";		//Graphics: High
var Languageletter113="Graphisme : Moyen";		//Graphics: Medium"
var Languageletter114="Graphisme : Faible";		//Graphics: Low
var Languageletter115="Graphisme : Très faible";		//Graphics: Very Low
var Languageletter116="Exporter/Importer les paramètres";		//Export / import settings
var Languageletter117="Restaurer les paramètres par défaut";		//Restore default settings
var Languageletter118="Exporter les paramètres";		//Export settings
var Languageletter119="Importer les paramètres";		//Import settings
var Languageletter120="Pour exporter les paramètres sélectionnés, copiez le code ci-dessous et enregistrez-le dans un fichier texte codé en Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Pour importer les paramètres sélectionnés, collez un code exporté ci-dessous et appuyez sur le bouton 'Importer les paramètres'.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Commandes";		// Commands
var Languageletter123="Raccourcis";		// Hotkeys
var Languageletter124="Profil";		// Profiles
var Languageletter125="Paramètres";		// Settings
var Languageletter126="Thème";		// Theme
var Languageletter127="Paramètres exportés";		//Export settings
var Languageletter128="Paramètres importés";		//Import settings
var Languageletter129="Thème de base";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimap";		//Minimap
var Languageletter134="Graphique et curseur";		//Graphics / cursors
var Languageletter135="Préréglage du thème";		//Theme preset
var Languageletter136="Legend original";		//Legend Original
var Languageletter137="Crazy style";		//Crazy Style 1
var Languageletter139="Fond";		//Background
var Languageletter140="Bord de la map";		//Map borders
var Languageletter141="Grille";		//Grid
var Languageletter142="Police des secteurs";		//Sectors font
var Languageletter143="Noms";		//Names
var Languageletter144="Noms mis en avant";		//Names stroke
var Languageletter145="Masse";		//Mass
var Languageletter146="Masse mise en avant";		//Mass stroke
var Languageletter147="Virus mis en avant";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter148a="Cellule mère";		//Mothercell
var Languageletter148b="Accident vasculaire cérébral";		//Mothercell stroke
var Languageletter149="Nourriture";		//Food
var Languageletter150="Indicateur de coéquipiers";		//Teammate indicator
var Languageletter151="Suivi du curseur";		//Cursor tracking
var Languageletter152="Portée de split";		//Split range
var Languageletter153="Police des noms";		//Names font
var Languageletter154="Police de la masse";		//Mass font
var Languageletter154a="Plus gros";		//Bigger
var Languageletter154b="Plus petite";		//Smaller
var Languageletter155="Police des secteurs";		//Sectors font
var Languageletter157="Taille de police des secteurs";		//Sectors font size
var Languageletter158="Echelle des noms";		//Names scale
var Languageletter159="Echelle de la masse";		//Mass scale
var Languageletter160="Echelle de la masse d'un virus";		//Virus mass scale
var Languageletter161="Echelle du texte mis en avant";		//Text stroke scale
var Languageletter162="Taille de la nourriture";		//Food size: 
var Languageletter163="Taille des virus mis en avant";		//Virus stroke size
var Languageletter164="Largeur des bords de la map";		//Map borders width
var Languageletter165="Largeur de la grille des secteurs";		//Sectors grid width
var Languageletter166="Cellules transparentes";		//Cells transparency
var Languageletter167="Skins transparents";		//Skins transparency
var Languageletter168="Virus transparents";		//Virus transparency
var Languageletter169="Noms et masse transparents";		//Names & mass transparency
var Languageletter170="Restaurer les paramètres par défaut du thème";		//Restore theme default settings
var Languageletter171="Sauvegarder les paramètres";		//Save settings
var Languageletter172="Thème du menu";		//Menu theme
var Languageletter173="Fond";		//Background
var Languageletter174="Transparence";		//Transparency
var Languageletter175="Couleur principale";		//Main color
var Languageletter176="Texte du bouton";		//Button text
var Languageletter177="Tableau de bord";		//Panel
var Languageletter179="Texte du tableau de bord";		//Panel text
var Languageletter181="Bouton";		//Button
var Languageletter189="Image d'arrière plan du tableau de bord";		//Panel background image
var Languageletter190="Image URL";		//Image URL
var Languageletter191="Couleur principale";		//Main color
var Languageletter192="Fond";		//Background
var Languageletter193="Texte";		//Text
var Languageletter194="Statistiques";		//Stats
var Languageletter195="Temps";		//Time
var Languageletter196="Top 5 de la masse";		//Top 5 mass
var Languageletter197="Classement - moi";		//Leaderboard - me
var Languageletter198="Classement - coéquipiers";		//Leaderboard - teammate
var Languageletter199="Police du HUD";		//HUD font
var Languageletter200="Echelle du HUD";		//HUD scale: 
var Languageletter201="Message du fond";		//Message background
var Languageletter202="Message du texte";		//Message text
var Languageletter203="Message du temps";		//Message time
var Languageletter204="Message du nom";		//Message nick
var Languageletter205="Commande du fond";		//Command background
var Languageletter206="Commande du texte";		//Command text
var Languageletter207="Commande du temps";		//Command time
var Languageletter208="Commande du nom";		//Command nick
var Languageletter209="Couleur du chat";		//Chatbox color
var Languageletter210="Echelle du chat";		//Chat scale
var Languageletter211="Secteurs";		//Sectors
var Languageletter212="Secteur actuel";		//Current sector
var Languageletter213="Nom";		//Nick
var Languageletter214="Nom mis en avant";		//Nick stroke
var Languageletter215="Ma cellule";		//My cell
var Languageletter216="Ma cellule mise en avant";		//My cell stroke
var Languageletter217="Coéquipiers";		//Teammates
var Languageletter218="Location de sa mort";		//Death location
var Languageletter219="Guides";		//Guides
var Languageletter220="Police de la minimap";		//Minimap font
var Languageletter221="Police du nom";		//Nick font
var Languageletter222="Largeur de la minimap";		//Minimap width
var Languageletter223="Secteurs transparents";		//Sectors transparency
var Languageletter224="Taille du nom";		//Nick size
var Languageletter225="Taille du nom en avant";		//Nick stroke size
var Languageletter226="Taille de ma cellule";		//My cell size
var Languageletter227="Taille de ma cellule mise en avant";		//My cell stroke size
var Languageletter228="Taille des coéquipiers";		//Teammates size
var Languageletter229="Image de fond personnalisé";		//Custom background image
var Languageletter230="Image de curseur personnalisée";		//Custom cursor image
var Languageletter231="Image URL";		//Image URL
var Languageletter232="Curseur de l'image URL";		//Cursor image URL
var Languageletter233="Feed";		//Feed
var Languageletter234="Macro feed";		//Macro feed
var Languageletter235="Split";		//Split
var Languageletter236="Double split";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="Split en 16";		//Split 16
var Languageletter239="Cellule en pause";		//Cell pause
var Languageletter240="Afficher/masquer le top 5 de l'équipe";		//Show/hide team top 5
var Languageletter241="Afficher/masquer le temps actuel";		//Show/hide current time
var Languageletter242="Afficher/masquer la portée de split";		//Show/hide split range"
var Languageletter243="Afficher/masquer les indicateurs de coéquipiers";		//Show/hide teammates indicators
var Languageletter244="Afficher/masquer les indicateurs de split";		//Show/hide split indicators
var Languageletter245="Afficher/masquer la couleur des adversaires";		//Show/hide opponents colors
var Languageletter246="Basculer les skins (customisé/par défaut)";		//Toggle skins (custom/default)
var Languageletter247="Basculer les skins transparents";		//Toggle transparent skins
var Languageletter248="Afficher/masquer les skins";		//Show/hide skins
var Languageletter249="Afficher/masquer les statistiques de jeu";		//Show/hide game stats
var Languageletter250="Basculer sur ses cellules (les plus petites/plus grandes)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Afficher/masquer la nourriture";		//Show/hide food
var Languageletter252="Afficher/masquer la grille";		//Show/hide grid
var Languageletter253="Afficher/masquer les guides sur la minimap";		//Show/hide minimap guides
var Languageletter254="Afficher/masquer le chat";		//Show/hide chat
var Languageletter255="Afficher/masquer le HUD";		//Show/hide HUD
var Languageletter256="Copier le classement";		//Copy leaderboard
var Languageletter257="Afficher/masquer le classement";		//Show/hide leaderboard
var Languageletter258="Lancer le zoom automatique";		//Toggle auto zoom
var Languageletter259="Réinitialiser le zoom";		//Reset zoom
var Languageletter260="Basculer la localisation de sa mort";		//Toggle death location
var Languageletter261="Show chat history / Clear chat";		//Show chat history / Clear chat
var Languageletter262="Afficher/masquer les secteurs de fond";		//Show/hide background sectors
var Languageletter263="Afficher/masquer les petits bots";		//Show/hide small bots
var Languageletter264="Afficher/masquer les noms";		//Show/hide names
var Languageletter265="Afficher/masquer le nom de ses coéquipiers";		//Show/hide teammates names
var Languageletter266="Afficher/masquer la masse";		//Show/hide mass
var Languageletter267="Afficher/masquer la minimap";		//Show/hide minimap
var Languageletter268="Entrer un message dans le chat";		//Enter chat message
var Languageletter269="Respawn rapide";		//Quick respawn
var Languageletter270="Basculer le respawn automatique";		//Toggle auto respawn
var Languageletter271="Niveau du zoom";		//Zoom level 
var Languageletter271a="Voix au texte";		//Voice to text
var Languageletter271b="Afficher les informations sur les cellules fantômes";		//Show ghost cells information
var Languageletter271c="Jeu automatique";		//Auto Play
var Languageletter272="Afficher/masquer le panneau de ciblage";		//Show/hide targeting panel
var Languageletter273="Commencer/arrêter le ciblage (suivi)";		//Start/stop targeting (following)
var Languageletter274="Annuler le ciblage";		//Cancel targeting
var Languageletter275="Changer de cible";		//Change target
var Languageletter276="Montrer la cible sur la minimap";		//Show target on the minimap
var Languageletter277="Afficher/masquer la quête";		//Show/hide quest
var Languageletter278="Pour attribuer un raccourci, cliquez sur le champ de saisie et appuyez sur la touche choisie.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Pour supprimer un raccourci, cliquez sur le champ de saisie et appuyez sur la touche DELETE.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Possibilité de combinaisons de touches avec les touches CTRL et ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Restaurer les paramètres par défaut";		//Restore default settings
var Languageletter282="Sauvegarder les paramètres";		//Save settings
var Languageletter283="Fermer";		//Close
var Languageletter284="URL Youtube";		//Youtube player
var Languageletter284a="URL Youtube";		// Youtube Url
var Languageletter285="Collez votre vidéo/playlist ici";		//Paste your video/playlist here
var Languageletter286="Sons";		//Sounds
var Languageletter287="Message de notification sonore";		//Message notification sound
var Languageletter288="Commande de notification sonore";		//Command notification sound
var Languageletter289="Copier le lien/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Lien";		//Token
var Languageletter290a="Classement"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Copier";		//Copy


var Languageletter291a="Copier le classement (L)";		//Copy Leaderboard (L)
var Languageletter291b="Copier le jeton / SIP et mot de passe"; 	//Copy Token/SIP&Password
var Languageletter291c="Copier tout..."; //Copy Token/SIP, Password, Leaderboard
var Languageletter292="Joindre le serveur (Backspace)";		//Join server (Backspace)
var Languageletter293="Changer de serveur (+)";		//Change server (+)
var Languageletter294="Historique du classement";		//Leaderboard history
var Languageletter295="Entrer le lien d'un ami, adresse IP, classement, nom ou tag de clan...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Effacer la liste"; //Clear list
var Languageletter295b="Entrez le message de chat..."; //Enter chat message...
var Languageletter298="Top de l'équipe";		//Team top 
var Languageletter299="Classement";		//Leaderbodard
var Languageletter300="Communication";		//Communication
var Languageletter301="Message des scripts de commande";		//Message Script Commands
var Languageletter302="Message Imgur";		//Message Imgur Icons
var Languageletter303="Message des vidéos Youtube";		//Message Youtube Videos
var Languageletter304="Editer les noms";		//Edit names
var Languageletter305="[Mode spectateur uniquement] Jumelles";		//[Spectate Mode Only] Binoculars
var Languageletter306="Play / Pause";		//Play / Pause
var Languageletter307="Plein écran";		//Fullscreen
var Languageletter308="Tourner";		//Rotate
var Languageletter309="Défaut";		//Default
var Languageletter310="Retour";		//Back
var Languageletter311="Sauvegarder pour plus tard";		//Save for later
var Languageletter312="Région";		//Region
var Languageletter313="Joueurs";		//Players
var Languageletter314="Serveurs";		//Servers
var Languageletter315="[Cible non définie]";		//[Target not set]
var Languageletter316="Fond manuel";		//Manual background
var Languageletter317="Message manuel des îcones et de Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Position du chat";		//Chat Position
var Languageletter319="URL Discord Webhook (pour envoyer un lien)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Classement";		//Leaderboard
var Languageletter321="Tableau d'équipe";		//Teamboard
var Languageletter322="Bloc principal";		//Main Canvas
var Languageletter323="Bannière principale";		//Main Banner
var Languageletter324="Salut l'équipe !";		//Hello Team!
var Languageletter325="Rire";		//Laugh to Team
var Languageletter326="Changer le nom de l'équipe en";		//Team Change Name to yours
var Languageletter327="Troll";		//Troll on Death
var Languageletter328="Ouvrir la musique Youtube";		//Open Youtube Music
var Languageletter329="Mode insane (Cacher tout)";		//Insane mode (Hide Everything)
var Languageletter330="URL de l'image commençant par http://... ou https://...";		//Url of image starting with http://... or https://...
var Languageletter331="URL de l'image de la minimap";		//Minimap Image URL
var Languageletter332="Texte de la minimap";		//Minimap Text
var Languageletter333="Texte du logo du classement";		//Leaderboard Logo Text
var Languageletter333a="URL de l'image du classement";		// Leaderboard Image URL
var Languageletter334="Texte du logo du tableau de l'équipe";		//Teamboard Logo Text
var Languageletter334a="URL de l'image du tableau de l'équipe";		// Teamboard Image URL
var Languageletter335="URL de l'image principale";		//Main Canvas Image URL
var Languageletter336="URL principale de l'icône de la bannière";		//Main Banner Icon URL
var Languageletter337="URL principale du lien de bannière";		//Main Banner Link URL
var Languageletter338="Icône";		//Icon
var Languageletter339="par exemple";		//e.g
var Languageletter340="Url Youtube à afficher";		//Url of youtube to be shown
var Languageletter341="Url de redirection";		//Url of link to redirect
var Languageletter342="Url Discord Webhook";		//Discord Webhook Url
var Languageletter342a="Message du texte Imgur";		//Message Icon Text
var Languageletter342b="Message du texte Youtube";		//Youtube Message Text
var Languageletter342c="Message de l'URL Imgur";		//Message Icon Imgur Url
var Languageletter342d="Message de l'URL Youtube";		//Youtube Message Url
var Languageletter343="Doit être rempli pour fonctionner";		//Must be filled for function to work.
var Languageletter344="Webhook secondaire (optionnel)";		//Secondary Webhook(optional)
var Languageletter345="ATTENTION ! Les fenêtres popups sont bloquées dans les paramètres.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Débloquer temporairement";		//Temporary unblock
var Languageletter347="ATTENTION ! Les fenêtres popups sont bloquées dans les paramètres.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Débloquer temporairement";		//Temporary unblock

var Languageletter349="Potions";	//Potions
var Languageletter350="Vieux Skins";	//Old Skins
var Languageletter351="Offres spéciales"; //Special Deals
var Languageletter352="Classements"; //Leaderboards
var Languageletter353="Nouveau formulaire d'idées et de statistiques"; //New Ideas & Statistics Form
var Languageletter354="Peaux vidéo"; //Video Skins
var Languageletter355="Mini-scripts"; //Mini Scripts
var Languageletter356="Scripts utilisateur"; //User Scripts
var Languageletter357="Conversation vocale et caméra";	//Voice & Camera Chat
var Languageletter358="S'il vous plaît soutenir le développement du mod Légende";	//Please support the development of Legend mod
var Languageletter359="Design Nickname Police";	//Design Nickname Font
var Languageletter360="Signaler la peau de la fausse";	//Flag the Fake's Skin
var Languageletter361="Plus FPS";	//More FPS
var Languageletter362="Nom";	//Name
var Languageletter363="Identifiant social";	//Social ID
var Languageletter364="Les expansions";	//Expansions
var Languageletter365="Universel";	//Universal
var Languageletter366="Résultat";	//Score
var Languageletter367="Distance";	//Distance
var Languageletter368="Masse totale";	//Total Mass
var Languageletter369="Mort";	//Dead

var Premadeletter0="Communication Activée"; 		//Communication Activated
var Premadeletter1="Impossible d'ouvrir cette URL Youtube";		 //Cannot open this youtube URL
var Premadeletter2="Vous ne pouvez pas discuter si le nom du joueur est supérieur à 15 caractères"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Activé"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Activé";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Activé";		//Easter Egg 3 Activated
var Premadeletter6="La vidéo fonctionne mieux sur vanilla, visitez :";		//Video works better on vanilla, visit:
var Premadeletter7="Notes : La compatibilité de <b>Facebook</b> est meilleure que celle de <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notes : Agar.io peut seulement se connecter à <b>Google Plus</b> sur les événements en charge. Si la déconnexion persiste, rejoignez Agar.io ou utiliser <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Si le déconnexion se produit sur les événements en charge, supprimez les cookies Chrome de";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Déconnecté du serveur :(";		//Disconnected from server :(
var Premadeletter11="Vous avez été banni, redémarrez votre routeur !";		//You were banned, restart your rooter!
var Premadeletter12="Connecté !";		//Connected!
var Premadeletter13="JOUER";		//PLAY
var Premadeletter14="REGARDER";		//SPECTATE
var Premadeletter15="Lien invalide ou le serveur a été fermé :(";		//Invalid token or server has closed :(
var Premadeletter16="Peut être mis à jour";		//can be Updated to
var Premadeletter17="Bon retour";			//Welcome back
var Premadeletter18="Votre zone de raccourci et d'autres zones (depuis le dernier onglet) sont encore désactivées ! Nous vous suggérons de les activer.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Activez-les";		//Enable Them
var Premadeletter20="Gardez-les désactivés";		//Keep Them Disabled
var Premadeletter21="Recherche de l'IP";		//Searching IP
var Premadeletter22="Votre coéquipier";		//Your teammate
var Premadeletter23="Voulez-vous tout cacher (le classement et la minimap) ?";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Acceptez";		//Accept
var Premadeletter25="PAS MOYEN !";		//NO WAY!
var Premadeletter26="Voulez-vous chnger votre nom en";		//wants you to change your name to
var Premadeletter27="Voulez-vous permettre un troll ?";		//wants you to hide Enable Troll on death
var Premadeletter28="Voulez-vous ouvrir Youtube ?";			//wants you to open Youtube Player
var Premadeletter29="Classement trouvé";		//Leaderboard found
var Premadeletter30="Recherche";		//Search
var Premadeletter31="Le classement n'a pas été trouvé. Continuez d'essayer...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="La recherche a été annulée";		//Search was canceled
var Premadeletter33="Vous êtes invisible pour vos coéquipiers";		//You are invisible to Team / Clan
var Premadeletter34="Vous êtes visible pour vos coéquipiers";		//You are visible to Team / Clan
var Premadeletter35="Afficher/masquer peut être utilisé uniquement pendant la lecture";			//Hide/Show can be used only while playing
var Premadeletter36="Ceci n'est pas une adresse Discord Webhook valide";		//This is not valid Discord Webhook address
var Premadeletter37="Le serveur est fermé";		//Server is locked
var Premadeletter38="Vous devez être en mode spectateur";		//You must be on spectate mode
var Premadeletter39="En raison de problèmes de spam, vous devez être dans le jeu et utiliser le mot de passe";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube on";		//Auto Youtube On
var Premadeletter41="Auto Youtube off";		//Auto Youtube Off
var Premadeletter42="Afficher raccour.";		//Show Shortcuts
var Premadeletter43="Masquer raccour.";		//Hide Shortcuts
var Premadeletter44="Afficher barre d'XP";		//Show XP BAR
var Premadeletter45="Masquer barre d'XP";		//Hide XP BAR
var Premadeletter45a = "Arrondie Hud"; //Rounded Hud
var Premadeletter45b = "Carré Hud"; //Square Hud

var Premadeletter46 = "Couleur linéaire"; //Linear color Hud
var Premadeletter47 = "Couleur audac."; //Bold color Hud
var Premadeletter48="Tout afficher";		//Show Everything
var Premadeletter49="Tout masquer";		//Hide Everything
var Premadeletter50="Affich. chronom.";		//Show Timer Calc.
var Premadeletter51="Masquer chronom."		//Hide Timer Calc.
var Premadeletter52="Éditer les noms";		//Edit Names
var Premadeletter52a="Fermer les noms";		//Close Names
var Premadeletter53="automatiq. coins";		//Auto free coins
var Premadeletter54="Pas automatiques";		//Stop free coins
var Premadeletter55="Troll";		//Troll on Death
var Premadeletter56="Pas de troll";		//No troll on Death

var Premadeletter57="Communication";		//Communication
var Premadeletter58="Caché";		//Hidden
var Premadeletter59="Visible";		//Visible
var Premadeletter60="Pause";		//Pause

var Premadeletter61 = "Activer YT en arrière-plan";	//Enable YT as background
var Premadeletter62 = "Désactiver YT en arrière-plan";	//Disable YT as background";
var Premadeletter63 = "veut que vous ouvriez l'URL";	//wants you to open the url
var Premadeletter64 = "veut que vous embarquiez et jouiez cette vidéo youtube";	//wants you to embed and play this youtube video
var Premadeletter65 = "veut vous joindre à la salle Skype suivante";	//wants you to join the following Skype room
var Premadeletter66 = "veut que vous rejoignez la salle Discord suivante";	//wants you to join the following Discord room
var Premadeletter67 = "veut que tu quittes ce serveur et rejoins ce nouveau";	//wants you to leave this server and join this new one

var Premadeletter68 = "Vous avez appuyé"; //You pressed
var Premadeletter69 = "redémarrer si"; //restart if
var Premadeletter70 = "gouttes"; //drops
var Premadeletter71 = "Peaux animées"; //Animated skins
var Premadeletter72 = "activée"; //enabled
var Premadeletter73 = "laissez tomber"; //drop
var Premadeletter74 = "quand"; //when
var Premadeletter75 = "Les skins animés seront"; //Animated skins will be
var Premadeletter76 = "désactivée"; //disabled
var Premadeletter77 = "après rejoindre"; //after rejoin
var Premadeletter78 = "Meilleurs FPS"; //Better FPS
var Premadeletter79 = "performance quand 16"; //performance when 16
var Premadeletter80 = "Lorsque l'option Dying Light Expansion est activée, Troll on death ne peut pas se produire"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Serveur privé"; //Private Server
var Premadeletter82 = "Connectez-vous à n'importe quel"; //Connect to any
var Premadeletter83 = "serveur, ou faites le vôtre"; //server, or make your own
var Premadeletter84 = "Jouez à des jeux similaires à ceux de l'agario si vous connaissez l'adresse IP des serveurs"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Votre image a été copiée dans le presse-papiers. Coller"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "à la zone d'URL personnalisée de la peau"; //to custom skin Url area
var Premadeletter87 = "Vous devez vous connecter pour utiliser la photo de votre profil"; //You must Login to use picture of your profile
var Premadeletter88 = "Vous utilisez une mauvaise version"; //You are using a wrong version
var Premadeletter89 = "Le jeu va se terminer maintenant"; //Game will terminate now
var Premadeletter90 = "Offres spéciales"; //Special Deals
var Premadeletter91 = "Agario peut ou non vous donner la peau, mais seulement les pièces"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "À utiliser à vos risques et périls"; //Use at your own risk
var Premadeletter92 = "Si l'UID de votre ami est faux, l'achat échouera"; //If friend's UID is wrong, purchase will fail
var Premadeletter93 = "Paramètres d'usine UID"; //UID Factory Settings
var Premadeletter94 = "Vous devez vous connecter pour charger Offres spéciales"; //You must login to load Special Deals
var Premadeletter95 = "Une fausse image a été copiée dans le presse-papiers. Coller"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "à la zone personnalisée Url de la peau afin d'activer la fonction de faux drapeau"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Informez-moi quand vous avez fini avec Recaptcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "j'ai fini"; //I have finished
var Premadeletter99 = "Ça ne fait rien"; //Never Mind
var Premadeletter100 = "Calcul de votre XP, veuillez patienter ..."; //Calculating your XP, please wait...
var Premadeletter101 = ""; //Do <---- I erased it in purpose
var Premadeletter102 = "N'appuie"; //NOT <--
var Premadeletter103 = "pas"; //press
var Premadeletter104 = "Effacer l'URL de l'habillage personnalisé"; //Erase custom skin URL
var Premadeletter105 = "sélectionnez la peau de la vidéo";	//select video skin
var Premadeletter106 = "désélectionner la peau de la vidéo"; //unselect video skin
var Premadeletter107 = "couper le son"; //mute audio
var Premadeletter108 = "Le projet LM"; //The LM Project
var Premadeletter109 = "Upload"; //Upload 
var Premadeletter109a = "Download"; //Download
var Premadeletter109b = "Chargement"; //Load

var Premadeletter110 = "n'entrez rien ici sauf si vous savez ce que c'est";	//do not enter anything here unless you know what it is
var Premadeletter111 = "cliquez sur l'icône orange pour acheter"; //click on the orange icon to buy
var Premadeletter112 = "Pour certaines méthodes de paiement"; //For some payment methods
var Premadeletter113 = "Fermer";	//Close
var Premadeletter114 = "COPIE"; //COPY	
var Premadeletter115 = "est utilisé pour acheter des offres pour vos amis"; //is used to buy offers for your friends
var Premadeletter116 = "Pour effectuer des achats, vous devez être connecté à votre compte ..."; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Bibliothèque"; //Library
var Premadeletter118 = "visite"; //visit
var Premadeletter119 = "Signaler comme faux (changer la peau)"; //Report as Fake (change Skin)
var Premadeletter120 = "Entrez votre nom exact du joueur"; //Enter your EXACT name of the player
var Premadeletter121 = "Abus des joueurs et utilisation inappropriée conduira UID de l'utilisateur"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "à l'interdiction permanente de l'utilisation de cette extension"; //to permanent ban from usage of this extension
var Premadeletter128 = "Connexion utilisateur nécessaire"; //User login needed
var Premadeletter129 = "Paramètres téléchargés avec succès"; //Settings successfully uploaded

//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERVEUR"; //SERVER
var Premadeletter124 = "Évitez d'utiliser des skins vidéo de plus de 6 minutes"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Carte fixe"; //Map fixed
var Premadeletter126 = "Connecté à"; //Logged in to
var Premadeletter127 = "Déconnecté"; //Logged out
var Premadeletter130 = "Total"; //Total
var Premadeletter131 = "NOUVEAU"; //NEW
var Premadeletter132 = "Rejoindre"; //Join Back
var Premadeletter133 = "Connectez-vous à la dernière adresse IP que vous avez jouée"; //Connect to last IP you played
var Premadeletter134 = "Amérique du Nord"; //North America
var Premadeletter135 = "Amérique du sud"; //South America
var Premadeletter136 = "L'Europe"; //Europe
var Premadeletter137 = "Russie"; //Russia
var Premadeletter138 = "Turquie"; //Turkey
var Premadeletter139 = "Asie de l'Est"; //East Asia
var Premadeletter139a = "Chine"; //China
var Premadeletter140 = "Océanie"; //Oceania
var Premadeletter140a = " -- Sélectionnez une région -- "; // -- Select a Region -- 
var Premadeletter141 = "Libre"; //FFA
var Premadeletter142 = "Bataille royale"; //Battle Royale
var Premadeletter143 = "Les équipes"; //Teams
var Premadeletter144 = "Expérimental"; //Experimental
var Premadeletter145 = "La partie"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "LANGUES"; //LANGUAGES
var Externalletter0b = "Choisissez une langue"; //Choose a language
var Externalletter0c = "Les changements auront lieu complètement après le redémarrage"; //Changes will take place completely after the restart
var Externalletter1 = "INFORMATION"; //INFORMATION
var Externalletter2 = "TEMPLATES"; //TEMPLATES
var Externalletter3 = "MANUAL TEMPLATES"; //MANUAL TEMPLATES
var Externalletter4 = "Choisissez votre template"; //Choose your template
var Externalletter5 = "Ou choisissez une extension"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "ENVOYER LE CODE AUX DÉVELOPPEURS"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Collez votre script dans cette Textarea, vous pouvez charger plusieurs Scripts"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Charger un script depuis Textarea"; //Load Script from Textarea
var Externalletter8 = "Choisir"; //Choose
var Externalletter9 = "Effacer le script"; //Erase Script
var Externalletter10 = "Nom"; //Name
var Externalletter11 = "Url de Raw Github, ou autre Raw Script, commençant par"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Laissez ce champ vide si le script n'est pas importé depuis l'URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "AVIS IMPORTANT: Ne conservez pas les URL qui ne fonctionnent pas, car elles sont utilisées en tant qu'événements onload. Si le scénario a endommagé les événements, puis SUPPRIMER LES COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
