/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="Unknown";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Home";		//Home
var Languageletter1="User";		//User
var Languageletter2="Settings";		//Settings
var Languageletter3="Theme";		//Theme
var Languageletter4="Hotkeys";		//Hotkeys
var Languageletter5="Youtube & Sounds";		//Youtube & Sounds
var Languageletter6="Tools";		//Tools
var Languageletter7="Leave it empty for Public, or insert password of Clan, or use it as Tag";		//Password/Tag
var Languageletter7a="Password/Tag"	;	//Password/Tag
var Languageletter8="Insert your in-game name, 50 chars are visible on Mod users, 15 to other users";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Name";		//Name
var Languageletter9="Insert your manual skin weblink";		//Insert your manual skin weblink
var Languageletter9a="Manual direct skin URL";		//Manual direct skin URL
var Languageletter10="The region to play";		//The region to play
var Languageletter11="The mode to play";		//The mode to play
var Languageletter12="Connect to server, or restablish communication";		//Connect to server, or restablish communication
var Languageletter12a="Connect";		//Connect
var Languageletter13="Join";		//Join
var Languageletter14="Play as guest";		//Play as guest
var Languageletter15="Login and Play";		//Login and Play
var Languageletter16="Spectate";		//Spectate
var Languageletter17="Sign in with Facebook";		//Sign in with Facebook
var Languageletter18="Sign in with Google";			//Sign in with Google
var Languageletter19="Play";		//Play
var Languageletter20="Shop"	;		//Shop
var Languageletter21="Free Coins";		//Free Coins
var Languageletter22="Gifts";		//Gifts
var Languageletter23="Daily Quests";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Legend Promo Video";		//Legend Promo Video
var Languageletter25a="New Ideas & Statistics Form";		//New Ideas & Statistics Form
var Languageletter25b="Mod Info & Templates";		//Mod Info & Templates
var Languageletter26="Add skins";		//Add skins
var Languageletter26a="Copy Server, Password, Teamboard & Leaderboard"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Logout";		//Logout
var Languageletter32="Times Used";		//Times Used
var Languageletter33="Legend Mod by";		//Legend Mod by
var Languageletter34="Translation by";		//Translation by
var Languageletter35="copy leaderboard names and cell names. (press x to show/hide)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animation";		//Animation
var Languageletter37="Animation delay";		//Animation delay
var Languageletter37a="Auto zoom";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Zoom speed:";		//Zoom speed: 

var Languageletter39="Respawn";			//Respawn
var Languageletter40="Auto respawn";		//Auto respawn 
var Languageletter41="Quick respawn ";			//Quick respawn 
var Languageletter41a="Spawn special effects ";			//Spawn special effects 
var Languageletter41b="Merge timer off ";			//Merge timer BETA off
var Languageletter41c="Suggested to be enabled for Lag reduce";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Virus shot sound";			//Virus shot sound

var Languageletter42="Names";			//Names
var Languageletter43="No names";		//No names 
var Languageletter44="Optimized names";		//Optimized names 
var Languageletter45="Auto hide names";		//Auto hide names 
var Languageletter46="Hide my name";		//Hide my name 
var Languageletter47="Hide teammates names";		//Hide teammates names 
var Languageletter48="Names stroke";		//Names stroke 
var Languageletter49="Mass";		//Mass
var Languageletter50="Show mass";		//Show mass 
var Languageletter51="Optimized mass"	;	//Optimized mass 
var Languageletter52="Auto hide mass";			//Auto hide mass 
var Languageletter53="Hide my mass";		//Hide my mass 
var Languageletter54="Hide enemies mass";		//Hide enemies mass 
var Languageletter55="Short mass";		//Short mass
var Languageletter56="Virus shots";		//Virus shots 
var Languageletter57="Mass stroke";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="No skins ";		//No skins 
var Languageletter60="Custom skins";		//Custom skins 
var Languageletter61="Vanilla skins";		//Vanilla skins 
var Languageletter61a="Jelly physics";		//Jelly physics 
var Languageletter61b="Video skins";		//Video skins
var Languageletter61c="Sound from other\'s Video skins when both C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Optimized food";		//Optimized food 
var Languageletter6a2="Food";		//Food 
var Languageletter63="Auto hide food (mass)";		//Auto hide food (mass) 
var Languageletter64="Auto hide food (zoom)";		//Auto hide food (zoom) 
var Languageletter65="Rainbow food";		//Rainbow food 
var Languageletter66="Transparency / colors";		//Transparency / colors
var Languageletter67="No colors";		//No colors 
var Languageletter68="My custom color";		//My custom color 
var Languageletter69="My transparent skin";		//My transparent skin 
var Languageletter70="Transparent skins";		//Transparent skins 
var Languageletter70a="Transparent cells";		//Transparent cells
var Languageletter71="Transparent viruses";		//Transparent viruses 
var Languageletter71a="Virus Glow";		//Virus Glow
var Languageletter71b="Animated rainbow colors";		//Animated rainbow colors

var Languageletter72="Grid / sectors";		//Grid / sectors
var Languageletter73="Show grid";		//Show grid 
var Languageletter74="Show background sectors";		//Show background sectors 
var Languageletter75="Show map borders";		//Show map borders 
var Languageletter75a="Border Glow";		//Border Glow

var Languageletter76="Chat";		//Chat
var Languageletter77="Disable chat";		//Disable chat 
var Languageletter78="Sound notifications";		//Sound notifications 
var Languageletter79="Emoticons";		//Emoticons 
var Languageletter80="Show images on chat";		//Show images on chat 
var Languageletter81="Show videos on chat";		//Show videos on chat 
var Languageletter82="Chatbox instead of popups";		//Chatbox instead of popups 
var Languageletter82a="Minimap";		//Minimap
var Languageletter82b="Show minimap";		//Show minimap 
var Languageletter82c="Show minimap grid";		//Show minimap grid 
var Languageletter82d="Show minimap guides";		//Show minimap guides 
var Languageletter82e="One-colored teammates";		//One-colored teammates 
var Languageletter82f="Show extra minimap guides";		//Show extra minimap guides
var Languageletter82g="Show ghost cells";		//Show ghost cells

var Languageletter83="Helpers";		//Helpers
var Languageletter84="Opponents colors";		//Opponents colors
var Languageletter85="Opponents rings";		//Opponents rings 
var Languageletter86="Viruses colors";		//Viruses colors 
var Languageletter87="Split range";		//Split range 
var Languageletter87a="Quick double split range";		//Quick double split range
var Languageletter87b="Slow double split range";		//Slow double split range

var Languageletter88="Viruses range";		//Viruses range 
var Languageletter89="Cursor tracking";		//Cursor tracking 
var Languageletter90="Teammates indicators";		//Teammates indicators 
var Languageletter90a="Ghost cells";		//Ghost cells

var Languageletter91="Mouse control";		//Mouse control
var Languageletter92="LMB - Mouse split";		//LMB - Mouse split 
var Languageletter93="RMB - Mouse feed";		//RMB - Mouse feed 
var Languageletter94="Invert mouse buttons";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="Team";		//Team
var Languageletter96="Show targeting";		//Show targeting 
var Languageletter96a="Show leaderboard mass";		//Show leaderboard mass

var Languageletter97="Centered leaderboard";		//Centered leaderboard 
var Languageletter97a="\"Leaderboard\" header ";		//\"Leaderboard\" header 

var Languageletter98="Game stats at the top";		//Game stats at the top 
var Languageletter98a="Skins on teamboard";		//Skins on teamboard

var Languageletter99="Stats";		//Stats
var Languageletter100="Show game stats";		//Show game stats 
var Languageletter101="Game stats";		//Game stats
//the \' is needed
var Languageletter102="Enemy\'s";		//Enemy\'s 		
var Languageletter103="Our";		//Our
var Languageletter104="Minimal tricksplit teammate\'s mass";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Maximal enemy\'s mass for presplit";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Show current time";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Skip stats after death";		//Skip stats after death 
var Languageletter108="Show quesτ";		//Show quest 
var Languageletter108a="Game sounds"; //Game Sounds
var Languageletter108b="Menu sounds"; //Menu Sounds
var Languageletter109="Block popups (ads/shop/quest)";		//Block popups (ads/shop/quest) 
var Languageletter109a="VOICE"; //Voice
var Languageletter109b="Voice-Prefix"; //Voice-Prefix
var Languageletter109c="Voice-lang"; //Voice-language
var Languageletter109d="UnPause"; //UnPause

var Languageletter110="-- Graphics Quality --";		//-- Graphics Quality --
var Languageletter111="Graphics: Retina";		//Graphics: Retina
var Languageletter112="Graphics: High";		//Graphics: High
var Languageletter113="Graphics: Medium";		//Graphics: Medium"
var Languageletter114="Graphics: Low";		//Graphics: Low
var Languageletter115="Graphics: Very Low";		//Graphics: Very Low
var Languageletter116="Export / import settings";		//Export / import settings
var Languageletter117="Restore default settings";		//Restore default settings
var Languageletter118="Export settings";		//Export settings
var Languageletter119="Import settings";		//Import settings
var Languageletter120="To export selected settings copy the code below and save it to a text file encoded in Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="To import selected settings paste an exported code below and press the 'Import settings' button.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Commands";		// Commands
var Languageletter123="Hotkeys";		// Hotkeys
var Languageletter124="Profiles";		// Profiles
var Languageletter125="Settings";		// Settings
var Languageletter126="Theme";		// Theme
var Languageletter127="Export settings";		//Export settings
var Languageletter128="Import settings";		//Import settings
var Languageletter129="Basic theming";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimap";		//Minimap
var Languageletter134="Graphics / cursors";		//Graphics / cursors
var Languageletter135="Theme preset";		//Theme preset
var Languageletter136="Legend Original";		//Legend Original
var Languageletter137="Crazy Style";		//Crazy Style 1
var Languageletter139="Background";		//Background
var Languageletter140="Map borders";		//Map borders
var Languageletter141="Grid";		//Grid
var Languageletter142="Sectors font";		//Sectors font
var Languageletter143="Names";		//Names
var Languageletter144="Names stroke";		//Names stroke
var Languageletter145="Mass";		//Mass
var Languageletter146="Mass stroke";		//Mass stroke
var Languageletter147="Virus stroke";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter148a="Mothercell";		//Mothercell
var Languageletter148b="Mothercell stroke";		//Mothercell stroke
var Languageletter149="Food";		//Food
var Languageletter150="Teammate indicator";		//Teammate indicator
var Languageletter151="Cursor tracking";		//Cursor tracking
var Languageletter152="Split range";		//Split range
var Languageletter153="Names font";		//Names font
var Languageletter154="Mass font";		//Mass font
var Languageletter154a="Bigger";		//Bigger
var Languageletter154b="Smaller";		//Smaller
var Languageletter155="Sectors font";		//Sectors font
var Languageletter157="Sectors font size";		//Sectors font size
var Languageletter158="Names scale";		//Names scale
var Languageletter159="Mass scale";		//Mass scale
var Languageletter160="Virus mass scale";		//Virus mass scale
var Languageletter161="Text stroke scale";		//Text stroke scale
var Languageletter162="Food size";		//Food size: 
var Languageletter163="Virus stroke size";		//Virus stroke size
var Languageletter164="Map borders width";		//Map borders width
var Languageletter165="Sectors grid width";		//Sectors grid width
var Languageletter166="Cells transparency";		//Cells transparency
var Languageletter167="Skins transparency";		//Skins transparency
var Languageletter168="Virus transparency";		//Virus transparency
var Languageletter169="Names & mass transparency";		//Names & mass transparency
var Languageletter170="Restore theme default settings";		//Restore theme default settings
var Languageletter171="Save settings";		//Save settings
var Languageletter172="Menu theme";		//Menu theme
var Languageletter173="Background";		//Background
var Languageletter174="Transparency";		//Transparency
var Languageletter175="Main color";		//Main color
var Languageletter176="Button text";		//Button text
var Languageletter177="Panel";		//Panel
var Languageletter179="Panel text";		//Panel text
var Languageletter181="Button";		//Button
var Languageletter189="Panel background image";		//Panel background image
var Languageletter190="Image URL";		//Image URL
//var Languageletter191="Main color";		//Main color
var Languageletter192="Background";		//Background
var Languageletter193="Text";		//Text
var Languageletter194="Stats";		//Stats
var Languageletter195="Time";		//Time
var Languageletter196="Top 5 mass";		//Top 5 mass
var Languageletter197="Leaderboard - me";		//Leaderboard - me
var Languageletter198="Leaderboard - teammate";		//Leaderboard - teammate
var Languageletter199="HUD font";		//HUD font
var Languageletter200="HUD scale";		//HUD scale: 
var Languageletter201="Message background";		//Message background
var Languageletter202="Message text";		//Message text
var Languageletter203="Message time";		//Message time
var Languageletter204="Message nick";		//Message nick
var Languageletter205="Command background";		//Command background
var Languageletter206="Command text";		//Command text
var Languageletter207="Command time";		//Command time
var Languageletter208="Command nick";		//Command nick
var Languageletter209="Chatbox color";		//Chatbox color
var Languageletter210="Chat scale";		//Chat scale
var Languageletter211="Sectors";		//Sectors
var Languageletter212="Current sector";		//Current sector
var Languageletter213="Nick";		//Nick
var Languageletter214="Nick stroke";		//Nick stroke
var Languageletter215="My cell";		//My cell
var Languageletter216="My cell stroke";		//My cell stroke
var Languageletter217="Teammates";		//Teammates
var Languageletter218="Death location";		//Death location
var Languageletter219="Guides";		//Guides
var Languageletter220="Minimap font";		//Minimap font
var Languageletter221="Nick font";		//Nick font
var Languageletter222="Minimap width";		//Minimap width
var Languageletter223="Sectors transparency";		//Sectors transparency
var Languageletter224="Nick size";		//Nick size
var Languageletter225="Nick stroke size";		//Nick stroke size
var Languageletter226="My cell size";		//My cell size
var Languageletter227="My cell stroke size";		//My cell stroke size
var Languageletter228="Teammates size";		//Teammates size
var Languageletter229="Custom background image";		//Custom background image
var Languageletter230="Custom cursor image";		//Custom cursor image
var Languageletter231="Image URL";		//Image URL
var Languageletter232="Cursor image URL";		//Cursor image URL
var Languageletter233="Feed";		//Feed
var Languageletter234="Macro feed";		//Macro feed
var Languageletter235="Split";		//Split
var Languageletter236="Double split";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="Split 16";		//Split 16
var Languageletter239="Cell pause";		//Cell pause
var Languageletter240="Show/hide team top 5";		//Show/hide team top 5
var Languageletter241="Show/hide current time";		//Show/hide current time
var Languageletter242="Show/hide split range";		//Show/hide split range"
var Languageletter243="Show/hide teammates indicators";		//Show/hide teammates indicators
var Languageletter244="Show/hide split indicators";		//Show/hide split indicators
var Languageletter245="Show/hide opponents colors";		//Show/hide opponents colors
var Languageletter246="Toggle skins (custom/default)";		//Toggle skins (custom/default)
var Languageletter247="Toggle transparent skins";		//Toggle transparent skins
var Languageletter248="Show/hide skins";		//Show/hide skins
var Languageletter249="Show/hide game stats";		//Show/hide game stats
var Languageletter250="Toggle own cells (smallest/biggest)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Show/hide food";		//Show/hide food
var Languageletter252="Show/hide grid";		//Show/hide grid
var Languageletter253="Show/hide minimap guides";		//Show/hide minimap guides
var Languageletter254="Show/hide chat";		//Show/hide chat
var Languageletter255="Show/hide HUD";		//Show/hide HUD
var Languageletter256="Copy leaderboard";		//Copy leaderboard
var Languageletter257="Show/hide leaderboard";		//Show/hide leaderboard
var Languageletter258="Toggle auto zoom";		//Toggle auto zoom
var Languageletter259="Reset zoom";		//Reset zoom
var Languageletter260="Toggle death location";		//Toggle death location
var Languageletter261="Show chat history / Clear chat";		//Show chat history / Clear chat
var Languageletter262="Show/hide background sectors";		//Show/hide background sectors
var Languageletter263="Show/hide small bots";		//Show/hide small bots
var Languageletter264="Show/hide names";		//Show/hide names
var Languageletter265="Show/hide teammates names";		//Show/hide teammates names
var Languageletter266="Show/hide mass";		//Show/hide mass
var Languageletter267="Show/hide minimap";		//Show/hide minimap
var Languageletter268="Enter chat message";		//Enter chat message
var Languageletter269="Quick respawn";		//Quick respawn
var Languageletter270="Toggle auto respawn";		//Toggle auto respawn
var Languageletter271="Zoom level";		//Zoom level 
var Languageletter271a="Voice to text";		//Voice to text
var Languageletter271b="Show ghost cells information";		//Show ghost cells information
var Languageletter271c="Auto Play";		//Auto Play
var Languageletter272="Show/hide targeting panel";		//Show/hide targeting panel
var Languageletter273="Start/stop targeting (following)";		//Start/stop targeting (following)
var Languageletter274="Cancel targeting";		//Cancel targeting
var Languageletter275="Change target";		//Change target
var Languageletter276="Show target on the minimap";		//Show target on the minimap
var Languageletter277="Show/hide quest";		//Show/hide quest
var Languageletter278="To assign a hotkey click on the input field and press your chosen key.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="To delete a hotkey click on the input field and press the DELETE key.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Possible key combinations with the CTRL and ALT keys.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Restore default settings";		//Restore default settings
var Languageletter282="Save settings";		//Save settings
var Languageletter283="Close";		//Close
var Languageletter284="Youtube player";		//Youtube player
var Languageletter284a="Youtube Url";		// Youtube Url
var Languageletter285="Paste your video/playlist here";		//Paste your video/playlist here
var Languageletter286="Sounds";		//Sounds
var Languageletter287="Message notification sound";		//Message notification sound
var Languageletter288="Command notification sound";		//Command notification sound
var Languageletter289="Copy Token/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Token";		//Token
var Languageletter290a="Board"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALL"; //TK&ALL (Token and All)
var Languageletter291="Copy";		//Copy

var Languageletter291a="Copy Leaderboard (L)";		//Copy Leaderboard (L)
var Languageletter291b="Copy Token/SIP&Password"; 	//Copy Token/SIP&Password
var Languageletter291c="Copy Token/SIP, Password, Leaderboard..."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="Join server (Backspace)";		//Join server (Backspace)
var Languageletter293="Change server (+)";		//Change server (+)
var Languageletter294="Leaderboard history";		//Leaderboard history
var Languageletter295="Enter friend token, IP, leaderboard, name or clan tag...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Clear list"; //Clear list
var Languageletter295b="Enter chat message..."; //Enter chat message...
var Languageletter298="Team top ";		//Team top 
var Languageletter299="Leaderbodard";		//Leaderbodard
var Languageletter300="Communication";		//Communication
var Languageletter301="Message Script Commands";		//Message Script Commands
var Languageletter302="Message Imgur Icons";		//Message Imgur Icons
var Languageletter303="Message Youtube Videos";		//Message Youtube Videos
var Languageletter304="Edit names";		//Edit names
var Languageletter305="[Spectate Mode Only] Binoculars";		//[Spectate Mode Only] Binoculars
var Languageletter306="Play / Pause";		//Play / Pause
var Languageletter307="Fullscreen";		//Fullscreen
var Languageletter308="Rotate";		//Rotate
var Languageletter309="Default";		//Default
var Languageletter310="Back";		//Back
var Languageletter311="Save for later";		//Save for later
var Languageletter312="Region";		//Region
var Languageletter313="Players";		//Players
var Languageletter314="Servers";		//Servers
var Languageletter315="[Target not set]";		//[Target not set]
var Languageletter316="Manual background";		//Manual background
var Languageletter317="Manual Message Icons&Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Chat Position";		//Chat Position
var Languageletter319="Discord Webhook Url (for sending TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Leaderboard";		//Leaderboard
var Languageletter321="Teamboard";		//Teamboard
var Languageletter322="Main Canvas";		//Main Canvas
var Languageletter323="Main Banner";		//Main Banner
var Languageletter324="Hello Team!";		//Hello Team!
var Languageletter325="Laugh to Team";		//Laugh to Team
var Languageletter326="Team Change Name to yours";		//Team Change Name to yours
var Languageletter327="Troll on Death";		//Troll on Death
var Languageletter328="Open Youtube Music";		//Open Youtube Music
var Languageletter329="Insane mode (Hide Everything)";		//Insane mode (Hide Everything)
var Languageletter330="Url of image starting with http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="Minimap Image URL";		//Minimap Image URL
var Languageletter332="Minimap Text";		//Minimap Text
var Languageletter333="Leaderboard Logo Text";		//Leaderboard Logo Text
var Languageletter333a="Leaderboard Image URL";		// Leaderboard Image URL
var Languageletter334="Teamboard Logo Text";		//Teamboard Logo Text
var Languageletter334a="Teamboard Image URL";		// Teamboard Image URL
var Languageletter335="Main Canvas Image URL";		//Main Canvas Image URL
var Languageletter336="Main Banner Icon URL";		//Main Banner Icon URL
var Languageletter337="Main Banner Link URL";		//Main Banner Link URL
var Languageletter338="Icon";		//Icon
var Languageletter339="e.g";		//e.g
var Languageletter340="Url of youtube to be shown";		//Url of youtube to be shown
var Languageletter341="Url of link to redirect";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="Message Icon Text";		//Message Icon Text
var Languageletter342b="Youtube Message Text";		//Youtube Message Text
var Languageletter342c="Message Icon Imgur Url";		//Message Icon Imgur Url
var Languageletter342d="Youtube Message Url";		//Youtube Message Url
var Languageletter343="Must be filled for function to work";		//Must be filled for function to work.
var Languageletter344="Secondary Webhook(optional)";		//Secondary Webhook(optional)
var Languageletter345="WARNING! Popups are blocked in the settings.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Temporary unblock";		//Temporary unblock
var Languageletter347="WARNING! Popups are blocked in the settings.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Temporary unblock";		//Temporary unblock

var Languageletter349="Potions";	//Potions
var Languageletter350="Old Skins";	//Old Skins
var Languageletter351="Special Deals"; //Special Deals
var Languageletter352="Leaderboards"; //Leaderboards
var Languageletter353="New Ideas & Statistics Form"; //New Ideas & Statistics Form
var Languageletter354="Video Skins"; //Video Skins
var Languageletter355="Mini Scripts"; //Mini Scripts
var Languageletter356="User Scripts"; //User Scripts
var Languageletter357="Voice & Camera Chat";	//Voice & Camera Chat
var Languageletter358="Please support the development of Legend mod";	//Please support the development of Legend mod
var Languageletter359="Design Nickname Font";	//Design Nickname Font
var Languageletter360="Flag the Fake Skin";	//Flag the Fake Skin
var Languageletter361="More FPS";	//More FPS
var Languageletter362="Name";	//Name
var Languageletter363="Social ID";	//Social ID
var Languageletter364="Expansions";	//Expansions
var Languageletter365="Universal";	//Universal
var Languageletter366="Score";	//Score
var Languageletter367="Distance";	//Distance
var Languageletter368="Total Mass";	//Total Mass
var Languageletter369="Dead";	//Dead

var Premadeletter0="Communication Activated"; 		//Communication Activated
var Premadeletter1="Cannot open this youtube URL";		 //Cannot open this youtube URL
var Premadeletter2="You cannot chat if player name > 15 chars"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Activated"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Activated";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Activated";		//Easter Egg 3 Activated
var Premadeletter6="Video works better on vanilla, visit:";		//Video works better on vanilla, visit:
var Premadeletter7="Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="If logout occurs on onload events, delete Chrome cookies from";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Disconnected from server :(";		//Disconnected from server :(
var Premadeletter11="You were banned, restart your rooter!";		//You were banned, restart your rooter!
var Premadeletter12="Connected!";		//Connected!
var Premadeletter13="PLAY";		//PLAY
var Premadeletter14="SPECTATE";		//SPECTATE
var Premadeletter15="Invalid token or server has closed :(";		//Invalid token or server has closed :(
var Premadeletter16="can be Updated to";		//can be Updated to
var Premadeletter17="Welcome back";			//Welcome back
var Premadeletter18="Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Enable Them";		//Enable Them
var Premadeletter20="Keep Them Disabled";		//Keep Them Disabled
var Premadeletter21="Searching IP";		//Searching IP
var Premadeletter22="Your teammate";		//Your teammate
var Premadeletter23="wants you to hide all (leaderboard and minimap)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Accept";		//Accept
var Premadeletter25="NO WAY!";		//NO WAY!
var Premadeletter26="wants you to change your name to";		//wants you to change your name to
var Premadeletter27="wants you to Enable Troll on death";		//wants you to hide Enable Troll on death
var Premadeletter28="wants you to open Youtube Player";			//wants you to open Youtube Player
var Premadeletter29="Leaderboard found";		//Leaderboard found
var Premadeletter30="Search";		//Search
var Premadeletter31="The leaderboard was not found. Keep trying...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Search was canceled";		//Search was canceled
var Premadeletter33="You are invisible to Team / Clan";		//You are invisible to Team / Clan
var Premadeletter34="You are visible to Team / Clan";		//You are visible to Team / Clan
var Premadeletter35="Hide/Show can be used only while playing";			//Hide/Show can be used only while playing
var Premadeletter36="This is not valid Discord Webhook address";		//This is not valid Discord Webhook address
var Premadeletter37="Server is locked";		//Server is locked
var Premadeletter38="You must be on spectate mode";		//You must be on spectate mode
var Premadeletter39="Due to spamming issues, you must be in game and use password";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube On";		//Auto Youtube On
var Premadeletter41="Auto Youtube Off";		//Auto Youtube Off
var Premadeletter42="Show Shortcuts";		//Show Shortcuts
var Premadeletter43="Hide Shortcuts";		//Hide Shortcuts
var Premadeletter44="Show XP BAR";		//Show XP BAR
var Premadeletter45="Hide XP BAR";		//Hide XP BAR
var Premadeletter45a = "Rounded Hud"; //Rounded Hud
var Premadeletter45b = "Square Hud"; //Square Hud
var Premadeletter46 = "Lin. color Hud"; //Linear color Hud
var Premadeletter47 = "Hide Anim. Skins"; //Bold color Hud

var Premadeletter48="Show Everything";		//Show Everything
var Premadeletter49="Hide Everything";		//Hide Everything
var Premadeletter50="Show Timer Calc.";		//Show Timer Calc.
var Premadeletter51="Hide Timer Calc."		//Hide Timer Calc.

var Premadeletter53="Auto free coins";		//Auto free coins
var Premadeletter54="Stop free coins";		//Stop free coins
var Premadeletter55="Troll on Death";		//Troll on Death
var Premadeletter56="No troll on Death";		//No troll on Death

var Premadeletter57="Communication";		//Communication
var Premadeletter58="Hidden";		//Hidden
var Premadeletter59="Visible";		//Visible
var Premadeletter60="Pause";		//Pause

var Premadeletter61 = "Enable YT as background";	//Enable YT as background
var Premadeletter62 = "Disable YT as background";	//Disable YT as background";
var Premadeletter63 = "wants you to open the url";	//wants you to open the url
var Premadeletter64 = "wants you to embed and play this youtube video";	//wants you to embed and play this youtube video
var Premadeletter65 = "wants you to join the following Skype room";	//wants you to join the following Skype room
var Premadeletter66 = "wants you to join the following Discord room";	//wants you to join the following Discord room
var Premadeletter67 = "wants you to leave this server and join this new one";	//wants you to leave this server and join this new one

var Premadeletter68 = "You pressed"; //You pressed
var Premadeletter69 = "restart if"; //restart if
var Premadeletter70 = "drops"; //drops
var Premadeletter71 = "Animated skins"; //Animated skins
var Premadeletter72 = "enabled"; //enabled
var Premadeletter73 = "drop"; //drop
var Premadeletter74 = "when"; //when
var Premadeletter75 = "Animated skins will be"; //Animated skins will be
var Premadeletter76 = "disabled"; //disabled
var Premadeletter77 = "after rejoin"; //after rejoin
var Premadeletter78 = "Better FPS"; //Better FPS
var Premadeletter79 = "performance when 16"; //performance when 16
var Premadeletter80 = "When Dying Light Expansion is enabled, Troll on death cannot occur"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Private Server"; //Private Server
var Premadeletter82 = "Connect to any"; //Connect to any
var Premadeletter83 = "server, or make your own"; //server, or make your own
var Premadeletter84 = "Play agario-like games if you know the IP of servers"; //Play agario-like games if you know the IP of servers
var Premadeletter85 = "Your image has been copied to clipboard. Paste it"; // Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "to custom skin Url area"; //to custom skin Url area
var Premadeletter87 = "You must Login to use picture of your profile"; //You must Login to use picture of your profile
var Premadeletter88 = "You are using a wrong version"; //You are using a wrong version
var Premadeletter89 = "Game will terminate now"; //Game will terminate now
var Premadeletter90 = "Special Deals"; //Special Deals
var Premadeletter91 = "Agario may or may not give you the Skin, but only the coins"; //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Use at your own risk"; //Use at your own risk
var Premadeletter92 = "If UID of your friend is wrong, purchase will fail"; //If friend UID is wrong, purchase will fail
var Premadeletter93 = "UID Factory Settings"; //UID Factory Settings
var Premadeletter94 = "You must login to load Special Deals"; //You must login to load Special Deals
var Premadeletter95 = "Fake image has been copied to clipboard. Paste it"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 = "to custom skin Url area in order to activate the fake flag function"; // o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Inform me when you finish with Recapatcha"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "I have finished"; //I have finished
var Premadeletter99 = "Never Mind"; //Never Mind
var Premadeletter100 = "Calculating your XP, please wait..."; //Calculating your XP, please wait...
var Premadeletter101 = "Do"; //Do
var Premadeletter102 = "NOT"; //NOT
var Premadeletter103 = "press"; //press
var Premadeletter104 = "Erase custom skin URL"; //Erase custom skin URL
var Premadeletter105 = "select video skin";	//select video skin
var Premadeletter106 = "unselect video skin"; //unselect video skin
var Premadeletter107 = "mute audio"; //mute audio
var Premadeletter108 = "The LM Project"; //The LM Project
var Premadeletter109 = "Upload"; //Upload 
var Premadeletter109a = "Download"; //Download
var Premadeletter109b = "Load"; //Load
var Premadeletter110 = "do not enter anything here unless you know what it is";	//do not enter anything here unless you know what it is
var Premadeletter111 = "click on the orange icon to buy"; //click on the orange icon to buy
var Premadeletter112 = "For some payment methods"; //For some payment methods
var Premadeletter113 = "Close";	//Close
var Premadeletter114 = "COPY"; //COPY	
var Premadeletter115 = "is used to buy offers for your friends"; //is used to buy offers for your friends
var Premadeletter116 = "To make purchases, you must be logged in to your account…"; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Library"; //Library
var Premadeletter118 = "visit"; //visit
var Premadeletter119 = "Report as Fake (change Skin)"; //Report as Fake (change Skin)
var Premadeletter120 = "Enter your EXACT name of the player"; //Enter your EXACT name of the player
var Premadeletter121 = "Abusing players and inappropriate use will lead UID of user"; //Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "to permanent ban from usage of this extension"; //to permanent ban from usage of this extension
var Premadeletter128 = "User login needed"; //User login needed
var Premadeletter129 = "Settings successfully uploaded"; //Settings successfully uploaded

//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERVER"; //SERVER
var Premadeletter124 = "Avoid using video skins bigger than 6 minutes"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Map fixed"; //Map fixed
var Premadeletter126 = "Logged in to"; //Logged in to
var Premadeletter127 = "Logged out"; //Logged out
var Premadeletter130 = "Total"; //Total
var Premadeletter131 = "NEW"; //NEW
var Premadeletter132 = "Join Back"; //Join Back
var Premadeletter133 = "Connect to last IP you played"; //Connect to last IP you played
var Premadeletter134 = "North America"; //North America
var Premadeletter135 = "South America"; //South America
var Premadeletter136 = "Europe"; //Europe
var Premadeletter137 = "Russia"; //Russia
var Premadeletter138 = "Turkey"; //Turkey
var Premadeletter139 = "East Asia"; //East Asia
var Premadeletter139a = "China"; //China
var Premadeletter140 = "Oceania"; //Oceania
var Premadeletter140a = " -- Select a Region -- "; // -- Select a Region -- 
var Premadeletter141 = "FFA"; //FFA
var Premadeletter142 = "Battle Royale"; //Battle Royale
var Premadeletter143 = "Teams"; //Teams
var Premadeletter144 = "Experimental"; //Experimental
var Premadeletter145 = "Party Mode"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "LANGUAGES"; //LANGUAGES
var Externalletter0b = "Choose a language"; //Choose a language
var Externalletter0c = "Changes will take place completely after the restart"; //Changes will take place completely after the restart
var Externalletter1 = "INFORMATION"; //INFORMATION
var Externalletter2 = "TEMPLATES"; //TEMPLATES
var Externalletter3 = "MANUAL TEMPLATES"; //MANUAL TEMPLATES
var Externalletter4 = "Choose your template"; //Choose your template
var Externalletter5 = "Or choose an expansion"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "SEND CODE TO DEVELOPERS"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Paste your Script in this Textarea, you can load multiple Scripts"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Load Script from Textarea"; //Load Script from Textarea
var Externalletter8 = "Choose"; //Choose
var Externalletter9 = "Erase Script"; //Erase Script
var Externalletter10 = "Name"; //Name
var Externalletter11 = "Url of Raw Github, or other Raw Script, starting with"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Leave this empty if script not imported from URL"; //Leave this empty if script not imported from URL
var Externalletter13 = "IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
