/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="Unknown";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Home";		//Home
var Languageletter1="User";		//User
var Languageletter2="Settings";		//Settings
var Languageletter3="Theme";		//Theme
var Languageletter4="Hotkeys";		//Hotkeys
var Languageletter5="Youtube & Sounds";		//Youtube & Sounds
var Languageletter6="Tools";		//Tools
var Languageletter7="Leave it empty for Public, or insert password of Clan, or use it as Tag";		//Password/Tag
var Languageletter7a="Password/Tag"	;	//Password/Tag
var Languageletter8="Insert your in-game name, 50 chars are visible on Mod users, 15 to other users";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Name";		//Name
var Languageletter9="Insert your manual skin weblink";		//Insert your manual skin weblink
var Languageletter9a="Manual direct skin URL";		//Manual direct skin URL
var Languageletter10="The region to play";		//The region to play
var Languageletter11="The mode to play";		//The mode to play
var Languageletter12="Connect to server, or restablish communication";		//Connect to server, or restablish communication
var Languageletter12a="Connect";		//Connect
var Languageletter13="Join";		//Join
var Languageletter14="Play as guest";		//Play as guest
var Languageletter15="Login and Play";		//Login and Play
var Languageletter16="Spectate";		//Spectate
var Languageletter17="Sign in with Facebook";		//Sign in with Facebook
var Languageletter18="Sign in with Google";			//Sign in with Google
var Languageletter19="Play";		//Play
var Languageletter20="Shop"	;		//Shop
var Languageletter21="Free Coins";		//Free Coins
var Languageletter22="Gifts";		//Gifts
var Languageletter23="Daily Quests";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Legend Promo Video";		//Legend Promo Video
var Languageletter26="Add skins";		//Add skins
var Languageletter27="Free Coins";		//Free Coins
var Languageletter31="Logout";		//Logout
var Languageletter32="Times Used";		//Times Used
var Languageletter33="Legend Mod by";		//Legend Mod by
var Languageletter34="Translation by";		//Translation by
var Languageletter35="copy leaderboard names and cell names. (press x to show/hide)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animation";		//Animation
var Languageletter37="Animation delay:";		//Animation delay: 
var Languageletter37a="Auto zoom";		// Auto zoom
var Languageletter38="Zoom speed:";		//Zoom speed: 
var Languageletter39="Respawn";			//Respawn
var Languageletter40="Auto respawn";		//Auto respawn 
var Languageletter41="Quick respawn (hotkey) ";			//Quick respawn (hotkey) 
var Languageletter42="Names";			//Names
var Languageletter43="No names ";		//No names 
var Languageletter44="Optimized names";		//Optimized names 
var Languageletter45="Auto hide names ";		//Auto hide names 
var Languageletter46="Hide my name ";		//Hide my name 
var Languageletter47="Hide teammates names ";		//Hide teammates names 
var Languageletter48="Names stroke ";		//Names stroke 
var Languageletter49="Mass";		//Mass
var Languageletter50="Show mass ";		//Show mass 
var Languageletter51="Optimized mass (+/-2%) "	;	//Optimized mass (+/-2%) 
var Languageletter52="Auto hide mass ";			//Auto hide mass 
var Languageletter53="Hide my mass ";		//Hide my mass 
var Languageletter54="Hide enemies mass ";		//Hide enemies mass 
var Languageletter55="Short mass";		//Short mass
var Languageletter56="Virus shots";		//Virus shots 
var Languageletter57="Mass stroke";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="No skins ";		//No skins 
var Languageletter60="Custom skins";		//Custom skins 
var Languageletter61="Vanilla skins";		//Vanilla skins 
var Languageletter62="Optimized food";		//Optimized food 
var Languageletter6a2="Food";		//Food 
var Languageletter63="Auto hide food (mass)";		//Auto hide food (mass) 
var Languageletter64="Auto hide food (zoom)";		//Auto hide food (zoom) 
var Languageletter65="Rainbow food";		//Rainbow food 
var Languageletter66="Transparency / colors";		//Transparency / colors
var Languageletter67="No colors";		//No colors 
var Languageletter68="My custom color";		//My custom color 
var Languageletter69="My transparent skin";		//My transparent skin 
var Languageletter70="Transparent skins";		//Transparent skins 
var Languageletter71="Transparent viruses";		//Transparent viruses 
var Languageletter72="Grid / sectors";		//Grid / sectors
var Languageletter73="Show grid";		//Show grid 
var Languageletter74="Show background sectors";		//Show background sectors 
var Languageletter75="Show map borders";		//Show map borders 
var Languageletter76="Chat";		//Chat
var Languageletter77="Disable chat";		//Disable chat 
var Languageletter78="Sound notifications";		//Sound notifications 
var Languageletter79="Emoticons";		//Emoticons 
var Languageletter80="Show images on chat";		//Show images on chat 
var Languageletter81="Show videos on chat";		//Show videos on chat 
var Languageletter82="Chatbox instead of popups";		//Chatbox instead of popups 
var Languageletter83="Helpers";		//Helpers
var Languageletter84="Opponents colors";		//Opponents colors
var Languageletter85="Opponents rings";		//Opponents rings 
var Languageletter86="Viruses colors";		//Viruses colors 
var Languageletter87="Split range";		//Split range 
var Languageletter88="Viruses range";		//Viruses range 
var Languageletter89="Cursor tracking";		//Cursor tracking 
var Languageletter90="Teammates indicators";		//Teammates indicators 
var Languageletter91="Mouse control";		//Mouse control
var Languageletter92="LMB - Mouse split";		//LMB - Mouse split 
var Languageletter93="RMB - Mouse feed";		//RMB - Mouse feed 
var Languageletter94="Invert mouse buttons";		//Invert mouse buttons 
var Languageletter94a=" HUD";		// HUD
var Languageletter95="Show team top 5";		//Show team top 5 
var Languageletter96="Show targeting";		//Show targeting 
var Languageletter97="Centered leaderboard";		//Centered leaderboard 
var Languageletter98="Game stats at the top";		//Game stats at the top 
var Languageletter99="Stats";		//Stats
var Languageletter100="Show game stats";		//Show game stats 
var Languageletter101="Game stats: Mass";		//Game stats: Mass 
var Languageletter102="Game stats: STE";		//Game stats: STE 
var Languageletter103="Game stats: n/16";		//Game stats: n/16 
var Languageletter104="Game stats: FPS";		//Game stats: FPS 
var Languageletter105="Show current time";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Skip stats after death";		//Skip stats after death 
var Languageletter108="Show ques ";		//Show quest 
var Languageletter109="Block popups (ads/shop/quest)";		//Block popups (ads/shop/quest) 
var Languageletter110="-- Graphics Quality --";		//-- Graphics Quality --
var Languageletter111="Graphics: Retina";		//Graphics: Retina
var Languageletter112="Graphics: High";		//Graphics: High
var Languageletter113="Graphics: Medium";		//Graphics: Medium"
var Languageletter114="Graphics: Low";		//Graphics: Low
var Languageletter115="Graphics: Very Low";		//Graphics: Very Low
var Languageletter116="Export / import settings";		//Export / import settings
var Languageletter117="Restore default settings";		//Restore default settings
var Languageletter118="Export settings";		//Export settings
var Languageletter119="Import settings";		//Import settings
var Languageletter120="To export selected settings copy the code below and save it to a text file encoded in Unicode.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="To import selected settings paste an exported code below and press the 'Import settings' button.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Commands";		// Commands
var Languageletter123="Hotkeys";		// Hotkeys
var Languageletter124="Profiles";		// Profiles
var Languageletter125="Settings";		// Settings
var Languageletter126="Theme";		// Theme
var Languageletter127="Export settings";		//Export settings
var Languageletter128="Import settings";		//Import settings
var Languageletter129="Basic theming";		//Basic theming
var Languageletter130="Menu";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimap";		//Minimap
var Languageletter134="Graphics / cursors";		//Graphics / cursors
var Languageletter135="Theme preset";		//Theme preset
var Languageletter136="Legend Original";		//Legend Original
var Languageletter137="Crazy Style ";		//Crazy Style 1
var Languageletter139="Background";		//Background
var Languageletter140="Map borders";		//Map borders
var Languageletter141="Grid";		//Grid
var Languageletter142="Sectors font";		//Sectors font
var Languageletter143="Names";		//Names
var Languageletter144="Names stroke";		//Names stroke
var Languageletter145="Mass";		//Mass
var Languageletter146="Mass stroke";		//Mass stroke
var Languageletter147="Virus stroke";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter149="Food";		//Food
var Languageletter150="Teammate indicator";		//Teammate indicator
var Languageletter151="Cursor tracking";		//Cursor tracking
var Languageletter152="Split range";		//Split range
var Languageletter153="Names font";		//Names font
var Languageletter154="Mass font";		//Mass font
var Languageletter155="Sectors font";		//Sectors font
var Languageletter156="Sectors font size";		//Sectors font size
var Languageletter157="Sectors font size";		//Sectors font size
var Languageletter158="Names scale";		//Names scale
var Languageletter159="Mass scale";		//Mass scale
var Languageletter160="Virus mass scale";		//Virus mass scale
var Languageletter161="Text stroke scale";		//Text stroke scale
var Languageletter162="Text stroke scale";		// Text stroke scale
var Languageletter163="Food size";		//Food size: 
var Languageletter164="Virus stroke size";		//Virus stroke size
var Languageletter165="Map borders width";		//Map borders width
var Languageletter166="Cells transparency";		//Cells transparency
var Languageletter167="Skins transparency";		//Skins transparency
var Languageletter168="Virus transparency";		//Virus transparency
var Languageletter169="Names & mass transparency";		//Names & mass transparency
var Languageletter170="Restore theme default settings";		//Restore theme default settings
var Languageletter171="Save settings";		//Save settings
var Languageletter172="Menu theme";		//Menu theme
var Languageletter173="Background";		//Background
var Languageletter174="Transparency";		//Transparency
var Languageletter175="Main color";		//Main color
var Languageletter176="Button text";		//Button text
var Languageletter177="Panel";		//Panel
var Languageletter179="Panel text";		//Panel text
var Languageletter181="Button";		//Button
var Languageletter189="Panel background image";		//Panel background image
var Languageletter190="Image URL";		//Image URL
var Languageletter191="Main color";		//Main color
var Languageletter192="Background";		//Background
var Languageletter193="Text";		//Text
var Languageletter194="Stats";		//Stats
var Languageletter195="Time";		//Time
var Languageletter196="Top 5 mass";		//Top 5 mass
var Languageletter197="Leaderboard - me";		//Leaderboard - me
var Languageletter198="Leaderboard - teammate";		//Leaderboard - teammate
var Languageletter199="HUD font";		//HUD font
var Languageletter200="HUD scale: ";		//HUD scale: 
var Languageletter201="Message background";		//Message background
var Languageletter202="Message text";		//Message text
var Languageletter203="Message time";		//Message time
var Languageletter204="Message nick";		//Message nick
var Languageletter205="Command background";		//Command background
var Languageletter206="Command text";		//Command text
var Languageletter207="Command time";		//Command time
var Languageletter208="Command nick";		//Command nick
var Languageletter209="Chatbox color";		//Chatbox color
var Languageletter210="Chat scale";		//Chat scale
var Languageletter211="Sectors";		//Sectors
var Languageletter212="Current sector";		//Current sector
var Languageletter213="Nick";		//Nick
var Languageletter214="Nick stroke";		//Nick stroke
var Languageletter215="My cell";		//My cell
var Languageletter216="My cell stroke";		//My cell stroke
var Languageletter217="Teammates";		//Teammates
var Languageletter218="Death location";		//Death location
var Languageletter219="Guides";		//Guides
var Languageletter220="Minimap font";		//Minimap font
var Languageletter221="Nick font";		//Nick font
var Languageletter222="Minimap width";		//Minimap width
var Languageletter223="Sectors transparency";		//Sectors transparency
var Languageletter224="Nick size";		//Nick size
var Languageletter225="Nick stroke size";		//Nick stroke size
var Languageletter226="My cell size";		//My cell size
var Languageletter227="My cell stroke size";		//My cell stroke size
var Languageletter228="Teammates size";		//Teammates size
var Languageletter229="Custom background image";		//Custom background image
var Languageletter230="Custom cursor image";		//Custom cursor image
var Languageletter231="Image URL";		//Image URL
var Languageletter232="Cursor image URL";		//Cursor image URL
var Languageletter233="Feed";		//Feed
var Languageletter234="Macro feed";		//Macro feed
var Languageletter235="Split";		//Split
var Languageletter236="Double split";		//Double split
var Languageletter237="Popsplit";		//Popsplit
var Languageletter238="Split 16";		//Split 16
var Languageletter239="Cell pause";		//Cell pause
var Languageletter240="Show/hide team top 5";		//Show/hide team top 5
var Languageletter241="Show/hide current time";		//Show/hide current time
var Languageletter242="Show/hide split range";		//Show/hide split range"
var Languageletter243="Show/hide teammates indicators";		//Show/hide teammates indicators
var Languageletter244="Show/hide split indicators";		//Show/hide split indicators
var Languageletter245="Show/hide opponents colors";		//Show/hide opponents colors
var Languageletter246="Toggle skins (custom/default)";		//Toggle skins (custom/default)
var Languageletter247="Toggle transparent skins";		//Toggle transparent skins
var Languageletter248="Show/hide skins";		//Show/hide skins
var Languageletter249="Show/hide game stats";		//Show/hide game stats
var Languageletter250="Toggle own cells (smallest/biggest)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Show/hide food";		//Show/hide food
var Languageletter252="Show/hide grid";		//Show/hide grid
var Languageletter253="Show/hide minimap guides";		//Show/hide minimap guides
var Languageletter254="Show/hide chat";		//Show/hide chat
var Languageletter255="Show/hide HUD";		//Show/hide HUD
var Languageletter256="Copy leaderboard";		//Copy leaderboard
var Languageletter257="Show/hide leaderboard";		//Show/hide leaderboard
var Languageletter258="Toggle auto zoom";		//Toggle auto zoom
var Languageletter259="Reset zoom";		//Reset zoom
var Languageletter260="Toggle death location";		//Toggle death location
var Languageletter261="Show chat history / Clear chat";		//Show chat history / Clear chat
var Languageletter262="Show/hide background sectors";		//Show/hide background sectors
var Languageletter263="Show/hide small bots";		//Show/hide small bots
var Languageletter264="Show/hide names";		//Show/hide names
var Languageletter265="Show/hide teammates names";		//Show/hide teammates names
var Languageletter266="Show/hide mass";		//Show/hide mass
var Languageletter267="Show/hide minimap";		//Show/hide minimap
var Languageletter268="Enter chat message";		//Enter chat message
var Languageletter269="Quick respawn";		//Quick respawn
var Languageletter270="Toggle auto respawn";		//Toggle auto respawn
var Languageletter271="Zoom level";		//Zoom level 
var Languageletter272="Show/hide targeting panel";		//Show/hide targeting panel
var Languageletter273="Start/stop targeting (following)";		//Start/stop targeting (following)
var Languageletter274="Cancel targeting";		//Cancel targeting
var Languageletter275="Change target";		//Change target
var Languageletter276="Show target on the minimap";		//Show target on the minimap
var Languageletter277="Show/hide quest";		//Show/hide quest
var Languageletter278="To assign a hotkey click on the input field and press your chosen key.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="To delete a hotkey click on the input field and press the DELETE key.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Possible key combinations with the CTRL and ALT keys.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Restore default settings";		//Restore default settings
var Languageletter282="Save settings";		//Save settings
var Languageletter283="Close";		//Close
var Languageletter284="Youtube player";		//Youtube player
var Languageletter284a="Youtube Url";		// Youtube Url
var Languageletter285="Paste your video/playlist here";		//Paste your video/playlist here
var Languageletter286="Sounds";		//Sounds
var Languageletter287="Message notification sound";		//Message notification sound
var Languageletter288="Command notification sound";		//Command notification sound
var Languageletter289="Copy Token/SIP";		//Copy Token/SIP
var Languageletter290="Token";		//Token
var Languageletter291="Copy";		//Copy
var Languageletter291="Copy Leaderboard (L)";		//Copy Leaderboard (L)
var Languageletter292="Join server (Backspace)";		//Join server (Backspace)
var Languageletter293="Change server (+)";		//Change server (+)
var Languageletter294="Leaderboard history";		//Leaderboard history
var Languageletter295="Enter friend\'s token, IP, leaderboard, name or clan tag...";		//Enter friend\'s token, IP, leaderboard, name or clan tag...
var Languageletter296="Active players";		// Active players
var Languageletter297="Total mass";		// Total mass
var Languageletter298="Team top ";		//Team top 
var Languageletter299="Leaderbodard";		//Leaderbodard
var Languageletter300="Communication";		//Communication
var Languageletter301="Message Script Commands";		//Message Script Commands
var Languageletter302="Message Imgur Icons";		//Message Imgur Icons
var Languageletter303="Message Youtube Videos";		//Message Youtube Videos
var Languageletter304="Edit names";		//Edit names
var Languageletter305="[Spectate Mode Only] Binoculars";		//[Spectate Mode Only] Binoculars
var Languageletter306="Play / Pause";		//Play / Pause
var Languageletter307="Fullscreen";		//Fullscreen
var Languageletter308="Rotate";		//Rotate
var Languageletter309="Default";		//Default
var Languageletter310="Back";		//Back
var Languageletter311="Save for later";		//Save for later
var Languageletter312="Region";		//Region
var Languageletter313="Players";		//Players
var Languageletter314="Servers";		//Servers
var Languageletter315="[Target not set]";		//[Target not set]
var Languageletter316="Manual background";		//Manual background
var Languageletter317="Manual Message Icons&Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Chat Position";		//Chat Position
var Languageletter319="Discord Webhook Url (for sending TOKEN)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Leaderboard";		//Leaderboard
var Languageletter321="Teamboard";		//Teamboard
var Languageletter322="Main Canvas";		//Main Canvas
var Languageletter323="Main Banner";		//Main Banner
var Languageletter324="Hello Team!";		//Hello Team!
var Languageletter325="Laugh to Team";		//Laugh to Team
var Languageletter326="Team Change Name to yours";		//Team Change Name to yours
var Languageletter327="Troll on Death";		//Troll on Death
var Languageletter328="Open Youtube Music";		//Open Youtube Music
var Languageletter329="Insane mode (Hide Everything)";		//Insane mode (Hide Everything)
var Languageletter330="Url of image starting with http://... or https://...";		//Url of image starting with http://... or https://...
var Languageletter331="Minimap Image URL";		//Minimap Image URL
var Languageletter332="Minimap Text";		//Minimap Text
var Languageletter333="Leaderboard Logo Text";		//Leaderboard Logo Text
var Languageletter333a=" Leaderboard Image URL";		// Leaderboard Image URL
var Languageletter334="Teamboard Logo Text";		//Teamboard Logo Text
var Languageletter334a=" Teamboard Image URL";		// Teamboard Image URL
var Languageletter335="Main Canvas Image URL";		//Main Canvas Image URL
var Languageletter336="Main Banner Icon URL";		//Main Banner Icon URL
var Languageletter337="Main Banner Link URL";		//Main Banner Link URL
var Languageletter338="Icon";		//Icon
var Languageletter339="e.g";		//e.g
var Languageletter340="Url of youtube to be shown";		//Url of youtube to be shown
var Languageletter341="Url of link to redirect";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter343="Must be filled for fuction to work";		//Must be filled for fuction to work.
var Languageletter344="Secondary Webhook(optional)";		//Secondary Webhook(optional)
var Languageletter345="Temporarily Hide/Show Everything. Function for Youtubers";		//Temporarily Hide/Show Everything. Function for Youtubers
var Premadeletter0= "Communication Activated"; 		//Communication Activated
var Premadeletter1="Cannot open this youtube URL";		 //Cannot open this youtube URL
var Premadeletter2="[SERVER]: You cannot chat if player name > 15 chars"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Activated"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Activated";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Activated";		//Easter Egg 3 Activated
var Premadeletter6="Video works better on vanilla, visit:";		//Video works better on vanilla, visit:
var Premadeletter7="Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="If logout occurs on onload events, delete Chrome cookies from ";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Disconnected from server :(";		//Disconnected from server :(
var Premadeletter11="You were banned, restart your rooter!";		//You were banned, restart your rooter!
var Premadeletter12="Connected!";		//Connected!
var Premadeletter13="PLAY";		//PLAY
var Premadeletter14="SPECTATE";		//SPECTATE
var Premadeletter15="Invalid token or server has closed :(";		//Invalid token or server has closed :(
var Premadeletter16="can be Updated to";		//can be Updated to
var Premadeletter17="Welcome back";			//Welcome back
var Premadeletter18="Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Enable Them";		//Enable Them
var Premadeletter20="Keep Them Disabled";		//Keep Them Disabled
var Premadeletter21="Searching IP";		//Searching IP
var Premadeletter22="Your teammate";		//Your teammate
var Premadeletter23="wants you to hide all (leaderboard and minimap)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Accept";		//Accept
var Premadeletter25="NO WAY!";		//NO WAY!
var Premadeletter26="wants you to change your name to";		//wants you to change your name to
var Premadeletter27="wants you to hide Enable Troll on death";		//wants you to hide Enable Troll on death
var Premadeletter28="wants you to open Youtube Player";			//wants you to open Youtube Player
var Premadeletter29="Leaderboard found";		//Leaderboard found
var Premadeletter30="Search";		//Search
var Premadeletter31="The leaderboard was not found. Keep trying...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Search was canceled";		//Search was canceled
var Premadeletter33="You are invisible to Team / Clan";		//You are invisible to Team / Clan
var Premadeletter34="You are visible to Team / Clan";		//You are visible to Team / Clan
var Premadeletter35="Hide/Show can be used only while playing";			//Hide/Show can be used only while playing
var Premadeletter36="This is not valid Discord Webhook address";		//This is not valid Discord Webhook address
var Premadeletter37="Server is locked";		//Server is locked
var Premadeletter38="You must be on spectate mode";		//You must be on spectate mode
var Premadeletter39="Due to spamming issues, you must be in game and use password";		//Due to spamming issues, you must be in game and use password
var Premadeletter40="Auto Youtube On";		//Auto Youtube On
var Premadeletter41="Auto Youtube Off";		//Auto Youtube Off
var Premadeletter42="Show Shortcuts";		//Show Shortcuts
var Premadeletter43="Hide Shortcuts";		//Hide Shortcuts
var Premadeletter44="Show XP BAR";		//Show XP BAR
var Premadeletter45="Hide XP BAR";		//Hide XP BAR
var Premadeletter46="Show TIME";		//Show TIME
var Premadeletter47="Hide TIME";		//Hide TIME
var Premadeletter48="Show Everything";		//Show Everything
var Premadeletter49="Hide Everything";		//Hide Everything
var Premadeletter50="Show Timer Calc.";		//Show Timer Calc.
var Premadeletter51="Hide Timer Calc."		//Hide Timer Calc.
var Premadeletter52="Edit Names";		//Edit Names
var Premadeletter53="Auto free coins";		//Auto free coins
var Premadeletter54="Stop free coins";		//Stop free coins
var Premadeletter55="Troll on Death";		//Troll on Death
var Premadeletter56="No troll on Death";		//No troll on Death
var Premadeletter57="Communication";		//Communication
var Premadeletter58="Hidden";		//Hidden
var Premadeletter59="Visible";		//Visible
