/*         var Languageletter =         "hello you" <---  You tranlate this, keep the " "; as they are.       // <-Means notes, no need to change           */

/* Example            var Languageletter0="Home";  //Home      ->    var Languageletter0="Maison";            //Home                                        */

/* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is        */

/*                                                  Thank you for supporting Legend Agar.io mod                                                             */



var translator="Gold1Aut";		//Put your nickname, in order to be reffered to mod, or use name "Unknown"


var Languageletter0="Home";		//Home
var Languageletter1="Benutzer";		//User
var Languageletter2="Einstellungen";		//Settings
var Languageletter3="Design";		//Theme
var Languageletter4="Hotkeys";		//Hotkeys
var Languageletter5="Youtube & Sounds";		//Youtube & Sounds
var Languageletter6="Tools";		//Tools
var Languageletter7="lass es für die Öffentlichkeit leer, füge das Passwort des Clans ein oder verwende es als Tag";		//Leave it empty for Public, or insert password of Clan, or use it as Tag";
//Password/Tag
var Languageletter7a="Passwort/Tag"	;	//Password/Tag
var Languageletter8= "Gib deinen Spielernamen ein, 50 Zeichen sind für Mod-Benutzer sichtbar, 15 für Andere";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users
var Languageletter8a="Name";		//Name
var Languageletter9="Füge deinen Skin Weblink ein";		//Insert your manual skin weblink
var Languageletter9a="Manuelle direkte Skin URL";		//Manual direct skin URL
var Languageletter10="Die Region zum Spielen";		//The region to play
var Languageletter11="Der Modus zum Spielen";		//The mode to play
var Languageletter12="Zum Server verbinden oder Kommunikation herstellen";		//Connect to server, or restablish communication
var Languageletter12a="Verbinden";		//Connect
var Languageletter13="Beitreten";		//Join
var Languageletter14="Spiel als Gast";		//Play as guest
var Languageletter15="Einloggen und spielen";		//Login and Play
var Languageletter16="Zusehen";		//Spectate
var Languageletter17="Einloggen über Facebook";		//Sign in with Facebook
var Languageletter18="Einloggen über Google";			//Sign in with Google
var Languageletter19="Spielen";		//Play
var Languageletter20="Shop"	;		//Shop
var Languageletter21="Gratis Münzen";		//Free Coins
var Languageletter22="Geschenke";		//Gifts
var Languageletter23="Tägliche Aufgaben";			//Daily Quests
var Languageletter24="Skins";		//Skins
var Languageletter25="Legend Promo Video";		//Legend Promo Video
var Languageletter25a="Neue Ideen & Statistiken";		//New Ideas & Statistics Form
var Languageletter25b="Mod Info & Vorlagen";		//Mod Info & Templates
var Languageletter26="Skins hinzufügen";		//Add skins
var Languageletter26a="Server, Passwort, Leaderboard & Teamboard kopieren"; //Copy Server, Password, Teamboard & Leaderboard

var Languageletter31="Ausloggen";		//Logout
var Languageletter32="Verwendete Male";		//Times Used
var Languageletter33="Legend Mod von";		//Legend Mod by
var Languageletter34="Übersetzung von";		//Translation by
var Languageletter35="Kopiere Leaderbord und Zellnamen. (drücke x zum Ein-/Ausblenden)";		//copy leaderboard names and cell names. (press x to show/hide)
var Languageletter36="Animation";		//Animation
var Languageletter37=" Animationsverzögerung ";		//Animation delay
var Languageletter37a="Automatischer Zoom";		// Auto zoom
var Languageletter37b="Zoom";		// Zoom
var Languageletter38="Zoom Geschwindigkeit:";		//Zoom speed: 
var Languageletter39="Wiederbeleben";			//Respawn
var Languageletter40="Automatisch Wiederbeleben";		//Auto respawn 
var Languageletter41="Schnell Wiederbeleben";			//Quick respawn 
var Languageletter41a="Beginne mit Spezialeffekten";			//Spawn special effects 
var Languageletter41b="Timer ausschalten ";			//Merge timer off
var Languageletter41c="Empfohlen, um die Verzögerung zu reduzieren";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Virus schiessen Ton";			//Virus shot sound

var Languageletter42="Namen";			//Names
var Languageletter43="Keine Namen";		//No names 
var Languageletter44="Optimierte Namen";		//Optimized names 
var Languageletter45="Namen automatisch verbergen";		//Auto hide names 
var Languageletter46="Meinen Namen verbergen";		//Hide my name 
var Languageletter47="Namen von Mitspielern verbergen";		//Hide teammates names 
var Languageletter48="Namen unterstreichen";		//Names stroke 
var Languageletter49="Masse";		//Mass
var Languageletter50="Masse anzeigen";		//Show mass 
var Languageletter51="Optimierte Masse"	;	//Optimized mass 
var Languageletter52="Masse automatisch ausblenden";			//Auto hide mass 
var Languageletter53="Meine Masse ausblenden";		//Hide my mass 
var Languageletter54="Masse der Gegner ausblenden";		//Hide enemies mass 
var Languageletter55="Kurze Massenanzeige";		//Short mass
var Languageletter56="Virus schießen";		//Virus shots 
var Languageletter57="Masse Umrahmung";		//Mass stroke 
var Languageletter58="Skins";		//Skins
var Languageletter59="Keine Skins";		//No skins 
var Languageletter60="Benutzerdefinierte Skins";		//Custom skins 
var Languageletter61="Standard Skins";		//Vanilla skins 
var Languageletter61a="Jelly Physik";		//Jelly physics 
var Languageletter61b="Video skins";		//Video skins
var Languageletter61c="Sound von anderen Video Skins, wenn beide C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Optimiertes Essen";		//Optimized food 
var Languageletter6a2="Essen";		//Food 
var Languageletter63="Automatisch Essen verbergen (Masse)";		//Auto hide food (mass) 
var Languageletter64="Automatisch Essen verbergen (Zoom)";		//Auto hide food (zoom) 
var Languageletter65="Regenbogen Essen";		//Rainbow food 
var Languageletter66="Transparenz / Farben";		//Transparency / colors
var Languageletter67="Keine Farben";		//No colors 
var Languageletter68="Benutzerdefinierte Farbe";		//My custom color 
var Languageletter69="Transparenter Skin";		//My transparent skin 
var Languageletter70="Transparente Skins";		//Transparent skins 
var Languageletter70a="Transparente Zellen";		//Transparent cells
var Languageletter71="Transparente Viren";		//Transparent viruses 
var Languageletter71a="Virus scheint";		//Virus Glow
var Languageletter71b="Animierte Regenbogenfarben";		//Animated rainbow colors

var Languageletter72="Raster / Sektoren";		//Grid / sectors
var Languageletter73="Raster anzeigen";		//Show grid 
var Languageletter74="Hintergrundsektoren anzeigen";		//Show background sectors 
var Languageletter75="Kartengrenzen anzeigen";		//Show map borders 
var Languageletter75a="Glühen der Grenzen";		//Border Glow

var Languageletter76="Chat";		//Chat
var Languageletter77="Chat deaktivieren";		//Disable chat 
var Languageletter78="Soundbenachrichtigungen";		//Sound notifications 
var Languageletter79="Emoticons";		//Emoticons 
var Languageletter80="Zeigt Bilder im Chat an";		//Show images on chat 
var Languageletter81="Zeigt Videos im Chat an";		//Show videos on chat 
var Languageletter82="Chatbox statt Popups";		//Chatbox instead of popups 
var Languageletter82a="Minimap";		//Minimap
var Languageletter82b="Minimap anzeigen";		//Show minimap 
var Languageletter82c="Minipap-Raster anzeigen";		//Show minimap grid 
var Languageletter82d="Minimap-Hilfen anzeigen";		//Show minimap guides 
var Languageletter82e="Mitspieler Einfarbig";		//One-colored teammates 
var Languageletter82f="Zusätzliche Mini-Kartenführer anzeigen";		//Show extra minimap guides
var Languageletter82g="Geisterzellen anzeigen";		//Show ghost cells

var Languageletter83="Helfer";		//Helpers
var Languageletter84="Gegnerfarbe";		//Opponents colors
var Languageletter85="Gegner Rahmen";		//Opponents rings 
var Languageletter86="Virusfarben";		//Viruses colors 
var Languageletter87="Splitreichweite";		//Split range 
var Languageletter87a="Schneller Double-Split-Bereich";		//Quick double split range
var Languageletter87b="Langsamer Double-Split-Bereich";		//Slow double split range

var Languageletter88="Virusreichweite";		//Viruses range 
var Languageletter89="Zeigerverfolgung";		//Cursor tracking 
var Languageletter90="Mitspieler Indikatoren";		//Teammates indicators 
var Languageletter90a="Geisterzellen";		//Ghost cells

var Languageletter91="Mauseinstellungen";		//Mouse control
var Languageletter92="LMT - teilen";		//LMB - Mouse split 
var Languageletter93="RMT - teilen";		//RMB - Mouse feed 
var Languageletter94="Maustasten invertieren";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD
var Languageletter95="Team";		//Team
var Languageletter96="Ziel anzeigen";		//Show targeting 
var Languageletter96a="Zeige die Bestenliste";		//Show leaderboard mass

var Languageletter97="Zentriert Leaderboard";		//Centered leaderboard 
var Languageletter97a="Leaderboard-Header";		//\"Leaderboard\" header 

var Languageletter98="Spielstatistiken an der Spitze";		//Game stats at the top 
var Languageletter98a="Skins auf dem Teamboard";		//Skins on teamboard

var Languageletter99="Statistik";		//Stats
var Languageletter100="Spielstatistik anzeigen";		//Show game stats 
var Languageletter101="Spielstatistik";		//Game stats
//the \' is needed
var Languageletter102="Feind";		//Enemy\'s 		
var Languageletter103="unsere";		//Our
var Languageletter104="Minimaler Tricksplit, der die Masse des Teamkollegen aufteilt";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Maximale feindliche Masse für Pre-Split";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Zeigt aktuelle Zeit";		//Show current time 
var Languageletter106="Extras";		//Extras
var Languageletter107="Überspringt Statistiken nach dem Tot";		//Skip stats after death 
var Languageletter108="Zeigt Quest";		//Show quest 
var Languageletter108a="Spiel Sounds"; //Game Sounds
var Languageletter108b="Menü Sounds"; //Menu Sounds
var Languageletter109="Popups blockieren (Ads/Shop/Quest)";		//Block popups (ads/shop/quest) 
var Languageletter109a="Stimme"; //Voice
var Languageletter109b="Stimm-Präfix"; //Voice-Prefix
var Languageletter109c="Stimme-Sprache"; //Voice-language
var Languageletter109d="Pause aufheben"; //UnPause

var Languageletter110="-- Grafik Qualität --";		//-- Graphics Quality --
var Languageletter111="Grafik: Ultra";		//Graphics: Retina
var Languageletter112="Grafik: Hoch";		//Graphics: High
var Languageletter113="Grafik: Mittel";		//Graphics: Medium"
var Languageletter114="Grafik: Niedrig";		//Graphics: Low
var Languageletter115="Grafik: sehr Niedrig";		//Graphics: Very Low
var Languageletter116="Export / Import Einstellungen";		//Export / import settings
var Languageletter117="Zurücksetzen auf Standardeinstellungen";		//Restore default settings
var Languageletter118="Export Einstellungen";		//Export settings
var Languageletter119="Import Einstellungen";		//Import settings
var Languageletter120="Um ausgewählte Einstellungen zu exportieren, kopieren sie den folgenden Code und speichern sie ihn in einer Unicode-codierten Textdatei.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode.
var Languageletter121="Um ausgewählte Einstellungen zu importieren, fügen Sie einen exportierten Code ein und drücken Sie den 'Einstellungen importieren' Knopf.";		//To import selected settings paste an exported code below and press the 'Import settings' button.
var Languageletter122="Kommandos";		// Commands
var Languageletter123="Tastenkürzel";		// Hotkeys
var Languageletter124="Profile";		// Profiles
var Languageletter125="Einstellungen";		// Settings
var Languageletter126="Design";		// Theme
var Languageletter127="Export Einstellungen";		//Export settings
var Languageletter128="Import Einstellungen";		//Import settings
var Languageletter129="Grundlegendes Design";		//Basic theming
var Languageletter130="Menü";		//Menu
var Languageletter131="HUD";		//HUD
var Languageletter132="Chat";		//Chat
var Languageletter133="Minimap";		//Minimap
var Languageletter134="Grafik/Zeiger";		//Graphics / cursors
var Languageletter135="Thema voreingestellt";		//Theme preset
var Languageletter136="Legend Original";		//Legend Original
var Languageletter137="Verrückter Stil 1";		//Crazy Style 1
var Languageletter139="Hintergrund";		//Background
var Languageletter140="Kartengrenzen";		//Map borders
var Languageletter141="Raster";		//Grid
var Languageletter142="Sektoren Schriftart";		//Sectors font
var Languageletter143="Namen";		//Names
var Languageletter144="Namen Rahmen";		//Names stroke
var Languageletter145="Masse";		//Mass
var Languageletter146="Masse Rahmen";		//Mass stroke
var Languageletter147="Virus Rahmen";		//Virus stroke
var Languageletter148="Virus";		//Virus
var Languageletter148a="Mutterzelle";		//Mothercell
var Languageletter148b="Mutterzell-Schlaganfall";		//Mothercell stroke
var Languageletter149="Essen";		//Food
var Languageletter150="Mitspieler Indikator";		//Teammate indicator
var Languageletter151="Zeigerverfolgung";		//Cursor tracking
var Languageletter152="Splitreichweite";		//Split range
var Languageletter153="Namensschriftart";		//Names font
var Languageletter154="Masseschriftart";		//Mass font
var Languageletter154a="Größer";		//Bigger
var Languageletter154b="Kleiner";		//Smaller
var Languageletter155="Sektorenschriftart";		//Sectors font
var Languageletter157="Sektorenschriftartgrösse";		//Sectors font size
var Languageletter158="Namen Skalierung";		//Names scale
var Languageletter159="Masse Skalierung";		//Mass scale
var Languageletter160="Virusmasse Skalierung";		//Virus mass scale
var Languageletter161="Textrahmen Skalierung";		//Text stroke scale
var Languageletter162="Essen Grösse";		//Food size: 
var Languageletter163="Virusrahmengrösse";		//Virus stroke size
var Languageletter164="Kartengrenzenbreite";		//Map borders width
var Languageletter165="Sektorengitterbreite";		//Sectors grid width
var Languageletter166="Zellen Transparenz";		//Cells transparency
var Languageletter167="Skins Transparenz";		//Skins transparency
var Languageletter168="Virus Transparenz";		//Virus transparency
var Languageletter169="Namen&Masse Transparenz";		//Names & mass transparency
var Languageletter170="Die Standarteinstellungen des Designs wiederherstellen";		//Restore theme default settings
var Languageletter171="Einstellungen speichern";		//Save settings
var Languageletter172="Menü Design";		//Menu theme
var Languageletter173="Hintergrund";		//Background
var Languageletter174="Transparenz";		//Transparency
var Languageletter175="Hauptfarbe";		//Main color
var Languageletter176="Tasten Text";		//Button text
var Languageletter177="Panel";		//Panel
var Languageletter179="Panel Text";		//Panel text
var Languageletter181="Taste";		//Button
var Languageletter189="Panel Hintergrundbild ";		//Panel background image
var Languageletter190="Bild URL";		//Image URL
var Languageletter191="Hauptfarbe";		//Main color
var Languageletter192="Hintergrund";		//Background
var Languageletter193="Text";		//Text
var Languageletter194="Statistiken";		//Stats
var Languageletter195="Zeit";		//Time
var Languageletter196="Top 5 Masse";		//Top 5 mass
var Languageletter197="Leaderboard - Ich";		//Leaderboard - me
var Languageletter198="Leaderboard - Mitspieler";		//Leaderboard - teammate
var Languageletter199="HUD Schriftart";		//HUD font
var Languageletter200="HUD Raster";		//HUD scale: 
var Languageletter201="Nachrichten Hintergrund";		//Message background
var Languageletter202="Nachrichten Text";		//Message text
var Languageletter203="Nachrichten Zeit";		//Message time
var Languageletter204="Nachrichten Nick";		//Message nick
var Languageletter205="Kommando Hintergrund";		//Command background
var Languageletter206="Kommando Text";		//Command text
var Languageletter207="Kommando Zeit";		//Command time
var Languageletter208="Kommando Nick";		//Command nick
var Languageletter209="Chatbox Farbe";		//Chatbox color
var Languageletter210="Chat Skalierung";		//Chat scale
var Languageletter211="Sektoren";		//Sectors
var Languageletter212="Aktueller Sektor";		//Current sector
var Languageletter213="Nick";		//Nick
var Languageletter214="Nick Umrahmung";		//Nick stroke
var Languageletter215="Meine Zelle";		//My cell
var Languageletter216="Meine Zellumrahmung";		//My cell stroke
var Languageletter217="Mitspieler";		//Teammates
var Languageletter218="Todesort";		//Death location
var Languageletter219="Helfer";		//Guides
var Languageletter220="Minimap Schriftart";		//Minimap font
var Languageletter221="Nick Schriftart";		//Nick font
var Languageletter222="Minimap Breite";		//Minimap width
var Languageletter223="Sektoren Transparenz";		//Sectors transparency
var Languageletter224="Nick Größe";		//Nick size
var Languageletter225="Nick Rahmenstärke";		//Nick stroke size
var Languageletter226="Meine Zellengröße";		//My cell size
var Languageletter227="Meine Zellrahmenstärke";		//My cell stroke size
var Languageletter228="Mitspieler Größe";		//Teammates size
var Languageletter229="Benutzerdefiniertes Hintergrundbild";		//Custom background image
var Languageletter230="Benutzerdefiniertes Zeiger-Bild";		//Custom cursor image
var Languageletter231="Bild URL";		//Image URL
var Languageletter232="Zeigerbild URL";		//Cursor image URL
var Languageletter233="Füttern";		//Feed
var Languageletter234="Makro Füttern";		//Macro feed
var Languageletter235="Teilen";		//Split
var Languageletter236="Doppelteilung";		//Double split
var Languageletter237="Popteilung";		//Popsplit
var Languageletter238="Zerteilen in 16";		//Split 16
var Languageletter239="Zelle Pause";		//Cell pause
var Languageletter240="Team Top 5 ein-/ausblenden";		//Show/hide team top 5
var Languageletter241="Aktuelle Zeit ein-/ausblenden";		//Show/hide current time
var Languageletter242="Teilungsreichweite ein-/ausblenden";		//Show/hide split range"
var Languageletter243="Mitspieler-Indikatoren ein-/ausblenden";		//Show/hide teammates indicators
var Languageletter244="Split-Indikatoren ein-/ausblenden";		//Show/hide split indicators
var Languageletter245="Gegnerfarben ein-/ausblenden";		//Show/hide opponents colors
var Languageletter246="Skins umschalten (Eigener/Standard)";		//Toggle skins (custom/default)
var Languageletter247="Transparente Skins umschalten";		//Toggle transparent skins
var Languageletter248="Skins ein-/ausblenden";		//Show/hide skins
var Languageletter249="Spielstatistiken ein-/ausblenden";		//Show/hide game stats
var Languageletter250="Eigene Zellen umschalten (klein / groß)";		//Toggle own cells (smallest/biggest)
var Languageletter251="Essen ein-/ausblenden";		//Show/hide food
var Languageletter252="Raster ein-/ausblenden";		//Show/hide grid
var Languageletter253="Minipap-Helfer ein-/ausblenden";		//Show/hide minimap guides
var Languageletter254="Chat ein-/ausblenden";		//Show/hide chat
var Languageletter255="HUD ein-/ausblenden";		//Show/hide HUD
var Languageletter256="Leaderboard kopieren";		//Copy leaderboard
var Languageletter257="Leaderboard ein-/ausblenden";		//Show/hide leaderboard
var Languageletter258="Automatisches Zoomen umschalten";		//Toggle auto zoom
var Languageletter259="Zoom zurücksetzen";		//Reset zoom
var Languageletter260="Todesort umschalten";		//Toggle death location
var Languageletter261="Chatverlauf anzeigen / Chat löschen";		//Show chat history / Clear chat
var Languageletter262="Hintergrundsektoren ein-/ausblenden";		//Show/hide background sectors
var Languageletter263="Kleine Bots ein-/ausblenden";		//Show/hide small bots
var Languageletter264="Namen ein-/ausblenden";		//Show/hide names
var Languageletter265="Namen der Mitspieler ein-/ausblenden";		//Show/hide teammates names
var Languageletter266="Masse ein-/ausblenden";		//Show/hide mass
var Languageletter267="Minipap ein-/ausblenden";		//Show/hide minimap
var Languageletter268="Chat-Nachricht eingeben";		//Enter chat message
var Languageletter269="Schneller Respawn";		//Quick respawn
var Languageletter270="Automatischen Respawn umschalten";		//Toggle auto respawn
var Languageletter271="Zoomstufe";		//Zoom level 
var Languageletter271a="Stimme zu Text";		//Voice to text
var Languageletter271b="Informationen zu Geisterzellen anzeigen";		//Show ghost cells information
var Languageletter271c="Automatisches Spiel";		//Auto Play
var Languageletter272="Ziel-Bereich ein-/ausblenden";		//Show/hide targeting panel
var Languageletter273="Zielen starten/stoppen (folgend)";		//Start/stop targeting (following)
var Languageletter274="Zielen abbrechen";		//Cancel targeting
var Languageletter275="Ziel ändern";		//Change target
var Languageletter276="Zeige Ziel auf der Minimap";		//Show target on the minimap
var Languageletter277="Quest ein-/ausblenden";		//Show/hide quest
var Languageletter278="Um einen Hotkey zuzuweisen, klicken Sie auf das Eingabefeld und drücken Sie die gewünschte Taste.";		//To assign a hotkey click on the input field and press your chosen key.
var Languageletter279="Um einen Hotkey zu löschen, klicken Sie auf das Eingabefeld und drücken Sie die DELETE Taste.";		//To delete a hotkey click on the input field and press the DELETE key.
var Languageletter280="Mögliche Tastenkombinationen mit den Tasten STRG und ALT.";		//Possible key combinations with the CTRL and ALT keys.
var Languageletter281="Standardeinstellungen wiederherstellen";		//Restore default settings
var Languageletter282="Einstellungen speichern";		//Save settings
var Languageletter283="Schließen";		//Close
var Languageletter284="Youtube Spieler";		//Youtube player
var Languageletter284a="Youtube Url";		// Youtube Url
var Languageletter285="Füge dein Video/deine Playlist ein";		//Paste your video/playlist here
var Languageletter286="Sounds";		//Sounds
var Languageletter287="Mitteilung Benachrichtigungssound";		//Message notification sound
var Languageletter288="Befehl Benachrichtigungssound";		//Command notification sound
var Languageletter289="Kopiere Token/SIP";		//Copy Token/SIP
//keep this small
var Languageletter290="Token";		//Token
var Languageletter290a="Board"; //Board
var Languageletter290b="TK&PW";	//TK&PW (Token and Password)
var Languageletter290c="TK&ALLE"; //TK&ALL (Token and All)
var Languageletter291="Kopieren";		//Copy

var Languageletter291a="Kopiere Leaderboard (L)";		//Copy Leaderboard (L)
var Languageletter291b="Kopiere Token/SIP&Passwort"; 	//Copy Token/SIP&Password
var Languageletter291c="Kopiere Token/SIP, Passwort, Leaderboard.."; //Copy Token/SIP, Password, Leaderboard...
var Languageletter292="Betrete Server (Rücktaste)";		//Join server (Backspace)
var Languageletter293="Server wechseln (+)";		//Change server (+)
var Languageletter294="Leaderboard History";		//Leaderboard history
var Languageletter295="Gib Zeichen des Freundes, IP, Leaderboard, Name oder Clan-Tag ein...";		//Enter friend token, IP, leaderboard, name or clan tag...
var Languageletter295a="Liste löschen"; //Clear list
var Languageletter295b="Chat-Nachricht eingeben..."; //Enter chat message...
var Languageletter298="Team top";		//Team top 
var Languageletter299="Leaderboard";		//Leaderbodard
var Languageletter300="Kommunikation";		//Communication
var Languageletter301="Nachricht Skriptbefehle";		//Message Script Commands
var Languageletter302="Nachricht Imgur Symbole";		//Message Imgur Icons
var Languageletter303="Nachricht Youtube Videos";		//Message Youtube Videos
var Languageletter304="Namen bearbeiten";		//Edit names
var Languageletter305="[Nur Zuschaumodus] Ferngläser";		//[Spectate Mode Only] Binoculars
var Languageletter306="Spielen/Pause";		//Play / Pause
var Languageletter307="Vollbild";		//Fullscreen
var Languageletter308="Drehen";		//Rotate
var Languageletter309="Standard";		//Default
var Languageletter310="Zurück";		//Back
var Languageletter311="für später Speichern";		//Save for later
var Languageletter312="Region";		//Region
var Languageletter313="Spieler";		//Players
var Languageletter314="Server";		//Servers
var Languageletter315="[Ziel nicht festgelegt]";		//[Target not set]
var Languageletter316="Manueller Hintergrund";		//Manual background
var Languageletter317="Manuelle Nachrichtensymbole&Youtube";		//Manual Message Icons&Youtube
var Languageletter318="Chat Position";		//Chat Position
var Languageletter319="Discord Webhook Url (für TOKEN versenden)";		//Discord Webhook Url (for sending TOKEN)
var Languageletter320="Leaderboard";		//Leaderboard
var Languageletter321="Teamboard";		//Teamboard
var Languageletter322="Hauptspielfläche";		//Main Canvas
var Languageletter323="Hauptbanner";		//Main Banner
var Languageletter324="Hallo Team!";		//Hello Team!
var Languageletter325="Lache dem Team zu";		//Laugh to Team
var Languageletter326="Team wechselt auf deinen Namen";		//Team Change Name to yours
var Languageletter327="Troll im Tod";		//Troll on Death
var Languageletter328="Öffnet Youtube Musik";		//Open Youtube Music
var Languageletter329="schwerster Modus (Alles ausblenden)";		//Insane mode (Hide Everything)
var Languageletter330="Url des Bildes beginnend mit http://... oder https://...";		//Url of image starting with http://... or https://...
var Languageletter331="Minimap Bild URL";		//Minimap Image URL
var Languageletter332="Minimap Text";		//Minimap Text
var Languageletter333="Leaderboard Logo Text";		//Leaderboard Logo Text
var Languageletter333a="Leaderboard Bild URL";		// Leaderboard Image URL
var Languageletter334="Teamboard Logo Text";		//Teamboard Logo Text
var Languageletter334a="Teamboard Bild URL";		// Teamboard Image URL
var Languageletter335="Hauptspielfläche URL";		//Main Canvas Image URL
var Languageletter336="Hauptbanner Symbol URL";		//Main Banner Icon URL
var Languageletter337="Hauptbanner Link URL";		//Main Banner Link URL
var Languageletter338="Symbol";		//Icon
var Languageletter339="z.B.";		//e.g
var Languageletter340="Url Youtube anzeigen";		//Url of youtube to be shown
var Languageletter341="Url vom Link umleiten";		//Url of link to redirect
var Languageletter342="Discord Webhook Url";		//Discord Webhook Url
var Languageletter342a="Nachrichtensymbol für Text";		//Message Icon Text
var Languageletter342b="Youtube Nachrichtentext";		//Youtube Message Text
var Languageletter342c="Nachricht Icon Imgur Url";		//Message Icon Imgur Url
var Languageletter342d="Youtube Nachricht Url";		//Youtube Message Url
var Languageletter343="Muss ausgefüllt werden, damit die Funktion funktioniert";		//Must be filled for function to work.
var Languageletter344="Sekundärer Webhook(optional)";		//Secondary Webhook(optional)
var Languageletter345="WARNUNG! Popups sind in den Einstellungen blockiert.";		//WARNING! Popups are blocked in the settings.
var Languageletter346="Temporäres Entsperren";		//Temporary unblock
var Languageletter347="WARNUNG! Popups sind in den Einstellungen gesperrt.";		//WARNING! Popups are blocked in the settings.
var Languageletter348="Temporäres Entsperren";		//Temporary unblock

var Languageletter349="Tränke";	//Potions
var Languageletter350="Alte Skins";	//Old Skins
var Languageletter351="Spezielle Angebote"; //Special Deals
var Languageletter352="Leaderboards"; //Leaderboards
var Languageletter353="Neue Ideen & Statistikformular"; //New Ideas & Statistics Form
var Languageletter354="Video Skins"; //Video Skins
var Languageletter355="Mini Skripte"; //Mini Scripts
var Languageletter356="Benutzer Skripte"; //User Scripts
var Languageletter357="Sprach & Kamera Chat";	//Voice & Camera Chat
var Languageletter358="Bitte unterstützt die Entwicklung von Legend Mod";	//Please support the development of Legend mod
var Languageletter359="Design Nickname Schriftart";	//Design Nickname Font
var Languageletter360="Kennzeichne die falschen Skins"	//Flag the Fake Skin
var Languageletter361="Mehr FPS";	//More FPS
var Languageletter362="Name";	//Name
var Languageletter363="Soziale ID";	//Social ID
var Languageletter364="Erweiterungen";	//Expansions
var Languageletter365="Universal";	//Universal
var Languageletter366="Ergebnis";	//Score
var Languageletter367="Entfernung";	//Distance
var Languageletter368="Totale Masse";	//Total Mass
var Languageletter369="Tot";	//Dead

var Premadeletter0="Kommunikation Aktiviert"; 		//Communication Activated
var Premadeletter1="Kein Öffnen von Youtube URL möglich";		 //Cannot open this youtube URL
var Premadeletter2="[SERVER]: Du kannst nicht chatten, wenn der Spielername > 15 Zeichen"; 		//[SERVER]: You cannot chat if player name > 15 chars
var Premadeletter3="Easter Egg 1 Aktiviert"; 		//Easter Egg 1 Activated
var Premadeletter4="Easter Egg 2 Aktiviert";		//Easter Egg 2 Activated
var Premadeletter5="Easter Egg 3 Aktiviert";		//Easter Egg 3 Activated
var Premadeletter6="Video arbeitet besser mit Vanilla, wechsle:";		//Video works better on vanilla, visit:
var Premadeletter7="Notiz:<b>Facebook</b> Compatibilität ist besser als <b>Google Plus</b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>.
var Premadeletter8="Notiz:Agar.io kann bei onload Events nur mit <b>Google Plus</b> verbinden. Wenn ein Logout passiert, lade Agar.io neu oder verwende <b>Facebook</b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>.
var Premadeletter9="Wenn bei Onload-Events eine Abmeldung auftritt, löschen Sie Chrome-Cookies";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Vom Server getrennt :(";		//Disconnected from server :(
var Premadeletter11="Du wurdest gesperrt, starte deinen Router neu!";		//You were banned, restart your rooter!
var Premadeletter12="Verbunden!";		//Connected!
var Premadeletter13="SPIELEN";		//PLAY
var Premadeletter14="ZUSCHAUEN";		//SPECTATE
var Premadeletter15="Ungültiger Token oder Server ist geschlossen :(";		//Invalid token or server has closed :(
var Premadeletter16="Kann aktualisiert werden";		//can be Updated to
var Premadeletter17="Willkommen zurück";			//Welcome back
var Premadeletter18="Der Verknüpfungsbereich und andere Bereiche (vom letzten Tab) sind weiterhin deaktiviert! Wir empfehlen, sie zu aktivieren.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them.
var Premadeletter19="Aktivieren";		//Enable Them
var Premadeletter20="Deaktiviert lassen";		//Keep Them Disabled
var Premadeletter21="Suche IP";		//Searching IP
var Premadeletter22="Dein Mitspieler";		//Your teammate
var Premadeletter23="Möchte, dass du alle versteckst (Rangliste und Minimap)";		//wants you to hide all (leaderboard and minimap)
var Premadeletter24="Akzeptieren";		//Accept
var Premadeletter25="AUF KEINEN FALL!";		//NO WAY!
var Premadeletter26="Möchte, dass du deinen Namen änderst in";		//wants you to change your name to
var Premadeletter27="Möchte, dass du Trollen im Tod versteckst";		//wants you to hide Enable Troll on death
var Premadeletter28="Möchte, dass du Youtube Player öffnest";			//wants you to open Youtube Player
var Premadeletter29="Leaderboard gefunden";		//Leaderboard found
var Premadeletter30="Suche";		//Search
var Premadeletter31="Das Leaderboard wurde nicht gefunden. Versuche es weiter ...";		//The leaderboard was not found. Keep trying...
var Premadeletter32="Suche wurde abgebrochen";		//Search was canceled
var Premadeletter33="Du bist für das Team / Clan unsichtbar";		//You are invisible to Team / Clan
var Premadeletter34="Du bist für das Team / Clan sichtbar";		//You are visible to Team / Clan
var Premadeletter35="Ein-/Ausblenden kann nur während des Spieles verwendet werden";			//Hide/Show can be used only while playing
var Premadeletter36="Keine gültige Discord Webhook Adresse";		//This is not valid Discord Webhook address
var Premadeletter37="Server ist gesperrt";		//Server is locked
var Premadeletter38="Du musst im Zuschauer-Modus sein ";		//You must be on spectate mode
var Premadeletter39="Aufgrund von Spam-Problemen musst du im Spiel sein und ein Passwort verwenden";		//Due to spamming issues, you must be in game and use password

//					These buttons must no be big in length
var Premadeletter40="Auto Youtube An";		//Auto Youtube On
var Premadeletter41="Auto Youtube Aus";		//Auto Youtube Off
var Premadeletter42="Verknüpfungen anzeigen";		//Show Shortcuts
var Premadeletter43="Verknüpfungen verbergen";		//Hide Shortcuts
var Premadeletter44="Zeigt XP BALKEN";		//Show XP BAR
var Premadeletter45="Verbirgt XP BALKEN";		//Hide XP BAR
var Premadeletter45a ="Abgerundetes Hud"; //Rounded Hud
var Premadeletter45b ="Eckiges Hud"; //Square Hud
var Premadeletter46 = "Lineare Farbe"; //Linear color Hud
var Premadeletter47 = "Mutige Farbe"; //Bold color Hud

var Premadeletter48="Zeigt Alles";		//Show Everything
var Premadeletter49="Verbirgt Alles";		//Hide Everything
var Premadeletter50="Zeigt Timer Calc.";		//Show Timer Calc.
var Premadeletter51="Verbirgt Timer Calc."		//Hide Timer Calc.

var Premadeletter53="Auto freie Münzen";		//Auto free coins
var Premadeletter54="Stoppt freie Münzen";		//Stop free coins
var Premadeletter55="Troll im Tod";		//Troll on Death
var Premadeletter56="Kein Troll im Tod";		//No troll on Death

var Premadeletter57="Kommunikation";		//Communication
var Premadeletter58="Versteckt";		//Hidden
var Premadeletter59="Sichtbar";		//Visible
var Premadeletter60="Pause";		//Pause

var Premadeletter61 = "Aktiviere YT als Hintergrund";	//Enable YT as background
var Premadeletter62 = "Deaktiviere YT als Hintergrund";	//Disable YT as background";
var Premadeletter63 = "Möchte, dass du die URL öffnest";	//wants you to open the url
var Premadeletter64 = "Möchte, dass du dieses YouTube-Video einfügst und spielst";	//wants you to embed and play this youtube video
var Premadeletter65 = "Möchte, dass du dem folgenden Skype-Raum betrittst";	//wants you to join the following Skype room
var Premadeletter66 = "Möchte, dass du dich dem folgenden Discord Raum anschließt";	//wants you to join the following Discord room
var Premadeletter67 = "Möchte, dass du diesen Server verlässt und diesem Neuen beitrittst";	//wants you to leave this server and join this new one

var Premadeletter68 = "Du hast gedrückt"; //You pressed
var Premadeletter69 = "Neustart wenn"; //restart if
var Premadeletter70 = "Fällt"; //drops
var Premadeletter71 = "Animierte Skins"; //Animated skins
var Premadeletter72 = "Aktiviert"; //enabled
var Premadeletter73 = "Fallen"; //drop
var Premadeletter74 = "Wann"; //when
var Premadeletter75 = "Animierte Skins werden";//Animated skins will be
var Premadeletter76 = "Deaktivieren"; //disabled
var Premadeletter77 = "Nach dem Wiedereinstieg"; //after rejoin
var Premadeletter78 = "Bessere FPS"; //Better FPS
var Premadeletter79 = "Leistung bei 16"; //performance when 16
var Premadeletter80 = "Wenn Dying Light Erweiterung aktiviert ist, kann Troll im Tod nicht passieren"; //When Dying Light Expansion is enabled, Troll on death cannot occur
var Premadeletter81 = "Privater Server"; //Private Server
var Premadeletter82 = "Verbinde dich mit Allen"; //Connect to any
var Premadeletter83 = "Server, oder mache deinen Eigenen"; //server, or make your own
var Premadeletter84 = "Spiele Agario-ähnliche Spiele, wenn du die IP von Servern kennst";//Play agario-like games if you know the IP of servers
var Premadeletter85 = "Dein Bild wurde in die Zwischenablage kopiert. Füge es ein";// Image of your has been copied to clipboard. Paste it
var Premadeletter86 = "Benutzerdefinierte Skins URL-Bereich "; //to custom skin Url area
var Premadeletter87 = "Du musst dich anmelden, um das Bild deines Profils zu verwenden";//You must Login to use picture of your profile
var Premadeletter88 = "Du verwendest eine falsche Version"; //You are using a wrong version
var Premadeletter89 = "Das Spiel wird jetzt beendet";//Game will terminate now
var Premadeletter90 = " Spezialangebote"; //Special Deals
var Premadeletter91 = "Agar.io kann oder darf dir nicht den Skin geben, nur die Münzen" //Agario may or may not give you the Skin, but only the coins
var Premadeletter91a = "Benutzung auf eigene Gefahr";//Use at your own risk
var Premadeletter92 = "Wenn die UID deines Freundes falsch ist, wird der Kauf fehlschlagen";//If friend UID is wrong, purchase will fail
var Premadeletter93 = "UID Factory Einstellungen"; //UID Factory Settings
var Premadeletter94 = "Du musst dich anmelden, um Sonderangebote zu laden"; //You must login to load Special Deals
var Premadeletter95 = "Die Fälschung wurde in die Zwischenablage kopiert. Füge sie ein"; // Fake image has been copied to clipboard. Paste it
var Premadeletter96 ="Benutzerdefinierten URL-Bereich anpassen, um die Fake-Flag-Funktion zu aktivieren";// o custom skin Url area in order to activate the fake flag function
var Premadeletter97 = "Informiert dich, wenn du mit Recaptcha fertig bist"; //Inform me when you finish with Recapatcha
var Premadeletter98 = "Ich bin fertig"; //I have finished
var Premadeletter99 = "Macht nichts"; //Never Mind
var Premadeletter100 = "Kalkuliert deine XP, bitte warten..."; //Calculating your XP, please wait...
var Premadeletter101 = "Mache"; //Do
var Premadeletter102 = "NICHT"; //NOT
var Premadeletter103 = "Drücke"; //press
var Premadeletter104 = "Löscht die benutzerdefinierten Skins-URL"; //Erase custom skin URL
var Premadeletter105 = "Wählt Video Skin";	//select video skin
var Premadeletter106 = "Hebt Video Skin auf"; //unselect video skin
var Premadeletter107 = "Ton aus"; //mute audio
var Premadeletter108 = "Das LM Projekt"; //The LM Project
var Premadeletter109 = "Hochladen"; //Upload 
var Premadeletter109a = "Herunterladen"; //Download
var Premadeletter109b = "Wird geladen"; //Load

var Premadeletter110 = "Gib nichts hier ein, wenn du nicht weißt, was es ist";	//do not enter anything here unless you know what it is
var Premadeletter111 = "Klicke auf das orange Symbol, um zu kaufen"; //click on the orange icon to buy
var Premadeletter112 = "Für manche Zahlungsmethoden"; //For some payment methods
var Premadeletter113 = "Schließen";	//Close
var Premadeletter114 = "KOPIEREN"; //COPY	
var Premadeletter115 = "Wird verwendet, um Angebote für Ihre Freunde zu kaufen";//is used to buy offers for your friends
var Premadeletter116 = "Um Einkäufe tätigen zu können, müssen Sie in Ihrem Konto angemeldet sein …"; //To make purchases, you must be logged in to your account…
var Premadeletter117 = "Bibliothek"; //Library
var Premadeletter118 = "Besuchen"; //visit
var Premadeletter119 = "Als Fake melden (Skin wechseln)";//Report as Fake (change Skin)
var Premadeletter120 = "Gib den GENAUEN Namen des Spielers ein";//Enter your EXACT name of the player
var Premadeletter121 = "Missbrauch von Spielern und unangemessene Verwendung führt zur UID des Benutzers";//Abusing players and inappropriate use will lead UID of user
var Premadeletter122 = "Ein dauerhaftes Verbot der Nutzung dieser Erweiterung";//to permanent ban from usage of this extension
var Premadeletter128 = "Benutzeranmeldung erforderlich"; //User login needed
var Premadeletter129 = "Einstellungen erfolgreich hochgeladen"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "SERVER"; //SERVER
var Premadeletter124 = "Vermeiden Sie die Verwendung von Video-Skins, die länger als 6 Minuten sind"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Karte behoben"; //Map fixed
var Premadeletter126 = "Eingeloggt in"; //Logged in to
var Premadeletter127 = "Ausloggen"; //Logged out
var Premadeletter130 = "Gesamt"; //Total
var Premadeletter131 = "NEU"; //NEW
var Premadeletter132 = "Join Back"; //Join Back
var Premadeletter133 = "Stellen Sie eine Verbindung zur zuletzt gespielten IP her"; //Connect to last IP you played
var Premadeletter134 = "Nordamerika"; //North America
var Premadeletter135 = "Südamerika"; //South America
var Premadeletter136 = "Europa"; //Europe
var Premadeletter137 = "Russland"; //Russia
var Premadeletter138 = "Truthahn"; //Turkey
var Premadeletter139 = "Ostasien"; //East Asia
var Premadeletter139a = "China"; //China
var Premadeletter140 = "Ozeanien"; //Oceania
var Premadeletter140a = " -- Wählen Sie eine Region aus -- "; // -- Select a Region -- 
var Premadeletter141 = "Kostenlos"; //FFA
var Premadeletter142 = "Battle Royale"; //Battle Royale
var Premadeletter143 = "Mannschaften"; //Teams
var Premadeletter144 = "Experimental"; //Experimental
var Premadeletter145 = "Party Mod"; //Party Mode

//These are for file: https://jimboy3100.github.io/legendhelper.js
var Externalletter0a = "SPRACHEN"; //LANGUAGES
var Externalletter0b = "Wähle eine Sprache";//Choose a language
var Externalletter0c = "Änderungen werden erst nach dem Neustart vollständig durchgeführt";//Changes will take place completely after the restart
var Externalletter1 = "INFORMATION"; //INFORMATION
var Externalletter2 = "VORLAGEN"; //TEMPLATES
var Externalletter3 = "MANUELLE VORLAGEN";//MANUAL TEMPLATES
var Externalletter4 = "Wähle deine Vorlage"; //Choose your template
var Externalletter5 = "Oder wähle deine eine Erweiterung"; //Or choose an expansion

//These are for file: https://jimboy3100.github.io/legendformIframe.js
var Externalletter5a = "CODE AN ENTWICKLER SENDEN"; //SEND CODE TO DEVELOPERS

//These are for file: https://jimboy3100.github.io/legend.sniff3.js
var Externalletter6 = "Füge dein Skript in dieses Textfeld ein, du kannst mehrere Skripte laden"; //Paste your Script in this Textarea, you can load multiple Scripts
var Externalletter7 = "Skript aus Textarea laden"; //Load Script from Textarea
var Externalletter8 = "Wähle"; //Choose
var Externalletter9 = "Skript löschen"; //Erase Script
var Externalletter10 = "Name"; //Name
var Externalletter11 = "Url von Raw Github oder einem anderen Raw Script, beginnend mit"; //Url of Raw Github, or other Raw Script, starting with
var Externalletter12 = "Lass dies leer, wenn das Skript nicht aus der URL importiert wurde"; //Leave this empty if script not imported from URL
var Externalletter13 = "WICHTIGER HINWEIS: Verwalte keine URLs, die nicht funktionieren, da sie als Onload-Ereignisse verwendet werden. Wenn das Szenario Onload-Ereignisse beschädigt, LÖSCHEN SIE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
