/* var Languageletter = "hello you" <--- You tranlate this, keep the " "; as they are. // <-Means notes, no need to change */
/* Example var Languageletter0="Home"; //Home -> var Languageletter0="Maison"; //Home */ /* Don't make exact Translation, just translate the meaning. Don't make very long texts, because it might not fit. Keep the <b></b> and SPACES as is */ 
/* Thank you for supporting Legend Agar.io mod */
var translator="Дохтер";		//Put your nickname, in order to be reffered to mod, or use name "Unknown" 
var Languageletter0="Главная";		//Home 
var Languageletter1="Пользователь";		//User 
var Languageletter2="Настройки";		//Settings 
var Languageletter3="Тема";		//Theme 
var Languageletter4="Клавиши";		//Hotkeys 
var Languageletter5="Звуки";		//Youtube & Sounds 
var Languageletter6="Инструменты";		//Tools 
var Languageletter7="Оставьте его пустым для того что бы все видели или или вставьте свой пароль что бы видели те кто под паролем";		//Password/Tag 
var Languageletter7a="Пароль / Тег"	;	//Password/Tag 
var Languageletter8="Вставьте свое внутриигровое имя, 50 символов видны пользователям мода, 15 - другим пользователям";		//Insert your in-game name, 50 chars are visible on Mod users, 15 to other users 
var Languageletter8a="Имя";		//Name
var Languageletter9="Вставьте свой URL скина";		//Insert your manual skin weblink
var Languageletter9a="Прямая ссылка на скин";		//Manual direct skin URL 
var Languageletter10="Регион сервера";		//The region to play 
var Languageletter11="Режим игры";		//The mode to play 
var Languageletter12="Подключиться к игровому серверу или восстановить связь";		//Connect to server, or restablish communication 
var Languageletter12a="Подключится";		//Connect 
var Languageletter13="Войти";		//Join 
var Languageletter14="Играть как гость";		//Play as guest
var Languageletter15="Войти";		//Login and Play 
var Languageletter16="Наблюдение";		//Spectate 
var Languageletter17="Войти через Facebook";		//Sign in with Facebook 
var Languageletter18="Войти через Google";			//Sign in with Google
var Languageletter19="Играть";		//Play 
var Languageletter20="Магазин"	;		//Shop 
var Languageletter21="Бесплатные монеты";		//Free Coins 
var Languageletter22="Подарки";		//Gifts 
var Languageletter23="Ежедневные задания";			//Daily Quests 
var Languageletter24="Скины";		//Skins 
var Languageletter25="Промо-видео Legendmod";		//Legend Promo Video
var Languageletter25a="Отправить предложение";		//New Ideas & Statistics Form 
var Languageletter25b="Инфо мода и шаблоны";		//Mod Info & Templates
var Languageletter26="Добавить скины";		//Add skins 
var Languageletter26a="Копировать сервер, пароль, топ команды и лидерборд"; //Copy Server, Password, Teamboard & Leaderboard 
var Languageletter31="Выйти";		//Logout 
var Languageletter32="Использовано раз";		//Times Used 
var Languageletter33="Legend Mod, автор:";		//Legend Mod by 
var Languageletter34="Перевод от";		//Translation by 
var Languageletter35="Копировать имена топа. (нажмите x, чтобы показать / скрыть)";		//copy leaderboard names and cell names. (press x to show/hide) 
var Languageletter36="Анимация";		//Animation 
var Languageletter37="Задержка анимации";		//Animation delay 
var Languageletter37a="Авто увеличение";		// Auto zoom 
var Languageletter37b="Увеличить";		// Zoom 
var Languageletter38="Скорость увеличения:";		//Zoom speed:
var Languageletter39="Респавн";			//Respawn 
var Languageletter40="Авто-респавн";		//Auto respawn 
var Languageletter41="Быстрый-респавн ";			//Quick respawn 
var Languageletter41a="Спецэффекты спавна";			//Spawn special effects 
var Languageletter41b="Таймер соединения шаров выключен ";			//Merge timer off
var Languageletter41c="Предлагается включить для уменьшения задержки";			//Suggested to be enabled for Lag reduce
var Languageletter41d="Звуки выстрела вируса";			//Virus shot sound

var Languageletter42="Имена";			//Names 
var Languageletter43="Нет имен";		//No names 
var Languageletter44="Оптимизированные имена";		//Optimized names 
var Languageletter45="Авто скрыть имена";		//Auto hide names 
var Languageletter46="Скрыть мое имя";		//Hide my name 
var Languageletter47="Скрыть имена товарищей по команде";		//Hide teammates names 
var Languageletter48="Обводка имен";		//Names stroke 
var Languageletter49="Масса";		//Mass 
var Languageletter50="Показать массу";		//Show mass 
var Languageletter51="Оптимизированная масса"	;	//Optimized mass 
var Languageletter52="Авто скрыть массу";			//Auto hide mass 
var Languageletter53="Скрыть мою массу";		//Hide my mass 
var Languageletter54="Скрыть массу врагов";		//Hide enemies mass 
var Languageletter55="Укороченая масса";		//Short mass 
var Languageletter56="Счетчик выстрелов вируса";		//Virus shots 
var Languageletter57="Обводка массы";		//Mass stroke 
var Languageletter58="Скины";		//Skins 
var Languageletter59="Нет скинов ";		//No skins 
var Languageletter60="Пользовательские скины";		//Custom skins 
var Languageletter61="Агаровские скины";		//Vanilla skins 
var Languageletter61a="Неровности в шарах";		//Jelly physics 
var Languageletter61b="Видео скины";		//Video skins
var Languageletter61c="Звук из других видео скинов, когда оба C3";		//Sound from other\'s Video skins when both C3

var Languageletter62="Оптимизированная еда";		//Optimized food 
var Languageletter6a2="Еда";		//Food 
var Languageletter63="Авто скрыть еду (в зависимости от массы)";		//Auto hide food (mass) 
var Languageletter64="Авто скрыть еду (в зависимости от зума)";		//Auto hide food (zoom) 
var Languageletter65="Разноцветная еда";		//Rainbow food 
var Languageletter66="Прозрачность / цвета";		//Transparency / colors
var Languageletter67="Нет цветов";		//No colors 
var Languageletter68="Мой цвет";		//My custom color 
var Languageletter69="Мой прозрачный скин";		//My transparent skin 
var Languageletter70="Все прозрачные скины";		//Transparent skins 
var Languageletter70a="Прозрачные шары";		//Transparent cells 
var Languageletter71="Прозрачные вирусы";		//Transparent viruses 
var Languageletter71a="Свечение вирусов";		//Virus Glow
var Languageletter71b="Вызов цветной эпилепсии";		//Animated rainbow colors

var Languageletter72="Сетка / сектора";		//Grid / sectors 
var Languageletter73="Показать сетку";		//Show grid 
var Languageletter74="Показать сектора на фоне";		//Show background sectors 
var Languageletter75="Показать границы карты";		//Show map borders
var Languageletter75a="Свечение границ";		//Border Glow

var Languageletter76="Чат";		//Chat
var Languageletter77="Вырубить чат";		//Disable chat 
var Languageletter78="Звук сообщений";		//Sound notifications 
var Languageletter79="Смайлики";		//Emoticons 
var Languageletter80="Отображать изображения в чате";		//Show images on chat 
var Languageletter81="Отображать видосы в чате";		//Show videos on chat 
var Languageletter82="Рамка чата вместо всплывающих уведомлений";		//Chatbox instead of popups 
var Languageletter82a="Мини-карта";		//Minimap 
var Languageletter82b="Показывать мини-карту";		//Show minimap 
var Languageletter82c="Показывать сетку мини-карты";		//Show minimap grid
var Languageletter82d="Показать указатели к позиции на мини-карте";		//Show minimap guides 
var Languageletter82e="Одноцветные товарищи по команде";		//One-colored teammates 
var Languageletter82f="Показывать оси мини-карте";		//Show extra minimap guides
var Languageletter82g="Призраки шаров на мини-карте";		//Show ghost cells

var Languageletter83="Помогаторы";		//Helpers 
var Languageletter84="Цвет противников";		//Opponents colors
var Languageletter85="Кольца противников";		//Opponents rings 
var Languageletter86="Цвет вирусов";		//Viruses colors 
var Languageletter87="Сплит-дальность";		//Split range 
var Languageletter87a="Быстрый двойной сплит дальность";		//Quick double split range
var Languageletter87b="Медленный двойной сплит дальность";		//Slow double split range

var Languageletter88="дальность вирусов";		//Viruses range 
var Languageletter89="Линии к курсору";		//Cursor tracking 
var Languageletter90="Индикатор товарищей";		//Teammates indicators
var Languageletter90a="Призраки шаров на карте";		//Ghost cells

var Languageletter91="Управление мышью";		//Mouse control 
var Languageletter92="Левая - сплит";		//LMB - Mouse split 
var Languageletter93="Правая - кормить";		//RMB - Mouse feed 
var Languageletter94="Инвертировать кнопки мыши";		//Invert mouse buttons 
var Languageletter94a="HUD";		// HUD 
var Languageletter95="Показать топ товарищей";		//Show team top 5
var Languageletter96="Показать таргетинг";		//Show targeting 
var Languageletter96a="Показать массу в лидерборде";		//Show leaderboard mass

var Languageletter97="Отцентрированый лидерборд";		//Centered leaderboard 
var Languageletter97a="Нормальный заголовок лидерборда";		//\"Leaderboard\" header 

var Languageletter98="Статистика игры в верхнем углу";		//Game stats at the top 
var Languageletter98a="Скины в топ 5";		//Skins on teamboard

var Languageletter99="Статистика";		//Stats 
var Languageletter100="Показать статистику игры";		//Show game stats 
var Languageletter101="Статистика игры";		//Game stats
//the \' is needed
var Languageletter102="Вражеский";		//Enemy\'s 		
var Languageletter103="Наш";		//Our
var Languageletter104="Минимальная массса тиммера для трика";		//Minimal tricksplit teammate\'s mass
var Languageletter104a="Максимальная масса врага для предварительного сплита";		//Maximal enemy\'s mass for presplit 
var Languageletter105="Показать время";		//Show current time 
var Languageletter106="Дополнительно";		//Extras 
var Languageletter107="Пропустить статистику после смерти";		//Skip stats after death 
var Languageletter108="Показать quesτ";		//Show quest 
var Languageletter108a="Игровые звуки"; //Game Sounds 
var Languageletter108b="Звуки меню"; //Menu Sounds 
var Languageletter109="Блокировать всплывающие окна (объявления / магазин / квест)";		//Block popups (ads/shop/quest) 
var Languageletter109a="Голос"; //Voice 
var Languageletter109b="Приставка"; //Voice-Prefix 
var Languageletter109c="Язык"; //Voice-language 
var Languageletter109d="Возобновить"; //UnPause

var Languageletter110="-- Качество графики --";		//-- Graphics Quality -- 
var Languageletter111="Графика: сетчатка";		//Graphics: Retina 
var Languageletter112="Графика: высокая";		//Graphics: High 
var Languageletter113="Графика: средний";		//Graphics: Medium" 
var Languageletter114="Графика: низкая";		//Graphics: Low 
var Languageletter115="Графика: очень низкая";		//Graphics: Very Low 
var Languageletter116="Настройки экспорта / импорта";		//Export / import settings 
var Languageletter117="Восстановить настройки по умолчанию";		//Restore default settings 
var Languageletter118="Экспорт настроек";		//Export settings 
var Languageletter119="Импорт настроек";		//Import settings 
var Languageletter120="Чтобы экспортировать выбранные настройки, скопируйте приведенный ниже код и сохраните его в текстовом файле, в кодировки юникода.";		//To export selected settings copy the code below and save it to a text file encoded in Unicode. 
var Languageletter121="Чтобы импортировать выбранные настройки, вставьте экспортированный код ниже и нажмите кнопку «Импорт настроек».";		//To import selected settings paste an exported code below and press the 'Import settings' button. 
var Languageletter122="Команды";		// Commands 
var Languageletter123="Клавиши";		// Hotkeys 
var Languageletter124="Профили";		// Profiles 
var Languageletter125="Настройки";		// Settings 
var Languageletter126="Тема";		// Theme 
var Languageletter127="Экспорт настроек";		//Export settings 
var Languageletter128="Импорт настроек";		//Import settings 
var Languageletter129="Основные темы";		//Basic theming 
var Languageletter130="Меню";		//Menu 
var Languageletter131="HUD";		//HUD 
var Languageletter132="Чат";		//Chat 
var Languageletter133="Мини-карта";		//Minimap 
var Languageletter134="Графика / курсоры";		//Graphics / cursors 
var Languageletter135="Предустановленная тема";		//Theme preset 
var Languageletter136="Легенд Оригинал";		//Legend Original 
var Languageletter137="Крейзи стайл";		//Crazy Style 1 
var Languageletter139="Фон";		//Background 
var Languageletter140="Границы карты";		//Map borders 
var Languageletter141="Сетка";		//Grid 
var Languageletter142="Размер шрифта";		//Sectors font 
var Languageletter143="Имена";		//Names 
var Languageletter144="Обводка имен";		//Names stroke 
var Languageletter145="Масса";		//Mass 
var Languageletter146="Обводка массы";		//Mass stroke 
var Languageletter147="Обводка вирусов";		//Virus stroke 
var Languageletter148="Вирус";		//Virus 
var Languageletter148a="Mатеринская клетка";		//Mothercell
var Languageletter148b="Обводка материнской клетки";		//Mothercell stroke
var Languageletter149="Еда";		//Food 
var Languageletter150="Индикатор товарищей";		//Teammate indicator 
var Languageletter151="Отслеживание курсора";		//Cursor tracking 
var Languageletter152="Сплит-дальность";		//Split range 
var Languageletter153="Шрифт имен";		//Names font 
var Languageletter154="Размер шрифта";		//Mass font 
var Languageletter154a="Больше";		//Bigger
var Languageletter154b="Меньшие";		//Smaller
var Languageletter155="Шрифт секторов";		//Sectors font 
var Languageletter157="Размер шрифта секторов";		//Sectors font size 
var Languageletter158="Масштаб имен";		//Names scale 
var Languageletter159="Масштаб массы";		//Mass scale 
var Languageletter160="Масштаб массы вируса";		//Virus mass scale 
var Languageletter161="Толщина обводки текста";		//Text stroke scale 
var Languageletter162="Размер еды";		//Food size: 
var Languageletter163="Толщина обводки вируса";		//Virus stroke size 
var Languageletter164="Ширина границ карты";		//Map borders width 
var Languageletter165="Ширина сетки";		//Sectors grid width 
var Languageletter166="Прозрачность ячеек";		//Cells transparency 
var Languageletter167="Прозрачность скинов";		//Skins transparency 
var Languageletter168="Прозрачность вирусов";		//Virus transparency 
var Languageletter169="Прозрачность массы и имени";		//Names & mass transparency 
var Languageletter170="Восстановить настройки темы по умолчанию";		//Restore theme default settings 
var Languageletter171="Сохранить настройки";		//Save settings 
var Languageletter172="Тема меню";		//Menu theme 
var Languageletter173="Фон";		//Background 
var Languageletter174="Прозрачность";		//Transparency 
var Languageletter175="Основной цвет";		//Main color 
var Languageletter176="Текст кнопки";		//Button text 
var Languageletter177="Панель";		//Panel 
var Languageletter179="Текст панели";		//Panel text 
var Languageletter181="Кнопка";		//Button 
var Languageletter189="Изображение фона панели";		//Panel background image 





var Languageletter190="URL картиники";		//Image URL 
var Languageletter191="Основной цвет";		//Main color 
var Languageletter192="Задний план";		//Background 
var Languageletter193="Текст";		//Text 
var Languageletter194="Статистика";		//Stats 
var Languageletter195="Время";		//Time 
var Languageletter196="Top 5 масса";		//Top 5 mass 
var Languageletter197="Мой цвет в топе";		//Leaderboard - me 
var Languageletter198="Товарищей цвет в топе";		//Leaderboard - teammate 
var Languageletter199="HUD шрифт";		//HUD font 
var Languageletter200="HUD масштаб";		//HUD scale: 
var Languageletter201="Фон сообщения";		//Message background 
var Languageletter202="Текст сообщения";		//Message text 
var Languageletter203="Время сообщения";		//Message time 
var Languageletter204="Ник сообщения";		//Message nick 
var Languageletter205="Фон команды";		//Command background 
var Languageletter206="Текст команды";		//Command text 
var Languageletter207="Время команды";		//Command time 
var Languageletter208="Ник команды";		//Command nick 
var Languageletter209="Цвет чатбокса";		//Chatbox color 
var Languageletter210="Размер чата";		//Chat scale 
var Languageletter211="Секторы";		//Sectors 
var Languageletter212="Текущий сектор";		//Current sector 
var Languageletter213="Ник";		//Nick 
var Languageletter214="Обводка ника";		//Nick stroke 
var Languageletter215="Мой шар";		//My cell 
var Languageletter216="Обводка моего шара";		//My cell stroke 
var Languageletter217="Товариши";		//Teammates 
var Languageletter218="Место смерти";		//Death location 
var Languageletter219="Руководство";		//Guides 
var Languageletter220="Шрифт мини-карты";		//Minimap font 
var Languageletter221="Шрифт ника";		//Nick font 
var Languageletter222="Ширина мини-карты";		//Minimap width 
var Languageletter223="Прозрачность секторов";		//Sectors transparency 
var Languageletter224="Размер ника";		//Nick size 
var Languageletter225="Толщина обводки ника";		//Nick stroke size 
var Languageletter226="Размер моего шара";		//My cell size 
var Languageletter227="Размер обводки моего шара";		//My cell stroke size 
var Languageletter228="Размер товарищей";		//Teammates size 
var Languageletter229="Кастомное фоновое изображение";		//Custom background image 
var Languageletter230="Кастомное изображение курсора";		//Custom cursor image 
var Languageletter231="URL изображения";		//Image URL 
var Languageletter232="URL изображения курсора";		//Cursor image URL 
var Languageletter233="Еда";		//Feed 
var Languageletter234="Быстро кормить";		//Macro feed 
var Languageletter235="Сплит";		//Split 
var Languageletter236="Дабл сплит";		//Double split 
var Languageletter237="Попсплит";		//Popsplit 
var Languageletter238="Сплит на 16";		//Split 16 
var Languageletter239="Остановка шара";		//Cell pause 
var Languageletter240="Показать / скрыть топ 5 товарищей";		//Show/hide team top 5 
var Languageletter241="Показать / скрыть время";		//Show/hide current time 
var Languageletter242="Показать / скрыть радиус сплита";		//Show/hide split range" 
var Languageletter243="Показать / скрыть индикаторы товарищей";		//Show/hide teammates indicators 
var Languageletter244="Показать / скрыть сплит индикаторы";		//Show/hide split indicators 
var Languageletter245="Показать / скрыть цвета противников";		//Show/hide opponents colors 
var Languageletter246="Переключить скины (пользовательские / по умолчанию)";		//Toggle skins (custom/default) 
var Languageletter247="Переключить прозрачные скины";		//Toggle transparent skins 
var Languageletter248="Показать / скрыть скины";		//Show/hide skins 
var Languageletter249="Показать / скрыть статистику игры";		//Show/hide game stats 
var Languageletter250="Переключить свои шары (самые маленькие / самые большие)";		//Toggle own cells (smallest/biggest) 
var Languageletter251="Показать / скрыть еду";		//Show/hide food 
var Languageletter252="Показать / скрыть сетку";		//Show/hide grid 
var Languageletter253="Показать / скрыть оси на мини-карте";		//Show/hide minimap guides 
var Languageletter254="Показать / скрыть чат";		//Show/hide chat 
var Languageletter255="Показать / спрятать HUD";		//Show/hide HUD 
var Languageletter256="Копировать лидерборд";		//Copy leaderboard 
var Languageletter257="Показать / скрыть лидерборд";		//Show/hide leaderboard 
var Languageletter258="Переключить автоматозум";		//Toggle auto zoom 
var Languageletter259="Сбросить зум";		//Reset zoom 
var Languageletter260="Переключить местоположение смерти";		//Toggle death location 
var Languageletter261="Показать историю чата / Очистить чат";		//Show chat history / Clear chat 
var Languageletter262="Показать / скрыть сектора";		//Show/hide background sectors 
var Languageletter263="Показать / скрыть маленьких";		//Show/hide small bots 
var Languageletter264="Показать / скрыть имена";		//Show/hide names 
var Languageletter265="Показать / скрыть имена товарищей";		//Show/hide teammates names 
var Languageletter266="Показать / скрыть массу";		//Show/hide mass 
var Languageletter267="Показать / скрыть мини-карту";		//Show/hide minimap 
var Languageletter268="Введите сообщение";		//Enter chat message 
var Languageletter269="Быстрый респавн";		//Quick respawn 
var Languageletter270="Переключить авто-респавн";		//Toggle auto respawn 
var Languageletter271="Уровень зума";		//Zoom level 
var Languageletter271a="Голос в текст";		//Voice to text
var Languageletter271b="Показать информацию на призраках";		//Show ghost cells information
var Languageletter271c="Автоматическая игра";		//Auto Play
var Languageletter272="Показать / скрыть панель таргетинга";		//Show/hide targeting panel 
var Languageletter273="Начать / остановить таргетинг (следование)";		//Start/stop targeting (following) 
var Languageletter274="Отменить таргетинг";		//Cancel targeting 
var Languageletter275="Изменить цель";		//Change target 
var Languageletter276="Показать цель на мини-карте";		//Show target on the minimap 
var Languageletter277="Показать / скрыть квест";		//Show/hide quest 
var Languageletter278="Чтобы назначить горячую клавишу, нажмите на поле ввода и нажмите выбранную вами клавишу";		//To assign a hotkey click on the input field and press your chosen key. 
var Languageletter279="Чтобы удалить горячую клавишу, нажмите на поле ввода и нажмите клавишу DELETE";		//To delete a hotkey click on the input field and press the DELETE key. 
var Languageletter280="Возможны комбинации клавиш с CTRL и ALT";		//Possible key combinations with the CTRL and ALT keys. 
var Languageletter281="Восстановить настройки по умолчанию";		//Restore default settings 
var Languageletter282="Сохранить настройки";		//Save settings 
var Languageletter283="Закрыть";		//Close 
var Languageletter284="Youtube плеер";		//Youtube player 
var Languageletter284a="Youtube ссылка";		// Youtube Url 
var Languageletter285="Вставьте свое видео / плейлист здесь";		//Paste your video/playlist here 
var Languageletter286="Звуки";		//Sounds 
var Languageletter287="Звук сообщений";		//Message notification sound 
var Languageletter288="Звук команд";		//Command notification sound 
var Languageletter289="Копировать токен / SIP";		//Copy Token/SIP //keep this small 
var Languageletter290="Токен";		//Token 
var Languageletter290a="Доска"; //Board 
var Languageletter290b="токен+тег";	//TK&PW (Token and Password) 
var Languageletter290c="токен"; //TK&ALL (Token and All) 
var Languageletter291="Copy";		//Copy 
var Languageletter291a="Копировать лидерборд (L)";		//Copy Leaderboard (L) 
var Languageletter291b="Копировать токен / SIP и тег"; 	//Copy Token/SIP&Password 
var Languageletter291c="Копировать токен / SIP, тег, лидерборд ..."; //Copy Token/SIP, Password, Leaderboard... 
var Languageletter292="Присоединиться к серверу (Backspace)";		//Join server (Backspace) 
var Languageletter293="Изменить сервер (+)";		//Change server (+) 
var Languageletter294="История лидерборда";		//Leaderboard history 
var Languageletter295="Введите токен друга, IP, лидерборд, имя или клан ...";		//Enter friend token, IP, leaderboard, name or clan tag... 
var Languageletter295a="Очистить список"; //Clear list 
var Languageletter295b="Введите сообщение..."; //Enter chat message... 
var Languageletter298="Товарищи";		//Team
var Languageletter299="Лидерборд";		//Leaderbodard 
var Languageletter300="Коммуникация";		//Communication 
var Languageletter301="Команды скрипт сообщения";		//Message Script Commands 
var Languageletter302="Картинки сообщений Imgur";		//Message Imgur Icons 
var Languageletter303="Видео сообщений для Youtube";		//Message Youtube Videos 
var Languageletter304="Изменить имена";		//Edit names 
var Languageletter305="[Только для наблюдения] Бинокль";		//[Spectate Mode Only] Binoculars 
var Languageletter306="Играть / Пауза";		//Play / Pause 
var Languageletter307="На весь экран";		//Fullscreen 
var Languageletter308="Поворот";		//Rotate 
var Languageletter309="По умолчанию";		//Default 
var Languageletter310="Назад";		//Back 
var Languageletter311="Сохранить на потом";		//Save for later 
var Languageletter312="Регион";		//Region 
var Languageletter313="Игроки";		//Players 
var Languageletter314="Серверы";		//Servers 
var Languageletter315="[Цель не установлена]";		//[Target not set] 
var Languageletter316="Ручной фон";		//Manual background 
var Languageletter317="Иконки сообщений руководства и Youtube";		//Manual Message Icons&Youtube 
var Languageletter318="Позиция чата";		//Chat Position 
var Languageletter319="Адрес вебхука дискорда (для отправки токенов)";		//Discord Webhook Url (for sending TOKEN) 
var Languageletter320="Лидерборд";		//Leaderboard 
var Languageletter321="Товарищи";		//Teamboard 
var Languageletter322="Основной холст";		//Main Canvas 
var Languageletter323="Главный баннер";		//Main Banner 
var Languageletter324="Слава Украине!";		//Hello Team! 
var Languageletter325="Смех для команды";		//Laugh to Team 
var Languageletter326="Изменить имя команды на свое";		//Team Change Name to yours 
var Languageletter327="Троллировать когда съели";		//Troll on Death 
var Languageletter328="Открыть музыку Youtube";		//Open Youtube Music 
var Languageletter329="Безумный режим (Скрыть все)";		//Insane mode (Hide Everything) 
var Languageletter330="URL-адрес изображения, начинающегося с http(s)";		//Url of image starting with http://... or https://... 
var Languageletter331="URL-адрес фона миникарты";		//Minimap Image URL 
var Languageletter332="Текст мини-карты";		//Minimap Text 
var Languageletter333="Лидерборд лого-текст";		//Leaderboard Logo Text 
var Languageletter333a="URL-адрес фона лидерборда";		// Leaderboard Image URL 
var Languageletter334="Тест тимборда";		//Teamboard Logo Text 
var Languageletter334a="URL-адрес фона тимборда";		// Teamboard Image URL 
var Languageletter335="URL-адрес основного фона";		//Main Canvas Image URL 
var Languageletter336="URL-адрес основного баннера";		//Main Banner Icon URL 
var Languageletter337="URL-адрес баннерной ссылки";		//Main Banner Link URL 
var Languageletter338="Значок";		//Icon 
var Languageletter339="например";		//e.g 
var Languageletter340="Адрес Youtube для отображения";		//Url of youtube to be shown 
var Languageletter341="URL-адрес для перенаправления";		//Url of link to redirect 
var Languageletter342="Discord Webhook адрес";		//Discord Webhook Url 
var Languageletter342a="Иконка сообщения";		//Message Icon Text 
var Languageletter342b="Текст сообщения Youtube";		//Youtube Message Text 
var Languageletter342c="Картинка сообщения Imgur";		//Message Icon Imgur Url 
var Languageletter342d="Адрес сообщения Youtube";		//Youtube Message Url 
var Languageletter343="Должно быть заполнено для работы";		//Must be filled for function to work. 
var Languageletter344="Вторичный Webhook (необязательно)";		//Secondary Webhook(optional) 
var Languageletter345="ПРЕДУПРЕЖДЕНИЕ! Всплывающие окна блокируются в настройках.";		//WARNING! Popups are blocked in the settings. 
var Languageletter346="Временно разблокировать";		//Temporary unblock 
var Languageletter347="ПРЕДУПРЕЖДЕНИЕ! Всплывающие окна блокируются в настройках.";		//WARNING! Popups are blocked in the settings. 
var Languageletter348="Временно разблокировать";		//Temporary unblock 
var Languageletter349="Зелья";	//Potions 
var Languageletter350="Старые скины";	//Old Skins 
var Languageletter351="Специальные предложения"; //Special Deals 
var Languageletter352="Доска лидеров"; //Leaderboards 
var Languageletter353="Новые идеи и форма статистики"; //New Ideas & Statistics Form 
var Languageletter354="Видео скины"; //Video Skins 
var Languageletter355="Мини-скрипты"; //Mini Scripts 
var Languageletter356="Пользовательские скрипты"; //User Scripts 
var Languageletter357="Голосовой и видео чат";	//Voice & Camera Chat 
var Languageletter358="Пожалуйста, поддержите разработку мода Legend";	//Please support the development of Legend mod 
var Languageletter359="Генератор ника";	//Design Nickname Font 
var Languageletter360="Поддельный скин";	//Flag the Fake Skin 
var Languageletter361="Больше FPS";	//More FPS 
var Languageletter362="Имя";	//Name
var Languageletter363="ID";	//Social ID
var Languageletter364="Расширения";	//Expansions
var Languageletter365 = "Универсальный чат";	//Universal
var Languageletter366="Счёт";	//Score
var Languageletter367="Расстояние";	//Distance
var Languageletter368="Общая масса";	//Total Mass
var Languageletter369="Мертв";	//Dead

var Premadeletter0="Активация связи"; 		//Communication Activated 
var Premadeletter1="Не удается открыть этот URL-адрес YouTube.";		 //Cannot open this youtube URL 
var Premadeletter2="Вы не можете общаться, если имя игрока> 15 символов"; 		//[SERVER]: You cannot chat if player name > 15 chars 
var Premadeletter3="Пасхальное яйцо 1 активировано"; 		//Easter Egg 1 Activated 
var Premadeletter4="Пасхальное яйцо 2 активировано";		//Easter Egg 2 Activated 
var Premadeletter5="Пасхальное яйцо 3 активировано";		//Easter Egg 3 Activated 
var Premadeletter6="Видео работает лучше на ваниль, посетите:";		//Video works better on vanilla, visit: 
var Premadeletter7="Примечания: <b> Facebook </b> совместимость лучше, чем <b> Google Plus </b>."; 		//Notes:<b>Facebook</b> compatibility is better than <b>Google Plus</b>. 
var Premadeletter8="Примечания. Agar.io может подключаться только к <b> Google Plus </ b> при событиях onload. Если происходит выход из системы, присоединитесь к Agar.io или используйте <b> Facebook </b>.";		//Notes:Agar.io can only connect to <b>Google Plus</b> on onload events. If logout occurs, rejoin Agar.io or use <b>Facebook</b>. 
var Premadeletter9="Если в событиях onload произошел выход из системы, удалите почистите куки";		//If logout occurs on onload events, delete Chrome cookies from 
var Premadeletter10="Отключен от сервера :(";		//Disconnected from server :( 
var Premadeletter11="Вы были заблокированы, перезаподключитесь к интернету!";		//You were banned, restart your rooter! 
var Premadeletter12="Соединено!";		//Connected! 
var Premadeletter13="ИГРАТЬ";		//PLAY 
var Premadeletter14="НАБЛЮДАТЬ";		//SPECTATE 
var Premadeletter15="Недопустимый токен или сервер закрыт :(";		//Invalid token or server has closed :( 
var Premadeletter16="может быть обновлено до";		//can be Updated to 
var Premadeletter17="Добро пожаловать";			//Welcome back 
var Premadeletter18="Ваша область ярлыка и другие области (с последней вкладки) по-прежнему отключены! Мы предлагаем вам включить их.";		//Your shortcut area and other areas (from last tab) are still disabled! We suggest you enable them. 
var Premadeletter19="Включить их";		//Enable Them 
var Premadeletter20="Оставить их отключенными";		//Keep Them Disabled 
var Premadeletter21="Поиск IP-адреса";		//Searching IP 
var Premadeletter22="Ваш товарищ по команде";		//Your teammate 
var Premadeletter23="хочет, чтобы вы спрятали все (таблица лидеров и мини-карта)";		//wants you to hide all (leaderboard and minimap) 
var Premadeletter24="принимать";		//Accept 
var Premadeletter25="ответ отрицательный!";		//NO WAY! 
var Premadeletter26="хочет, чтобы вы изменили свое имя на";		//wants you to change your name to 
var Premadeletter27="хочет, чтобы вы включили троллинг при смерти";		//wants you to hide Enable Troll on death 
var Premadeletter28="хочет, чтобы вы открыли Youtube Player";			//wants you to open Youtube Player 
var Premadeletter29="Найден лидерборд";		//Leaderboard found 
var Premadeletter30="Поиск";		//Search 
var Premadeletter31="Таблица лидеров не найдена. Продолжайте ...";		//The leaderboard was not found. Keep trying... 
var Premadeletter32="Поиск отменен";		//Search was canceled 
var Premadeletter33="Вы невидимы для команды / клана";		//You are invisible to Team / Clan 
var Premadeletter34="Вы видите команду / клан";		//You are visible to Team / Clan 
var Premadeletter35="Скрыть / показать можно использовать только во время воспроизведения";			//Hide/Show can be used only while playing 
var Premadeletter36="Что то тут неправильно";		//This is not valid Discord Webhook address 
var Premadeletter37="Сервер закрыт";		//Server is locked 
var Premadeletter38="Вы должны быть в наблюдении";		//You must be on spectate mode 
var Premadeletter39="Из-за проблем со спамом вы должны быть в игре и использовать пароль";		//Due to spamming issues, you must be in game and use password //					These buttons must no be big in length 
var Premadeletter40="Авто Youtube вкл";		//Auto Youtube On 
var Premadeletter41="Авто Youtube выкл";		//Auto Youtube Off 
var Premadeletter42="Показать ярлыки";		//Show Shortcuts 
var Premadeletter43="Скрыть ярлыки";		//Hide Shortcuts 
var Premadeletter44="Показать XP BAR";		//Show XP BAR 
var Premadeletter45="Скрыть XP BAR";		//Hide XP BAR 
var Premadeletter45a = "Округление HUD"; //Rounded Hud 
var Premadeletter45b = "Квадратный HUD"; //Square Hud 
var Premadeletter46 = "Цвет линий HUD"; //Linear color Hud
var Premadeletter47 = "Жирный цвет HUD"; //Bold color Hud
var Premadeletter48="Показать все";		//Show Everything 
var Premadeletter49="Скрыть все";		//Hide Everything 
var Premadeletter50="Показ. кальк. времени";		//Show Timer Calc. 
var Premadeletter51="Скры. кальк. времени"		//Hide Timer Calc. 
var Premadeletter53="Автом. беспл. монеты";		//Auto free coins 
var Premadeletter54="Останов. беспл. монеты";		//Stop free coins 
var Premadeletter55="Троллинг при смерти";		//Troll on Death 
var Premadeletter56="Не троллить при смерти";		//No troll on Death 
var Premadeletter57="Связь";		//Communication 
var Premadeletter58="Скрытый";		//Hidden 
var Premadeletter59="Видимый";		//Visible 
var Premadeletter60="Пауза";		//Pause 
var Premadeletter61 = "Включить YT в качестве фона";	//Enable YT as background 
var Premadeletter62 = "Отключить YT в качестве фона";	//Disable YT as background"; 
var Premadeletter63 = "хочет, чтобы вы открыли URL-адрес";	//wants you to open the url 
var Premadeletter64 = "хочет, чтобы вы вставили и это видео с YouTube";	//wants you to embed and play this youtube video 
var Premadeletter65 = "хочет, чтобы вы присоединились к Skype";	//wants you to join the following Skype room 
var Premadeletter66 = "хочет, чтобы вы присоединились к Discord";	//wants you to join the following Discord room 
var Premadeletter67 = "хочет, чтобы вы перешли на другой сервер";	//wants you to leave this server and join this new one 
var Premadeletter68 = "Вы нажали"; //You pressed 
var Premadeletter69 = "перезапустить, если"; //restart if 
var Premadeletter70 = "броски"; //drops 
var Premadeletter71 = "Анимированные скины"; //Animated skins 
var Premadeletter72 = "включен"; //enabled 
var Premadeletter73 = "бросок"; //drop 
var Premadeletter74 = "когда"; //when 
var Premadeletter75 = "Анимированные скины будут"; //Animated skins will be 
var Premadeletter76 = "отключен"; //disabled 
var Premadeletter77 = "после перезахода"; //after rejoin 
var Premadeletter78 = "Лучше FPS"; //Better FPS 
var Premadeletter79 = "производительность когда 16"; //performance when 16 
var Premadeletter80 = "Когда Dying Light Expansion включен, трольь при смерти невозможен"; //When Dying Light Expansion is enabled, Troll on death cannot occur 
var Premadeletter81 = "Приватный сервер"; //Private Server 
var Premadeletter82 = "Подключиться к любому"; //Connect to any 
var Premadeletter83 = "сервер, или создать собственный"; //server, or make your own 
var Premadeletter84 = "Играйте в игры, подобные азарио, если вы знаете IP-серверы"; //Play agario-like games if you know the IP of servers 
var Premadeletter85 = "Ваше изображение было скопировано в буфер обмена. Вставьте его"; // Image of your has been copied to clipboard. Paste it 
var Premadeletter86 = "к пользовательской области URL-адреса"; //to custom skin Url area 
var Premadeletter87 = "Вы должны Войти, чтобы использовать фотографию своего профиля"; //You must Login to use picture of your profile 
var Premadeletter88 = "Вы используете неправильную версию"; //You are using a wrong version 
var Premadeletter89 = "Игра закончится сейчас"; //Game will terminate now 
var Premadeletter90 = "Специальные предложения"; //Special Deals 
var Premadeletter91 = "Агарио может назначать и не назначать скины, но только монеты"; //Agario may or may not give you the Skin, but only the coins 
var Premadeletter91a = "Используйте на свой риск"; //Use at your own risk 
var Premadeletter92 = "Если UID вашего друга ошибочен, покупка не удастся"; //If friend UID is wrong, purchase will fail 
var Premadeletter93 = "Заводские настройки UID"; //UID Factory Settings 
var Premadeletter94 = "Вы должны войти, чтобы загрузить специальные предложения"; //You must login to load Special Deals 
var Premadeletter95 = "Поддельное изображение было скопировано в буфер обмена. Вставить его"; // Fake image has been copied to clipboard. Paste it 
var Premadeletter96 = "к пользовательской области URL-адреса скина, чтобы активировать функцию фальшивого флага"; // o custom skin Url area in order to activate the fake flag function 
var Premadeletter97 = "Сообщите мне, когда вы закончите с Recaptcha"; //Inform me when you finish with Recapatcha 
var Premadeletter98 = "Я закончил"; //I have finished 
var Premadeletter99 = "Неважно"; //Never Mind 
var Premadeletter100 = "Определение XP, подождите ..."; //Calculating your XP, please wait... 
var Premadeletter101 = "Применить"; //Do 
var Premadeletter102 = "Нет"; //NOT 
var Premadeletter103 = "Нажмите"; //press 
var Premadeletter104 = "Стереть пользовательский URL-адрес скина"; //Erase custom skin URL 
var Premadeletter105 = "выбрать видео скин";	//select video skin 
var Premadeletter106 = "снять видео с экрана"; //unselect video skin 
var Premadeletter107 = "звук без звука"; //mute audio 
var Premadeletter108 = "Проект LegendMod"; //The LM Project 
var Premadeletter109 = "Загрузить"; //Upload 
var Premadeletter109a = "Скачать"; //Download
var Premadeletter109b = "Загрузка"; //Load

var Premadeletter110 = "не вводите ничего здесь, если вы не знаете, что это такое";	//do not enter anything here unless you know what it is 
var Premadeletter111 = "нажмите на значок оранжевого цвета, чтобы купить"; //click on the orange icon to buy 
var Premadeletter112 = "Для некоторых способов оплаты"; //For some payment methods 
var Premadeletter113 = "Закрыть";	//Close 
var Premadeletter114 = "Копия"; //COPY	 
var Premadeletter115 = "используется для покупки предложений для ваших друзей"; //is used to buy offers for your friends 
var Premadeletter116 = "Чтобы совершать покупки, вы должны войти в свою учетную запись ..."; //To make purchases, you must be logged in to your account… 
var Premadeletter117 = "Библиотека"; //Library 
var Premadeletter118 = "посетить"; //visit 
var Premadeletter119 = "Сообщить как фальшивый (изменение скина)"; //Report as Fake (change Skin) 
var Premadeletter120 = "Введите свое ТОЧНОЕ имя игрока"; //Enter your EXACT name of the player 
var Premadeletter121 = "Злоупотребление игроками и неправильное использование UID пользователя"; //Abusing players and inappropriate use will lead UID of user 
var Premadeletter122 = "к постоянному запрету использования этого расширения"; //to permanent ban from usage of this extension 
var Premadeletter128 = "Требуется логин"; //User login needed
var Premadeletter129 = "Настройки успешно загружены"; //Settings successfully uploaded
//These are for file: https://jimboy3100.github.io/ogario/ogario.v4.js and https://jimboy3100.github.io/ogario/ogario.v4.master.js
var Premadeletter123 = "Серврер"; //SERVER
var Premadeletter124 = "Избегайте использования видео-скинов больше 6 минут"; //Avoid using video skins bigger than 6 minutes
var Premadeletter125 = "Карта нормализирована"; //Map fixed
var Premadeletter126 = "Выполнен вход в"; //Logged in to
var Premadeletter127 = "Выполнен выход"; //Logged out
var Premadeletter130 = "Всего"; //Total
var Premadeletter131 = "NEW"; //NEW
var Premadeletter132 = "Присоединиться к предыдущему"; //Join Back
var Premadeletter133 = "Подключиться к последнему серверу, на котором вы играли"; //Connect to last IP you played
var Premadeletter134 = "Северная Америка"; //North America
var Premadeletter135 = "Южная Америка"; //South America
var Premadeletter136 = "Европа"; //Europe
var Premadeletter137 = "Россия"; //Russia
var Premadeletter138 = "Турция"; //Turkey
var Premadeletter139 = "Восточная Азия"; //East Asia
var Premadeletter139a = "Китай"; //China
var Premadeletter140 = "Океания"; //Oceania
var Premadeletter140a = " -- Где играть? -- "; // -- Select a Region -- 
var Premadeletter141 = "FFA"; //FFA
var Premadeletter142 = "Королевская битва"; //Battle Royale
var Premadeletter143 = "Команды"; //Teams
var Premadeletter144 = "Экспа"; //Experimental
var Premadeletter145 = "Пати"; //Party Mode

var Externalletter0a = "ЯЗЫКИ"; //LANGUAGES 
var Externalletter0b = "Выберать язык"; //Choose a language 
var Externalletter0c = "Изменения будут отображены после перезапуска"; //Changes will take place completely after the restart 
var Externalletter1 = "ИНФОРМАЦИЯ"; //INFORMATION 
var Externalletter2 = "ШАБЛОНЫ"; //TEMPLATES 
var Externalletter3 = "РУЧНЫЕ ШАБЛОНЫ"; //MANUAL TEMPLATES 
var Externalletter4 = "Выберите шаблон"; //Choose your template 
var Externalletter5 = "Или выберите расширение"; //Or choose an expansion //These are for file: https://jimboy3100.github.io/legendformIframe.js 
var Externalletter5a = "ПЕРЕДАТЬ КОД ДЛЯ РАЗРАБОТЧИКАМ"; //SEND CODE TO DEVELOPERS //These are for file: https://jimboy3100.github.io/legend.sniff3.js 
var Externalletter6 = "Вставьте свой скрипт в это поле ввода. Можно загрузить несколько скриптов"; //Paste your Script in this Textarea, you can load multiple Scripts 
var Externalletter7 = "Загрузить скрипт из поля ввода"; //Load Script from Textarea 
var Externalletter8 = "Выбор"; //Choose 
var Externalletter9 = "Стереть скрипт"; //Erase Script 
var Externalletter10 = "Имя"; //Name 
var Externalletter11 = "Адрес на другой скрипт"; //Url of Raw Github, or other Raw Script, starting with 
var Externalletter12 = "Оставьте это пустым, если скрипт не должен быть импортирован по адресу"; //Leave this empty if script not imported from URL 
var Externalletter13 = "ВАЖНОЕ ЗАМЕЧАНИЕ. Не держите URL-адреса, которые не работают, потому что они используются как события onload. Если сценарий повреждает события onload, тогда DELETE COOKIES"; //IMPORTANT NOTICE: Do not keep URLs which do not work, because they are used as onload events. If Scenario damages onload events, then DELETE COOKIES
