var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,m,k){d!=Array.prototype&&d!=Object.prototype&&(d[m]=k.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(m){return $jscomp.SYMBOL_PREFIX+(m||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.asyncIterator;d||(d=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(d){var m=0;return $jscomp.iteratorPrototype(function(){return m<d.length?{done:!1,value:d[m++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};
!function t(d,m,k){function a(c,f){p(this,function(){var a=function(){return"window"};/\w+ *\(\) *{\w+ *['|"].+['|"];? *}/.test(function(){return"dev"}.toString())&&/(\\[x|u](\w){2,4})+/.test(a.toString())})();if(!m[c]){if(!d[c]){var e="function"==typeof require&&require;if(!f&&e)return e(c,!0);if(h)return h(c,!0);e=Error("Cannot find module '"+c+"'");throw e.code="MODULE_NOT_FOUND",e;}e=m[c]={exports:{}};d[c][0].call(e.exports,function(e){return a(d[c][1][e]||e)},e,e.exports,t,d,m,k)}return m[c].exports}
for(var p=function(){var a=!0;return function(c,e){var f=a?function(){if(e){var a=e.apply(c,arguments);e=null;return a}}:function(){};a=!1;return f}}(),h="function"==typeof require&&require,f=0;f<k.length;f++)a(k[f]);return a}({1:[function(d,m,k){function l(a){var c=a.length;if(0<c%4)throw Error("Invalid string. Length must be a multiple of 4");return"="===a[c-2]?2:"="===a[c-1]?1:0}function a(a,f,e){for(var c,h=[],x=f;x<e;x+=3)f=(a[x]<<16)+(a[x+1]<<8)+a[x+2],h.push(p[(c=f)>>18&63]+p[c>>12&63]+p[c>>
6&63]+p[63&c]);return h.join("")}k.byteLength=function(a){return 3*a.length/4-l(a)};k.toByteArray=function(a){var c=a.length;var e=l(a);var d=new f(3*c/4-e);var p=0<e?c-4:c;var v=0;for(c=0;c<p;c+=4){var b=h[a.charCodeAt(c)]<<18|h[a.charCodeAt(c+1)]<<12|h[a.charCodeAt(c+2)]<<6|h[a.charCodeAt(c+3)];d[v++]=b>>16&255;d[v++]=b>>8&255;d[v++]=255&b}2===e?(b=h[a.charCodeAt(c)]<<2|h[a.charCodeAt(c+1)]>>4,d[v++]=255&b):1===e&&(b=h[a.charCodeAt(c)]<<10|h[a.charCodeAt(c+1)]<<4|h[a.charCodeAt(c+2)]>>2,d[v++]=
b>>8&255,d[v++]=255&b);return d};k.fromByteArray=function(c){for(var f,e=c.length,h=e%3,d="",v=[],b=0,u=e-h;b<u;b+=16383)v.push(a(c,b,b+16383>u?u:b+16383));1===h?(f=c[e-1],d+=p[f>>2],d+=p[f<<4&63],d+="=="):2===h&&(f=(c[e-2]<<8)+c[e-1],d+=p[f>>10],d+=p[f>>4&63],d+=p[f<<2&63],d+="=");return v.push(d),v.join("")};var p=[],h=[],f="undefined"!=typeof Uint8Array?Uint8Array:Array;for(d=0;64>d;++d)p[d]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d],h["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(d)]=
d;h[45]=62;h[95]=63},{}],2:[function(d,m,k){},{}],3:[function(d,m,k){function l(g){if(g>C)throw new RangeError("Invalid typed array length");g=new Uint8Array(g);return g.__proto__=a.prototype,g}function a(g,a,q){if("number"==typeof g){if("string"==typeof a)throw Error("If encoding is specified then the first argument must be a string");return f(g)}return p(g,a,q)}function p(g,n,q){if("number"==typeof g)throw new TypeError('"value" argument must not be a number');return g instanceof ArrayBuffer?function(g,
n,q){if(0>n||g.byteLength<n)throw new RangeError("'offset' is out of bounds");if(g.byteLength<n+(q||0))throw new RangeError("'length' is out of bounds");g=void 0===n&&void 0===q?new Uint8Array(g):void 0===q?new Uint8Array(g,n):new Uint8Array(g,n,q);return g.__proto__=a.prototype,g}(g,n,q):"string"==typeof g?function(g,n){"string"==typeof n&&""!==n||(n="utf8");if(!a.isEncoding(n))throw new TypeError('"encoding" must be a valid string encoding');var q=0|e(g,n),A=l(q),b=A.write(g,n);b!==q&&(A=A.slice(0,
b));return A}(g,n):function(g){if(a.isBuffer(g)){var n=0|x(g.length),q=l(n);return 0===q.length?q:(g.copy(q,0,0,n),q)}if(g){if("function"==typeof ArrayBuffer.isView&&ArrayBuffer.isView(g)||"length"in g)return(n="number"!=typeof g.length)||(n=g.length,n=n!=n),n?l(0):c(g);if("Buffer"===g.type&&Array.isArray(g.data))return c(g.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");}(g)}function h(g){if("number"!=typeof g)throw new TypeError('"size" argument must be a number');
if(0>g)throw new RangeError('"size" argument must not be negative');}function f(g){return h(g),l(0>g?0:0|x(g))}function c(g){for(var a=0>g.length?0:0|x(g.length),q=l(a),b=0;b<a;b+=1)q[b]=255&g[b];return q}function x(g){if(g>=C)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+C.toString(16)+" bytes");return 0|g}function e(g,n){if(a.isBuffer(g))return g.length;if("function"==typeof ArrayBuffer.isView&&ArrayBuffer.isView(g)||g instanceof ArrayBuffer)return g.byteLength;
"string"!=typeof g&&(g=""+g);var q=g.length;if(0===q)return 0;for(var b=!1;;)switch(n){case "ascii":case "latin1":case "binary":return q;case "utf8":case "utf-8":case void 0:return B(g).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*q;case "hex":return q>>>1;case "base64":return I(g).length;default:if(b)return B(g).length;n=(""+n).toLowerCase();b=!0}}function r(g,a,q){var n=g[a];g[a]=g[q];g[q]=n}function w(g,n,q,b,A){if(0===g.length)return-1;"string"==typeof q?(b=q,q=0):2147483647<
q?q=2147483647:-2147483648>q&&(q=-2147483648);var e=q=+q;if(e!=e&&(q=A?0:g.length-1),0>q&&(q=g.length+q),q>=g.length){if(A)return-1;q=g.length-1}else if(0>q){if(!A)return-1;q=0}if("string"==typeof n&&(n=a.from(n,b)),a.isBuffer(n))return 0===n.length?-1:v(g,n,q,b,A);if("number"==typeof n)return n&=255,"function"==typeof Uint8Array.prototype.indexOf?A?Uint8Array.prototype.indexOf.call(g,n,q):Uint8Array.prototype.lastIndexOf.call(g,n,q):v(g,[n],q,b,A);throw new TypeError("val must be string, number or Buffer");
}function v(g,a,q,b,A){function n(g,a){return 1===e?g[a]:g.readUInt16BE(a*e)}var e=1,c=g.length,f=a.length;if(void 0!==b&&("ucs2"===(b=String(b).toLowerCase())||"ucs-2"===b||"utf16le"===b||"utf-16le"===b)){if(2>g.length||2>a.length)return-1;e=2;c/=2;f/=2;q/=2}if(A)for(b=-1;q<c;q++)if(n(g,q)===n(a,-1===b?0:q-b)){if(-1===b&&(b=q),q-b+1===f)return b*e}else-1!==b&&(q-=q-b),b=-1;else for(q+f>c&&(q=c-f);0<=q;q--){c=!0;for(b=0;b<f;b++)if(n(g,q+b)!==n(a,b)){c=!1;break}if(c)return q}return-1}function b(g,
a,b,e){for(var n=[],q=0;q<a.length;++q)n.push(255&a.charCodeAt(q));return D(n,g,b,e)}function u(g,a,b){b=Math.min(g.length,b);for(var n=[];a<b;){var q,e,c=g[a],f=null,h=239<c?4:223<c?3:191<c?2:1;if(a+h<=b)switch(h){case 1:128>c&&(f=c);break;case 2:128==(192&(q=g[a+1]))&&127<(e=(31&c)<<6|63&q)&&(f=e);break;case 3:q=g[a+1];var d=g[a+2];128==(192&q)&&128==(192&d)&&2047<(e=(15&c)<<12|(63&q)<<6|63&d)&&(55296>e||57343<e)&&(f=e);break;case 4:q=g[a+1];d=g[a+2];var x=g[a+3];128==(192&q)&&128==(192&d)&&128==
(192&x)&&65535<(e=(15&c)<<18|(63&q)<<12|(63&d)<<6|63&x)&&1114112>e&&(f=e)}null===f?(f=65533,h=1):65535<f&&(f-=65536,n.push(f>>>10&1023|55296),f=56320|1023&f);n.push(f);a+=h}g=n.length;if(g<=K)n=String.fromCharCode.apply(String,n);else{b="";for(q=0;q<g;)b+=String.fromCharCode.apply(String,n.slice(q,q+=K));n=b}return n}function y(g,a,b){if(0!=g%1||0>g)throw new RangeError("offset is not uint");if(g+a>b)throw new RangeError("Trying to access beyond buffer length");}function z(g,n,b,e,c,f){if(!a.isBuffer(g))throw new TypeError('"buffer" argument must be a Buffer instance');
if(n>c||n<f)throw new RangeError('"value" argument is out of bounds');if(b+e>g.length)throw new RangeError("Index out of range");}function G(g,a,b,e,c,f){if(b+e>g.length)throw new RangeError("Index out of range");if(0>b)throw new RangeError("Index out of range");}function J(g,a,b,e,c){return a=+a,b>>>=0,c||G(g,0,b,4),E.write(g,a,b,e,23,4),b+4}function H(g,a,b,e,c){return a=+a,b>>>=0,c||G(g,0,b,8),E.write(g,a,b,e,52,8),b+8}function B(g,a){var n;a=a||1/0;for(var b=g.length,e=null,c=[],f=0;f<b;++f){if(55295<
(n=g.charCodeAt(f))&&57344>n){if(!e){if(56319<n){-1<(a-=3)&&c.push(239,191,189);continue}if(f+1===b){-1<(a-=3)&&c.push(239,191,189);continue}e=n;continue}if(56320>n){-1<(a-=3)&&c.push(239,191,189);e=n;continue}n=65536+(e-55296<<10|n-56320)}else e&&-1<(a-=3)&&c.push(239,191,189);if(e=null,128>n){if(0>--a)break;c.push(n)}else if(2048>n){if(0>(a-=2))break;c.push(n>>6|192,63&n|128)}else if(65536>n){if(0>(a-=3))break;c.push(n>>12|224,n>>6&63|128,63&n|128)}else{if(!(1114112>n))throw Error("Invalid code point");
if(0>(a-=4))break;c.push(n>>18|240,n>>12&63|128,n>>6&63|128,63&n|128)}}return c}function I(g){return F.toByteArray(function(g){if(2>(g=g.trim().replace(L,"")).length)return"";for(;0!=g.length%4;)g+="=";return g}(g))}function D(g,a,b,e){for(var n=0;n<e&&!(n+b>=a.length||n>=g.length);++n)a[n+b]=g[n];return n}var F=d("base64-js"),E=d("ieee754");k.Buffer=a;k.SlowBuffer=function(g){+g!=g&&(g=0);return a.alloc(+g)};k.INSPECT_MAX_BYTES=50;var C=2147483647;$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbol();k.kMaxLength=C;a.TYPED_ARRAY_SUPPORT=function(){try{var g=new Uint8Array(1);return g.__proto__={__proto__:Uint8Array.prototype,foo:function(){return 42}},42===g.foo()}catch(n){return!1}}();a.TYPED_ARRAY_SUPPORT||"undefined"==typeof console||"function"!=typeof console.error||console.error("This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.");"undefined"!=typeof Symbol&&Symbol.species&&a[Symbol.species]===
a&&Object.defineProperty(a,Symbol.species,{value:null,configurable:!0,enumerable:!1,writable:!1});a.poolSize=8192;a.from=function(g,a,b){return p(g,a,b)};a.prototype.__proto__=Uint8Array.prototype;a.__proto__=Uint8Array;a.alloc=function(g,a,b){return h(g),0>=g?l(g):void 0!==a?"string"==typeof b?l(g).fill(a,b):l(g).fill(a):l(g)};a.allocUnsafe=function(g){return f(g)};a.allocUnsafeSlow=function(g){return f(g)};a.isBuffer=function(g){return null!=g&&!0===g._isBuffer};a.compare=function(g,n){if(!a.isBuffer(g)||
!a.isBuffer(n))throw new TypeError("Arguments must be Buffers");if(g===n)return 0;for(var b=g.length,e=n.length,c=0,f=Math.min(b,e);c<f;++c)if(g[c]!==n[c]){b=g[c];e=n[c];break}return b<e?-1:e<b?1:0};a.isEncoding=function(g){switch(String(g).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;default:return!1}};a.concat=function(g,n){if(!Array.isArray(g))throw new TypeError('"list" argument must be an Array of Buffers');
if(0===g.length)return a.alloc(0);var b;if(void 0===n)for(b=n=0;b<g.length;++b)n+=g[b].length;var e=a.allocUnsafe(n),c=0;for(b=0;b<g.length;++b){var f=g[b];if(!a.isBuffer(f))throw new TypeError('"list" argument must be an Array of Buffers');f.copy(e,c);c+=f.length}return e};a.byteLength=e;a.prototype._isBuffer=!0;a.prototype.swap16=function(){var g=this.length;if(0!=g%2)throw new RangeError("Buffer size must be a multiple of 16-bits");for(var a=0;a<g;a+=2)r(this,a,a+1);return this};a.prototype.swap32=
function(){var g=this.length;if(0!=g%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var a=0;a<g;a+=4)r(this,a,a+3),r(this,a+1,a+2);return this};a.prototype.swap64=function(){var a=this.length;if(0!=a%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var b=0;b<a;b+=8)r(this,b,b+7),r(this,b+1,b+6),r(this,b+2,b+5),r(this,b+3,b+4);return this};a.prototype.toString=function(){var a=this.length;return 0===a?"":0===arguments.length?u(this,0,a):function(a,g,
b){var n=!1;if(((void 0===g||0>g)&&(g=0),g>this.length)||((void 0===b||b>this.length)&&(b=this.length),0>=b)||(b>>>=0)<=(g>>>=0))return"";for(a||(a="utf8");;)switch(a){case "hex":a=g;g=b;b=this.length;(!a||0>a)&&(a=0);(!g||0>g||g>b)&&(g=b);n="";for(b=a;b<g;++b)a=n,n=this[b],n=16>n?"0"+n.toString(16):n.toString(16),n=a+n;return n;case "utf8":case "utf-8":return u(this,g,b);case "ascii":a="";for(b=Math.min(this.length,b);g<b;++g)a+=String.fromCharCode(127&this[g]);return a;case "latin1":case "binary":a=
"";for(b=Math.min(this.length,b);g<b;++g)a+=String.fromCharCode(this[g]);return a;case "base64":return 0===g&&b===this.length?F.fromByteArray(this):F.fromByteArray(this.slice(g,b));case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":g=this.slice(g,b);b="";for(a=0;a<g.length;a+=2)b+=String.fromCharCode(g[a]+256*g[a+1]);return b;default:if(n)throw new TypeError("Unknown encoding: "+a);a=(a+"").toLowerCase();n=!0}}.apply(this,arguments)};a.prototype.equals=function(g){if(!a.isBuffer(g))throw new TypeError("Argument must be a Buffer");
return this===g||0===a.compare(this,g)};a.prototype.inspect=function(){var a="",b=k.INSPECT_MAX_BYTES;return 0<this.length&&(a=this.toString("hex",0,b).match(/.{2}/g).join(" "),this.length>b&&(a+=" ... ")),"<Buffer "+a+">"};a.prototype.compare=function(g,b,e,c,f){if(!a.isBuffer(g))throw new TypeError("Argument must be a Buffer");if(void 0===b&&(b=0),void 0===e&&(e=g?g.length:0),void 0===c&&(c=0),void 0===f&&(f=this.length),0>b||e>g.length||0>c||f>this.length)throw new RangeError("out of range index");
if(c>=f&&b>=e)return 0;if(c>=f)return-1;if(b>=e)return 1;if(this===g)return 0;var n=(f>>>=0)-(c>>>=0),A=(e>>>=0)-(b>>>=0),q=Math.min(n,A);c=this.slice(c,f);g=g.slice(b,e);for(b=0;b<q;++b)if(c[b]!==g[b]){n=c[b];A=g[b];break}return n<A?-1:A<n?1:0};a.prototype.includes=function(a,b,e){return-1!==this.indexOf(a,b,e)};a.prototype.indexOf=function(a,b,e){return w(this,a,b,e,!0)};a.prototype.lastIndexOf=function(a,b,e){return w(this,a,b,e,!1)};a.prototype.write=function(a,e,c,f){if(void 0===e)f="utf8",c=
this.length,e=0;else if(void 0===c&&"string"==typeof e)f=e,c=this.length,e=0;else{if(!isFinite(e))throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");e>>>=0;isFinite(c)?(c>>>=0,void 0===f&&(f="utf8")):(f=c,c=void 0)}var g=this.length-e;if((void 0===c||c>g)&&(c=g),0<a.length&&(0>c||0>e)||e>this.length)throw new RangeError("Attempt to write outside buffer bounds");f||(f="utf8");for(g=!1;;)switch(f){case "hex":a:{e=Number(e)||0;f=this.length-e;c?(c=Number(c))>f&&(c=
f):c=f;f=a.length;if(0!=f%2)throw new TypeError("Invalid hex string");c>f/2&&(c=f/2);for(f=0;f<c;++f){g=parseInt(a.substr(2*f,2),16);if(g!=g){c=f;break a}this[e+f]=g}c=f}return c;case "utf8":case "utf-8":return D(B(a,this.length-e),this,e,c);case "ascii":return b(this,a,e,c);case "latin1":case "binary":return b(this,a,e,c);case "base64":return D(I(a),this,e,c);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":f=c;g=this.length-e;for(var n=[],h=0;h<a.length&&!(0>(g-=2));++h){var q=a.charCodeAt(h);
c=q>>8;q%=256;n.push(q);n.push(c)}return D(n,this,e,f);default:if(g)throw new TypeError("Unknown encoding: "+f);f=(""+f).toLowerCase();g=!0}};a.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var K=4096;a.prototype.slice=function(g,b){var e=this.length;0>(g=~~g)?0>(g+=e)&&(g=0):g>e&&(g=e);0>(b=void 0===b?e:~~b)?0>(b+=e)&&(b=0):b>e&&(b=e);b<g&&(b=g);e=this.subarray(g,b);return e.__proto__=a.prototype,e};a.prototype.readUIntLE=function(a,b,e){a>>>=
0;b>>>=0;e||y(a,b,this.length);e=this[a];for(var g=1,c=0;++c<b&&(g*=256);)e+=this[a+c]*g;return e};a.prototype.readUIntBE=function(a,b,e){a>>>=0;b>>>=0;e||y(a,b,this.length);e=this[a+--b];for(var g=1;0<b&&(g*=256);)e+=this[a+--b]*g;return e};a.prototype.readUInt8=function(a,b){return a>>>=0,b||y(a,1,this.length),this[a]};a.prototype.readUInt16LE=function(a,b){return a>>>=0,b||y(a,2,this.length),this[a]|this[a+1]<<8};a.prototype.readUInt16BE=function(a,b){return a>>>=0,b||y(a,2,this.length),this[a]<<
8|this[a+1]};a.prototype.readUInt32LE=function(a,b){return a>>>=0,b||y(a,4,this.length),(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*this[a+3]};a.prototype.readUInt32BE=function(a,b){return a>>>=0,b||y(a,4,this.length),16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};a.prototype.readIntLE=function(a,b,e){a>>>=0;b>>>=0;e||y(a,b,this.length);e=this[a];for(var g=1,c=0;++c<b&&(g*=256);)e+=this[a+c]*g;return e>=128*g&&(e-=Math.pow(2,8*b)),e};a.prototype.readIntBE=function(a,b,e){a>>>=0;b>>>=0;
e||y(a,b,this.length);e=b;for(var g=1,c=this[a+--e];0<e&&(g*=256);)c+=this[a+--e]*g;return c>=128*g&&(c-=Math.pow(2,8*b)),c};a.prototype.readInt8=function(a,b){return a>>>=0,b||y(a,1,this.length),128&this[a]?-1*(255-this[a]+1):this[a]};a.prototype.readInt16LE=function(a,b){a>>>=0;b||y(a,2,this.length);var g=this[a]|this[a+1]<<8;return 32768&g?4294901760|g:g};a.prototype.readInt16BE=function(a,b){a>>>=0;b||y(a,2,this.length);var g=this[a+1]|this[a]<<8;return 32768&g?4294901760|g:g};a.prototype.readInt32LE=
function(a,b){return a>>>=0,b||y(a,4,this.length),this[a]|this[a+1]<<8|this[a+2]<<16|this[a+3]<<24};a.prototype.readInt32BE=function(a,b){return a>>>=0,b||y(a,4,this.length),this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};a.prototype.readFloatLE=function(a,b){return a>>>=0,b||y(a,4,this.length),E.read(this,a,!0,23,4)};a.prototype.readFloatBE=function(a,b){return a>>>=0,b||y(a,4,this.length),E.read(this,a,!1,23,4)};a.prototype.readDoubleLE=function(a,b){return a>>>=0,b||y(a,8,this.length),E.read(this,
a,!0,52,8)};a.prototype.readDoubleBE=function(a,b){return a>>>=0,b||y(a,8,this.length),E.read(this,a,!1,52,8)};a.prototype.writeUIntLE=function(a,b,e,c){(a=+a,b>>>=0,e>>>=0,c)||z(this,a,b,e,Math.pow(2,8*e)-1,0);c=1;var g=0;for(this[b]=255&a;++g<e&&(c*=256);)this[b+g]=a/c&255;return b+e};a.prototype.writeUIntBE=function(a,b,e,c){(a=+a,b>>>=0,e>>>=0,c)||z(this,a,b,e,Math.pow(2,8*e)-1,0);c=e-1;var g=1;for(this[b+c]=255&a;0<=--c&&(g*=256);)this[b+c]=a/g&255;return b+e};a.prototype.writeUInt8=function(a,
b,e){return a=+a,b>>>=0,e||z(this,a,b,1,255,0),this[b]=255&a,b+1};a.prototype.writeUInt16LE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,2,65535,0),this[b]=255&a,this[b+1]=a>>>8,b+2};a.prototype.writeUInt16BE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,2,65535,0),this[b]=a>>>8,this[b+1]=255&a,b+2};a.prototype.writeUInt32LE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,4,4294967295,0),this[b+3]=a>>>24,this[b+2]=a>>>16,this[b+1]=a>>>8,this[b]=255&a,b+4};a.prototype.writeUInt32BE=function(a,
b,e){return a=+a,b>>>=0,e||z(this,a,b,4,4294967295,0),this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=255&a,b+4};a.prototype.writeIntLE=function(a,b,e,c){(a=+a,b>>>=0,c)||(c=Math.pow(2,8*e-1),z(this,a,b,e,c-1,-c));c=0;var g=1,f=0;for(this[b]=255&a;++c<e&&(g*=256);)0>a&&0===f&&0!==this[b+c-1]&&(f=1),this[b+c]=(a/g>>0)-f&255;return b+e};a.prototype.writeIntBE=function(a,b,e,c){(a=+a,b>>>=0,c)||(c=Math.pow(2,8*e-1),z(this,a,b,e,c-1,-c));c=e-1;var g=1,f=0;for(this[b+c]=255&a;0<=--c&&(g*=256);)0>
a&&0===f&&0!==this[b+c+1]&&(f=1),this[b+c]=(a/g>>0)-f&255;return b+e};a.prototype.writeInt8=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,1,127,-128),0>a&&(a=255+a+1),this[b]=255&a,b+1};a.prototype.writeInt16LE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,2,32767,-32768),this[b]=255&a,this[b+1]=a>>>8,b+2};a.prototype.writeInt16BE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,2,32767,-32768),this[b]=a>>>8,this[b+1]=255&a,b+2};a.prototype.writeInt32LE=function(a,b,e){return a=+a,b>>>=0,e||
z(this,a,b,4,2147483647,-2147483648),this[b]=255&a,this[b+1]=a>>>8,this[b+2]=a>>>16,this[b+3]=a>>>24,b+4};a.prototype.writeInt32BE=function(a,b,e){return a=+a,b>>>=0,e||z(this,a,b,4,2147483647,-2147483648),0>a&&(a=4294967295+a+1),this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=255&a,b+4};a.prototype.writeFloatLE=function(a,b,e){return J(this,a,b,!0,e)};a.prototype.writeFloatBE=function(a,b,e){return J(this,a,b,!1,e)};a.prototype.writeDoubleLE=function(a,b,e){return H(this,a,b,!0,e)};a.prototype.writeDoubleBE=
function(a,b,e){return H(this,a,b,!1,e)};a.prototype.copy=function(a,b,e,c){if((e||(e=0),c||0===c||(c=this.length),b>=a.length&&(b=a.length),b||(b=0),0<c&&c<e&&(c=e),c===e)||0===a.length||0===this.length)return 0;if(0>b)throw new RangeError("targetStart out of bounds");if(0>e||e>=this.length)throw new RangeError("sourceStart out of bounds");if(0>c)throw new RangeError("sourceEnd out of bounds");c>this.length&&(c=this.length);a.length-b<c-e&&(c=a.length-b+e);var g=c-e;if(this===a&&e<b&&b<c)for(c=g-
1;0<=c;--c)a[c+b]=this[c+e];else if(1E3>g)for(c=0;c<g;++c)a[c+b]=this[c+e];else Uint8Array.prototype.set.call(a,this.subarray(e,e+g),b);return g};a.prototype.fill=function(b,e,c,f){if("string"==typeof b){if("string"==typeof e?(f=e,e=0,c=this.length):"string"==typeof c&&(f=c,c=this.length),1===b.length){var g=b.charCodeAt(0);256>g&&(b=g)}if(void 0!==f&&"string"!=typeof f)throw new TypeError("encoding must be a string");if("string"==typeof f&&!a.isEncoding(f))throw new TypeError("Unknown encoding: "+
f);}else"number"==typeof b&&(b&=255);if(0>e||this.length<e||this.length<c)throw new RangeError("Out of range index");if(c<=e)return this;if(e>>>=0,c=void 0===c?this.length:c>>>0,b||(b=0),"number"==typeof b)for(f=e;f<c;++f)this[f]=b;else for(b=a.isBuffer(b)?b:new a(b,f),g=b.length,f=0;f<c-e;++f)this[f+e]=b[f%g];return this};var L=/[^+\/0-9A-Za-z-_]/g},{"base64-js":1,ieee754:9}],4:[function(d,m,k){(function(d){k.isArray=function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)};
k.isBoolean=function(a){return"boolean"==typeof a};k.isNull=function(a){return null===a};k.isNullOrUndefined=function(a){return null==a};k.isNumber=function(a){return"number"==typeof a};k.isString=function(a){return"string"==typeof a};k.isSymbol=function(a){return"symbol"==typeof a};k.isUndefined=function(a){return void 0===a};k.isRegExp=function(a){return"[object RegExp]"===Object.prototype.toString.call(a)};k.isObject=function(a){return"object"==typeof a&&null!==a};k.isDate=function(a){return"[object Date]"===
Object.prototype.toString.call(a)};k.isError=function(a){return"[object Error]"===Object.prototype.toString.call(a)||a instanceof Error};k.isFunction=function(a){return"function"==typeof a};k.isPrimitive=function(a){return null===a||"boolean"==typeof a||"number"==typeof a||"string"==typeof a||"symbol"==typeof a||void 0===a};k.isBuffer=d.isBuffer}).call(this,{isBuffer:d("../../is-buffer/index.js")})},{"../../is-buffer/index.js":11}],5:[function(d,m,k){k.UINT32=d("./lib/uint32");k.UINT64=d("./lib/uint64")},
{"./lib/uint32":6,"./lib/uint64":7}],6:[function(d,m,k){!function(d){function a(c,d){return this instanceof a?(this._low=0,this._high=0,this.remainder=null,void 0===d?h.call(this,c):"string"==typeof c?f.call(this,c,d):void p.call(this,c,d)):new a(c,d)}function p(a,f){return this._low=0|a,this._high=0|f,this}function h(a){return this._low=65535&a,this._high=a>>>16,this}function f(a,f){var e=parseInt(a,f||10);return this._low=65535&e,this._high=e>>>16,this}a(Math.pow(36,5));a(Math.pow(16,7));a(Math.pow(10,
9));a(Math.pow(2,30));a(36);a(16);a(10);a(2);a.prototype.fromBits=p;a.prototype.fromNumber=h;a.prototype.fromString=f;a.prototype.toNumber=function(){return 65536*this._high+this._low};a.prototype.toString=function(a){return this.toNumber().toString(a||10)};a.prototype.add=function(a){var c=this._low+a._low,e=c>>>16;return e+=this._high+a._high,this._low=65535&c,this._high=65535&e,this};a.prototype.subtract=function(a){return this.add(a.clone().negate())};a.prototype.multiply=function(a){var c,e,
f=this._high,d=this._low,h=a._high;a=a._low;return c=(e=d*a)>>>16,c+=f*a,c&=65535,c+=d*h,this._low=65535&e,this._high=65535&c,this};a.prototype.div=function(c){if(0==c._low&&0==c._high)throw Error("division by zero");if(0==c._high&&1==c._low)return this.remainder=new a(0),this;if(c.gt(this))return this.remainder=this.clone(),this._low=0,this._high=0,this;if(this.eq(c))return this.remainder=new a(0),this._low=1,this._high=0,this;c=c.clone();for(var f=-1;!this.lt(c);)c.shiftLeft(1,!0),f++;this.remainder=
this.clone();for(this._high=this._low=0;0<=f;f--)c.shiftRight(1),this.remainder.lt(c)||(this.remainder.subtract(c),16<=f?this._high|=1<<f-16:this._low|=1<<f);return this};a.prototype.negate=function(){var a=1+(65535&~this._low);return this._low=65535&a,this._high=~this._high+(a>>>16)&65535,this};a.prototype.equals=a.prototype.eq=function(a){return this._low==a._low&&this._high==a._high};a.prototype.greaterThan=a.prototype.gt=function(a){return this._high>a._high||!(this._high<a._high)&&this._low>
a._low};a.prototype.lessThan=a.prototype.lt=function(a){return this._high<a._high||!(this._high>a._high)&&this._low<a._low};a.prototype.or=function(a){return this._low|=a._low,this._high|=a._high,this};a.prototype.and=function(a){return this._low&=a._low,this._high&=a._high,this};a.prototype.not=function(){return this._low=65535&~this._low,this._high=65535&~this._high,this};a.prototype.xor=function(a){return this._low^=a._low,this._high^=a._high,this};a.prototype.shiftRight=a.prototype.shiftr=function(a){return 16<
a?(this._low=this._high>>a-16,this._high=0):16==a?(this._low=this._high,this._high=0):(this._low=this._low>>a|this._high<<16-a&65535,this._high>>=a),this};a.prototype.shiftLeft=a.prototype.shiftl=function(a,f){return 16<a?(this._high=this._low<<a-16,this._low=0,f||(this._high&=65535)):16==a?(this._high=this._low,this._low=0):(this._high=this._high<<a|this._low>>16-a,this._low=this._low<<a&65535,f||(this._high&=65535)),this};a.prototype.rotateLeft=a.prototype.rotl=function(a){var c=this._high<<16|
this._low;return c=c<<a|c>>>32-a,this._low=65535&c,this._high=c>>>16,this};a.prototype.rotateRight=a.prototype.rotr=function(a){var c=this._high<<16|this._low;return c=c>>>a|c<<32-a,this._low=65535&c,this._high=c>>>16,this};a.prototype.clone=function(){return new a(this._low,this._high)};"undefined"!=typeof define&&define.amd?define([],function(){return a}):void 0!==m&&m.exports?m.exports=a:d.UINT32=a}(this)},{}],7:[function(d,m,k){!function(d){function a(e,c,d,v){return this instanceof a?(this.remainder=
null,"string"==typeof e?f.call(this,e,c):void 0===c?h.call(this,e):void p.apply(this,arguments)):new a(e,c,d,v)}function p(a,c,f,d){return void 0===f?(this._a00=65535&a,this._a16=a>>>16,this._a32=65535&c,this._a48=c>>>16,this):(this._a00=0|a,this._a16=0|c,this._a32=0|f,this._a48=0|d,this)}function h(a){return this._a00=65535&a,this._a16=a>>>16,this._a32=0,this._a48=0,this}function f(e,f){f=f||10;this._a48=this._a32=this._a16=this._a00=0;for(var d=c[f]||new a(Math.pow(f,5)),h=0,b=e.length;h<b;h+=5){var p=
Math.min(5,b-h),x=parseInt(e.slice(h,h+p),f);this.multiply(5>p?new a(Math.pow(f,p)):d).add(new a(x))}return this}var c={16:a(Math.pow(16,5)),10:a(Math.pow(10,5)),2:a(Math.pow(2,5))},x={16:a(16),10:a(10),2:a(2)};a.prototype.fromBits=p;a.prototype.fromNumber=h;a.prototype.fromString=f;a.prototype.toNumber=function(){return 65536*this._a16+this._a00};a.prototype.toString=function(e){var c=x[e=e||10]||new a(e);if(!this.gt(c))return this.toNumber().toString(e);for(var f=this.clone(),d=Array(64),b=63;0<=
b&&(f.div(c),d[b]=f.remainder.toNumber().toString(e),f.gt(c));b--);return d[b-1]=f.toNumber().toString(e),d.join("")};a.prototype.add=function(a){var e=this._a00+a._a00,c=e>>>16,f=(c+=this._a16+a._a16)>>>16,b=(f+=this._a32+a._a32)>>>16;return b+=this._a48+a._a48,this._a00=65535&e,this._a16=65535&c,this._a32=65535&f,this._a48=65535&b,this};a.prototype.subtract=function(a){return this.add(a.clone().negate())};a.prototype.multiply=function(a){var e=this._a00,c=this._a16,f=this._a32,b=this._a48,d=a._a00,
h=a._a16,p=a._a32,x=e*d,k=x>>>16,l=(k+=e*h)>>>16;k&=65535;l+=(k+=c*d)>>>16;var m=(l+=e*p)>>>16;return l&=65535,m+=(l+=c*h)>>>16,l&=65535,m+=(l+=f*d)>>>16,m+=e*a._a48,m&=65535,m+=c*p,m&=65535,m+=f*h,m&=65535,m+=b*d,this._a00=65535&x,this._a16=65535&k,this._a32=65535&l,this._a48=65535&m,this};a.prototype.div=function(e){if(0==e._a16&&0==e._a32&&0==e._a48){if(0==e._a00)throw Error("division by zero");if(1==e._a00)return this.remainder=new a(0),this}if(e.gt(this))return this.remainder=this.clone(),this._a00=
0,this._a16=0,this._a32=0,this._a48=0,this;if(this.eq(e))return this.remainder=new a(0),this._a00=1,this._a16=0,this._a32=0,this._a48=0,this;e=e.clone();for(var c=-1;!this.lt(e);)e.shiftLeft(1,!0),c++;this.remainder=this.clone();for(this._a48=this._a32=this._a16=this._a00=0;0<=c;c--)e.shiftRight(1),this.remainder.lt(e)||(this.remainder.subtract(e),48<=c?this._a48|=1<<c-48:32<=c?this._a32|=1<<c-32:16<=c?this._a16|=1<<c-16:this._a00|=1<<c);return this};a.prototype.negate=function(){var a=1+(65535&~this._a00);
return this._a00=65535&a,a=(65535&~this._a16)+(a>>>16),this._a16=65535&a,a=(65535&~this._a32)+(a>>>16),this._a32=65535&a,this._a48=~this._a48+(a>>>16)&65535,this};a.prototype.equals=a.prototype.eq=function(a){return this._a48==a._a48&&this._a00==a._a00&&this._a32==a._a32&&this._a16==a._a16};a.prototype.greaterThan=a.prototype.gt=function(a){return this._a48>a._a48||!(this._a48<a._a48)&&(this._a32>a._a32||!(this._a32<a._a32)&&(this._a16>a._a16||!(this._a16<a._a16)&&this._a00>a._a00))};a.prototype.lessThan=
a.prototype.lt=function(a){return this._a48<a._a48||!(this._a48>a._a48)&&(this._a32<a._a32||!(this._a32>a._a32)&&(this._a16<a._a16||!(this._a16>a._a16)&&this._a00<a._a00))};a.prototype.or=function(a){return this._a00|=a._a00,this._a16|=a._a16,this._a32|=a._a32,this._a48|=a._a48,this};a.prototype.and=function(a){return this._a00&=a._a00,this._a16&=a._a16,this._a32&=a._a32,this._a48&=a._a48,this};a.prototype.xor=function(a){return this._a00^=a._a00,this._a16^=a._a16,this._a32^=a._a32,this._a48^=a._a48,
this};a.prototype.not=function(){return this._a00=65535&~this._a00,this._a16=65535&~this._a16,this._a32=65535&~this._a32,this._a48=65535&~this._a48,this};a.prototype.shiftRight=a.prototype.shiftr=function(a){return 48<=(a%=64)?(this._a00=this._a48>>a-48,this._a16=0,this._a32=0,this._a48=0):32<=a?(a-=32,this._a00=65535&(this._a32>>a|this._a48<<16-a),this._a16=this._a48>>a&65535,this._a32=0,this._a48=0):16<=a?(a-=16,this._a00=65535&(this._a16>>a|this._a32<<16-a),this._a16=65535&(this._a32>>a|this._a48<<
16-a),this._a32=this._a48>>a&65535,this._a48=0):(this._a00=65535&(this._a00>>a|this._a16<<16-a),this._a16=65535&(this._a16>>a|this._a32<<16-a),this._a32=65535&(this._a32>>a|this._a48<<16-a),this._a48=this._a48>>a&65535),this};a.prototype.shiftLeft=a.prototype.shiftl=function(a,c){return 48<=(a%=64)?(this._a48=this._a00<<a-48,this._a32=0,this._a16=0,this._a00=0):32<=a?(a-=32,this._a48=this._a16<<a|this._a00>>16-a,this._a32=this._a00<<a&65535,this._a16=0,this._a00=0):16<=a?(a-=16,this._a48=this._a32<<
a|this._a16>>16-a,this._a32=65535&(this._a16<<a|this._a00>>16-a),this._a16=this._a00<<a&65535,this._a00=0):(this._a48=this._a48<<a|this._a32>>16-a,this._a32=65535&(this._a32<<a|this._a16>>16-a),this._a16=65535&(this._a16<<a|this._a00>>16-a),this._a00=this._a00<<a&65535),c||(this._a48&=65535),this};a.prototype.rotateLeft=a.prototype.rotl=function(a){if(0==(a%=64))return this;if(32<=a){var c=this._a00;if(this._a00=this._a32,this._a32=c,c=this._a48,this._a48=this._a16,this._a16=c,32==a)return this;a-=
32}var e=this._a48<<16|this._a32,f=this._a16<<16|this._a00;c=e<<a|f>>>32-a;a=f<<a|e>>>32-a;return this._a00=65535&a,this._a16=a>>>16,this._a32=65535&c,this._a48=c>>>16,this};a.prototype.rotateRight=a.prototype.rotr=function(a){if(0==(a%=64))return this;if(32<=a){var c=this._a00;if(this._a00=this._a32,this._a32=c,c=this._a48,this._a48=this._a16,this._a16=c,32==a)return this;a-=32}var e=this._a48<<16|this._a32,f=this._a16<<16|this._a00;c=e>>>a|f<<32-a;a=f>>>a|e<<32-a;return this._a00=65535&a,this._a16=
a>>>16,this._a32=65535&c,this._a48=c>>>16,this};a.prototype.clone=function(){return new a(this._a00,this._a16,this._a32,this._a48)};"undefined"!=typeof define&&define.amd?define([],function(){return a}):void 0!==m&&m.exports?m.exports=a:d.UINT64=a}(this)},{}],8:[function(d,m,k){function l(){this._events=this._events||{};this._maxListeners=this._maxListeners||void 0}function a(a){return"function"==typeof a}function p(a){return"object"==typeof a&&null!==a}m.exports=l;l.EventEmitter=l;l.prototype._events=
void 0;l.prototype._maxListeners=void 0;l.defaultMaxListeners=10;l.prototype.setMaxListeners=function(a){if("number"!=typeof a||0>a||isNaN(a))throw TypeError("n must be a positive number");return this._maxListeners=a,this};l.prototype.emit=function(d){var f,c,h;if(this._events||(this._events={}),"error"===d&&(!this._events.error||p(this._events.error)&&!this._events.error.length)){if((f=arguments[1])instanceof Error)throw f;var e=Error('Uncaught, unspecified "error" event. ('+f+")");throw e.context=
f,e;}if(void 0===(e=this._events[d]))return!1;if(a(e))switch(arguments.length){case 1:e.call(this);break;case 2:e.call(this,arguments[1]);break;case 3:e.call(this,arguments[1],arguments[2]);break;default:f=Array.prototype.slice.call(arguments,1),e.apply(this,f)}else if(p(e))for(f=Array.prototype.slice.call(arguments,1),e=(h=e.slice()).length,c=0;c<e;c++)h[c].apply(this,f);return!0};l.prototype.addListener=function(d,f){var c;if(!a(f))throw TypeError("listener must be a function");return this._events||
(this._events={}),this._events.newListener&&this.emit("newListener",d,a(f.listener)?f.listener:f),this._events[d]?p(this._events[d])?this._events[d].push(f):this._events[d]=[this._events[d],f]:this._events[d]=f,p(this._events[d])&&!this._events[d].warned&&(c=void 0===this._maxListeners?l.defaultMaxListeners:this._maxListeners)&&0<c&&this._events[d].length>c&&(this._events[d].warned=!0,console.error("(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.",
this._events[d].length),"function"==typeof console.trace&&console.trace()),this};l.prototype.on=l.prototype.addListener;l.prototype.once=function(d,f){function c(){this.removeListener(d,c);h||(h=!0,f.apply(this,arguments))}if(!a(f))throw TypeError("listener must be a function");var h=!1;return c.listener=f,this.on(d,c),this};l.prototype.removeListener=function(d,f){var c,h,e;if(!a(f))throw TypeError("listener must be a function");if(!this._events||!this._events[d])return this;if(e=(c=this._events[d]).length,
h=-1,c===f||a(c.listener)&&c.listener===f)delete this._events[d],this._events.removeListener&&this.emit("removeListener",d,f);else if(p(c)){for(;0<e--;)if(c[e]===f||c[e].listener&&c[e].listener===f){h=e;break}if(0>h)return this;1===c.length?(c.length=0,delete this._events[d]):c.splice(h,1);this._events.removeListener&&this.emit("removeListener",d,f)}return this};l.prototype.removeAllListeners=function(d){var f;if(!this._events)return this;if(!this._events.removeListener)return 0===arguments.length?
this._events={}:this._events[d]&&delete this._events[d],this;if(0===arguments.length){for(f in this._events)"removeListener"!==f&&this.removeAllListeners(f);return this.removeAllListeners("removeListener"),this._events={},this}if(a(f=this._events[d]))this.removeListener(d,f);else if(f)for(;f.length;)this.removeListener(d,f[f.length-1]);return delete this._events[d],this};l.prototype.listeners=function(d){return this._events&&this._events[d]?a(this._events[d])?[this._events[d]]:this._events[d].slice():
[]};l.prototype.listenerCount=function(d){if(this._events){d=this._events[d];if(a(d))return 1;if(d)return d.length}return 0};l.listenerCount=function(a,f){return a.listenerCount(f)}},{}],9:[function(d,m,k){k.read=function(d,a,p,h,f){var c=8*f-h-1;var k=(1<<c)-1,e=k>>1,l=-7;f=p?f-1:0;var m=p?-1:1,v=d[a+f];f+=m;p=v&(1<<-l)-1;v>>=-l;for(l+=c;0<l;p=256*p+d[a+f],f+=m,l-=8);c=p&(1<<-l)-1;p>>=-l;for(l+=h;0<l;c=256*c+d[a+f],f+=m,l-=8);if(0===p)p=1-e;else{if(p===k)return c?NaN:1/0*(v?-1:1);c+=Math.pow(2,h);
p-=e}return(v?-1:1)*c*Math.pow(2,p-h)};k.write=function(d,a,p,h,f,c){var l,e,k,m=8*c-f-1,v=(1<<m)-1,b=v>>1,u=23===f?Math.pow(2,-24)-Math.pow(2,-77):0;c=h?0:c-1;h=h?1:-1;var y=0>a||0===a&&0>1/a?1:0;a=Math.abs(a);for(isNaN(a)||a===1/0?(e=isNaN(a)?1:0,l=v):(l=Math.floor(Math.log(a)/Math.LN2),1>a*(k=Math.pow(2,-l))&&(l--,k*=2),2<=(a+=1<=l+b?u/k:u*Math.pow(2,1-b))*k&&(l++,k/=2),l+b>=v?(e=0,l=v):1<=l+b?(e=(a*k-1)*Math.pow(2,f),l+=b):(e=a*Math.pow(2,b-1)*Math.pow(2,f),l=0));8<=f;d[p+c]=255&e,c+=h,e/=256,
f-=8);l=l<<f|e;for(m+=f;0<m;d[p+c]=255&l,c+=h,l/=256,m-=8);d[p+c-h]|=128*y}},{}],10:[function(d,m,k){"function"==typeof Object.create?m.exports=function(d,a){d.super_=a;d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}})}:m.exports=function(d,a){d.super_=a;var p=function(){};p.prototype=a.prototype;d.prototype=new p;d.prototype.constructor=d}},{}],11:[function(d,m,k){function l(a){return!!a.constructor&&"function"==typeof a.constructor.isBuffer&&
a.constructor.isBuffer(a)}m.exports=function(a){return null!=a&&(l(a)||"function"==typeof a.readFloatLE&&"function"==typeof a.slice&&l(a.slice(0,0))||!!a._isBuffer)}},{}],12:[function(d,m,k){var l={}.toString;m.exports=Array.isArray||function(a){return"[object Array]"==l.call(a)}},{}],13:[function(d,m,k){function l(a,d,h,f,c,l){var e=c;l-=c;c=0;if(2113929216<=a.length)throw Error("input too large");if(12<a.length){var p=k.compressBound(a.length);if(l<p)throw Error("output too small: "+l+" < "+p);
l=67;for(p=a.length-12;h+4<p;){var m=a[h+1]<<8|a[h],v=a[h+3]<<8|a[h+2],b=Math.imul(m|v<<16,2654435761)>>>16,u=f[b]-1;if(f[b]=h+1,0>u||0<h-u>>>16||(a[u+3]<<8|a[u+2])!=v||(a[u+1]<<8|a[u])!=m)h+=l++>>6;else{l=67;m=h-c;v=h-u;u+=4;for(b=h+=4;h<p&&a[h]==a[u];)h++,u++;u=15>(b=h-b)?b:15;if(15<=m){d[e++]=240+u;for(u=m-15;254<u;u-=255)d[e++]=255;d[e++]=u}else d[e++]=(m<<4)+u;for(u=0;u<m;u++)d[e++]=a[c+u];if(d[e++]=v,d[e++]=v>>8,15<=b){for(b-=15;255<=b;)b-=255,d[e++]=255;d[e++]=b}c=h}}}if(0==c)return 0;if(15<=
(m=a.length-c)){d[e++]=240;for(h=m-15;254<h;h-=255)d[e++]=255;d[e++]=h}else d[e++]=m<<4;for(h=c;h<a.length;)d[e++]=a[h++];return e}d("cuint").UINT32;Math.imul||(Math.imul=function(a,d){var h=65535&a,f=65535&d;return h*f+((a>>>16)*f+h*(d>>>16)<<16)|0});k.uncompress=function(a,d,h,f){var c=h=h||0;h=f||a.length-h;for(f=0;c<h;){var p=a[c++],e=p>>4;if(0<e){for(var l=e+240;255===l;)e+=l=a[c++];for(l=c+e;c<l;)d[f++]=a[c++];if(c===h)break}e=a[c++]|a[c++]<<8;if(0===e||e>f)return-(c-2);p&=15;for(l=p+240;255===
l;)p+=l=a[c++];e=f-e;for(l=f+p+4;f<l;)d[f++]=d[e++]}return f};k.compressBound=function(a){return 2113929216<a?0:a+a/255+16|0};k.compress=function(a,d,h,f){for(var c=Array(65536),p=0;65536>p;p++)c[p]=0;return l(a,d,0,c,h||0,f||d.length)};k.compressHC=k.compress;k.compressDependent=l},{cuint:5}],14:[function(d,m,k){(function(l){var a=d("./decoder_stream");k.LZ4_uncompress=function(d,h){var f=[],c=new a(h);return c.on("data",function(a){f.push(a)}),c.end(d),l.concat(f)}}).call(this,d("buffer").Buffer)},
{"./decoder_stream":15,buffer:3}],15:[function(d,m,k){(function(l){function a(c){if(!(this instanceof a))return new a(c);p.call(this,c);this.options=c||{};this.binding=this.options.useJS?e:k;this.buffer=null;this.pos=0;this.descriptor=null;this.state=r.MAGIC;this.notEnoughData=!1;this.descriptorStart=0;this.currentStreamChecksum=this.dictId=this.streamSize=null;this.skippableSize=this.dataBlockSize=0}var p=d("stream").Transform,h=d("util").inherits,f=d("./static"),c=f.utils,k=c.bindings,e=d("./binding"),
r=f.STATES,w=f.SIZES;h(a,p);a.prototype._transform=function(a,b,c){if(0<this.skippableSize){if(this.skippableSize-=a.length,0<this.skippableSize)return void c();a=a.slice(-this.skippableSize);this.skippableSize=0;this.state=r.MAGIC}this.buffer=this.buffer?l.concat([this.buffer,a],this.buffer.length+a.length):a;this._main(c)};a.prototype.emit_Error=function(a){this.emit("error",Error(a+" @"+this.pos))};a.prototype.check_Size=function(a){var b=this.buffer.length-this.pos;return 0>=b||b<a?(this.notEnoughData&&
this.emit_Error("Unexpected end of LZ4 stream"),!0):(this.pos+=a,!1)};a.prototype.read_MagicNumber=function(){var a=this.pos;if(this.check_Size(w.MAGIC))return!0;var b=c.readInt32LE(this.buffer,a);if((4294967280&b)!==f.MAGICNUMBER_SKIPPABLE)return b!==f.MAGICNUMBER?(this.pos=a,this.emit_Error("Invalid magic number: "+b.toString(16).toUpperCase()),!0):void(this.state=r.DESCRIPTOR);this.state=r.SKIP_SIZE};a.prototype.read_SkippableSize=function(){var a=this.pos;if(this.check_Size(w.SKIP_SIZE))return!0;
this.state=r.SKIP_DATA;this.skippableSize=c.readInt32LE(this.buffer,a)};a.prototype.read_Descriptor=function(){var a=this.pos;if(this.check_Size(w.DESCRIPTOR))return!0;this.descriptorStart=a;var b=this.buffer[a],c=b>>6;if(c!==f.VERSION)return this.pos=a,this.emit_Error("Invalid version: "+c+" != "+f.VERSION),!0;if(b>>1&1)return this.pos=a,this.emit_Error("Reserved bit set"),!0;c=this.buffer[a+1]>>4&7;var e=f.blockMaxSizes[c];if(null===e)return this.pos=a,this.emit_Error("Invalid block max size: "+
c),!0;this.descriptor={blockIndependence:!!(b>>5&1),blockChecksum:!!(b>>4&1),blockMaxSize:e,streamSize:!!(b>>3&1),streamChecksum:!!(b>>2&1),dict:!!(1&b),dictId:0};this.state=r.SIZE};a.prototype.read_Size=function(){if(this.descriptor.streamSize){var a=this.pos;if(this.check_Size(w.SIZE))return!0;this.streamSize=this.buffer.slice(a,a+8)}this.state=r.DICTID};a.prototype.read_DictId=function(){if(this.descriptor.dictId){var a=this.pos;if(this.check_Size(w.DICTID))return!0;this.dictId=c.readInt32LE(this.buffer,
a)}this.state=r.DESCRIPTOR_CHECKSUM};a.prototype.read_DescriptorChecksum=function(){var a=this.pos;if(this.check_Size(w.DESCRIPTOR_CHECKSUM))return!0;var b=this.buffer[a];if(c.descriptorChecksum(this.buffer.slice(this.descriptorStart,a))!==b)return this.pos=a,this.emit_Error("Invalid stream descriptor checksum"),!0;this.state=r.DATABLOCK_SIZE};a.prototype.read_DataBlockSize=function(){var a=this.pos;if(this.check_Size(w.DATABLOCK_SIZE))return!0;a=c.readInt32LE(this.buffer,a);a!==f.EOS?(this.dataBlockSize=
a,this.state=r.DATABLOCK_DATA):this.state=r.EOS};a.prototype.read_DataBlockData=function(){var a=this.pos,b=this.dataBlockSize;if(2147483648&b&&(b&=2147483647),this.check_Size(b))return!0;this.dataBlock=this.buffer.slice(a,a+b);this.state=r.DATABLOCK_CHECKSUM};a.prototype.read_DataBlockChecksum=function(){var a=this.pos;if(this.descriptor.blockChecksum){if(this.check_Size(w.DATABLOCK_CHECKSUM))return!0;var b=c.readInt32LE(this.buffer,this.pos-4);if(c.blockChecksum(this.dataBlock)!==b)return this.pos=
a,this.emit_Error("Invalid block checksum"),!0}this.state=r.DATABLOCK_UNCOMPRESS};a.prototype.uncompress_DataBlock=function(){if(2147483648&this.dataBlockSize)var a=this.dataBlock;else{a=new l(this.descriptor.blockMaxSize);var b=this.binding.uncompress(this.dataBlock,a);if(0>b)return this.emit_Error("Invalid data block: "+-b),!0;b<this.descriptor.blockMaxSize&&(a=a.slice(0,b))}this.dataBlock=null;this.push(a);this.descriptor.streamChecksum&&(this.currentStreamChecksum=c.streamChecksum(a,this.currentStreamChecksum));
this.state=r.DATABLOCK_SIZE};a.prototype.read_EOS=function(){if(this.descriptor.streamChecksum){var a=this.pos;if(this.check_Size(w.EOS))return!0;var b=c.readInt32LE(this.buffer,a);if(b!==c.streamChecksum(null,this.currentStreamChecksum))return this.pos=a,this.emit_Error("Invalid stream checksum: "+b.toString(16).toUpperCase()),!0}this.state=r.MAGIC};a.prototype._flush=function(a){this.notEnoughData=!0;this._main(a)};a.prototype._main=function(a){for(var b,c=this.pos;!b&&this.pos<this.buffer.length;)this.state===
r.MAGIC&&(b=this.read_MagicNumber()),this.state===r.SKIP_SIZE&&(b=this.read_SkippableSize()),this.state===r.DESCRIPTOR&&(b=this.read_Descriptor()),this.state===r.SIZE&&(b=this.read_Size()),this.state===r.DICTID&&(b=this.read_DictId()),this.state===r.DESCRIPTOR_CHECKSUM&&(b=this.read_DescriptorChecksum()),this.state===r.DATABLOCK_SIZE&&(b=this.read_DataBlockSize()),this.state===r.DATABLOCK_DATA&&(b=this.read_DataBlockData()),this.state===r.DATABLOCK_CHECKSUM&&(b=this.read_DataBlockChecksum()),this.state===
r.DATABLOCK_UNCOMPRESS&&(b=this.uncompress_DataBlock()),this.state===r.EOS&&(b=this.read_EOS());this.pos>c&&(this.buffer=this.buffer.slice(this.pos),this.pos=0);a()};m.exports=a}).call(this,d("buffer").Buffer)},{"./binding":13,"./static":19,buffer:3,stream:37,util:42}],16:[function(d,m,k){(function(l){var a=d("./encoder_stream");k.LZ4_compress=function(d,h){var f=[],c=new a(h);return c.on("data",function(a){f.push(a)}),c.end(d),l.concat(f)}}).call(this,d("buffer").Buffer)},{"./encoder_stream":17,
buffer:3}],17:[function(d,m,k){(function(l){function a(b){if(!(this instanceof a))return new a(b);p.call(this,b);var c=b||v;c!==v&&Object.keys(v).forEach(function(a){c.hasOwnProperty(a)||(c[a]=v[a])});this.options=c;this.binding=this.options.useJS?e:k;this.compress=c.highCompression?this.binding.compressHC:this.binding.compress;b=0|f.VERSION<<6;b|=(1&c.blockIndependence)<<5;b|=(1&c.blockChecksum)<<4;b|=(1&c.streamSize)<<3;b|=(1&c.streamChecksum)<<2;b|=1&c.dict;var d=f.blockMaxSizes.indexOf(c.blockMaxSize);
if(0>d)throw Error("Invalid blockMaxSize: "+c.blockMaxSize);this.descriptor={flg:b,bd:(7&d)<<4};this.buffer=[];this.length=0;this.first=!0;this.checksum=null}var p=d("stream").Transform,h=d("util").inherits,f=d("./static"),c=f.utils,k=c.bindings,e=d("./binding"),r=f.STATES,w=f.SIZES,v={blockIndependence:!0,blockChecksum:!1,blockMaxSize:4194304,streamSize:!1,streamChecksum:!0,dict:!1,dictId:0,highCompression:!1};h(a,p);a.prototype.headerSize=function(){return w.MAGIC+1+1+(this.options.streamSize?w.DESCRIPTOR:
0)+(this.options.dict?w.DICTID:0)+1};a.prototype.header=function(){var a=this.headerSize();a=new l(a);this.state=r.MAGIC;a.writeInt32LE(f.MAGICNUMBER,0,!0);this.state=r.DESCRIPTOR;var e=a.slice(w.MAGIC,a.length-1);e.writeUInt8(this.descriptor.flg,0,!0);e.writeUInt8(this.descriptor.bd,1,!0);var d=2;return this.state=r.SIZE,this.options.streamSize&&(e.writeInt32LE(0,d,!0),e.writeInt32LE(this.size,d+4,!0),d+=w.SIZE),this.state=r.DICTID,this.options.dict&&(e.writeInt32LE(this.dictId,d,!0),d+=w.DICTID),
this.state=r.DESCRIPTOR_CHECKSUM,a.writeUInt8(c.descriptorChecksum(e),w.MAGIC+d,!1),a};a.prototype.update_Checksum=function(a){this.state=r.CHECKSUM_UPDATE;this.options.streamChecksum&&(this.checksum=c.streamChecksum(a,this.checksum))};a.prototype.compress_DataBlock=function(a){this.state=r.DATABLOCK_COMPRESS;var b=this.options.blockChecksum?w.DATABLOCK_CHECKSUM:0,e=this.binding.compressBound(a.length),f=new l(w.DATABLOCK_SIZE+e+b);e=f.slice(w.DATABLOCK_SIZE,w.DATABLOCK_SIZE+e);var d=this.compress(a,
e);(this.state=r.DATABLOCK_SIZE,0<d&&d<=this.options.blockMaxSize?(f.writeUInt32LE(d,0,!0),f=f.slice(0,w.DATABLOCK_SIZE+d+b)):(f.writeInt32LE(2147483648|a.length,0,!0),f=f.slice(0,w.DATABLOCK_SIZE+a.length+b),a.copy(f,w.DATABLOCK_SIZE)),this.state=r.DATABLOCK_CHECKSUM,this.options.blockChecksum)&&f.slice(-b).writeInt32LE(c.blockChecksum(e),0,!0);return this.update_Checksum(a),this.size+=a.length,f};a.prototype._transform=function(a,c,e){a&&(this.buffer.push(a),this.length+=a.length);this.first&&(this.push(this.header()),
this.first=!1);a=this.options.blockMaxSize;if(this.length<a)return e();c=l.concat(this.buffer,this.length);for(var b=0,f=c.length;f>=a;f-=a,b+=a)this.push(this.compress_DataBlock(c.slice(b,b+a)));0<f?(this.buffer=[c.slice(b)],this.length=this.buffer[0].length):(this.buffer=[],this.length=0);e()};a.prototype._flush=function(a){if(this.first&&(this.push(this.header()),this.first=!1),0<this.length){var b=l.concat(this.buffer,this.length);this.buffer=[];this.length=0;b=this.compress_DataBlock(b);this.push(b)}this.options.streamChecksum?
(this.state=r.CHECKSUM,(b=new l(w.EOS+w.CHECKSUM)).writeInt32LE(c.streamChecksum(null,this.checksum),w.EOS,!0)):b=new l(w.EOS);this.state=r.EOS;b.writeInt32LE(f.EOS,0,!0);this.push(b);a()};m.exports=a}).call(this,d("buffer").Buffer)},{"./binding":13,"./static":19,buffer:3,stream:37,util:42}],18:[function(d,m,k){m.exports=d("./static");m.exports.version="0.5.1";m.exports.createDecoderStream=d("./decoder_stream");m.exports.decode=d("./decoder").LZ4_uncompress;m.exports.createEncoderStream=d("./encoder_stream");
m.exports.encode=d("./encoder").LZ4_compress;d=m.exports.utils.bindings;m.exports.decodeBlock=d.uncompress;m.exports.encodeBound=d.compressBound;m.exports.encodeBlock=d.compress;m.exports.encodeBlockHC=d.compressHC},{"./decoder":14,"./decoder_stream":15,"./encoder":16,"./encoder_stream":17,"./static":19}],19:[function(d,m,k){m=d("buffer").Buffer;k.MAGICNUMBER=407708164;k.MAGICNUMBER_BUFFER=new m(4);k.MAGICNUMBER_BUFFER.writeUInt32LE(k.MAGICNUMBER,0,!1);k.EOS=0;k.EOS_BUFFER=new m(4);k.EOS_BUFFER.writeUInt32LE(k.EOS,
0,!1);k.VERSION=1;k.MAGICNUMBER_SKIPPABLE=407710288;k.blockMaxSizes=[null,null,null,null,65536,262144,1048576,4194304];k.extension=".lz4";k.STATES={MAGIC:0,DESCRIPTOR:1,SIZE:2,DICTID:3,DESCRIPTOR_CHECKSUM:4,DATABLOCK_SIZE:5,DATABLOCK_DATA:6,DATABLOCK_CHECKSUM:7,DATABLOCK_UNCOMPRESS:8,DATABLOCK_COMPRESS:9,CHECKSUM:10,CHECKSUM_UPDATE:11,EOS:90,SKIP_SIZE:101,SKIP_DATA:102};k.SIZES={MAGIC:4,DESCRIPTOR:2,SIZE:8,DICTID:4,DESCRIPTOR_CHECKSUM:1,DATABLOCK_SIZE:4,DATABLOCK_CHECKSUM:4,CHECKSUM:4,EOS:4,SKIP_SIZE:4};
k.utils=d("./utils")},{"./utils":20,buffer:3}],20:[function(d,m,k){var l=d("xxhashjs");k.descriptorChecksum=function(a){return l(a,0).toNumber()>>8&255};k.blockChecksum=function(a){return l(a,0).toNumber()};k.streamChecksum=function(a,d){return null===a?d.digest().toNumber():(null===d&&(d=l(0)),d.update(a))};k.readInt32LE=function(a,d){return a[d]|a[d+1]<<8|a[d+2]<<16|a[d+3]<<24};k.bindings=d("./binding")},{"./binding":13,xxhashjs:46}],21:[function(d,m,k){(function(d){!d.version||0===d.version.indexOf("v0.")||
0===d.version.indexOf("v1.")&&0!==d.version.indexOf("v1.8.")?m.exports=function(a,l,h,f){if("function"!=typeof a)throw new TypeError('"callback" argument must be a function');var c=arguments.length;switch(c){case 0:case 1:return d.nextTick(a);case 2:return d.nextTick(function(){a.call(null,l)});case 3:return d.nextTick(function(){a.call(null,l,h)});case 4:return d.nextTick(function(){a.call(null,l,h,f)});default:var k=Array(c-1);for(c=0;c<k.length;)k[c++]=arguments[c];return d.nextTick(function(){a.apply(null,
k)})}}:m.exports=d.nextTick}).call(this,d("_process"))},{_process:22}],22:[function(d,m,k){function l(){throw Error("setTimeout has not been defined");}function a(){throw Error("clearTimeout has not been defined");}function p(a){if(e===setTimeout)return setTimeout(a,0);if((e===l||!e)&&setTimeout)return e=setTimeout,setTimeout(a,0);try{return e(a,0)}catch(z){try{return e.call(null,a,0)}catch(G){return e.call(this,a,0)}}}function h(){b&&w&&(b=!1,w.length?v=w.concat(v):u=-1,v.length&&f())}function f(){if(!b){var c=
p(h);b=!0;for(var e=v.length;e;){w=v;for(v=[];++u<e;)w&&w[u].run();u=-1;e=v.length}w=null;b=!1;(function(b){if(r===clearTimeout)return clearTimeout(b);if((r===a||!r)&&clearTimeout)return r=clearTimeout,clearTimeout(b);try{r(b)}catch(J){try{return r.call(null,b)}catch(H){return r.call(this,b)}}})(c)}}function c(a,b){this.fun=a;this.array=b}function x(){}d=m.exports={};try{var e="function"==typeof setTimeout?setTimeout:l}catch(y){e=l}try{var r="function"==typeof clearTimeout?clearTimeout:a}catch(y){r=
a}!0;var w,v=[],b=!1,u=-1;d.nextTick=function(a){var e=Array(arguments.length-1);if(1<arguments.length)for(var d=1;d<arguments.length;d++)e[d-1]=arguments[d];v.push(new c(a,e));1!==v.length||b||p(f)};c.prototype.run=function(){this.fun.apply(null,this.array)};d.title="browser";d.browser=!0;d.env={};d.argv=[];d.version="";d.versions={};d.on=x;d.addListener=x;d.once=x;d.off=x;d.removeListener=x;d.removeAllListeners=x;d.emit=x;d.prependListener=x;d.prependOnceListener=x;d.listeners=function(a){return[]};
d.binding=function(a){throw Error("process.binding is not supported");};d.cwd=function(){return"/"};d.chdir=function(a){throw Error("process.chdir is not supported");};d.umask=function(){return 0}},{}],23:[function(d,m,k){m.exports=d("./lib/_stream_duplex.js")},{"./lib/_stream_duplex.js":24}],24:[function(d,m,k){function l(d){if(!(this instanceof l))return new l(d);f.call(this,d);c.call(this,d);d&&!1===d.readable&&(this.readable=!1);d&&!1===d.writable&&(this.writable=!1);this.allowHalfOpen=!0;d&&
!1===d.allowHalfOpen&&(this.allowHalfOpen=!1);this.once("end",a)}function a(){this.allowHalfOpen||this._writableState.ended||h(p,this)}function p(a){a.end()}var h=d("process-nextick-args");k=Object.keys||function(a){var c=[],f;for(f in a)c.push(f);return c};m.exports=l;m=d("core-util-is");m.inherits=d("inherits");var f=d("./_stream_readable"),c=d("./_stream_writable");m.inherits(l,f);d=k(c.prototype);for(m=0;m<d.length;m++)k=d[m],l.prototype[k]||(l.prototype[k]=c.prototype[k]);Object.defineProperty(l.prototype,
"destroyed",{get:function(){return void 0!==this._readableState&&void 0!==this._writableState&&this._readableState.destroyed&&this._writableState.destroyed},set:function(a){void 0!==this._readableState&&void 0!==this._writableState&&(this._readableState.destroyed=a,this._writableState.destroyed=a)}});l.prototype._destroy=function(a,c){this.push(null);this.end();h(c,a)}},{"./_stream_readable":26,"./_stream_writable":28,"core-util-is":4,inherits:10,"process-nextick-args":21}],25:[function(d,m,k){function l(d){if(!(this instanceof
l))return new l(d);a.call(this,d)}m.exports=l;var a=d("./_stream_transform");m=d("core-util-is");m.inherits=d("inherits");m.inherits(l,a);l.prototype._transform=function(a,d,f){f(null,a)}},{"./_stream_transform":27,"core-util-is":4,inherits:10}],26:[function(d,m,k){(function(l,a){function k(a,b){I=I||d("./_stream_duplex");a=a||{};this.objectMode=!!a.objectMode;b instanceof I&&(this.objectMode=this.objectMode||!!a.readableObjectMode);var c=a.highWaterMark,e=this.objectMode?16:16384;this.highWaterMark=
c||0===c?c:e;this.highWaterMark=Math.floor(this.highWaterMark);this.buffer=new q;this.length=0;this.pipes=null;this.pipesCount=0;this.flowing=null;this.reading=this.endEmitted=this.ended=!1;this.sync=!0;this.destroyed=this.resumeScheduled=this.readableListening=this.emittedReadable=this.needReadable=!1;this.defaultEncoding=a.defaultEncoding||"utf8";this.awaitDrain=0;this.readingMore=!1;this.encoding=this.decoder=null;a.encoding&&(n||(n=d("string_decoder/").StringDecoder),this.decoder=new n(a.encoding),
this.encoding=a.encoding)}function h(a){if(I=I||d("./_stream_duplex"),!(this instanceof h))return new h(a);this._readableState=new k(a,this);this.readable=!0;a&&("function"==typeof a.read&&(this._read=a.read),"function"==typeof a.destroy&&(this._destroy=a.destroy));F.call(this)}function f(a,b,d,f,g){var A,h=a._readableState;null===b?(h.reading=!1,function(a,b){if(!b.ended){if(b.decoder){var c=b.decoder.end();c&&c.length&&(b.buffer.push(c),b.length+=b.objectMode?1:c.length)}b.ended=!0;e(a)}}(a,h)):
(g||(A=function(a,b){var c;var e=b;E.isBuffer(e)||e instanceof C||"string"==typeof b||void 0===b||a.objectMode||(c=new TypeError("Invalid non-string/buffer chunk"));return c}(h,b)),A?a.emit("error",A):h.objectMode||b&&0<b.length?("string"==typeof b||h.objectMode||Object.getPrototypeOf(b)===E.prototype||(b=E.from(b)),f?h.endEmitted?a.emit("error",Error("stream.unshift() after end event")):c(a,h,b,!0):h.ended?a.emit("error",Error("stream.push() after EOF")):(h.reading=!1,h.decoder&&!d?(b=h.decoder.write(b),
h.objectMode||0!==b.length?c(a,h,b,!1):w(a,h)):c(a,h,b,!1))):f||(h.reading=!1));return!h.ended&&(h.needReadable||h.length<h.highWaterMark||0===h.length)}function c(a,b,c,f){b.flowing&&0===b.length&&!b.sync?(a.emit("data",c),a.read(0)):(b.length+=b.objectMode?1:c.length,f?b.buffer.unshift(c):b.buffer.push(c),b.needReadable&&e(a));w(a,b)}function x(a,b){if(0>=a||0===b.length&&b.ended)var c=0;else if(b.objectMode)c=1;else if(a!=a)c=b.flowing&&b.length?b.buffer.head.data.length:b.length;else{if(a>b.highWaterMark){var e=
a;c=(8388608<=e?e=8388608:(e--,e|=e>>>1,e|=e>>>2,e|=e>>>4,e|=e>>>8,e|=e>>>16,e++),e);b.highWaterMark=c}c=a<=b.length?a:b.ended?b.length:(b.needReadable=!0,0)}return c}function e(a){var b=a._readableState;b.needReadable=!1;b.emittedReadable||(g("emitReadable",b.flowing),b.emittedReadable=!0,b.sync?B(r,a):r(a))}function r(a){g("emit readable");a.emit("readable");y(a)}function w(a,b){b.readingMore||(b.readingMore=!0,B(v,a,b))}function v(a,b){for(var c=b.length;!b.reading&&!b.flowing&&!b.ended&&b.length<
b.highWaterMark&&(g("maybeReadMore read 0"),a.read(0),c!==b.length);)c=b.length;b.readingMore=!1}function b(a){g("readable nexttick read 0");a.read(0)}function u(a,b){b.reading||(g("resume read 0"),a.read(0));b.resumeScheduled=!1;b.awaitDrain=0;a.emit("resume");y(a);b.flowing&&!b.reading&&a.read(0)}function y(a){var b=a._readableState;for(g("flow",b.flowing);b.flowing&&null!==a.read(););}function z(a,b){return 0===b.length?null:(b.objectMode?c=b.buffer.shift():!a||a>=b.length?(c=b.decoder?b.buffer.join(""):
1===b.buffer.length?b.buffer.head.data:b.buffer.concat(b.length),b.buffer.clear()):c=function(a,b,c){var e;a<b.head.data.length?(e=b.head.data.slice(0,a),b.head.data=b.head.data.slice(a)):e=a===b.head.data.length?b.shift():c?function(a,b){var c=b.head,e=1,f=c.data;for(a-=f.length;c=c.next;){var d=c.data,g=a>d.length?d.length:a;if(g===d.length?f+=d:f+=d.slice(0,a),0===(a-=g)){g===d.length?(++e,c.next?b.head=c.next:b.head=b.tail=null):(b.head=c,c.data=d.slice(g));break}++e}return b.length-=e,f}(a,b):
function(a,b){var c=E.allocUnsafe(a),e=b.head,d=1;e.data.copy(c);for(a-=e.data.length;e=e.next;){var f=e.data,g=a>f.length?f.length:a;if(f.copy(c,c.length-a,0,g),0===(a-=g)){g===f.length?(++d,e.next?b.head=e.next:b.head=b.tail=null):(b.head=e,e.data=f.slice(g));break}++d}return b.length-=d,c}(a,b);return e}(a,b.buffer,b.decoder),c);var c}function G(a){var b=a._readableState;if(0<b.length)throw Error('"endReadable()" called on non-empty stream');b.endEmitted||(b.ended=!0,B(J,b,a))}function J(a,b){a.endEmitted||
0!==a.length||(a.endEmitted=!0,b.readable=!1,b.emit("end"))}function H(a,b){for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1}var B=d("process-nextick-args");m.exports=h;var I,D=d("isarray");h.ReadableState=k;d("events").EventEmitter;var F=d("./internal/streams/stream"),E=d("safe-buffer").Buffer,C=a.Uint8Array||function(){},K=d("core-util-is");K.inherits=d("inherits");var L=d("util"),g=void 0;g=L&&L.debuglog?L.debuglog("stream"):function(){};var n,q=d("./internal/streams/BufferList");L=
d("./internal/streams/destroy");K.inherits(h,F);var M=["error","close","destroy","pause","resume"];Object.defineProperty(h.prototype,"destroyed",{get:function(){return void 0!==this._readableState&&this._readableState.destroyed},set:function(a){this._readableState&&(this._readableState.destroyed=a)}});h.prototype.destroy=L.destroy;h.prototype._undestroy=L.undestroy;h.prototype._destroy=function(a,b){this.push(null);b(a)};h.prototype.push=function(a,b){var c,e=this._readableState;return e.objectMode?
c=!0:"string"==typeof a&&((b=b||e.defaultEncoding)!==e.encoding&&(a=E.from(a,b),b=""),c=!0),f(this,a,b,!1,c)};h.prototype.unshift=function(a){return f(this,a,null,!0,!1)};h.prototype.isPaused=function(){return!1===this._readableState.flowing};h.prototype.setEncoding=function(a){return n||(n=d("string_decoder/").StringDecoder),this._readableState.decoder=new n(a),this._readableState.encoding=a,this};h.prototype.read=function(a){g("read",a);a=parseInt(a,10);var b=this._readableState,c=a;if(0!==a&&(b.emittedReadable=
!1),0===a&&b.needReadable&&(b.length>=b.highWaterMark||b.ended))return g("read: emitReadable",b.length,b.ended),0===b.length&&b.ended?G(this):e(this),null;if(0===(a=x(a,b))&&b.ended)return 0===b.length&&G(this),null;var f,d=b.needReadable;return g("need readable",d),(0===b.length||b.length-a<b.highWaterMark)&&g("length less than watermark",d=!0),b.ended||b.reading?g("reading or ended",!1):d&&(g("do read"),b.reading=!0,b.sync=!0,0===b.length&&(b.needReadable=!0),this._read(b.highWaterMark),b.sync=
!1,b.reading||(a=x(c,b))),null===(f=0<a?z(a,b):null)?(b.needReadable=!0,a=0):b.length-=a,0===b.length&&(b.ended||(b.needReadable=!0),c!==a&&b.ended&&G(this)),null!==f&&this.emit("data",f),f};h.prototype._read=function(a){this.emit("error",Error("_read() is not implemented"))};h.prototype.pipe=function(a,b){function c(b,l){g("onunpipe");b===n&&l&&!1===l.hasUnpiped&&(l.hasUnpiped=!0,g("cleanup"),a.removeListener("close",h),a.removeListener("finish",C),a.removeListener("drain",K),a.removeListener("error",
d),a.removeListener("unpipe",c),n.removeListener("end",e),n.removeListener("end",k),n.removeListener("data",f),u=!0,!p.awaitDrain||a._writableState&&!a._writableState.needDrain||K())}function e(){g("onend");a.end()}function f(b){g("ondata");q=!1;!1!==a.write(b)||q||((1===p.pipesCount&&p.pipes===a||1<p.pipesCount&&-1!==H(p.pipes,a))&&!u&&(g("false write response, pause",n._readableState.awaitDrain),n._readableState.awaitDrain++,q=!0),n.pause())}function d(b){g("onerror",b);k();a.removeListener("error",
d);0===a.listeners("error").length&&a.emit("error",b)}function h(){a.removeListener("finish",C);k()}function C(){g("onfinish");a.removeListener("close",h);k()}function k(){g("unpipe");n.unpipe(a)}var n=this,p=this._readableState;switch(p.pipesCount){case 0:p.pipes=a;break;case 1:p.pipes=[p.pipes,a];break;default:p.pipes.push(a)}p.pipesCount+=1;g("pipe count=%d opts=%j",p.pipesCount,b);var m=b&&!1===b.end||a===l.stdout||a===l.stderr?k:e;p.endEmitted?B(m):n.once("end",m);a.on("unpipe",c);var K=function(a){return function(){var b=
a._readableState;g("pipeOnDrain",b.awaitDrain);b.awaitDrain&&b.awaitDrain--;0===b.awaitDrain&&a.listeners("data").length&&(b.flowing=!0,y(a))}}(n);a.on("drain",K);var u=!1,q=!1;return n.on("data",f),function(a,b,c){if("function"==typeof a.prependListener)return a.prependListener(b,c);a._events&&a._events[b]?D(a._events[b])?a._events[b].unshift(c):a._events[b]=[c,a._events[b]]:a.on(b,c)}(a,"error",d),a.once("close",h),a.once("finish",C),a.emit("pipe",n),p.flowing||(g("pipe resume"),n.resume()),a};
h.prototype.unpipe=function(a){var b=this._readableState,c={hasUnpiped:!1};if(0===b.pipesCount)return this;if(1===b.pipesCount)return a&&a!==b.pipes?this:(a||(a=b.pipes),b.pipes=null,b.pipesCount=0,b.flowing=!1,a&&a.emit("unpipe",this,c),this);if(!a){a=b.pipes;var e=b.pipesCount;b.pipes=null;b.pipesCount=0;b.flowing=!1;for(b=0;b<e;b++)a[b].emit("unpipe",this,c);return this}e=H(b.pipes,a);return-1===e?this:(b.pipes.splice(e,1),--b.pipesCount,1===b.pipesCount&&(b.pipes=b.pipes[0]),a.emit("unpipe",this,
c),this)};h.prototype.on=function(a,c){var f=F.prototype.on.call(this,a,c);if("data"===a)!1!==this._readableState.flowing&&this.resume();else if("readable"===a){var d=this._readableState;d.endEmitted||d.readableListening||(d.readableListening=d.needReadable=!0,d.emittedReadable=!1,d.reading?d.length&&e(this):B(b,this))}return f};h.prototype.addListener=h.prototype.on;h.prototype.resume=function(){var a=this._readableState;a.flowing||(g("resume"),a.flowing=!0,a.resumeScheduled||(a.resumeScheduled=
!0,B(u,this,a)));return this};h.prototype.pause=function(){return g("call pause flowing=%j",this._readableState.flowing),!1!==this._readableState.flowing&&(g("pause"),this._readableState.flowing=!1,this.emit("pause")),this};h.prototype.wrap=function(a){var b=this._readableState,c=!1,e=this,d;for(d in a.on("end",function(){if(g("wrapped end"),b.decoder&&!b.ended){var a=b.decoder.end();a&&a.length&&e.push(a)}e.push(null)}),a.on("data",function(d){(g("wrapped data"),b.decoder&&(d=b.decoder.write(d)),
b.objectMode&&null==d)||(b.objectMode||d&&d.length)&&(e.push(d)||(c=!0,a.pause()))}),a)void 0===this[d]&&"function"==typeof a[d]&&(this[d]=function(b){return function(){return a[b].apply(a,arguments)}}(d));for(d=0;d<M.length;d++)a.on(M[d],e.emit.bind(e,M[d]));return e._read=function(b){g("wrapped _read",b);c&&(c=!1,a.resume())},e};h._fromList=z}).call(this,d("_process"),"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{"./_stream_duplex":24,"./internal/streams/BufferList":29,
"./internal/streams/destroy":30,"./internal/streams/stream":31,_process:22,"core-util-is":4,events:8,inherits:10,isarray:12,"process-nextick-args":21,"safe-buffer":36,"string_decoder/":38,util:2}],27:[function(d,m,k){function l(a){this.afterTransform=function(c,d){var e=a._transformState;e.transforming=!1;var f=e.writecb;f?(e.writechunk=null,e.writecb=null,null!=d&&a.push(d),f(c),e=a._readableState,e.reading=!1,(e.needReadable||e.length<e.highWaterMark)&&a._read(e.highWaterMark),e=void 0):e=a.emit("error",
Error("write callback called multiple times"));return e};this.transforming=this.needTransform=!1;this.writeencoding=this.writechunk=this.writecb=null}function a(d){if(!(this instanceof a))return new a(d);h.call(this,d);this._transformState=new l(this);var c=this;this._readableState.needReadable=!0;this._readableState.sync=!1;d&&("function"==typeof d.transform&&(this._transform=d.transform),"function"==typeof d.flush&&(this._flush=d.flush));this.once("prefinish",function(){"function"==typeof this._flush?
this._flush(function(a,e){p(c,a,e)}):p(c)})}function p(a,c,d){if(c)return a.emit("error",c);null!=d&&a.push(d);c=a._transformState;if(a._writableState.length)throw Error("Calling transform done when ws.length != 0");if(c.transforming)throw Error("Calling transform done when still transforming");return a.push(null)}m.exports=a;var h=d("./_stream_duplex");m=d("core-util-is");m.inherits=d("inherits");m.inherits(a,h);a.prototype.push=function(a,c){return this._transformState.needTransform=!1,h.prototype.push.call(this,
a,c)};a.prototype._transform=function(a,c,d){throw Error("_transform() is not implemented");};a.prototype._write=function(a,c,d){var e=this._transformState;(e.writecb=d,e.writechunk=a,e.writeencoding=c,e.transforming)||(a=this._readableState,(e.needTransform||a.needReadable||a.length<a.highWaterMark)&&this._read(a.highWaterMark))};a.prototype._read=function(a){a=this._transformState;null!==a.writechunk&&a.writecb&&!a.transforming?(a.transforming=!0,this._transform(a.writechunk,a.writeencoding,a.afterTransform)):
a.needTransform=!0};a.prototype._destroy=function(a,c){var d=this;h.prototype._destroy.call(this,a,function(a){c(a);d.emit("close")})}},{"./_stream_duplex":24,"core-util-is":4,inherits:10}],28:[function(d,m,k){(function(k,a){function l(a){var b=this;this.entry=this.next=null;this.finish=function(){var c=b.entry;for(b.entry=null;c;){var e=c.callback;a.pendingcb--;e(void 0);c=c.next}a.corkedRequestsFree?a.corkedRequestsFree.next=b:a.corkedRequestsFree=b;!0}}function h(){}function f(a,c){y=y||d("./_stream_duplex");
a=a||{};this.objectMode=!!a.objectMode;c instanceof y&&(this.objectMode=this.objectMode||!!a.writableObjectMode);var f=a.highWaterMark,h=this.objectMode?16:16384;this.highWaterMark=f||0===f?f:h;this.highWaterMark=Math.floor(this.highWaterMark);this.destroyed=this.finished=this.ended=this.ending=this.needDrain=this.finalCalled=!1;this.decodeStrings=!1!==a.decodeStrings;this.defaultEncoding=a.defaultEncoding||"utf8";this.length=0;this.writing=!1;this.corked=0;this.sync=!0;this.bufferProcessing=!1;this.onwrite=
function(a){!function(a,c){var d=a._writableState,f=d.sync,g=d.writecb;if(function(a){a.writing=!1;a.writecb=null;a.length-=a.writelen;a.writelen=0}(d),c)!function(a,c,d,e,f){--c.pendingcb;d?(u(f,e),u(b,a,c),a._writableState.errorEmitted=!0,a.emit("error",e)):(f(e),a._writableState.errorEmitted=!0,a.emit("error",e),b(a,c))}(a,d,f,c,g);else{var h=w(d);h||d.corked||d.bufferProcessing||!d.bufferedRequest||r(a,d);f?z(e,a,d,h,g):e(a,d,h,g)}}(c,a)};this.writecb=null;this.writelen=0;this.lastBufferedRequest=
this.bufferedRequest=null;this.pendingcb=0;this.errorEmitted=this.prefinished=!1;this.bufferedRequestCount=0;this.corkedRequestsFree=new l(this)}function c(a){if(y=y||d("./_stream_duplex"),!(D.call(c,this)||this instanceof y))return new c(a);this._writableState=new f(a,this);this.writable=!0;a&&("function"==typeof a.write&&(this._write=a.write),"function"==typeof a.writev&&(this._writev=a.writev),"function"==typeof a.destroy&&(this._destroy=a.destroy),"function"==typeof a["final"]&&(this._final=a["final"]));
H.call(this)}function x(a,b,c,e,d,f,h){b.writelen=e;b.writecb=h;b.writing=!0;b.sync=!0;c?a._writev(d,b.onwrite):a._write(d,f,b.onwrite);b.sync=!1}function e(a,c,e,d){e||0===c.length&&c.needDrain&&(c.needDrain=!1,a.emit("drain"));c.pendingcb--;d();b(a,c)}function r(a,b){b.bufferProcessing=!0;var c=b.bufferedRequest;if(a._writev&&c&&c.next){var e=Array(b.bufferedRequestCount),d=b.corkedRequestsFree;d.entry=c;for(var f=0,h=!0;c;)e[f]=c,c.isBuf||(h=!1),c=c.next,f+=1;e.allBuffers=h;x(a,b,!0,b.length,e,
"",d.finish);b.pendingcb++;b.lastBufferedRequest=null;d.next?(b.corkedRequestsFree=d.next,d.next=null):b.corkedRequestsFree=new l(b)}else{for(;c&&(e=c.chunk,x(a,b,!1,b.objectMode?1:e.length,e,c.encoding,c.callback),c=c.next,!b.writing););null===c&&(b.lastBufferedRequest=null)}b.bufferedRequestCount=0;b.bufferedRequest=c;b.bufferProcessing=!1}function w(a){return a.ending&&0===a.length&&null===a.bufferedRequest&&!a.finished&&!a.writing}function v(a,c){a._final(function(e){c.pendingcb--;e&&a.emit("error",
e);c.prefinished=!0;a.emit("prefinish");b(a,c)})}function b(a,b){var c=w(b);c&&(b.prefinished||b.finalCalled||("function"==typeof a._final?(b.pendingcb++,b.finalCalled=!0,u(v,a,b)):(b.prefinished=!0,a.emit("prefinish"))),!0,0===b.pendingcb&&(b.finished=!0,a.emit("finish")));return c}var u=d("process-nextick-args");m.exports=c;var y,z=!k.browser&&-1<["v0.10","v0.9."].indexOf(k.version.slice(0,5))?setImmediate:u;c.WritableState=f;var G=d("core-util-is");G.inherits=d("inherits");var J={deprecate:d("util-deprecate")},
H=d("./internal/streams/stream"),B=d("safe-buffer").Buffer,I=a.Uint8Array||function(){},D,F=d("./internal/streams/destroy");$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();G.inherits(c,H);f.prototype.getBuffer=function(){for(var a=this.bufferedRequest,b=[];a;)b.push(a),a=a.next;return b};(function(){try{Object.defineProperty(f.prototype,"buffer",{get:J.deprecate(function(){return this.getBuffer()},"_writableState.buffer is deprecated. Use _writableState.getBuffer instead.",
"DEP0003")})}catch(E){}})();"function"==typeof Symbol&&Symbol.hasInstance&&"function"==typeof Function.prototype[Symbol.hasInstance]?(D=Function.prototype[Symbol.hasInstance],Object.defineProperty(c,Symbol.hasInstance,{value:function(a){return!!D.call(this,a)||a&&a._writableState instanceof f}})):D=function(a){return a instanceof this};c.prototype.pipe=function(){this.emit("error",Error("Cannot pipe, not readable"))};c.prototype.write=function(a,b,c){var e,d=this._writableState,f=!1,k=(e=a,(B.isBuffer(e)||
e instanceof I)&&!d.objectMode);return k&&!B.isBuffer(a)&&(a=B.from(a)),"function"==typeof b&&(c=b,b=null),k?b="buffer":b||(b=d.defaultEncoding),"function"!=typeof c&&(c=h),d.ended?function(a,b){var c=Error("write after end");a.emit("error",c);u(b,c)}(this,c):(k||function(a,b,c,e){var d=!0,f=!1;return null===c?f=new TypeError("May not write null values to stream"):"string"==typeof c||void 0===c||b.objectMode||(f=new TypeError("Invalid non-string/buffer chunk")),f&&(a.emit("error",f),u(e,f),d=!1),
d}(this,d,a,c))&&(d.pendingcb++,f=function(a,b,c,e,d,f){if(!c){var g=e;b.objectMode||!1===b.decodeStrings||"string"!=typeof g||(g=B.from(g,d));e!==g&&(c=!0,d="buffer",e=g)}var h=b.objectMode?1:e.length;b.length+=h;(g=b.length<b.highWaterMark)||(b.needDrain=!0);b.writing||b.corked?(a=b.lastBufferedRequest,b.lastBufferedRequest={chunk:e,encoding:d,isBuf:c,callback:f,next:null},a?a.next=b.lastBufferedRequest:b.bufferedRequest=b.lastBufferedRequest,b.bufferedRequestCount+=1):x(a,b,!1,h,e,d,f);return g}(this,
d,k,a,b,c)),f};c.prototype.cork=function(){this._writableState.corked++};c.prototype.uncork=function(){var a=this._writableState;a.corked&&(a.corked--,a.writing||a.corked||a.finished||a.bufferProcessing||!a.bufferedRequest||r(this,a))};c.prototype.setDefaultEncoding=function(a){if("string"==typeof a&&(a=a.toLowerCase()),!(-1<"hex utf8 utf-8 ascii binary base64 ucs2 ucs-2 utf16le utf-16le raw".split(" ").indexOf((a+"").toLowerCase())))throw new TypeError("Unknown encoding: "+a);return this._writableState.defaultEncoding=
a,this};c.prototype._write=function(a,b,c){c(Error("_write() is not implemented"))};c.prototype._writev=null;c.prototype.end=function(a,c,e){var d=this._writableState;"function"==typeof a?(e=a,a=null,c=null):"function"==typeof c&&(e=c,c=null);null!=a&&this.write(a,c);d.corked&&(d.corked=1,this.uncork());d.ending||d.finished||(a=e,d.ending=!0,b(this,d),a&&(d.finished?u(a):this.once("finish",a)),d.ended=!0,this.writable=!1)};Object.defineProperty(c.prototype,"destroyed",{get:function(){return void 0!==
this._writableState&&this._writableState.destroyed},set:function(a){this._writableState&&(this._writableState.destroyed=a)}});c.prototype.destroy=F.destroy;c.prototype._undestroy=F.undestroy;c.prototype._destroy=function(a,b){this.end();b(a)}}).call(this,d("_process"),"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{"./_stream_duplex":24,"./internal/streams/destroy":30,"./internal/streams/stream":31,_process:22,"core-util-is":4,inherits:10,"process-nextick-args":21,
"safe-buffer":36,"util-deprecate":39}],29:[function(d,m,k){var l=d("safe-buffer").Buffer;m.exports=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");!0;this.tail=this.head=null;this.length=0}return a.prototype.push=function(a){a={data:a,next:null};0<this.length?this.tail.next=a:this.head=a;this.tail=a;++this.length},a.prototype.unshift=function(a){a={data:a,next:this.head};0===this.length&&(this.tail=a);this.head=a;++this.length},a.prototype.shift=
function(){if(0!==this.length){var a=this.head.data;return 1===this.length?this.head=this.tail=null:this.head=this.head.next,--this.length,a}},a.prototype.clear=function(){this.head=this.tail=null;this.length=0},a.prototype.join=function(a){if(0===this.length)return"";for(var d=this.head,f=""+d.data;d=d.next;)f+=a+d.data;return f},a.prototype.concat=function(a){if(0===this.length)return l.alloc(0);if(1===this.length)return this.head.data;for(var d,f,c=l.allocUnsafe(a>>>0),k=this.head,e=0;k;)a=k.data,
d=c,f=e,a.copy(d,f),e+=k.data.length,k=k.next;return c},a}()},{"safe-buffer":36}],30:[function(d,m,k){function l(a,d){a.emit("error",d)}var a=d("process-nextick-args");m.exports={destroy:function(d,h){var f=this,c=this._writableState&&this._writableState.destroyed;this._readableState&&this._readableState.destroyed||c?h?h(d):!d||this._writableState&&this._writableState.errorEmitted||a(l,this,d):(this._readableState&&(this._readableState.destroyed=!0),this._writableState&&(this._writableState.destroyed=
!0),this._destroy(d||null,function(c){!h&&c?(a(l,f,c),f._writableState&&(f._writableState.errorEmitted=!0)):h&&h(c)}))},undestroy:function(){this._readableState&&(this._readableState.destroyed=!1,this._readableState.reading=!1,this._readableState.ended=!1,this._readableState.endEmitted=!1);this._writableState&&(this._writableState.destroyed=!1,this._writableState.ended=!1,this._writableState.ending=!1,this._writableState.finished=!1,this._writableState.errorEmitted=!1)}}},{"process-nextick-args":21}],
31:[function(d,m,k){m.exports=d("events").EventEmitter},{events:8}],32:[function(d,m,k){m.exports=d("./readable").PassThrough},{"./readable":33}],33:[function(d,m,k){(k=m.exports=d("./lib/_stream_readable.js")).Stream=k;k.Readable=k;k.Writable=d("./lib/_stream_writable.js");k.Duplex=d("./lib/_stream_duplex.js");k.Transform=d("./lib/_stream_transform.js");k.PassThrough=d("./lib/_stream_passthrough.js")},{"./lib/_stream_duplex.js":24,"./lib/_stream_passthrough.js":25,"./lib/_stream_readable.js":26,
"./lib/_stream_transform.js":27,"./lib/_stream_writable.js":28}],34:[function(d,m,k){m.exports=d("./readable").Transform},{"./readable":33}],35:[function(d,m,k){m.exports=d("./lib/_stream_writable.js")},{"./lib/_stream_writable.js":28}],36:[function(d,m,k){function l(a,c){for(var d in a)c[d]=a[d]}function a(a,c,d){return h(a,c,d)}var p=d("buffer"),h=p.Buffer;h.from&&h.alloc&&h.allocUnsafe&&h.allocUnsafeSlow?m.exports=p:(l(p,k),k.Buffer=a);l(h,a);a.from=function(a,c,d){if("number"==typeof a)throw new TypeError("Argument must not be a number");
return h(a,c,d)};a.alloc=function(a,c,d){if("number"!=typeof a)throw new TypeError("Argument must be a number");a=h(a);return void 0!==c?"string"==typeof d?a.fill(c,d):a.fill(c):a.fill(0),a};a.allocUnsafe=function(a){if("number"!=typeof a)throw new TypeError("Argument must be a number");return h(a)};a.allocUnsafeSlow=function(a){if("number"!=typeof a)throw new TypeError("Argument must be a number");return p.SlowBuffer(a)}},{buffer:3}],37:[function(d,m,k){function l(){a.call(this)}m.exports=l;var a=
d("events").EventEmitter;d("inherits")(l,a);l.Readable=d("readable-stream/readable.js");l.Writable=d("readable-stream/writable.js");l.Duplex=d("readable-stream/duplex.js");l.Transform=d("readable-stream/transform.js");l.PassThrough=d("readable-stream/passthrough.js");l.Stream=l;l.prototype.pipe=function(d,h){function f(a){d.writable&&!1===d.write(a)&&p.pause&&p.pause()}function c(){p.readable&&p.resume&&p.resume()}function k(){b||(b=!0,d.end())}function e(){b||(b=!0,"function"==typeof d.destroy&&
d.destroy())}function l(b){if(m(),0===a.listenerCount(this,"error"))throw b;}function m(){p.removeListener("data",f);d.removeListener("drain",c);p.removeListener("end",k);p.removeListener("close",e);p.removeListener("error",l);d.removeListener("error",l);p.removeListener("end",m);p.removeListener("close",m);d.removeListener("close",m)}var p=this;p.on("data",f);d.on("drain",c);d._isStdio||h&&!1===h.end||(p.on("end",k),p.on("close",e));var b=!1;return p.on("error",l),d.on("error",l),p.on("end",m),p.on("close",
m),d.on("close",m),d.emit("pipe",p),d}},{events:8,inherits:10,"readable-stream/duplex.js":23,"readable-stream/passthrough.js":32,"readable-stream/readable.js":33,"readable-stream/transform.js":34,"readable-stream/writable.js":35}],38:[function(d,m,k){function l(a){switch(this.encoding=function(a){var b=function(a){if(!a)return"utf8";for(var b;;)switch(a){case "utf8":case "utf-8":return"utf8";case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return"utf16le";case "latin1":case "binary":return"latin1";
case "base64":case "ascii":case "hex":return a;default:if(b)return;a=(""+a).toLowerCase();b=!0}}(a);if("string"!=typeof b&&(w.isEncoding===v||!v(a)))throw Error("Unknown encoding: "+a);return b||a}(a),this.encoding){case "utf16le":this.text=h;this.end=f;a=4;break;case "utf8":this.fillLast=p;a=4;break;case "base64":this.text=c;this.end=x;a=3;break;default:return this.write=e,void(this.end=r)}this.lastTotal=this.lastNeed=0;this.lastChar=w.allocUnsafe(a)}function a(a){return 127>=a?0:6==a>>5?2:14==a>>
4?3:30==a>>3?4:-1}function p(a){var b=this.lastTotal-this.lastNeed;a:if(128!=(192&a[0]))var c=(this.lastNeed=0,"\u00ef\u00bf\u00bd".repeat(b));else{if(1<this.lastNeed&&1<a.length){if(128!=(192&a[1])){c=(this.lastNeed=1,"\u00ef\u00bf\u00bd".repeat(b+1));break a}if(2<this.lastNeed&&2<a.length&&128!=(192&a[2])){c=(this.lastNeed=2,"\u00ef\u00bf\u00bd".repeat(b+2));break a}}c=void 0}return void 0!==c?c:this.lastNeed<=a.length?(a.copy(this.lastChar,b,0,this.lastNeed),this.lastChar.toString(this.encoding,
0,this.lastTotal)):(a.copy(this.lastChar,b,0,a.length),void(this.lastNeed-=a.length))}function h(a,c){if(0==(a.length-c)%2){var b=a.toString("utf16le",c);if(b){var d=b.charCodeAt(b.length-1);if(55296<=d&&56319>=d)return this.lastNeed=2,this.lastTotal=4,this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1],b.slice(0,-1)}return b}return this.lastNeed=1,this.lastTotal=2,this.lastChar[0]=a[a.length-1],a.toString("utf16le",c,a.length-1)}function f(a){a=a&&a.length?this.write(a):"";return this.lastNeed?
a+this.lastChar.toString("utf16le",0,this.lastTotal-this.lastNeed):a}function c(a,c){var b=(a.length-c)%3;return 0===b?a.toString("base64",c):(this.lastNeed=3-b,this.lastTotal=3,1===b?this.lastChar[0]=a[a.length-1]:(this.lastChar[0]=a[a.length-2],this.lastChar[1]=a[a.length-1]),a.toString("base64",c,a.length-b))}function x(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+this.lastChar.toString("base64",0,3-this.lastNeed):a}function e(a){return a.toString(this.encoding)}function r(a){return a&&
a.length?this.write(a):""}var w=d("safe-buffer").Buffer,v=w.isEncoding||function(a){switch((a=""+a)&&a.toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":case "raw":return!0;default:return!1}};k.StringDecoder=l;l.prototype.write=function(a){if(0===a.length)return"";var b;if(this.lastNeed){if(void 0===(b=this.fillLast(a)))return"";var c=this.lastNeed;this.lastNeed=0}else c=0;return c<a.length?b?b+this.text(a,
c):this.text(a,c):b||""};l.prototype.end=function(a){a=a&&a.length?this.write(a):"";return this.lastNeed?a+"\u00ef\u00bf\u00bd".repeat(this.lastTotal-this.lastNeed):a};l.prototype.text=function(b,c){var d=b.length-1;if(d<c)d=0;else{var e=a(b[d]);d=0<=e?(0<e&&(this.lastNeed=e-1),e):--d<c?0:0<=(e=a(b[d]))?(0<e&&(this.lastNeed=e-2),e):--d<c?0:0<=(e=a(b[d]))?(0<e&&(2===e?e=0:this.lastNeed=e-3),e):0}if(!this.lastNeed)return b.toString("utf8",c);this.lastTotal=d;e=b.length-(d-this.lastNeed);return b.copy(this.lastChar,
0,e),b.toString("utf8",c,e)};l.prototype.fillLast=function(a){if(this.lastNeed<=a.length)return a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,this.lastNeed),this.lastChar.toString(this.encoding,0,this.lastTotal);a.copy(this.lastChar,this.lastTotal-this.lastNeed,0,a.length);this.lastNeed-=a.length}},{"safe-buffer":36}],39:[function(d,m,k){(function(d){function a(a){try{if(!d.localStorage)return!1}catch(h){return!1}a=d.localStorage[a];return null!=a&&"true"===String(a).toLowerCase()}m.exports=
function(d,h){if(a("noDeprecation"))return d;var f=!1;return function(){if(!f){if(a("throwDeprecation"))throw Error(h);a("traceDeprecation")?console.trace(h):console.warn(h);f=!0}return d.apply(this,arguments)}}}).call(this,"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{}],40:[function(d,m,k){arguments[4][10][0].apply(k,arguments)},{dup:10}],41:[function(d,m,k){m.exports=function(d){return d&&"object"==typeof d&&"function"==typeof d.copy&&"function"==
typeof d.fill&&"function"==typeof d.readUInt8}},{}],42:[function(d,m,k){(function(l,a){function m(a,b){var d={seen:[],stylize:f};return 3<=arguments.length&&(d.depth=arguments[2]),4<=arguments.length&&(d.colors=arguments[3]),w(b)?d.showHidden=b:b&&k._extend(d,b),u(d.showHidden)&&(d.showHidden=!1),u(d.depth)&&(d.depth=2),u(d.colors)&&(d.colors=!1),u(d.customInspect)&&(d.customInspect=!0),d.colors&&(d.stylize=h),c(d,a,d.depth)}function h(a,b){var c=m.styles[b];return c?"\u001b["+m.colors[c][0]+"m"+
a+"\u001b["+m.colors[c][1]+"m":a}function f(a,b){return a}function c(a,d,f){if(a.customInspect&&d&&H(d.inspect)&&d.inspect!==k.inspect&&(!d.constructor||d.constructor.prototype!==d)){var g=d.inspect(f,a);return b(g)||(g=c(a,g,f)),g}var h=function(a,c){if(u(c))return a.stylize("undefined","undefined");if(b(c)){var d="'"+JSON.stringify(c).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'";return a.stylize(d,"string")}if(v(c))return a.stylize(""+c,"number");if(w(c))return a.stylize(""+
c,"boolean");if(null===c)return a.stylize("null","null")}(a,d);if(h)return h;h=Object.keys(d);var l=function(a){var b={};return a.forEach(function(a,c){b[a]=!0}),b}(h);if(a.showHidden&&(h=Object.getOwnPropertyNames(d)),J(d)&&(0<=h.indexOf("message")||0<=h.indexOf("description")))return x(d);if(0===h.length){if(H(d))return a.stylize("[Function"+(d.name?": "+d.name:"")+"]","special");if(y(d))return a.stylize(RegExp.prototype.toString.call(d),"regexp");if(G(d))return a.stylize(Date.prototype.toString.call(d),
"date");if(J(d))return x(d)}var m="",p=!1,C=["{","}"];(r(d)&&(p=!0,C=["., "]),H(d))&&(m=" [Function"+(d.name?": "+d.name:"")+"]");return y(d)&&(m=" "+RegExp.prototype.toString.call(d)),G(d)&&(m=" "+Date.prototype.toUTCString.call(d)),J(d)&&(m=" "+x(d)),0!==h.length||p&&0!=d.length?0>f?y(d)?a.stylize(RegExp.prototype.toString.call(d),"regexp"):a.stylize("[Object]","special"):(a.seen.push(d),g=p?function(a,b,c,d,f){for(var g=[],h=0,k=b.length;h<k;++h)Object.prototype.hasOwnProperty.call(b,String(h))?
g.push(e(a,b,c,d,String(h),!0)):g.push("");return f.forEach(function(f){f.match(/^\d+$/)||g.push(e(a,b,c,d,f,!0))}),g}(a,d,f,l,h):h.map(function(b){return e(a,d,f,l,b,p)}),a.seen.pop(),function(a,b,c){return 60<a.reduce(function(a,b){return 0,0<=b.indexOf("\n")&&0,a+b.replace(/\u001b\[\d\d?m/g,"").length+1},0)?c[0]+(""===b?"":b+"\n ")+" "+a.join(",\n  ")+" "+c[1]:c[0]+b+" "+a.join(", ")+" "+c[1]}(g,m,C)):C[0]+m+C[1]}function x(a){return"["+Error.prototype.toString.call(a)+"]"}function e(a,b,d,e,f,
h){var g,k,l;if((l=Object.getOwnPropertyDescriptor(b,f)||{value:b[f]}).get?k=l.set?a.stylize("[Getter/Setter]","special"):a.stylize("[Getter]","special"):l.set&&(k=a.stylize("[Setter]","special")),Object.prototype.hasOwnProperty.call(e,f)||(g=". + _0x4e22c8 + "),k||(0>a.seen.indexOf(l.value)?-1<(k=null===d?c(a,l.value,null):c(a,l.value,d-1)).indexOf("\n")&&(k=h?k.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):"\n"+k.split("\n").map(function(a){return"   "+a}).join("\n")):k=a.stylize("[Circular]",
"special")),u(g)){if(h&&f.match(/^\d+$/))return k;(g=JSON.stringify(""+f)).match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(g=g.substr(1,g.length-2),g=a.stylize(g,"name")):(g=g.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),g=a.stylize(g,"string"))}return g+": "+k}function r(a){return Array.isArray(a)}function w(a){return"boolean"==typeof a}function v(a){return"number"==typeof a}function b(a){return"string"==typeof a}function u(a){return void 0===a}function y(a){return z(a)&&"[object RegExp]"===
Object.prototype.toString.call(a)}function z(a){return"object"==typeof a&&null!==a}function G(a){return z(a)&&"[object Date]"===Object.prototype.toString.call(a)}function J(a){return z(a)&&("[object Error]"===Object.prototype.toString.call(a)||a instanceof Error)}function H(a){return"function"==typeof a}function B(a){return 10>a?"0"+a.toString(10):a.toString(10)}var I=/%[sdj%]/g;k.format=function(a){if(!b(a)){for(var c=[],d=0;d<arguments.length;d++)c.push(m(arguments[d]));return c.join(" ")}d=1;var e=
arguments,f=e.length;c=String(a).replace(I,function(a){if("%%"===a)return"%";if(d>=f)return a;switch(a){case "%s":return String(e[d++]);case "%d":return Number(e[d++]);case "%j":try{return JSON.stringify(e[d++])}catch(A){return"[Circular]"}default:return a}});for(var h=e[d];d<f;h=e[++d])null!==h&&z(h)?c+=" "+m(h):c+=" "+h;return c};k.deprecate=function(b,c){if(u(a.process))return function(){return k.deprecate(b,c).apply(this,arguments)};if(!0===l.noDeprecation)return b;var d=!1;return function(){if(!d){if(l.throwDeprecation)throw Error(c);
l.traceDeprecation?console.trace(c):console.error(c);d=!0}return b.apply(this,arguments)}};var D,F={};k.debuglog=function(a){if(u(D)&&(D=l.env.NODE_DEBUG||""),a=a.toUpperCase(),!F[a])if((new RegExp("\\b"+a+"\\b","i")).test(D)){var b=l.pid;F[a]=function(){var c=k.format.apply(k,arguments);console.error("%s %d: %s",a,b,c)}}else F[a]=function(){};return F[a]};k.inspect=m;m.colors={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,
39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]};m.styles={special:"cyan",number:"yellow","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"};k.isArray=r;k.isBoolean=w;k.isNull=function(a){return null===a};k.isNullOrUndefined=function(a){return null==a};k.isNumber=v;k.isString=b;k.isSymbol=function(a){return"symbol"==typeof a};k.isUndefined=u;k.isRegExp=y;k.isObject=z;k.isDate=G;k.isError=J;k.isFunction=H;k.isPrimitive=function(a){return null===
a||"boolean"==typeof a||"number"==typeof a||"string"==typeof a||"symbol"==typeof a||void 0===a};k.isBuffer=d("./support/isBuffer");var E="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");k.log=function(){var a,b;console.log("%s - %s",(a=new Date,b=[B(a.getHours()),B(a.getMinutes()),B(a.getSeconds())].join(":"),[a.getDate(),E[a.getMonth()],b].join(" ")),k.format.apply(k,arguments))};k.inherits=d("inherits");k._extend=function(a,b){if(!b||!z(b))return a;for(var c=Object.keys(b),d=c.length;d--;)a[c[d]]=
b[c[d]];return a}}).call(this,d("_process"),"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{"./support/isBuffer":41,_process:22,inherits:40}],43:[function(d,m,k){arguments[4][5][0].apply(k,arguments)},{"./lib/uint32":44,"./lib/uint64":45,dup:5}],44:[function(d,m,k){arguments[4][6][0].apply(k,arguments)},{dup:6}],45:[function(d,m,k){arguments[4][7][0].apply(k,arguments)},{dup:7}],46:[function(d,m,k){(function(k){!function(a){function l(){return 2==
arguments.length?(new l(arguments[1])).update(arguments[0]).digest():this instanceof l?void h.call(this,arguments[0]):new l(arguments[0])}function h(a){return this.seed=a instanceof f?a.clone():f(a),this.v1=this.seed.clone().add(v),this.v2=this.seed.clone().add(x),this.v3=this.seed.clone(),this.v4=this.seed.clone().subtract(c),this.total_len=0,this.memsize=0,this.memory=null,this}var f=d("cuint").UINT32;f.prototype.xxh_update=function(a,d){var b,e=x._low,f=x._high;var h=(b=a*e)>>>16;h=h+d*e&65535;
h+=a*f;var k=this._low+(65535&b);h=(k>>>16)+(this._high+(65535&h))<<16|65535&k;f=(h=h<<13|h>>>19)>>>16;h=(b=(k=65535&h)*(e=c._low))>>>16;h+=f*e;h&=65535;h+=k*c._high;this._low=65535&b;this._high=65535&h};var c=f("2654435761"),x=f("2246822519"),e=f("3266489917"),r=f("668265263"),w=f("374761393"),v=c.clone().add(x);l.prototype.init=h;l.prototype.update=function(a){var b="string"==typeof a;if(b){var c=[];b=0;for(var d=a.length;b<d;b++){var e=a.charCodeAt(b);128>e?c.push(e):2048>e?c.push(192|e>>6,128|
63&e):55296>e||57344<=e?c.push(224|e>>12,128|e>>6&63,128|63&e):(b++,e=65536+((1023&e)<<10|1023&a.charCodeAt(b)),c.push(240|e>>18,128|e>>12&63,128|e>>6&63,128|63&e))}a=new Uint8Array(c);b=!1;c=!0}"undefined"!=typeof ArrayBuffer&&a instanceof ArrayBuffer&&(c=!0,a=new Uint8Array(a));d=0;var f=a.length;e=d+f;if(0==f)return this;if(this.total_len+=f,0==this.memsize&&(this.memory=b?"":c?new Uint8Array(16):new k(16)),16>this.memsize+f)return b?this.memory+=a:c?this.memory.set(a.subarray(0,f),this.memsize):
a.copy(this.memory,this.memsize,0,f),this.memsize+=f,this;0<this.memsize&&(b?this.memory+=a.slice(0,16-this.memsize):c?this.memory.set(a.subarray(0,16-this.memsize),this.memsize):a.copy(this.memory,this.memsize,0,16-this.memsize),f=0,b?(this.v1.xxh_update(this.memory.charCodeAt(f+1)<<8|this.memory.charCodeAt(f),this.memory.charCodeAt(f+3)<<8|this.memory.charCodeAt(f+2)),f+=4,this.v2.xxh_update(this.memory.charCodeAt(f+1)<<8|this.memory.charCodeAt(f),this.memory.charCodeAt(f+3)<<8|this.memory.charCodeAt(f+
2)),f+=4,this.v3.xxh_update(this.memory.charCodeAt(f+1)<<8|this.memory.charCodeAt(f),this.memory.charCodeAt(f+3)<<8|this.memory.charCodeAt(f+2)),f+=4,this.v4.xxh_update(this.memory.charCodeAt(f+1)<<8|this.memory.charCodeAt(f),this.memory.charCodeAt(f+3)<<8|this.memory.charCodeAt(f+2))):(this.v1.xxh_update(this.memory[f+1]<<8|this.memory[f],this.memory[f+3]<<8|this.memory[f+2]),f+=4,this.v2.xxh_update(this.memory[f+1]<<8|this.memory[f],this.memory[f+3]<<8|this.memory[f+2]),f+=4,this.v3.xxh_update(this.memory[f+
1]<<8|this.memory[f],this.memory[f+3]<<8|this.memory[f+2]),f+=4,this.v4.xxh_update(this.memory[f+1]<<8|this.memory[f],this.memory[f+3]<<8|this.memory[f+2])),d+=16-this.memsize,this.memsize=0,b&&(this.memory=""));if(d<=e-16){f=e-16;do b?(this.v1.xxh_update(a.charCodeAt(d+1)<<8|a.charCodeAt(d),a.charCodeAt(d+3)<<8|a.charCodeAt(d+2)),d+=4,this.v2.xxh_update(a.charCodeAt(d+1)<<8|a.charCodeAt(d),a.charCodeAt(d+3)<<8|a.charCodeAt(d+2)),d+=4,this.v3.xxh_update(a.charCodeAt(d+1)<<8|a.charCodeAt(d),a.charCodeAt(d+
3)<<8|a.charCodeAt(d+2)),d+=4,this.v4.xxh_update(a.charCodeAt(d+1)<<8|a.charCodeAt(d),a.charCodeAt(d+3)<<8|a.charCodeAt(d+2))):(this.v1.xxh_update(a[d+1]<<8|a[d],a[d+3]<<8|a[d+2]),d+=4,this.v2.xxh_update(a[d+1]<<8|a[d],a[d+3]<<8|a[d+2]),d+=4,this.v3.xxh_update(a[d+1]<<8|a[d],a[d+3]<<8|a[d+2]),d+=4,this.v4.xxh_update(a[d+1]<<8|a[d],a[d+3]<<8|a[d+2])),d+=4;while(d<=f)}return d<e&&(b?this.memory+=a.slice(d):c?this.memory.set(a.subarray(d,e),this.memsize):a.copy(this.memory,this.memsize,d,e),this.memsize=
e-d),this};l.prototype.digest=function(){var a,d,h=this.memory,k="string"==typeof h,l=0,m=this.memsize,p=new f;for((a=16<=this.total_len?this.v1.rotl(1).add(this.v2.rotl(7).add(this.v3.rotl(12).add(this.v4.rotl(18)))):this.seed.add(w)).add(p.fromNumber(this.total_len));l<=m-4;)k?p.fromBits(h.charCodeAt(l+1)<<8|h.charCodeAt(l),h.charCodeAt(l+3)<<8|h.charCodeAt(l+2)):p.fromBits(h[l+1]<<8|h[l],h[l+3]<<8|h[l+2]),a.add(p.multiply(e)).rotl(17).multiply(r),l+=4;for(;l<m;)p.fromBits(k?h.charCodeAt(l++):h[l++],
0),a.add(p.multiply(w)).rotl(11).multiply(c);return d=a.clone().shiftRight(15),a.xor(d).multiply(x),d=a.clone().shiftRight(13),a.xor(d).multiply(e),d=a.clone().shiftRight(16),a.xor(d),this.init(this.seed),a};"undefined"!=typeof define&&define.amd?define([],function(){return l}):void 0!==m&&m.exports?m.exports=l:a.XXH=l}(this)}).call(this,d("buffer").Buffer)},{buffer:3,cuint:43}],47:[function (r){window.require_=r}/*core*/,{buffer:3,lz4:18}]},{},[47]);



